(() => {
  "use strict";
  const STORE="codigo-gripsholm-v7-d0";
  const $=s=>document.querySelector(s);
  const screen=$("#screen"),actions=$("#actions"),topbar=$("#topbar"),progressBar=$("#day-progress"),progressFill=$("#day-progress-fill"),journeyTabs=$("#journey-tabs");
  const dayLabel=$("#day-label"),missionLabel=$("#mission-label"),fundValue=$("#fund-value"),fundUnit=$("#fund-unit");
  const imgBase="assets/images/";

  const legacyPrologue=[
    {k:"TRANSMISIÓN NO IDENTIFICADA",title:"No me conoces.",photo:true,html:`<dl class="transmission"><dt>ORIGEN</dt><dd>OCULTO</dd><dt>REMITENTE</dt><dd>SAGA</dd><dt>RIESGO</dt><dd>DESCONOCIDO</dd></dl><p class="lead">Yo, en cambio, sé tres cosas sobre ti.</p><p>Sé que vas a volar a Estocolmo. Sé que viajas en familia. Y sé que dentro de unos días llegarás a un lugar llamado Gripsholm.</p><p>No es casualidad que estés leyendo esto.</p>`},
    {k:"IDENTIDAD CONFIRMADA",title:"Me llamo Saga.",photo:true,html:`<p>En sueco suena aproximadamente <strong>SAA-ga</strong>. La primera vocal es larga.</p><button class="audio-inline speak" data-speak="Saga" type="button">▶ Escuchar mi nombre</button><p style="margin-top:16px">Una <em>saga</em> es una historia. El nombre aparece también en la mitología nórdica, relacionado con relatos y conocimiento.</p><p>Mis padres encontraban divertido ponerle el nombre de una historia a la hija de dos cartógrafos.</p><p><strong>Hasta anoche.</strong></p><details class="dossier"><summary>ABRIR EL EXPEDIENTE DEL NOMBRE</summary><p>No sabemos que Saga tuviera un cargo exacto como «diosa de la historia». El nombre puede relacionarse con narrar, ver o conocer. Aquí una tradición nunca contará como una prueba documental.</p></details>`},
    {k:"NUEVE MINUTOS SIN IMAGEN",title:"El estudio quedó vacío.",html:`<p>Anoche alguien entró en el estudio de mis padres.</p><p>Las cámaras dejaron de grabar durante nueve minutos. Cuando regresó la imagen, ellos habían desaparecido.</p><p class="note">«El silencio se compra<br>con el mapa del Norte».</p><p>No sé si se los llevaron o si consiguieron escapar.</p>`},
    {k:"MAPA DIVIDIDO",title:"Once fragmentos.",html:`<p>Mis padres reconstruían rutas históricas: fronteras, barcos, ejércitos y caminos que ya no existen.</p><p>Antes de desaparecer borraron los nombres de su último mapa y lo dividieron en once fragmentos.</p><div class="fragment-grid">${"<span></span>".repeat(10)}<span>GRIPSHOLM</span></div><p><strong>Un prólogo. Diez días. Once claves.</strong></p><p>Solo una palabra quedó intacta: <span class="redacted">GRIPSHOLM</span>.</p>`},
    {k:"FONDO DE EMERGENCIA",title:"El mapa también guarda dinero.",html:`<p>Sus fragmentos protegen un fondo en coronas suecas. Cada misión recuperada liberará una parte.</p><p>Necesito reunir <strong>al menos 300 kr cada día</strong> para mantener abierto el canal, moverme sin tocar las cuentas de mis padres y desbloquear el siguiente día.</p><p>Las primeras 300 kr aseguran la transmisión de hoy. Todo lo que consigas por encima quedará en la reserva. Completar las ocho misiones reconstruye la ruta.</p><p class="lead">Si ellos llegan antes a Gripsholm, encontrarán lo que mis padres ocultaron… y quizá también a mis padres.</p>`},
    {k:"TU FUNCIÓN",title:"Necesito que reconstruyas la ruta.",html:`<p>No busco un turista. Busco a alguien capaz de detectar lo que ha sido borrado, separar una pista de una leyenda y reparar un mensaje manipulado.</p><p>Yo mantendré el canal abierto. Tú recuperarás el mapa.</p><p class="lead"><strong>Meta diaria: al menos 300 kr.</strong></p><p>No hay tiempo que perder.</p>`}
  ];

  const legacyMissions=[
    {title:"Coordenadas cero",obstacle:"El mapa ha perdido todos sus nombres.",label:"Misión 01 · Mantén abierto el canal",goal:"Reconstruye países, territorios y mares. Después separa Escandinavia del resto de la región nórdica.",keys:3,time:"4–6 min",minimum:40,action:"Comenzar la misión",done:"Has recuperado la primera parte de la ruta y los primeros fondos para mantener abierto el canal.",questions:[
      {id:"m1k1",type:"mapPlacement",title:"Once nombres borrados",prompt:"Selecciona cada etiqueta y colócala en su posición. Los aciertos quedarán fijados; solo tendrás que revisar los errores.",items:[
        ["sweden","Suecia","geo",15.5,62],["norway","Noruega","geo",7.5,64],["finland","Finlandia","geo",26,64.5],["denmark","Dinamarca","geo",10.3,56.1],["iceland","Islandia","geo",-18.5,65],
        ["aland","Åland","geo",20.1,60.2],["norwegianSea","mar de Noruega","geo",-2,66.7],["baltic","mar Báltico","geo",19.5,57],["barents","mar de Barents","geo",31,72.3],["greenland","Groenlandia","inset"],["faroe","islas Feroe","inset"]
      ],hint:"Empieza por los cinco países. Åland está entre Suecia y Finlandia; Feroe y Groenlandia pertenecen al Reino de Dinamarca, pero tienen autonomía.",explanation:"Has recuperado cinco Estados nórdicos, tres territorios autónomos y tres mares. Groenlandia y Feroe forman parte del Reino de Dinamarca; Åland pertenece a Finlandia. Ninguno de los tres es un Estado independiente."},
      {id:"m1k2",type:"mapCountries",title:"La frontera interior",prompt:"El código «ESCANDINAVIA» abre tres países. Márcalos directamente sobre el mapa.",answer:["Denmark","Norway","Sweden"],hint:"La palabra no incluye automáticamente todos los países del norte. Busca los tres reinos unidos por historia, lenguas próximas y la península escandinava.",explanation:"Escandinavia suele referirse a Dinamarca, Noruega y Suecia. Noruega y Suecia ocupan la mayor parte de la península; Dinamarca se incluye por sus vínculos históricos, culturales y lingüísticos.",solutionMap:"scandinavia"},
      {id:"m1k3",type:"single",title:"Dos etiquetas infiltradas",prompt:"El mapa manipulado ha marcado Finlandia e Islandia como «escandinavas». ¿Qué etiqueta las devuelve a su lugar correcto?",options:["Países bálticos","Nórdicos, pero no escandinavos","Territorios autónomos"],answer:1,hint:"«Nórdico» abarca una región más amplia que «escandinavo».",explanation:"Finlandia e Islandia son países nórdicos, pero no suelen incluirse en Escandinavia. La región nórdica reúne Dinamarca, Finlandia, Islandia, Noruega y Suecia, más Groenlandia, Feroe y Åland."}
    ]},
    {title:"Las siete cruces",obstacle:"Siete banderas ocultan una misma señal.",label:"Misión 02 · Descifra la pista de las banderas",goal:"Relaciona cada cruz con su territorio, encuentra la excepción y decide qué parte del relato danés es historia y cuál es leyenda.",keys:4,time:"5–7 min",minimum:50,action:"Descifrar las banderas",done:"Las siete cruces vuelven a señalar sus territorios. La leyenda ya no puede confundirse con una prueba.",questions:[
      {id:"m2k1",type:"flagMatch",title:"Siete cruces sin nombre",prompt:"Relaciona cada bandera con el país o territorio correcto. Los emparejamientos válidos quedarán fijados.",pairs:[["dk","Dinamarca"],["se","Suecia"],["no","Noruega"],["fi","Finlandia"],["is","Islandia"],["fo","Feroe"],["ax","Åland"]],hint:"Observa los colores y los bordes de cada cruz. Åland combina azul, amarillo y una cruz roja interior.",explanation:"Todas usan una cruz desplazada hacia el asta. Cinco corresponden a Estados y dos a territorios autónomos: Feroe y Åland."},
      {id:"m2k2",type:"flagPick",title:"La octava bandera",prompt:"Una entidad nórdica no utiliza la cruz. Detecta la excepción.",flags:[["dk","Dinamarca"],["se","Suecia"],["gl","Groenlandia"],["fi","Finlandia"]],answer:"gl",hint:"Busca un disco rojo y blanco, no otra combinación de cruces.",explanation:"Groenlandia forma parte de la región nórdica y del Reino de Dinamarca, pero su bandera no lleva cruz nórdica."},
      {id:"m2k3",type:"single",title:"El relato que cayó del cielo",prompt:"El expediente afirma que una bandera roja con cruz blanca cayó del cielo durante la batalla de Lindanise, en la actual Estonia, el 15 de junio de 1219. ¿Cómo aseguras este dato?",options:["Documento contemporáneo demostrado","Leyenda nacional escrita mucho después","Invención de Saga"],answer:1,hint:"Una tradición puede ser muy antigua e importante sin ser un testimonio contemporáneo.",dossier:"Dannebrog significa aproximadamente «paño danés». La tradición sitúa su aparición en Lindanise, durante la conquista danesa del norte de Estonia en 1219. El relato de la caída del cielo fue escrito siglos después. Dinamarca fue el primer reino nórdico en usar la cruz, que inspiró la familia visual posterior.",explanation:"Es la leyenda nacional del Dannebrog. La batalla y la expansión danesa en Estonia son históricas; que la bandera cayera del cielo no está demostrado por una fuente de 1219. La cruz blanca sobre rojo se convirtió con el tiempo en la bandera danesa y en modelo para las demás cruces nórdicas.",estonia:true},
      {id:"m2k4",type:"timer",title:"Canal de respuesta rápida",prompt:"Identifica cinco banderas antes de que el canal cambie de frecuencia. Es opcional: omitirlo no reduce tu recompensa mínima.",explanation:"La señal rápida ha quedado registrada."}
    ]},
    {title:"El mar bloqueado",obstacle:"Una frontera de agua corta la ruta.",label:"Misión 03 · Abre un paso hacia el Báltico",goal:"Recupera mares y lagos, desmonta una pista falsa sobre Noruega y localiza el punto desde el que Estocolmo controlaba el tráfico.",keys:3,time:"5–7 min",minimum:40,action:"Abrir la ruta",done:"La ruta de agua vuelve a conectar el interior de Suecia con el Báltico.",questions:[
      {id:"m3k1",type:"waterPlacement",title:"Ocho masas de agua",prompt:"Devuelve cada nombre al mapa. Los lagos tienen contorno real; los mares ocupan zonas abiertas.",items:[["atlantic","océano Atlántico",-22,59],["arctic","océano Ártico",13,73.5],["baltic","mar Báltico",19,57],["bothnia","golfo de Botnia",20,63],["kattegat","Kattegat",11.5,57.4],["vanern","Vänern",13.4,58.9],["vattern","Vättern",14.5,58.3],["malaren","Mälaren",17.3,59.5]],hint:"Un golfo es una entrada amplia del mar en la tierra. Botnia es el largo brazo del Báltico entre Suecia y Finlandia; Kattegat está frente a Gotemburgo.",explanation:"El Báltico penetra entre Suecia y Finlandia formando el golfo de Botnia. Kattegat conecta la costa de Gotemburgo con Skagerrak y el mar del Norte. Vänern, Vättern y Mälaren son los tres grandes lagos que necesitas para leer la ruta."},
      {id:"m3k2",type:"single",title:"El informe de la costa cerrada",prompt:"Alguien ha escrito: «Noruega cerró a Suecia el acceso al mar». ¿Qué corrección evita seguir una pista falsa?",options:["Noruega construyó la frontera para bloquear Suecia","La geografía y siglos de fronteras dejaron la costa atlántica y ártica principalmente en Noruega; Suecia conserva una gran costa báltica y salida occidental","Suecia nunca necesitó llegar al mar"],answer:1,hint:"Suecia no está encerrada: mira el Báltico y la costa de Gotemburgo.",explanation:"No existió un único momento en que Noruega «cerrara» la costa. Los reinos y sus fronteras se formaron durante siglos y guerrearon muchas veces. Suecia buscó poder en el Báltico; tiene una costa inmensa allí y una salida occidental por Gotemburgo, Kattegat y Skagerrak. No tiene costa ártica. Suecia y Noruega incluso estuvieron unidas bajo una corona entre 1814 y 1905, tras una breve guerra en 1814."},
      {id:"m3k3",type:"stockholm",title:"El punto de control",prompt:"«La ciudad debía levantarse donde ningún barco pudiera entrar o salir del Mälaren sin ser visto». Marca A, B o C directamente en el mapa.",answer:"B",hint:"Busca el paso obligado entre el lago y el mar. Un punto dentro del lago o junto al mar abierto dejaría una ruta sin vigilancia.",explanation:"Estocolmo creció en el estrecho entre el lago Mälaren y el Báltico. Los barcos que viajaban entre ambos debían pasar por la ciudad: una posición ideal para controlar mercancías, defensa e impuestos."}
    ]},
    {title:"El mensaje que casi se entiende",obstacle:"Una voz desconocida ha entrado en el canal.",label:"Misión 04 · Descifra la transmisión",goal:"Traduce tres versiones del mismo mensaje, separa dos familias lingüísticas y ajusta el canal para que los vecinos puedan entenderse.",keys:3,time:"5–7 min",minimum:45,action:"Descifrar el mensaje",done:"El canal distingue ya las lenguas emparentadas de las que siguen otra ruta histórica.",questions:[
      {id:"m4k1",type:"single",title:"Un mensaje, tres versiones",prompt:"El diccionario solo tradujo la línea sueca. ¿Qué dicen las otras dos?",evidence:[["SUECO","Tack så mycket · Muchas gracias"],["NORUEGO","Takk så mye · ?"],["DANÉS","Tak så meget · ?"]],options:["Muchas gracias","Hasta mañana","Necesito ayuda"],answer:0,hint:"Compara las palabras, no su pronunciación.",explanation:"Las tres expresiones significan «muchas gracias». Sueco, noruego y danés son lenguas germánicas septentrionales y comparten mucho vocabulario y estructuras."},
      {id:"m4k2",type:"multi",title:"Dos fragmentos siguen otra ruta",prompt:"El sistema germánico rechaza dos tarjetas. Selecciona las dos lenguas de familia urálica.",options:["Sueco","Finés","Lenguas samis","Danés"],answer:[1,2],hint:"Ser una lengua hablada en el norte no significa pertenecer a la familia germánica.",explanation:"El finés y las lenguas samis son urálicas. «Urálica» nombra una gran familia lingüística extendida desde el norte de Europa hacia los Urales y más allá; no significa que todas nacieran en un único punto exacto de esa cordillera. Las lenguas samis se hablan en zonas de Noruega, Suecia, Finlandia y Rusia.",urals:true},
      {id:"m4k3",type:"multi",title:"Ajusta el receptor",prompt:"Elige las tres reglas que permitirían reconstruir una conversación entre vecinos nórdicos.",options:["Sueco, noruego y danés son parientes cercanos","Leer suele ser más fácil que entender habla rápida","El noruego suele funcionar como puente","El finés es sueco antiguo","Todos se entienden perfectamente"],answer:[0,1,2],hint:"La comprensión depende de velocidad, dialecto y exposición; no es automática.",explanation:"Las tres primeras reglas son útiles. Muchos hablantes pueden entender partes de las lenguas vecinas, sobre todo por escrito. En general, los noruegos suelen comprender mejor a suecos y daneses; el danés hablado resulta difícil para muchos suecos. No es una regla matemática."}
    ]},
    {title:"La tierra sin fronteras",obstacle:"Un territorio entero ha desaparecido.",label:"Misión 05 · Sigue el rastro del Norte",goal:"Localiza Sápmi antes de identificarlo y separa una cultura indígena real de la versión transformada por la ficción.",keys:3,time:"4–6 min",minimum:25,action:"Seguir el rastro",done:"Sápmi vuelve al mapa como territorio cultural, sin convertirlo en una frontera inventada.",questions:[
      {id:"m5k1",type:"sapmi",title:"La zona que atraviesa fronteras",prompt:"La pista dice: «Empieza en Noruega, cruza Suecia y Finlandia y alcanza la península de Kola». Elige A, B o C.",answer:"A",hint:"No busques una provincia dentro de Suecia. La pista atraviesa cuatro Estados por el extremo norte.",explanation:"La zona A representa de forma aproximada Sápmi, que se extiende por el norte de Noruega, Suecia y Finlandia y parte de la península de Kola en Rusia. No es un Estado ni posee una frontera única como la dibujada en un atlas político."},
      {id:"m5k2",type:"single",title:"El nombre recuperado",prompt:"Ahora que has localizado la zona, ¿qué descripción repara el expediente?",options:["Sápmi es un nuevo país nórdico","Sápmi es el territorio cultural tradicional del pueblo sámi","Sápmi es únicamente la provincia sueca de Laponia"],answer:1,hint:"Las fronteras estatales atraviesan este territorio cultural.",explanation:"Los samis son un pueblo indígena y Sápmi es su territorio cultural tradicional. «Laponia» puede nombrar regiones administrativas e históricas o una marca turística, pero no es un sinónimo exacto de todo Sápmi. Tampoco todos los samis crían renos ni viven del mismo modo.",samiFlag:true},
      {id:"m5k3",type:"single",title:"La pista del bosque encantado",prompt:"Los Northuldra aparecen en el fragmento cinematográfico. ¿Qué relación permite usar la pista sin confundir ficción y realidad?",options:["Los Northuldra son una comunidad sami real","Frozen 2 inventó al pueblo sami","Los Northuldra son ficticios; la película tomó inspiración sami y trabajó con asesores samis","Todos los samis viven como los Northuldra"],answer:2,hint:"Una inspiración cultural no convierte un personaje ficticio en un retrato documental.",explanation:"Los Northuldra son ficticios. Frozen 2 tomó inspiración de culturas y paisajes samis y contó con el grupo asesor Verddet, además de producir una versión en sami septentrional. La película es una pista secundaria: no define al pueblo sami.",frozen:true}
    ]},
    {title:"El archivo de los impostores",obstacle:"Alguien ha introducido pistas falsas.",label:"Misión 06 · Detecta el origen real",goal:"Separa empresas, música e inventos suecos de los señuelos vecinos. Después corrige dos expedientes especialmente engañosos.",keys:3,time:"4–6 min",minimum:35,action:"Detectar los impostores",done:"Los elementos infiltrados ya no pueden desviar la ruta hacia otro país.",questions:[
      {id:"m6k1",type:"multi",title:"Cuatro señales auténticas",prompt:"Selecciona los cuatro elementos de origen sueco.",options:["IKEA","LEGO","Spotify","Nokia","Volvo","ABBA","Björk","Zara"],answer:[0,2,4,5],hint:"Hay dos señuelos nórdicos, uno islandés y uno español.",explanation:"IKEA nació en Suecia en 1943; Spotify fue creada por Daniel Ek y Martin Lorentzon; Volvo nació en Gotemburgo en 1927; ABBA es un grupo sueco. LEGO es danesa, Nokia finlandesa, Björk islandesa y Zara española.",brands:true},
      {id:"m6k2",type:"single",title:"El premio dividido",prompt:"El expediente Nobel contiene dos ciudades. ¿Qué reparto es auténtico?",options:["Todos los premios se entregan en Estocolmo","Todos se entregan en Oslo","La mayoría se entrega en Estocolmo; el Nobel de la Paz se entrega en Oslo"],answer:2,hint:"Alfred Nobel dejó instrucciones distintas para el premio relacionado con la paz.",explanation:"Física, Química, Medicina, Literatura y el premio de Economía se entregan en Estocolmo. El Nobel de la Paz se entrega en Oslo. La separación procede del testamento de Alfred Nobel y del sistema político de su época, cuando Suecia y Noruega compartían monarca."},
      {id:"m6k3",type:"single",title:"La identidad de una empresa",prompt:"Volvo nació en Suecia, pero Volvo Cars pertenece hoy a un grupo chino. ¿Qué regla conserva la pista sin falsificarla?",options:["Origen, sede y propietario actual pueden ser distintos","Si cambia de propietario deja de tener origen sueco","Toda empresa fabricada en varios países pierde su origen"],answer:0,hint:"La pregunta pide el lugar de nacimiento, no todos los cambios posteriores.",explanation:"Volvo nació en Gotemburgo en 1927 y mantiene allí su sede. Volvo Cars pertenece a Geely desde 2010. Decir «de origen sueco» es correcto; usarlo para ocultar su propietario actual no lo sería. La misma regla debe aplicarse a todas las marcas."}
    ]},
    {title:"La cronología alterada",obstacle:"España y Suecia han intercambiado sus fechas.",label:"Misión 07 · Reconstruye la secuencia",goal:"Ordena la entrada europea de ambos países y descubre por qué compartir la Unión Europea no significa compartir moneda.",keys:3,time:"3–5 min",minimum:20,action:"Reconstruir la cronología",done:"Las fechas y las monedas vuelven a corresponder con cada país.",questions:[
      {id:"m7k1",type:"order",title:"Dos países, dos entradas",prompt:"Toca los acontecimientos en orden, del más antiguo al más reciente.",items:[["es","España entra en las Comunidades Europeas · 1986"],["se","Suecia entra en la Unión Europea · 1995"]],answer:["es","se"],hint:"España entró junto con Portugal; Suecia lo hizo nueve años después junto con Austria y Finlandia.",explanation:"España ingresó el 1 de enero de 1986. Suecia ingresó el 1 de enero de 1995. Las instituciones cambiaron de nombre y alcance entre ambas adhesiones, pero la secuencia es esa."},
      {id:"m7k2",type:"single",title:"La moneda que no encaja",prompt:"Ambos países pertenecen a la UE. ¿Por qué el fondo de Saga utiliza coronas?",options:["Porque Suecia aún no ha adoptado el euro y conserva la corona sueca","Porque la corona es una moneda inventada para la misión","Porque Suecia no pertenece a la UE"],answer:0,hint:"Pertenecer a la Unión Europea y pertenecer a la zona euro no son exactamente lo mismo.",explanation:"Suecia pertenece a la UE desde 1995, pero no está en la zona euro. Conserva la corona sueca (SEK) y no participa en el mecanismo ERM II, uno de los pasos necesarios para adoptar el euro."},
      {id:"m7k3",type:"single",title:"La decisión de 2003",prompt:"El expediente oculta una votación. ¿Qué ocurrió en el referéndum sueco de 2003?",options:["La mayoría votó a favor de adoptar el euro","La mayoría votó en contra de adoptar el euro","Suecia votó abandonar la UE"],answer:1,hint:"La corona que ves en el fondo de emergencia sigue siendo la moneda nacional.",explanation:"La mayoría votó contra la adopción del euro en 2003. Jurídicamente Suecia debe adoptarlo cuando cumpla las condiciones, pero no tiene una fecha objetivo y la corona no está en ERM II."}
    ]},
    {title:"La contraseña de tres palabras",obstacle:"El último cierre solo reconoce voz sueca.",label:"Misión 08 · Activa la clave de voz",goal:"Escucha un saludo, un agradecimiento y una despedida. Grábate si quieres, compara ambos audios y decide cuándo el mensaje se entiende.",keys:3,time:"3–5 min",minimum:20,action:"Activar la clave de voz",done:"Las tres palabras han abierto el último cierre. La ruta está completa.",questions:[
      {id:"m8k1",type:"speech",title:"La puerta del establecimiento",prompt:"Entras en una tienda y la persona del mostrador te mira. ¿Qué palabra abre la conversación?",word:"HEJ",meaning:"hola",speech:"hej",tip:"La j sueca se aproxima al sonido de la y española.",explanation:"Hej abre el canal: es un saludo habitual e informal."},
      {id:"m8k2",type:"speech",title:"El objeto recibido",prompt:"Te entregan la comida, una entrada o el cambio. ¿Qué palabra confirma que lo has recibido?",word:"TACK",meaning:"gracias",speech:"tack",tip:"La oirás constantemente en situaciones cotidianas.",explanation:"Tack confirma la recepción: significa «gracias»."},
      {id:"m8k3",type:"speech",title:"La salida",prompt:"Abandonas el establecimiento y quieres despedirte. ¿Qué palabra cierra la conversación?",word:"HEJ DÅ",meaning:"adiós",speech:"hej då",tip:"Se escribe en dos palabras. Escuchar el modelo es más útil que una transcripción española.",explanation:"Hej då cierra la transmisión: significa «adiós»."}
    ]}
  ];

  const prologue=window.DAY0_V7_PROLOGUE||legacyPrologue;
  const missions=window.DAY0_V7_MISSIONS||legacyMissions;
  const missionTotal=()=>missions.length;
  const defaultState=()=>({stage:"landing",intro:0,mission:0,key:0,balance:0,bonus:0,completedMissions:[],completedKeys:[],failedKeys:[],correctedKeys:[],awarded:{},keyProgress:{},correctionSkipped:false,spent:0,endingPage:0,finished:false});
  let state=load(),recording=null,recordUrl=null;
  function load(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(STORE)||"{}")}}catch{return defaultState()}}
  function save(){localStorage.setItem(STORE,JSON.stringify(state))}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
  function setChrome({show=true,dark=false,mission=state.mission,progress=null,correction=false}={}){
    topbar.hidden=!show;progressBar.hidden=!show;journeyTabs.hidden=false;actions.classList.toggle("darkbar",dark);
    if(show){dayLabel.textContent="DÍA 00";missionLabel.textContent=correction?`REPASO ${state.correctedKeys.length} DE ${state.failedKeys.length}`:`MISIÓN ${Math.min(mission+1,missionTotal())} DE ${missionTotal()}`;progressFill.style.width=`${progress??((state.completedMissions.length/missionTotal())*100)}%`}
    updateFund();
  }
  function setActions(list,dark=false){actions.hidden=!list.length;actions.className=`actions${dark?" darkbar":""}`;actions.innerHTML=list.map((a,i)=>`<button type="button" class="${a.kind||"primary"}" data-act="${i}" ${a.disabled?"disabled":""}>${a.label}</button>`).join("");actions.querySelectorAll("[data-act]").forEach(b=>b.onclick=()=>list[+b.dataset.act].run())}
  function updateFund(){fundValue.textContent=`${state.completedMissions.length}/${missionTotal()}`;fundUnit.textContent="evidencias"}
  function render(){window.scrollTo(0,0);({landing:renderLanding,intro:renderIntro,activation:renderActivation,missionCover:renderMissionCover,key:renderKey,missionEnd:renderMissionEnd,correctionIntro:renderCorrectionIntro,correction:renderCorrection,verified:renderVerified,fundFinal:renderFundFinal,ending:renderEnding,result:renderResult}[state.stage]||renderLanding)()}

  function logo(){return `<div class="code-logo"><p class="kicker">TRANSMISIÓN NO IDENTIFICADA</p><h1>CÓDIG<span class="logo-o">O<span class="logo-crowns">♛♛♛</span></span><br>GRIPSHOLM</h1><p class="tagline">ONCE CLAVES · DIEZ DÍAS · UN MAPA BORRADO</p></div>`}
  function renderLanding(){setChrome({show:false,dark:true});screen.className="screen dark center";screen.innerHTML=`${logo()}<div class="signal"><i></i><i></i><i></i><i></i></div><p class="kicker">DÍA 00 · PRÓLOGO</p><h2>La Carta del Norte ha perdido el contexto.</h2><div class="mission-stats"><div><strong>${missionTotal()}</strong><small>misiones</small></div><div><strong>5</strong><small>evidencias</small></div><div><strong>01</strong><small>coordenada final</small></div></div><p class="muted" style="margin-top:18px">${state.completedMissions.length?"Tu progreso sigue guardado en este dispositivo.":"Abre la Carta cuando quieras empezar la aventura."}</p>`;setActions([{label:state.completedMissions.length?"Retomar la Carta":"Abrir la Carta del Norte",run:()=>{state.stage=state.completedMissions.length?"missionCover":"intro";save();render()}}],true)}
  function renderIntro(){const x=prologue[state.intro];setChrome({show:false,dark:true});screen.className="screen dark";screen.innerHTML=`${x.photo?`<figure class="hero-photo"><img src="${imgBase}saga-transmision-inicial.png" alt="Saga habla desde una cafetería junto a una estación"></figure>`:""}<p class="kicker">${x.k}</p><h2>${x.title}</h2>${x.html}`;bindSpeechButtons();setActions([{label:state.intro===prologue.length-1?"Aceptar el Código Gripsholm":"Continuar",run:()=>{if(state.intro<prologue.length-1)state.intro++;else state.stage="activation";save();render()}}],true)}
  function renderActivation(){setChrome({show:false,dark:true});screen.className="screen dark center";screen.innerHTML=`${logo()}<p class="kicker">DÍA 00 ACTIVADO</p><h2>La Carta del Norte</h2><div class="coordinate">MISIONES&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ${missionTotal()}<br>EVIDENCIAS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0/${missionTotal()}<br>OBJETIVO&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; LEER EL CONTEXTO<br>PRIMERA MISIÓN&nbsp;&nbsp; SITUAR EL VIAJE</div><p>Las respuestas no dan dinero ni puntos: devuelven relaciones a la Carta.</p>`;setActions([{label:"Comenzar la misión",run:()=>{state.stage="missionCover";save();render()}}],true)}

  function fundMessage(){return `${state.completedMissions.length} de ${missionTotal()} evidencias recuperadas. Cada misión deja una idea útil para leer el siguiente lugar.`}
  function renderMissionCover(){const m=missions[state.mission];setChrome({mission:state.mission,progress:(state.completedMissions.length/missionTotal())*100});screen.className="screen";screen.innerHTML=`<p class="kicker">DÍA 00 · MISIÓN ${state.mission+1} DE ${missionTotal()}</p><article class="mission-cover"><span class="mission-index">${String(state.mission+1).padStart(2,"0")}</span><p class="obstacle"><strong>Saga:</strong> ${m.obstacle}</p><p class="kicker">${m.label}</p><h2>${m.title}</h2><p>${m.goal}</p><div class="mission-stats"><div><strong>${m.keys}</strong><small>retos</small></div><div><strong>${m.time}</strong><small>duración aproximada</small></div><div><strong>◈</strong><small>evidencia</small></div></div><div class="fund-status">${fundMessage()}<br><strong>La misión dejará:</strong> ${m.done}</div></article>`;setActions([{label:m.action,run:()=>{state.key=0;state.stage="key";save();render()}}])}
  function keyScope(q,correction=false){return `${correction?"c":"n"}-${q.id}`}
  function renderKey(){const m=missions[state.mission],q=m.questions[state.key],scope=keyScope(q);setChrome({mission:state.mission,progress:((state.mission+state.key/m.keys)/missionTotal())*100});screen.className="screen";screen.innerHTML=`<p class="key-count">MISIÓN ${state.mission+1} DE ${missionTotal()} · RETO ${state.key+1} DE ${m.keys}</p><h2>${q.title}</h2><p>${q.prompt}</p>${questionMarkup(q,scope)}<div id="feedback"></div>`;bindQuestion(q,scope,false)}

  function questionMarkup(q,scope){
    if(q.evidence)return `<div class="evidence">${q.evidence.map(x=>`<div class="evidence-row"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("")}</div>${optionsMarkup(q,scope)}`;
    if(q.type==="single"||q.type==="multi")return `${specialEvidence(q)}${optionsMarkup(q,scope)}`;
    if(q.type==="mapCountries")return geoMap({interactive:true,scope,selected:getProg(scope).selected||[],fixed:getProg(scope).fixed||[]});
    if(q.type==="mapPlacement"||q.type==="waterPlacement")return placementMarkup(q,scope,q.type==="waterPlacement");
    if(q.type==="flagMatch")return flagMatchMarkup(q,scope);
    if(q.type==="flagPick")return flagPickMarkup(q,scope);
    if(q.type==="timer")return `<div class="timer-card"><p class="kicker">RETO OPCIONAL</p><div class="timer-value" id="timer">00:45</div><p id="timer-copy">Cinco señales. Cuarenta y cinco segundos.</p><div id="timer-game"></div></div>`;
    if(q.type==="trueFalse")return trueFalseMarkup(q,scope);
    if(q.type==="stockholm")return stockholmMarkup(scope);
    if(q.type==="sapmi")return sapmiMarkup(scope);
    if(q.type==="order")return orderMarkup(q,scope);
    if(q.type==="speech")return speechMarkup(q,scope);
    return "";
  }
  function specialEvidence(q){let h="";if(q.mapHint==="nordic")h+=geoMap({showLabels:true,targets:[{id:"sweden",label:"Suecia",lon:15.5,lat:62},{id:"norway",label:"Noruega",lon:7.5,lat:64},{id:"finland",label:"Finlandia",lon:26,lat:64.5},{id:"denmark",label:"Dinamarca",lon:10.3,lat:56.1},{id:"iceland",label:"Islandia",lon:-18.5,lat:65}]});if(q.mapHint==="aland")h+=geoMap({showLabels:true,targets:[{id:"sweden",label:"Suecia",lon:17.5,lat:59.5},{id:"aland",label:"Åland",lon:20.1,lat:60.2},{id:"finland",label:"Finlandia",lon:24.5,lat:61.5}]});if(q.estonia)h+=`<div class="puzzle-card"><strong>1219 · Lindanise</strong><p style="margin:6px 0 0">La actual Tallin aparece en la costa norte de Estonia. Las fuerzas danesas conquistaban la zona cuando la tradición sitúa la caída del Dannebrog.</p></div>`;if(q.urals)h+=`<div class="puzzle-card"><strong>Ruta urálica</strong><p style="margin:6px 0 0">La familia se extiende desde el norte de Europa hacia una enorme zona de Rusia. Su nombre alude a los Urales, pero no es una dirección de viaje que todas las lenguas siguieran igual.</p></div>`;if(q.samiFlag)h+=samiFlagCard();if(q.frozen)h+=northuldraComparison();if(q.brands)h+=`<div class="puzzle-card"><p class="kicker">ELEMENTOS INTERCEPTADOS</p><p>IKEA · LEGO · Spotify · Nokia · Volvo · ABBA · Björk · Zara</p></div>`;return h}
  function optionsMarkup(q,scope){const p=getProg(scope),fixed=p.fixed||[],selected=p.selected||[];return `<div class="options">${q.options.map((o,i)=>`<button type="button" class="option ${fixed.includes(i)?"locked":selected.includes(i)?"selected":""}" data-option="${i}" ${fixed.includes(i)?"disabled":""}>${esc(o)}</button>`).join("")}</div>${q.dossier?`<details class="dossier"><summary>ABRIR EXPEDIENTE</summary><p>${q.dossier}</p></details>`:""}`}

  function getProg(scope){return state.keyProgress[scope]||(state.keyProgress[scope]={})}
  function orderedForScope(items,scope,key,idOf){if(scope.startsWith("c-"))return items;const p=getProg(scope),ids=items.map(idOf);if(!Array.isArray(p[key])||p[key].length!==ids.length||p[key].some(id=>!ids.includes(id))){const shuffled=[...ids];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}if(shuffled.length>1&&shuffled.every((id,i)=>id===ids[i]))shuffled.push(shuffled.shift());p[key]=shuffled;save()}return p[key].map(id=>items.find(item=>idOf(item)===id))}
  function bindQuestion(q,scope,correction){if(isComplete(scope)){showSuccess(q,scope,correction,true);return}if(q.type==="single")return bindSingle(q,scope,correction);if(q.type==="multi")return bindMulti(q,scope,correction);if(q.type==="mapCountries")return bindMapCountries(q,scope,correction);if(q.type==="mapPlacement"||q.type==="waterPlacement")return bindPlacement(q,scope,correction);if(q.type==="flagMatch")return bindFlagMatch(q,scope,correction);if(q.type==="flagPick")return bindFlagPick(q,scope,correction);if(q.type==="timer")return bindTimer(q,scope,correction);if(q.type==="trueFalse")return bindTrueFalse(q,scope,correction);if(q.type==="stockholm"||q.type==="sapmi")return bindMapPoint(q,scope,correction);if(q.type==="order")return bindOrder(q,scope,correction);if(q.type==="speech")return bindSpeech(q,scope,correction)}
  function isComplete(scope){return !!getProg(scope).complete}
  function markFailure(q,scope,correction){const p=getProg(scope);p.attempts=(p.attempts||0)+1;if(!correction&&!state.failedKeys.includes(q.id))state.failedKeys.push(q.id);save()}
  function markCheck(scope){const p=getProg(scope);p.attempts=(p.attempts||0)+1;save()}
  function completeKey(q,scope,correction){const p=getProg(scope);if(p.complete)return;p.complete=true;if(correction){if(!state.correctedKeys.includes(q.id))state.correctedKeys.push(q.id)}else if(!state.completedKeys.includes(q.id))state.completedKeys.push(q.id);save();updateFund();renderCurrent(q,scope,correction)}
  function showFailure(q,message){const f=$("#feedback");f.innerHTML=`<div class="feedback bad"><strong>La evidencia aún no encaja</strong><p>${message||q.hint}</p></div>`}
  function showSuccess(q,scope,correction,restored){const f=$("#feedback");if(f)f.innerHTML=`<div class="feedback"><strong>${q.type==="stockholm"?"PASO LOCALIZADO":"EVIDENCIA RECUPERADA"}</strong><p>${q.explanation}</p></div>${solutionExtra(q)}`;setActions([{label:correction?(state.correctedKeys.length===state.failedKeys.length?"Cerrar el repaso":"Volver al repaso"):nextKeyLabel(),run:()=>advance(correction)}])}
  function solutionExtra(q){if(q.solutionMap==="scandinavia")return `<div class="puzzle-card"><p class="kicker">MAPA RECUPERADO</p>${geoMap({solution:["Denmark","Norway","Sweden"]})}<p>El amarillo señala Escandinavia. Finlandia e Islandia permanecen dentro de la región nórdica, pero fuera de esta agrupación.</p></div>`;if(q.type==="mapPlacement"||q.type==="waterPlacement")return `<div class="puzzle-card"><p class="kicker">MAPA COMPLETO</p>${placementSolution(q,q.type==="waterPlacement")}</div>`;if(q.type==="stockholm")return stockholmMarkup("solution",true);if(q.type==="sapmi")return sapmiMarkup("solution",true);return ""}
  function nextKeyLabel(){const m=missions[state.mission];return state.key===m.keys-1?"Completar la misión":"Ir al siguiente reto"}
  function advance(correction){if(correction){state.stage=state.correctedKeys.length===state.failedKeys.length?"verified":"correction"}else{const m=missions[state.mission];if(state.key<m.keys-1)state.key++;else state.stage="missionEnd"}save();render()}

  function bindSingle(q,scope,correction){const p=getProg(scope);screen.querySelectorAll("[data-option]").forEach(b=>b.onclick=()=>{p.selected=[+b.dataset.option];save();renderCurrent(q,scope,correction)});setActions([{label:"Comprobar la clave",disabled:!p.selected?.length,run:()=>{if(p.selected[0]===q.answer){markCheck(scope);completeKey(q,scope,correction)}else{markFailure(q,scope,correction);p.selected=[];save();renderCurrent(q,scope,correction,q.hint)}}}])}
  function bindMulti(q,scope,correction){const p=getProg(scope);p.fixed||=[];p.selected||=[];screen.querySelectorAll("[data-option]").forEach(b=>b.onclick=()=>{const i=+b.dataset.option;p.selected=p.selected.includes(i)?p.selected.filter(x=>x!==i):[...p.selected,i];save();renderCurrent(q,scope,correction)});setActions([{label:"Comprobar selección",disabled:!p.selected.length,run:()=>{const good=p.selected.filter(i=>q.answer.includes(i)),bad=p.selected.filter(i=>!q.answer.includes(i));p.fixed=[...new Set([...p.fixed,...good])];p.selected=[];if(p.fixed.length===q.answer.length&&!bad.length){markCheck(scope);completeKey(q,scope,correction)}else{markFailure(q,scope,correction);save();renderCurrent(q,scope,correction,`${good.length?`Has fijado ${p.fixed.length} de ${q.answer.length} respuestas. `:""}${q.hint}`)}}}])}
  function renderCurrent(q,scope,correction,failure){if(correction)renderCorrectionQuestion(q,scope);else renderKey();if(failure)showFailure(q,failure)}

  function bindMapCountries(q,scope,correction){const p=getProg(scope);p.fixed||=[];p.selected||=[];screen.querySelectorAll("[data-country]").forEach(el=>el.onclick=()=>{const n=el.dataset.country;if(p.fixed.includes(n))return;p.selected=p.selected.includes(n)?p.selected.filter(x=>x!==n):[...p.selected,n];save();renderCurrent(q,scope,correction)});setActions([{label:"Comprobar el mapa",disabled:!p.selected.length,run:()=>{const good=p.selected.filter(x=>q.answer.includes(x)),bad=p.selected.filter(x=>!q.answer.includes(x));p.fixed=[...new Set([...p.fixed,...good])];p.selected=[];if(p.fixed.length===q.answer.length&&!bad.length){markCheck(scope);completeKey(q,scope,correction)}else{markFailure(q,scope,correction);save();renderCurrent(q,scope,correction,`Has recuperado ${p.fixed.length} de ${q.answer.length} países. ${q.hint}`)}}}])}

  function placementTargets(q,p={},water=false,solution=false){return q.items.map((x,i)=>{const inset=x[2]==="inset";return{id:x[0],label:x[1],lon:inset?null:(x[2]==="geo"?x[3]:x[2]),lat:inset?null:(x[2]==="geo"?x[4]:x[3]),index:i+1,inset:inset?x[0]:null,fixed:solution||!!p.fixed?.[x[0]],selected:!!p.pending?.[x[0]]}})}
  function placementMarkup(q,scope,water){const p=getProg(scope);p.fixed||={};p.pending||={};const fixedLabels=Object.values(p.fixed),assigned=Object.values(p.pending),targets=placementTargets(q,p,water),orderedLabels=orderedForScope(q.items,scope,"labelOrder",x=>x[0]);return `${geoMap({targets,water})}<p class="placement-progress">Has recuperado ${Object.keys(p.fixed).length} de ${q.items.length} nombres.</p><div class="label-bank">${orderedLabels.filter(x=>!fixedLabels.includes(x[1])&&!assigned.includes(x[1])).map(x=>`<button type="button" class="map-label-chip ${p.selectedLabel===x[1]?"selected":""}" data-label="${esc(x[1])}">${esc(x[1])}</button>`).join("")}</div><div class="puzzle-card"><strong>Asignaciones pendientes</strong>${q.items.filter(x=>p.pending[x[0]]).map(x=>`<p style="margin:7px 0">${x[1]} → posición ${q.items.indexOf(x)+1}</p>`).join("")||`<p class="muted" style="margin:6px 0 0">Selecciona un nombre y después una posición numerada.</p>`}</div>`}
  function bindPlacement(q,scope,correction){const p=getProg(scope);p.fixed||={};p.pending||={};screen.querySelectorAll("[data-label]").forEach(b=>b.onclick=()=>{p.selectedLabel=b.dataset.label;save();renderCurrent(q,scope,correction)});screen.querySelectorAll("[data-target]").forEach(b=>b.onclick=()=>{if(!p.selectedLabel||p.fixed[b.dataset.target])return;Object.keys(p.pending).forEach(k=>{if(p.pending[k]===p.selectedLabel)delete p.pending[k]});p.pending[b.dataset.target]=p.selectedLabel;p.selectedLabel=null;save();renderCurrent(q,scope,correction)});const ready=Object.keys(p.fixed).length+Object.keys(p.pending).length===q.items.length;setActions([{label:q.type==="waterPlacement"?"Comprobar las aguas":"Comprobar el mapa",disabled:!ready,run:()=>{let newGood=0,bad=0;q.items.forEach(x=>{if(p.pending[x[0]]===x[1]){p.fixed[x[0]]=x[1];delete p.pending[x[0]];newGood++}else if(p.pending[x[0]]){delete p.pending[x[0]];bad++}});if(Object.keys(p.fixed).length===q.items.length){markCheck(scope);completeKey(q,scope,correction)}else{markFailure(q,scope,correction);save();renderCurrent(q,scope,correction,`Has recuperado ${Object.keys(p.fixed).length} de ${q.items.length} nombres. Revisa los ${q.items.length-Object.keys(p.fixed).length} restantes. ${q.hint}`)}}}])}

  function flagMatchMarkup(q,scope){const p=getProg(scope);p.fixed||={};p.pending||={};const used=[...Object.values(p.fixed),...Object.values(p.pending)],flags=orderedForScope(q.pairs,scope,"flagOrder",x=>x[0]),territories=orderedForScope(q.pairs,scope,"territoryOrder",x=>x[1]);return `<div class="flag-grid">${flags.filter(x=>!used.includes(x[0])).map(x=>`<button type="button" class="flag-card ${p.selectedFlag===x[0]?"selected":""}" data-flag="${x[0]}"><span class="flag">${flagSvg(x[0])}</span><small>SEÑAL SIN NOMBRE</small></button>`).join("")}</div><div class="options">${territories.map(x=>`<button type="button" class="option ${p.fixed[x[1]]?"locked":p.pending[x[1]]?"selected":""}" data-flag-target="${x[1]}" ${p.fixed[x[1]]?"disabled":""}>${p.fixed[x[1]]?`${x[1]} · fijada`:p.pending[x[1]]?`${x[1]} · señal asignada`:x[1]}</button>`).join("")}</div><p class="placement-progress">Has recuperado ${Object.keys(p.fixed).length} de ${q.pairs.length} banderas.</p>`}
  function bindFlagMatch(q,scope,correction){const p=getProg(scope);p.fixed||={};p.pending||={};screen.querySelectorAll("[data-flag]").forEach(b=>b.onclick=()=>{p.selectedFlag=b.dataset.flag;save();renderCurrent(q,scope,correction)});screen.querySelectorAll("[data-flag-target]").forEach(b=>b.onclick=()=>{if(!p.selectedFlag||p.fixed[b.dataset.flagTarget])return;Object.keys(p.pending).forEach(k=>{if(p.pending[k]===p.selectedFlag)delete p.pending[k]});p.pending[b.dataset.flagTarget]=p.selectedFlag;p.selectedFlag=null;save();renderCurrent(q,scope,correction)});const ready=Object.keys(p.fixed).length+Object.keys(p.pending).length===q.pairs.length;setActions([{label:"Comprobar las banderas",disabled:!ready,run:()=>{q.pairs.forEach(x=>{if(p.pending[x[1]]===x[0]){p.fixed[x[1]]=x[0];delete p.pending[x[1]]}else delete p.pending[x[1]]});if(Object.keys(p.fixed).length===q.pairs.length){markCheck(scope);completeKey(q,scope,correction)}else{markFailure(q,scope,correction);save();renderCurrent(q,scope,correction,`Has recuperado ${Object.keys(p.fixed).length} de ${q.pairs.length}. ${q.hint}`)}}}])}
  function flagPickMarkup(q,scope){const p=getProg(scope),flags=orderedForScope(q.flags,scope,"pickFlagOrder",x=>x[0]);return `<div class="flag-grid">${flags.map(x=>`<button type="button" class="flag-card ${p.selected===x[0]?"selected":""}" data-flag-pick="${x[0]}"><span class="flag">${flagSvg(x[0])}</span><small>${x[1]}</small></button>`).join("")}</div>`}
  function bindFlagPick(q,scope,correction){const p=getProg(scope);screen.querySelectorAll("[data-flag-pick]").forEach(b=>b.onclick=()=>{p.selected=b.dataset.flagPick;save();renderCurrent(q,scope,correction)});setActions([{label:"Comprobar la señal",disabled:!p.selected,run:()=>{if(p.selected===q.answer){markCheck(scope);completeKey(q,scope,correction)}else{markFailure(q,scope,correction);p.selected=null;save();renderCurrent(q,scope,correction,q.hint)}}}])}

  function bindTimer(q,scope,correction){setActions([{label:"Saltar reto opcional",kind:"secondary",run:()=>{completeKey(q,scope,correction)}},{label:"Empezar 45 segundos",run:()=>startTimer(q,scope,correction)}])}
  function startTimer(q,scope,correction){const rounds=[["se","Suecia",["Suecia","Finlandia","Islandia"]],["dk","Dinamarca",["Noruega","Dinamarca","Feroe"]],["fi","Finlandia",["Finlandia","Suecia","Åland"]],["no","Noruega",["Islandia","Noruega","Dinamarca"]],["is","Islandia",["Feroe","Finlandia","Islandia"]]];let i=0,score=0,left=45;setActions([]);const draw=()=>{if(i===5)return finish();$("#timer-copy").textContent=`Señal ${i+1} de 5`;$("#timer-game").innerHTML=`<span class="flag" style="max-width:180px;margin:12px auto">${flagSvg(rounds[i][0])}</span><div class="options">${rounds[i][2].map(x=>`<button class="option timer-answer">${x}</button>`).join("")}</div>`;screen.querySelectorAll(".timer-answer").forEach(b=>b.onclick=()=>{if(b.textContent===rounds[i][1])score++;i++;draw()})};const finish=()=>{clearInterval(tick);completeKey({...q,explanation:`Has identificado ${score} de 5 banderas. La práctica queda registrada; puedes volver a intentarla otro día.`},scope,correction)};const tick=setInterval(()=>{left--;if($("#timer"))$("#timer").textContent=`00:${String(left).padStart(2,"0")}`;if(left<=0)finish()},1000);draw()}
  function trueFalseMarkup(q,scope){const p=getProg(scope),i=p.index||0,item=q.items[i];if(!item){const rs=p.results||[],ok=rs.filter(x=>x.ok).length;return `<section class="puzzle-card"><p class="kicker">RETO RÁPIDO COMPLETADO</p><h3>${ok} de ${rs.length} aciertos</h3><p>${q.explanation||""}</p></section>`}const answer=p.answer,timer=answer==null&&q.timeLimit?`<div class="speed-timer" aria-live="polite">⏱ <b id="true-false-seconds">${q.timeLimit}</b> segundos</div>`:"",status=p.timedOut?"TIEMPO AGOTADO":answer===item.answer?"CORRECTO":"NO EXACTAMENTE";return `<section class="puzzle-card"><p class="kicker">RETO RÁPIDO · SEÑAL ${i+1} DE ${q.items.length}</p>${timer}<h3>${esc(item.label)}</h3>${answer==null?`<div class="options"><button class="option" data-boolean="true">Verdadero</button><button class="option" data-boolean="false">Falso</button></div>`:`<div class="feedback ${answer===item.answer&&!p.timedOut?"":"bad"}"><strong>${status}</strong><p>${item.explanation}</p></div>`}</section>`}
  function bindTrueFalse(q,scope,correction){const p=getProg(scope),i=p.index||0,item=q.items[i];if(!item)return setActions([{label:"Guardar el reto rápido",run:()=>completeKey(q,scope,correction)}]);const resolve=(answer,timedOut=false)=>{if(p.answer!=null)return;p.answer=answer;p.timedOut=timedOut;p.results||=[];p.results.push({ok:!timedOut&&answer===item.answer});delete p.timerKey;save();renderCurrent(q,scope,correction)};if(p.answer==null){screen.querySelectorAll("[data-boolean]").forEach(b=>b.onclick=()=>resolve(b.dataset.boolean==="true"));if(q.timeLimit){const seconds=Math.max(1,Number(q.timeLimit)||5),token=`${i}-${Date.now()}`;p.timerKey=token;const started=Date.now(),tick=()=>{if(p.timerKey!==token||p.index!==i||p.answer!=null)return;const left=Math.max(0,seconds-Math.floor((Date.now()-started)/1000)),el=$("#true-false-seconds");if(el)el.textContent=left;if(left<=0)return resolve(!item.answer,true);setTimeout(tick,120)};setTimeout(tick,120)}setActions([{label:q.timeLimit?`${q.timeLimit} segundos para responder`:"Elige una opción",disabled:true,run:()=>{}}]);return}const last=i===q.items.length-1;setActions([{label:last?"Ver resultado":"Siguiente señal",run:()=>{p.index=i+1;delete p.answer;delete p.timedOut;delete p.timerKey;save();renderCurrent(q,scope,correction)}}])}

  function bindMapPoint(q,scope,correction){const p=getProg(scope);screen.querySelectorAll("[data-point]").forEach(b=>b.onclick=()=>{p.selected=b.dataset.point;save();renderCurrent(q,scope,correction)});setActions([{label:q.type==="stockholm"?"Comprobar ubicación":"Comprobar la zona",disabled:!p.selected,run:()=>{if(p.selected===q.answer){markCheck(scope);completeKey(q,scope,correction)}else{markFailure(q,scope,correction);p.selected=null;save();renderCurrent(q,scope,correction,q.hint)}}}])}
  function orderMarkup(q,scope){const p=getProg(scope);p.order||=[];return `<div class="timeline">${p.order.map((id,i)=>{const item=q.items.find(x=>x[0]===id);return `<button class="timeline-item option" data-remove-order="${id}"><strong>${i+1}</strong> · ${item[1]}</button>`}).join("")}</div><div class="options">${q.items.filter(x=>!p.order.includes(x[0])).map(x=>`<button class="option" data-order="${x[0]}">${x[1]}</button>`).join("")}</div>`}
  function bindOrder(q,scope,correction){const p=getProg(scope);screen.querySelectorAll("[data-order]").forEach(b=>b.onclick=()=>{p.order=[...(p.order||[]),b.dataset.order];save();renderCurrent(q,scope,correction)});screen.querySelectorAll("[data-remove-order]").forEach(b=>b.onclick=()=>{p.order=p.order.filter(x=>x!==b.dataset.removeOrder);save();renderCurrent(q,scope,correction)});setActions([{label:"Comprobar la cronología",disabled:(p.order||[]).length!==q.answer.length,run:()=>{if(q.answer.every((x,i)=>p.order[i]===x)){markCheck(scope);completeKey(q,scope,correction)}else{markFailure(q,scope,correction);p.order=[];save();renderCurrent(q,scope,correction,q.hint)}}}])}

  function speechMarkup(q,scope){const p=getProg(scope);if(!p.useConfirmed)return `<div class="scene-card"><span class="scene-icon">${q.word==="HEJ"?"↪":q.word==="TACK"?"◆":"↩"}</span><strong>Elige la clave adecuada</strong><p>Solo una de estas palabras encaja en esta situación.</p></div><div class="options use-options">${["HEJ","TACK","HEJ DÅ"].map(word=>`<button type="button" class="option ${p.selectedWord===word?"selected":""}" data-use-word="${word}">${word}</button>`).join("")}</div>`;return `<div class="feedback use-confirmed"><strong>Uso recuperado</strong><p>${q.word} es la palabra correcta para esta situación. Ahora escucha cómo suena y compárala con tu voz si quieres.</p></div><div class="flashcards"><div class="flashcard" data-flash><div class="flash-inner"><div class="flash-front"><strong>${q.word}</strong><small>TOCA PARA REVELAR</small></div><div class="flash-back"><div><strong>${q.meaning}</strong><span>${q.tip}</span></div><button class="round-btn speak" data-speak="${q.speech}" type="button" aria-label="Escuchar ${q.word}">▶</button></div></div></div></div><div class="record-tools"><button class="round-btn" id="record" type="button" aria-label="Grabar mi voz">●</button><button class="secondary" id="play-record" type="button" disabled>Escuchar mi voz</button><span class="record-status" id="record-status">La comparación es manual. No hay nota automática. Si no hay micrófono, escucha el modelo y continúa.</span></div>`}
  function bindSpeech(q,scope,correction){const p=getProg(scope);if(!p.useConfirmed){screen.querySelectorAll("[data-use-word]").forEach(b=>b.onclick=()=>{p.selectedWord=b.dataset.useWord;save();renderCurrent(q,scope,correction)});setActions([{label:"Comprobar la situación",disabled:!p.selectedWord,run:()=>{if(p.selectedWord===q.word){p.useConfirmed=true;p.selectedWord=null;save();renderCurrent(q,scope,correction)}else{markFailure(q,scope,correction);p.selectedWord=null;save();renderCurrent(q,scope,correction,`Esa palabra no encaja aquí. Piensa si estás entrando, recibiendo algo o marchándote.`)}}}]);return}bindSpeechButtons();$("[data-flash]").onclick=e=>{if(!e.target.closest("button"))e.currentTarget.classList.toggle("flipped")};bindRecorder();setActions([{label:"Clave de voz recuperada",run:()=>{markCheck(scope);completeKey(q,scope,correction,0)}}])}
  function bindSpeechButtons(){screen.querySelectorAll(".speak").forEach(b=>b.onclick=e=>{e.stopPropagation();if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(b.dataset.speak);u.lang="sv-SE";u.rate=.76;const v=speechSynthesis.getVoices().find(x=>x.lang.toLowerCase().startsWith("sv"));if(v)u.voice=v;speechSynthesis.speak(u)})}
  function bindRecorder(){const b=$("#record"),play=$("#play-record"),status=$("#record-status");if(!b)return;b.onclick=async()=>{if(recording?.state==="recording"){recording.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[];recording=new MediaRecorder(stream);recording.ondataavailable=e=>chunks.push(e.data);recording.onstop=()=>{stream.getTracks().forEach(x=>x.stop());if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=URL.createObjectURL(new Blob(chunks,{type:recording.mimeType}));play.disabled=false;b.classList.remove("recording");status.textContent="Grabación lista. Alterna el modelo y tu voz."};recording.start();b.classList.add("recording");status.textContent="Grabando… toca de nuevo para detener."}catch{status.textContent="El micrófono no está disponible. Puedes escuchar el modelo y continuar sin grabarte."}};play.onclick=()=>recordUrl&&new Audio(recordUrl).play()}

  function renderMissionEnd(){const m=missions[state.mission],minKey=`min-${state.mission}`;if(!state.awarded[minKey]){state.balance+=m.minimum;state.awarded[minKey]=m.minimum;if(!state.completedMissions.includes(state.mission))state.completedMissions.push(state.mission);save()}const bonus=m.questions.reduce((s,q)=>s+(state.awarded[`bonus-${q.id}`]||0),0);setChrome({mission:state.mission,progress:(state.completedMissions.length/8)*100});screen.className="screen result";screen.innerHTML=`<div class="mission-complete"><div class="seal">♛♛♛</div><p class="kicker">DÍA 00</p><h2>Misión ${state.mission+1} de 8 completada</h2><h3>${m.title}</h3><p>${m.done}</p><div class="reward-ledger"><div><span>Recompensa mínima</span><strong>+${m.minimum} kr</strong></div><div><span>Bonificación obtenida</span><strong>+${bonus} kr</strong></div><div><span>Fondo actualizado</span><strong>${state.balance} kr</strong></div></div><div class="mission-progress"><strong>${state.completedMissions.length} de 8 misiones completadas</strong><br>${fundMessage()}<br>Tu progreso se ha guardado automáticamente.</div></div>`;const last=state.mission===7;setActions([{label:"Salir por ahora",kind:"secondary",run:()=>{if(!last){state.mission++;state.key=0;state.stage="landing"}else state.stage=state.failedKeys.length?"correctionIntro":"verified";save();render()}},{label:last?(state.failedKeys.length?"Reparar las claves":"Verificar la ruta"):`Ir a la misión ${state.mission+2}`,run:()=>{if(last)state.stage=state.failedKeys.length?"correctionIntro":"verified";else{state.mission++;state.key=0;state.stage="missionCover"}save();render()}}])}

  function findQuestion(id){for(let mi=0;mi<missions.length;mi++){const qi=missions[mi].questions.findIndex(q=>q.id===id);if(qi>=0)return{q:missions[mi].questions[qi],mi,qi}}}
  function renderCorrectionIntro(){const count=state.failedKeys.length,secured=state.balance>=300;setChrome({correction:true,progress:100});screen.className="screen dark";screen.innerHTML=`<p class="kicker">DÍA 00 · CORRECCIÓN 0 DE ${count}</p><h1>La ruta aún tiene errores.</h1><p class="lead">El sistema ha conservado todas las claves que recuperaste a la primera.</p><p>${count===1?"Solo reaparecerá la clave en la que necesitaste otro intento.":`Solo reaparecerán las ${count} claves en las que necesitaste otro intento.`} Cuando repares una, desaparecerá de la lista.</p><div class="correction-list">${state.failedKeys.map((id,i)=>{const {q}=findQuestion(id);return `<div class="correction-item"><strong>${i+1}</strong><span>${q.title}</span></div>`}).join("")}</div>${secured?`<div class="note"><strong>La transmisión ya está asegurada.</strong><br>Puedes continuar ahora o reparar estas claves para conseguir 25 kr más para la reserva.</div>`:`<p>No hay límite de tiempo ni de intentos. Reparar estas claves liberará las 25 kr mínimas que faltan para asegurar el canal.</p>`}`;const actions=[];if(secured)actions.push({label:"Continuar sin corregir",kind:"secondary",run:()=>{state.correctionSkipped=true;state.stage="verified";save();render()}});actions.push({label:secured?"Corregir y conseguir 25 kr más":"Reparar las claves pendientes",run:()=>{state.correctionSkipped=false;state.stage="correction";save();render()}});setActions(actions,true)}
  function renderCorrection(){const pending=state.failedKeys.filter(id=>!state.correctedKeys.includes(id));if(!pending.length){state.stage="verified";save();return render()}const data=findQuestion(pending[0]),q=data.q,scope=keyScope(q,true);setChrome({correction:true,progress:100});screen.className="screen";screen.innerHTML=`<p class="key-count">CORRECCIÓN ${state.correctedKeys.length} DE ${state.failedKeys.length}</p><h2>${q.title}</h2><p>${q.prompt}</p>${q.media?mediaCard(q.media):""}${questionMarkup(q,scope)}<div id="feedback"></div>`;bindQuestion(q,scope,true)}
  function renderCorrectionQuestion(q,scope){setChrome({correction:true,progress:100});screen.className="screen";screen.innerHTML=`<p class="key-count">CORRECCIÓN ${state.correctedKeys.length} DE ${state.failedKeys.length}</p><h2>${q.title}</h2><p>${q.prompt}</p>${q.media?mediaCard(q.media):""}${questionMarkup(q,scope)}<div id="feedback"></div>`;bindQuestion(q,scope,true)}
  function renderVerified(){const award=!state.correctionSkipped;if(award&&!state.awarded.verify){state.balance+=25;state.awarded.verify=25;save()}const repaired=state.failedKeys.length===1?"Has reparado la única clave pendiente.":`Has reparado ${state.correctedKeys.length} de ${state.failedKeys.length} claves pendientes.`,status=state.correctionSkipped?`Has dejado ${state.failedKeys.length} ${state.failedKeys.length===1?"clave pendiente":"claves pendientes"}. La transmisión puede continuar porque ya habías superado el mínimo diario.`:state.failedKeys.length?repaired:"No quedó ninguna clave dañada. La corrección no era necesaria.";setChrome({progress:100});screen.className="screen dark center";screen.innerHTML=`<p class="kicker">OCHO MISIONES COMPLETADAS</p><h1>${state.correctionSkipped?"Canal asegurado.":"Ruta verificada."}</h1><div class="three-crowns">♛ ♛ ♛</div><p>${status}</p><p class="lead">El mapa puede revelar su primera coordenada.</p><div class="reward-ledger">${award?`<div><span>Verificación de la ruta</span><strong>+25 kr</strong></div>`:`<div><span>Corrección opcional</span><strong>omitida</strong></div>`}<div><span>Total recuperado</span><strong>${state.balance} kr</strong></div></div>`;setActions([{label:"Revisar el fondo de emergencia",run:()=>{state.stage="fundFinal";save();render()}}],true)}
  function renderFundFinal(){const reserve=Math.max(0,state.balance-300),correctionStatus=state.correctionSkipped?`${state.failedKeys.length} aplazada${state.failedKeys.length===1?"":"s"}`:`${state.correctedKeys.length} de ${state.failedKeys.length}`;setChrome({progress:100});screen.className="screen";screen.innerHTML=`<p class="kicker">DÍA 00 · FONDO DE EMERGENCIA</p><h1>La transmisión está a salvo.</h1><p>Has recuperado <strong>${state.balance} kr</strong>. El mínimo diario era de 300 kr para que Saga pudiera continuar sin utilizar las cuentas de sus padres.</p><div class="reward-ledger"><div><span>Mínimo diario</span><strong>300 kr</strong></div><div><span>Fondos recuperados</span><strong>${state.balance} kr</strong></div><div><span>Reserva disponible</span><strong>${reserve} kr</strong></div><div><span>Misiones</span><strong>8 de 8</strong></div><div><span>Corrección</span><strong>${correctionStatus}</strong></div></div><div class="puzzle-card"><p class="kicker">ASIGNACIÓN DE LOS FONDOS</p><div class="ledger"><div><dt>Canal seguro</dt><dd>120 kr</dd></div><div><dt>Billete sin vincular a sus cuentas</dt><dd>60 kr</dd></div><div><dt>Desplazamiento no rastreable</dt><dd>120 kr</dd></div></div><p style="margin:12px 0 0"><strong>Total utilizado: 300 kr</strong><br>Reserva después de la operación: ${reserve} kr</p></div>`;setActions([{label:"Asegurar el canal y continuar",run:()=>{state.spent=300;state.stage="ending";state.endingPage=0;save();render()}}])}
  function renderEnding(){setChrome({dark:true,progress:100});screen.className="screen dark";const pages=[`<figure class="hero-photo"><img src="${imgBase}saga-canal-asegurado.png" alt="Saga continúa la transmisión desde una estación"></figure><p class="kicker">DÍA 00 · CANAL ASEGURADO</p><h2>Lo has conseguido.</h2><p>El canal vuelve a estar protegido. He utilizado las 300 kr sin tocar las cuentas de mis padres. Las <strong>${state.balance-300} kr</strong> restantes quedan en la reserva.</p><p>Pero hay algo que no entiendo.</p><p>Mis padres diseñaron el sistema para que solo respondiera a las claves de nuestra familia. Aun así, ha aceptado las tuyas.</p><p class="lead"><strong>Creo que te estaban esperando.</strong></p>`,`<p class="kicker">CONSECUENCIA DESBLOQUEADA</p><h1>Una fecha. Un testigo.</h1><div class="coordinate">59.325° N&nbsp;&nbsp;18.070° E<br><br>08·11·1520<br>TESTIGO: K █ R I N<br>ESTADO: NO REGISTRADA</div><p>La coordenada apunta a una plaza de Estocolmo: <strong>Stortorget</strong>.</p><p>Karin puede ser una testigo, una identidad falsa o una clave que mis padres dejaron para ti.</p>`,`<p class="kicker">INTENTO DE ACCESO DETECTADO</p><h1>Alguien más busca la coordenada.</h1><p class="lead">Otro dispositivo acaba de intentar abrir la ruta.</p><p>No ha entrado. Todavía.</p><p>El siguiente día comenzará en Estocolmo. Si encuentras tres coronas, no supongas que decoran el mapa.</p><div class="three-crowns">♛ ♛ ♛</div>`];screen.innerHTML=pages[state.endingPage];setActions([{label:state.endingPage===0?"Revelar la primera coordenada":state.endingPage===1?"Seguir la señal":"Cerrar el canal",run:()=>{if(state.endingPage<2)state.endingPage++;else{state.stage="result";state.finished=true}save();render()}}],true)}
  function renderResult(){const correctionCopy=state.correctionSkipped?`Has dejado ${state.failedKeys.length} ${state.failedKeys.length===1?"clave":"claves"} para una revisión posterior.`:"No queda ninguna corrección pendiente.";setChrome({progress:100});screen.className="screen result";screen.innerHTML=`<div class="mission-complete"><div class="seal">♛♛♛</div><p class="kicker">DÍA 00 COMPLETADO</p><h1>La ruta borrada</h1><p>La transmisión está asegurada y las ocho misiones están completas. ${correctionCopy}</p><div class="reward-ledger"><div><span>Total recuperado</span><strong>${state.balance} kr</strong></div><div><span>Utilizado por Saga</span><strong>300 kr</strong></div><div><span>Reserva actual</span><strong>${state.balance-300} kr</strong></div><div><span>Fragmentos</span><strong>1 de 11</strong></div></div><p><strong>Siguiente señal:</strong> Stortorget · 8 de noviembre de 1520 · Karin.</p></div>`;setActions([{label:"Ver las misiones",kind:"secondary",run:openMenu},{label:"Abrir el Día 01",run:()=>{location.href="dia1.html"}}])}

  function targetOffset(id,water,solutionLabels){const waterOffsets={atlantic:[0,0],arctic:[0,0],baltic:[42,-22],bothnia:[34,-28],kattegat:[-28,-26],vanern:[-62,-34],vattern:[-14,-58],malaren:[50,-54]};const labelOffsets={sweden:[42,8],norway:[-48,-8],finland:[43,-12],denmark:[-18,28],iceland:[5,-26],aland:[48,25],norwegianSea:[-48,-18],baltic:[46,25],barents:[-32,-24]};return water?(waterOffsets[id]||[0,0]):solutionLabels?(labelOffsets[id]||[0,0]):[0,0]}
  function answerLabel(label,x,y,anchorX,anchorY){const width=Math.min(104,Math.max(42,label.length*5.3+14)),cx=Math.max(width/2+4,Math.min(416-width/2,x)),cy=Math.max(12,Math.min(318,y));return `<line class="map-leader" x1="${anchorX}" y1="${anchorY}" x2="${cx}" y2="${cy}"/><g class="map-answer"><rect x="${cx-width/2}" y="${cy-10}" width="${width}" height="20" rx="8"/><text x="${cx}" y="${cy}">${esc(label)}</text></g>`}
  function insetTargetsSvg(targets,showLabels){return targets.map(t=>{const green=t.id==="greenland",x=green?8:104,y=green?230:264,w=green?88:66,h=green?90:56,cx=x+w-15,cy=y+17,label=showLabels||t.fixed?t.label:`AMPLIACIÓN ${green?"A":"B"}`,shape=green?`<path class="inset-shape" d="M${x+31} ${y+19}l13 3 10 12-4 14 8 11-8 16-15 5-12-12 4-13-7-12 11-24z"/>`:`<g class="inset-shape-dots"><circle cx="${x+24}" cy="${y+26}" r="5"/><circle cx="${x+35}" cy="${y+19}" r="3"/><circle cx="${x+41}" cy="${y+34}" r="4"/><circle cx="${x+29}" cy="${y+41}" r="3"/></g>`;return `<g class="map-inset ${t.fixed?"fixed":t.selected?"selected":""}" data-target="${showLabels?"":t.id}" tabindex="${showLabels?"-1":"0"}" aria-label="${showLabels?esc(t.label):`Ampliación ${green?"A":"B"}`}"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="10"/>${shape}<text class="inset-caption" x="${x+7}" y="${y+13}">${esc(label)}</text>${showLabels?"":`<circle class="target-dot ${t.fixed?"fixed":t.selected?"selected":""}" cx="${cx}" cy="${cy}" r="10"/><text class="target-number ${t.fixed?"fixed":""}" x="${cx}" y="${cy}">${t.fixed?"✓":t.index}</text>`}</g>`}).join("")}
  function geoMap({interactive=false,scope="",selected=[],fixed=[],solution=[],targets=[],water=false,showLabels=false,bounds=[-29,45,53,74.8]}={}){const W=420,H=330,features=window.GRIPSHOLM_MAP_DATA?.countries||[],lakes=window.GRIPSHOLM_MAP_DATA?.lakes||[],path=f=>geometryPath(f.geometry,bounds,W,H);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Mapa geográfico del norte de Europa"><defs><clipPath id="map-clip"><rect width="${W}" height="${H}"/></clipPath></defs><g clip-path="url(#map-clip)">`;features.forEach(f=>{if(!geometryVisible(f.geometry,bounds))return;const cls=["country",interactive?"active":"",selected.includes(f.name)?"chosen":"",fixed.includes(f.name)?"solution":"",solution.includes(f.name)?"solution":""].join(" ");svg+=`<path class="${cls}" d="${path(f)}" ${interactive?`data-country="${f.name}" tabindex="0"`:""}/>`});lakes.forEach(l=>{if(geometryVisible(l.geometry,bounds))svg+=`<path class="lake" d="${path(l)}"/>`});svg+=`</g>`;if(interactive){[["Denmark","DK",10.2,56.1],["Norway","NO",8.5,64],["Sweden","SE",16.2,62],["Finland","FI",26,64],["Iceland","IS",-18.5,65]].forEach(x=>{const p=project(x[2],x[3],bounds,W,H),on=selected.includes(x[0])||fixed.includes(x[0]);svg+=`<g class="country-marker ${on?"chosen":""}" data-country="${x[0]}" tabindex="0" aria-label="${x[0]}"><circle cx="${p[0]}" cy="${p[1]}" r="13"/><text x="${p[0]}" y="${p[1]}">${x[1]}</text></g>`})}const insetTargets=targets.filter(t=>t.inset),regularTargets=targets.filter(t=>!t.inset);regularTargets.forEach(t=>{const anchor=project(t.lon,t.lat,bounds,W,H),offset=targetOffset(t.id,water,showLabels),x=anchor[0]+offset[0],y=anchor[1]+offset[1];if(showLabels)svg+=answerLabel(t.label,x,y,anchor[0],anchor[1]);else{if(offset[0]||offset[1])svg+=`<line class="map-leader puzzle" x1="${anchor[0]}" y1="${anchor[1]}" x2="${x}" y2="${y}"/>`;svg+=`<circle class="target-dot ${t.fixed?"fixed":t.selected?"selected":""}" cx="${x}" cy="${y}" r="10" data-target="${t.id}"/><text class="target-number ${t.fixed?"fixed":""}" x="${x}" y="${y}">${t.fixed?"✓":t.index}</text>`}});if(insetTargets.length)svg+=insetTargetsSvg(insetTargets,showLabels);svg+=`</svg>`;return `<div class="geo-map ${water?"water-map":""} ${showLabels?"solution-map":""}">${svg}</div>`}
  function project(lon,lat,b,W,H){return[(lon-b[0])/(b[1]-b[0])*W,(b[3]-lat)/(b[3]-b[2])*H]}
  function geometryVisible(g,b){const coords=g.type==="Polygon"?g.coordinates.flat(1):g.coordinates.flat(2);return coords.some(p=>p[0]>=b[0]-5&&p[0]<=b[1]+5&&p[1]>=b[2]-5&&p[1]<=b[3]+5)}
  function geometryPath(g,b,W,H){const polys=g.type==="Polygon"?[g.coordinates]:g.coordinates;return polys.map(poly=>poly.map(ring=>ring.map((p,i)=>{const q=project(p[0],p[1],b,W,H);return`${i?"L":"M"}${q[0].toFixed(1)},${q[1].toFixed(1)}`}).join("")+"Z").join(" ")).join(" ")}
  function placementSolution(q,water){return `${geoMap({water,showLabels:true,targets:placementTargets(q,{},water,true)})}<p class="map-caption">Todos los nombres han vuelto a su posición.</p>`}
  function stockholmMarkup(scope,solution=false){const p=getProg(scope),bounds=[16.4,19.6,58.8,60.3],pts=[["A",17.05,59.45],["B",18.07,59.325],["C",19.05,59.25]];let base=geoMap({bounds});base=base.replace("</svg>",`${pts.map(x=>{const q=project(x[1],x[2],bounds,420,330);return`<circle class="target-dot ${solution&&x[0]==="B"?"fixed":p.selected===x[0]?"selected":""}" cx="${q[0]}" cy="${q[1]}" r="14" data-point="${x[0]}"/><text class="target-number ${solution&&x[0]==="B"?"fixed":""}" x="${q[0]}" y="${q[1]}">${x[0]}</text>`}).join("")}<text class="sea-label" x="300" y="55">MAR BÁLTICO</text><text class="sea-label" x="45" y="188">LAGO MÄLAREN</text></svg>`);return base}
  function sapmiMarkup(scope,solution=false){const p=getProg(scope),base=geoMap({bounds:[-2,43,57,72.8]}),zones=[["A","65,30 345,25 370,112 120,128 45,90"],["B","80,188 265,175 270,255 88,270"],["C","250,110 395,95 400,190 275,190"]];return base.replace("</svg>",`${zones.map(z=>`<polygon points="${z[1]}" data-point="${z[0]}" fill="${solution&&z[0]==="A"?"rgba(247,201,0,.55)":p.selected===z[0]?"rgba(247,201,0,.35)":"rgba(255,255,255,.08)"}" stroke="${z[0]==="A"&&solution?"#9b7e00":"#173d50"}" stroke-width="2" stroke-dasharray="6 4"/><text class="target-number" x="${z[0]==="A"?210:z[0]==="B"?170:330}" y="${z[0]==="A"?75:z[0]==="B"?225:150}">${z[0]}</text>`).join("")}</svg>`)}
  function samiFlagCard(){return `<div class="puzzle-card"><p class="kicker">SEÑAL RECUPERADA</p><span class="flag" style="max-width:220px">${flagSvg("sami")}</span><p style="margin:12px 0 0">La bandera sami une azul, rojo, verde y amarillo. El círculo representa el sol y la luna.</p></div>`}
  function northuldraComparison(){return `<section class="culture-compare" aria-label="Comparación entre ficción y cultura sámi real"><figure><img src="${imgBase}comunidad-norte-ficcion-original.png" alt="Recreación original de una comunidad fantástica en un bosque del norte"><figcaption><strong>FICCIÓN</strong><span>Recreación original para la app. Evoca una comunidad fantástica del Norte, pero no copia ninguna escena ni representa al pueblo sámi.</span></figcaption></figure><figure><img src="${imgBase}familia-sami-jokkmokk-2025.jpg" alt="Familia sámi con ropa tradicional y renos en el mercado de invierno de Jokkmokk en 2025"><figcaption><strong>REALIDAD</strong><span>Familia sámi en el mercado de invierno de Jokkmokk, Suecia, 2025. La ropa tradicional varía según la región, la familia y la ocasión.</span></figcaption></figure><details class="dossier culture-credit"><summary>IMÁGENES Y PROCEDENCIA</summary><p>La primera imagen fue generada expresamente para Código Gripsholm y no reproduce un fotograma de <em>Frozen 2</em>. Fotografía real: «Sami family with their reindeer», LittleLoop, Wikimedia Commons, licencia CC BY-SA 4.0. <a href="https://commons.wikimedia.org/wiki/File:Sami_family_with_their_reindeer.jpg" target="_blank" rel="noopener">Ver fuente y licencia</a>.</p></details></section>`}
  const flagSvg=code=>({dk:`<svg viewBox="0 0 80 50"><rect width="80" height="50" fill="#c8102e"/><path d="M25 0v50M0 25h80" stroke="#fff" stroke-width="8"/></svg>`,se:`<svg viewBox="0 0 80 50"><rect width="80" height="50" fill="#006aa7"/><path d="M25 0v50M0 25h80" stroke="#fecc02" stroke-width="8"/></svg>`,no:`<svg viewBox="0 0 80 50"><rect width="80" height="50" fill="#ba0c2f"/><path d="M25 0v50M0 25h80" stroke="#fff" stroke-width="10"/><path d="M25 0v50M0 25h80" stroke="#00205b" stroke-width="5"/></svg>`,fi:`<svg viewBox="0 0 80 50"><rect width="80" height="50" fill="#fff"/><path d="M25 0v50M0 25h80" stroke="#003580" stroke-width="8"/></svg>`,is:`<svg viewBox="0 0 80 50"><rect width="80" height="50" fill="#02529c"/><path d="M25 0v50M0 25h80" stroke="#fff" stroke-width="10"/><path d="M25 0v50M0 25h80" stroke="#dc1e35" stroke-width="5"/></svg>`,fo:`<svg viewBox="0 0 80 50"><rect width="80" height="50" fill="#fff"/><path d="M25 0v50M0 25h80" stroke="#0065bd" stroke-width="10"/><path d="M25 0v50M0 25h80" stroke="#ed2939" stroke-width="5"/></svg>`,ax:`<svg viewBox="0 0 80 50"><rect width="80" height="50" fill="#0053a5"/><path d="M25 0v50M0 25h80" stroke="#ffce00" stroke-width="10"/><path d="M25 0v50M0 25h80" stroke="#d21034" stroke-width="5"/></svg>`,gl:`<svg viewBox="0 0 80 50"><rect width="80" height="25" fill="#fff"/><rect y="25" width="80" height="25" fill="#d00c33"/><circle cx="30" cy="25" r="15" fill="#fff"/><path d="M15 25a15 15 0 0 1 30 0" fill="#d00c33"/></svg>`,sami:`<svg viewBox="0 0 80 50"><rect width="20" height="50" fill="#1575b9"/><rect x="20" width="18" height="50" fill="#d52b36"/><rect x="38" width="18" height="50" fill="#f5d000"/><rect x="56" width="24" height="50" fill="#2a8b57"/><circle cx="38" cy="25" r="15" fill="none" stroke="#1575b9" stroke-width="5"/><path d="M38 10a15 15 0 0 0 0 30" fill="none" stroke="#d52b36" stroke-width="5"/></svg>`}[code]||"");

  function updateFundDialog(){const available=state.spent?state.balance-state.spent:state.balance,missing=Math.max(0,300-state.balance);$("#fund-dialog-title").textContent=state.spent?`${available} kr en reserva`:`${state.balance} kr recuperadas`;$("#fund-meter").style.width=`${Math.min(100,state.balance/3)}%`;$("#fund-ledger").innerHTML=state.spent?`<div><dt>Total recuperado</dt><dd>${state.balance} kr</dd></div><div><dt>Utilizado por Saga</dt><dd>300 kr</dd></div><div><dt>Reserva disponible</dt><dd>${available} kr</dd></div>`:`<div><dt>Mínimo diario</dt><dd>300 kr</dd></div><div><dt>Pendiente para hoy</dt><dd>${missing} kr</dd></div><div><dt>Bonificación incluida</dt><dd>${state.bonus} kr</dd></div>`}
  function openMenu(){const list=$("#mission-menu");list.innerHTML=missions.map((m,i)=>`<button type="button" data-jump="${i}" ${i>state.completedMissions.length?"disabled":""}><span class="${state.completedMissions.includes(i)?"done":""}">${state.completedMissions.includes(i)?"✓":String(i+1).padStart(2,"0")}</span><strong>${m.title}</strong><small>${state.completedMissions.includes(i)?"completada":i===state.mission?"actual":"bloqueada"}</small></button>`).join("");list.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>{$("#menu-dialog").close();state.mission=+b.dataset.jump;state.key=0;state.stage="missionCover";save();render()});$("#menu-dialog").showModal()}
  $("#fund-btn").onclick=()=>{updateFundDialog();$("#fund-dialog").showModal()};$("#menu-btn").onclick=openMenu;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());document.querySelectorAll("dialog").forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});$("#restart-btn").onclick=()=>{if(confirm("¿Borrar todo el progreso del Día 00?")){localStorage.removeItem(STORE);state=defaultState();$("#menu-dialog").close();render()}};
  if("serviceWorker" in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("service-worker.js?v=8-08").catch(()=>{});
  /* V7: se conserva el motor de V4, pero se sustituyen sus cierres económicos por evidencias. */
  const progressBlock=(current,total,label)=>`<section class="progress-block" aria-label="${esc(label)}: ${current} de ${total}"><div><span>${esc(label)}</span><strong>${current} de ${total}</strong></div><i><b style="width:${Math.round((current/total)*100)}%"></b></i></section>`;
  const sagaImage=(alt="Saga transmite desde La Carta")=>`<figure class="hero-photo character-hero"><img src="${imgBase}saga-transmision-inicial.png" alt="${esc(alt)}"></figure>`;
  const missionCloseCopy={
    "El viaje tiene un lugar":"Ya no viajamos hacia el Norte. Vamos a Suecia.",
    "Las cruces nórdicas":"La Carta se refiere a Suecia. Hemos identificado su bandera y su país.",
    "El mar bloqueado":"Suecia tiene salida al mar. La Carta vuelve a mostrar rutas, no una frontera cerrada.",
    "Tras la huella de Frozen":"Sápmi ha vuelto a la Carta sin convertir una cultura viva en un país o algo decorativo.",
    "Tres palabras y una coordenada":"Ya podéis abrir, agradecer y cerrar una conversación."
  };
  const reactionFor=q=>({
    "m1-map":"Que no se te olvide que nuestra misión es en Suecia. Vamos a empezar en Estocolmo.",
    "m1-scandinavia":"Finlandia e Islandia son países nórdicos, pero no se incluyen normalmente en este uso de Escandinavia.",
    "m1-precise":"Aunque los países escandinavos formaron una agrupación, también se pelearon entre sí. Lo vas a entender en la misión.",
    "m2-flags":"La Sombra ya no puede usar la cruz nórdica para decir que todo es lo mismo.",
    "m2-aland":"La Sombra nos quería hacer pensar que era un país. Prepárate: quizá os toque visitar este territorio.",
    "m2-legend":"La leyenda del Dannebrog explica por qué la cruz se convirtió en un símbolo importante en el norte. Pero compartir una cruz no significa tener la misma historia.",
    "m3-water":"La Carta confirma que mares y lagos son fundamentales para Suecia. Si no sabes diferenciar un golfo de un estrecho, pregunta a tus padres.",
    "m3-city":"En la Carta hemos reconstruido los límites de Suecia y descubierto por qué Estocolmo se levantó junto al agua.",
    "m3-coast":"Que no te líen. Noruega no cerró el mar a Suecia: ocupa gran parte de la costa más al norte y hacia el oeste.",
    "m4-sapmi-map":"Sápmi no es un país: es el territorio ancestral del pueblo sami, presente hoy en varios países del norte.",
    "m4-sapmi-name":"Hemos recuperado y respetado la cultura Sápmi que vuelve a estar en la Carta.",
    "m4-frozen":"No se trata de un país, pero sí de un territorio cultural.",
    "m5-hej":"Una palabra pequeña puede abrir una conversación.",
    "m5-tack":"Con curiosidad y respeto, una conversación ya ha empezado.",
    "m5-hejda":"Ya sé que sois las personas que me pueden ayudar a localizar a mis padres."
  }[q.id]||"La Carta ha recuperado una evidencia útil.");
  renderMissionCover=()=>{const m=missions[state.mission],n=state.mission+1;setChrome({mission:state.mission,progress:(state.completedMissions.length/missionTotal())*100});screen.className="screen dark mission-scene-screen";screen.innerHTML=`${sagaImage("Saga abre la misión ${n}: ${m.title}")}<p class="kicker">SAGA · NUEVO BLOQUE DE LA CARTA</p><h2>${m.title}</h2><p class="scene-dialogue">${m.obstacle}</p><section class="mission-brief"><p class="kicker">LO QUE NECESITAMOS ENTENDER</p><p>${m.goal}</p><p><strong>Al terminar:</strong> ${m.done}</p></section>${progressBlock(state.completedMissions.length,missionTotal(),"Evidencias de la Carta")}`;setActions([{label:m.action,run:()=>{state.key=0;state.stage="key";save();render()}}],true)};
  function mediaCard(media){return `<figure class="context-map"><img src="${imgBase+media.file}" alt="${media.alt||"Imagen de apoyo"}"><figcaption>${media.caption||"Imagen de apoyo"}</figcaption></figure>`}
  renderKey=()=>{const m=missions[state.mission],q=m.questions[state.key],scope=keyScope(q),missionNumber=state.mission+1;setChrome({mission:state.mission,progress:((state.mission+state.key/m.keys)/missionTotal())*100});screen.className="screen";screen.innerHTML=`<p class="key-count">MISIÓN ${missionNumber} DE ${missionTotal()} · RETO ${state.key+1} DE ${m.keys}</p>${progressBlock(state.key,m.keys,"Progreso de la misión")}<h2>${q.title}</h2><p>${q.prompt}</p>${q.media?mediaCard(q.media):""}${questionMarkup(q,scope)}<div id="feedback"></div>`;bindQuestion(q,scope,false)};
  showSuccess=(q,scope,correction)=>{const f=$("#feedback");if(f)f.innerHTML=`<div class="feedback"><strong>${q.type==="stockholm"?"PASO LOCALIZADO":"EVIDENCIA RECUPERADA"}</strong><p>${q.explanation}</p></div><section class="character-response"><img src="${imgBase}saga-transmision-inicial.png" alt="Saga confirma la evidencia recuperada"><div><p class="kicker">SAGA CONFIRMA</p><p>${reactionFor(q)}</p></div></section>`;setActions([{label:correction?(state.correctedKeys.length===state.failedKeys.length?"Cerrar el repaso":"Volver al repaso"):nextKeyLabel(),run:()=>advance(correction)}])};
  renderMissionEnd=()=>{const m=missions[state.mission];if(!state.completedMissions.includes(state.mission))state.completedMissions.push(state.mission);save();setChrome({mission:state.mission,progress:(state.completedMissions.length/missionTotal())*100});screen.className="screen dark mission-scene-screen";screen.innerHTML=`${sagaImage("Saga cierra la misión ${state.mission+1}: ${m.title}")}<p class="kicker">SAGA · EVIDENCIA RECUPERADA</p><h2>${m.title}</h2><p class="scene-dialogue">${missionCloseCopy[m.title]||m.done}</p><section class="mission-brief"><p class="kicker">LO QUE HEMOS CONSEGUIDO</p><p>${m.done}</p><p><strong>La siguiente misión parte de esta evidencia.</strong></p></section>${progressBlock(state.completedMissions.length,missionTotal(),"Evidencias de la Carta")}`;const last=state.mission===missionTotal()-1;setActions([{label:"Salir por ahora",kind:"secondary",run:()=>{if(!last){state.mission++;state.key=0;state.stage="landing"}else state.stage="ending";save();render()}},{label:last?"Revelar la coordenada":`Ir a la misión ${state.mission+2}`,run:()=>{if(last)state.stage="ending";else{state.mission++;state.key=0;state.stage="missionCover"}save();render()}}],true)};
  showSuccess=(q,scope,correction)=>{const f=$("#feedback");if(f)f.innerHTML=`<div class="feedback"><strong>${q.type==="stockholm"?"PASO LOCALIZADO":"EVIDENCIA RECUPERADA"}</strong><p>${q.explanation}</p></div>`;setActions([{label:correction?(state.correctedKeys.length===state.failedKeys.length?"Cerrar el repaso":"Volver al repaso"):nextKeyLabel(),run:()=>advance(correction)}])};
  renderMissionEnd=()=>{const m=missions[state.mission];if(!state.completedMissions.includes(state.mission))state.completedMissions.push(state.mission);save();setChrome({mission:state.mission,progress:(state.completedMissions.length/missionTotal())*100});screen.className="screen result";screen.innerHTML=`<div class="mission-complete"><div class="seal">✓</div><p class="kicker">EVIDENCIA RECUPERADA</p><h2>${m.title}</h2><p>${m.done}</p><div class="reward-ledger"><div><span>Evidencia del día</span><strong>◈ Guardada</strong></div><div><span>Progreso</span><strong>${state.completedMissions.length} de ${missionTotal()} misiones</strong></div></div><div class="mission-progress">${fundMessage()}<br>Tu progreso se ha guardado automáticamente.</div></div>`;const last=state.mission===missionTotal()-1;setActions([{label:"Salir por ahora",kind:"secondary",run:()=>{if(!last){state.mission++;state.key=0;state.stage="landing"}else state.stage="ending";save();render()}},{label:last?"Revelar la coordenada":`Ir a la misión ${state.mission+2}`,run:()=>{if(last)state.stage="ending";else{state.mission++;state.key=0;state.stage="missionCover"}save();render()}}])};
  renderEnding=()=>{setChrome({dark:true,progress:100});screen.className="screen dark";const pages=[`<figure class="hero-photo"><img src="${imgBase}saga-canal-asegurado.png" alt="Saga continúa la transmisión"></figure><p class="kicker">ATLAS RECUPERADO</p><h2>Lo habéis conseguido.</h2><p>El Atlas vuelve a leer el Norte con rutas, agua, lenguas, territorios y pruebas.</p><p>Pero hay algo que no entiendo: mis padres diseñaron el sistema para que solo respondiera a mi familia. Aun así, os ha dejado entrar.</p><p class="lead"><strong>Creo que os estaba esperando.</strong></p>`,`<p class="kicker">PRIMERA COORDENADA</p><h1>Una fecha. Un testigo.</h1><div class="coordinate">59.325° N&nbsp;&nbsp;18.070° E<br><br>08·11·1520<br>TESTIGO: K █ R I N<br>ESTADO: NO REGISTRADA</div><p>La coordenada apunta a una plaza de Estocolmo: <strong>Stortorget</strong>.</p><p>No sé si Karin era una testigo, una identidad creada para proteger una historia o una forma de conservar una voz sin inventar la de una víctima real.</p>`,`<p class="kicker">INTENTO DE ACCESO DETECTADO</p><h1>La Sombra sigue buscando.</h1><p class="lead">Otro dispositivo acaba de intentar abrir la ruta.</p><p>No ha entrado. Todavía.</p><p>Mañana la historia comienza en Estocolmo. Si encuentras tres coronas, no supongas que decoran el mapa.</p><div class="three-crowns">♛ ♛ ♛</div>`];screen.innerHTML=pages[state.endingPage];setActions([{label:state.endingPage===0?"Revelar la primera coordenada":state.endingPage===1?"Seguir la señal":"Cerrar el Día 0",run:()=>{if(state.endingPage<2)state.endingPage++;else{state.stage="result";state.finished=true}save();render()}}],true)};
  renderResult=()=>{setChrome({progress:100});screen.className="screen result";screen.innerHTML=`<div class="mission-complete"><div class="seal">♛♛♛</div><p class="kicker">DÍA 00 COMPLETADO</p><h1>Atlas del Norte legible</h1><p>Has recuperado ruta, banderas, agua, cultura y una primera conversación en sueco.</p><div class="reward-ledger"><div><span>Evidencia recuperada</span><strong>Atlas del Norte</strong></div><div><span>Siguiente señal</span><strong>Stortorget · Karin</strong></div></div><p><strong>Pregunta abierta:</strong> ¿Por qué el sistema de los padres os reconoce y quién quiere borrar el contexto que conduce a Gripsholm?</p></div>`;setActions([{label:"Ver las misiones",kind:"secondary",run:openMenu},{label:"Abrir el Día 01",run:()=>{location.href="dia1.html"}}])};
  updateFundDialog=()=>{$("#fund-dialog-title").textContent=`${state.completedMissions.length} de ${missionTotal()} evidencias recuperadas`;$("#fund-meter").style.width=`${Math.round((state.completedMissions.length/missionTotal())*100)}%`;$("#fund-ledger").innerHTML=missions.map((m,i)=>`<div><dt>${state.completedMissions.includes(i)?"✓":"○"} ${m.title}</dt><dd>${state.completedMissions.includes(i)?"recuperada":"pendiente"}</dd></div>`).join("")};
  // Sobrescrituras finales de la experiencia V7 del Día 0.
  // Estas versiones prevalecen sobre los adaptadores heredados de la V4.
  showSuccess=(q,scope,correction)=>{const f=$("#feedback");if(f)f.innerHTML=`<div class="feedback"><strong>${q.type==="stockholm"?"PASO LOCALIZADO":"EVIDENCIA RECUPERADA"}</strong><p>${q.explanation}</p></div><section class="character-response"><img src="${imgBase}saga-transmision-inicial.png" alt="Saga confirma la evidencia recuperada"><div><p class="kicker">SAGA CONFIRMA</p><p>${reactionFor(q)}</p></div></section>`;setActions([{label:correction?(state.correctedKeys.length===state.failedKeys.length?"Cerrar el repaso":"Volver al repaso"):nextKeyLabel(),run:()=>advance(correction)}])};
  renderMissionEnd=()=>{const m=missions[state.mission];if(!state.completedMissions.includes(state.mission))state.completedMissions.push(state.mission);save();setChrome({mission:state.mission,progress:(state.completedMissions.length/missionTotal())*100});screen.className="screen dark mission-scene-screen";screen.innerHTML=`${sagaImage("Saga cierra la misión ${state.mission+1}: ${m.title}")}<p class="kicker">SAGA · EVIDENCIA RECUPERADA</p><h2>${m.title}</h2><p class="scene-dialogue">${missionCloseCopy[m.title]||m.done}</p><section class="mission-brief"><p class="kicker">LO QUE HEMOS CONSEGUIDO</p><p>${m.done}</p><p><strong>La siguiente misión parte de esta evidencia.</strong></p></section>${progressBlock(state.completedMissions.length,missionTotal(),"Evidencias de la Carta")}`;const last=state.mission===missionTotal()-1;setActions([{label:"Salir por ahora",kind:"secondary",run:()=>{if(!last){state.mission++;state.key=0;state.stage="landing"}else state.stage="ending";save();render()}},{label:last?"Revelar la coordenada":`Ir a la misión ${state.mission+2}`,run:()=>{if(last)state.stage="ending";else{state.mission++;state.key=0;state.stage="missionCover"}save();render()}}],true)};
  const baseSolutionExtra=solutionExtra;
  solutionExtra=q=>{
    if(q.type==="trueFalse"){
      const p=getProg(keyScope(q)), results=p.booleanResults||[];
      const correct=results.filter(item=>item.answer===item.solution).length;
      const errors=results.length-correct;
      return `<section class="puzzle-card"><p class="kicker">RESUMEN DE SEÑALES SUECAS</p><p><strong>${correct} aciertos · ${errors} errores</strong></p>${results.map(item=>`<p><strong>Pregunta:</strong> ${item.question}<br><strong>Tu respuesta:</strong> ${item.answer?"Verdadero":"Falso"}<br><strong>Solución:</strong> ${item.solution?"Verdadero":"Falso"} · ${item.answer===item.solution?"acierto":"error"}</p>`).join("")}</section>`;
    }
    if(q.type==="timer"){
      const p=getProg(keyScope(q)), results=p.timerResults||[];
      const correct=results.filter(item=>item.answer===item.country).length;
      const errors=results.length-correct;
      return `<section class="puzzle-card"><p class="kicker">RESUMEN DE CRUCES A CONTRARRELOJ</p><p><strong>${correct} aciertos · ${errors} errores</strong></p>${results.map(item=>`<p><span class="flag" style="display:inline-block;width:54px;vertical-align:middle;margin-right:8px">${flagSvg(item.flag)}</span><strong>${item.country}</strong><br><small>Tu respuesta: ${item.answer||"sin responder"} · ${item.answer===item.country?"acierto":"solución: "+item.country}</small></p>`).join("")}</section>`;
    }
    if(q.type!=="flagMatch")return baseSolutionExtra(q);
    const p=getProg(keyScope(q));
    return `<section class="puzzle-card"><p class="kicker">LAS SIETE BANDERAS FIJADAS</p><p>La solución completa incluye también Åland.</p>${q.pairs.map(([flag,country])=>`<p><span class="flag" style="display:inline-block;width:54px;vertical-align:middle;margin-right:8px">${flagSvg(flag)}</span><strong>${country}</strong> · ${p.mistakes?.includes(country)?"revisada después de un fallo":"acertada"}</p>`).join("")}</section>`;
  };
  const baseBindFlagMatch=bindFlagMatch;
  bindFlagMatch=(q,scope,correction)=>{
    const p=getProg(scope);p.fixed||={};p.pending||={};p.mistakes||=[];
    screen.querySelectorAll("[data-flag]").forEach(b=>b.onclick=()=>{p.selectedFlag=b.dataset.flag;save();renderCurrent(q,scope,correction)});
    screen.querySelectorAll("[data-flag-target]").forEach(b=>b.onclick=()=>{if(!p.selectedFlag||p.fixed[b.dataset.flagTarget])return;Object.keys(p.pending).forEach(k=>{if(p.pending[k]===p.selectedFlag)delete p.pending[k]});p.pending[b.dataset.flagTarget]=p.selectedFlag;p.selectedFlag=null;save();renderCurrent(q,scope,correction)});
    const ready=Object.keys(p.fixed).length+Object.keys(p.pending).length===q.pairs.length;
    setActions([{label:"Comprobar las banderas",disabled:!ready,run:()=>{q.pairs.forEach(([flag,country])=>{if(p.pending[country]===flag){p.fixed[country]=flag;delete p.pending[country]}else if(p.pending[country]){p.mistakes.push(country);delete p.pending[country]}});if(Object.keys(p.fixed).length===q.pairs.length){markCheck(scope);completeKey(q,scope,correction)}else{markFailure(q,scope,correction);save();renderCurrent(q,scope,correction,`Has recuperado ${Object.keys(p.fixed).length} de ${q.pairs.length}. ${q.hint}`)}}}]);
  };
  bindTrueFalse=(q,scope,correction)=>{
    const p=getProg(scope), i=p.index||0, item=q.items[i];
    p.booleanResults||=[];
    if(p.answer==null){
      screen.querySelectorAll("[data-boolean]").forEach(button=>button.onclick=()=>{p.answer=button.dataset.boolean==="true";save();renderCurrent(q,scope,correction)});
      setActions([{label:"Elige una opción",disabled:true,run:()=>{}}]);
      return;
    }
    const saveAnswer=()=>{if(!p.booleanResults.some(result=>result.index===i))p.booleanResults.push({index:i,question:item.label,answer:p.answer,solution:item.answer});};
    const last=i===q.items.length-1;
    setActions([{label:last?"Guardar el reto opcional":"Siguiente señal",run:()=>{saveAnswer();if(last){save();completeKey(q,scope,correction)}else{p.index=i+1;delete p.answer;save();renderCurrent(q,scope,correction)}}}]);
  };
  startTimer=(q,scope,correction)=>{
    const rounds=[["se","Suecia",["Suecia","Finlandia","Islandia"]],["dk","Dinamarca",["Noruega","Dinamarca","Feroe"]],["fi","Finlandia",["Finlandia","Suecia","Åland"]],["no","Noruega",["Islandia","Noruega","Dinamarca"]],["is","Islandia",["Feroe","Finlandia","Islandia"]]];
    const p=getProg(scope);p.timerResults=[];let i=0,left=45;
    setActions([]);
    const finish=()=>{clearInterval(tick);while(p.timerResults.length<rounds.length){const round=rounds[p.timerResults.length];p.timerResults.push({flag:round[0],country:round[1],answer:null})}save();completeKey(q,scope,correction)};
    const draw=()=>{if(i===rounds.length)return finish();$("#timer-copy").textContent=`Señal ${i+1} de ${rounds.length}`;$("#timer-game").innerHTML=`<span class="flag" style="max-width:180px;margin:12px auto">${flagSvg(rounds[i][0])}</span><div class="options">${rounds[i][2].map(answer=>`<button class="option timer-answer">${answer}</button>`).join("")}</div>`;screen.querySelectorAll(".timer-answer").forEach(button=>button.onclick=()=>{p.timerResults.push({flag:rounds[i][0],country:rounds[i][1],answer:button.textContent});i++;draw()})};
    const tick=setInterval(()=>{left--;if($("#timer"))$("#timer").textContent=`00:${String(left).padStart(2,"0")}`;if(left<=0)finish()},1000);
    draw();
  };
  showSuccess=(q,scope,correction)=>{const f=$("#feedback");if(f)f.innerHTML=`<div class="feedback"><strong>${q.type==="stockholm"?"PASO LOCALIZADO":"EVIDENCIA RECUPERADA"}</strong><p>${q.explanation}</p></div>${solutionExtra(q)}<section class="character-response"><img src="${imgBase}saga-transmision-inicial.png" alt="Saga confirma la evidencia recuperada"><div><p class="kicker">SAGA CONFIRMA</p><p>${reactionFor(q)}</p></div></section>`;setActions([{label:correction?(state.correctedKeys.length===state.failedKeys.length?"Cerrar el repaso":"Volver al repaso"):nextKeyLabel(),run:()=>advance(correction)}])};
  renderEnding=()=>{setChrome({dark:true,progress:100});screen.className="screen dark";const p=(window.DAY0_V8_ENDING||[])[state.endingPage];if(!p){state.stage="result";state.finished=true;save();return render()}screen.innerHTML=`${p.image?`<figure class="hero-photo character-hero"><img src="${imgBase+p.image}" alt="Saga cierra el Día 0"><figcaption>Saga · transmisión de La Carta</figcaption></figure>`:""}<p class="kicker">${p.kicker}</p><h2>${p.title}</h2>${p.html}${progressBlock(missionTotal(),missionTotal(),"Evidencias de la Carta")}`;setActions([{label:p.action,run:()=>{if(state.endingPage<(window.DAY0_V8_ENDING.length-1))state.endingPage++;else{state.stage="result";state.finished=true}save();render()}}],true)};
  renderResult=()=>{setChrome({progress:100});screen.className="screen result";screen.innerHTML=`<div class="mission-complete"><div class="seal">♛♛♛</div><p class="kicker">DÍA 00 COMPLETADO</p><h1>La ruta borrada</h1><p>La transmisión queda asegurada y las cinco evidencias de la Carta están completas.</p>${progressBlock(missionTotal(),missionTotal(),"Evidencias de la Carta")}<p><strong>Siguiente señal:</strong><br>Stortorget · 8 de noviembre de 1520 · Karin.</p></div>`;setActions([{label:"Ver las misiones",kind:"secondary",run:openMenu},{label:"Abrir el Día 01",run:()=>{location.href="dia1.html"}}])};
  render();
})();
