/* Día 0 aprobado · contenido para el motor visual heredado de V4. */
window.DAY0_V7_PROLOGUE = [
  { k: 'TRANSMISIÓN INTERCEPTADA', title: 'No me conocéis.', photo: true, html: '<p>Yo, en cambio, sé tres cosas sobre vosotras: vais a viajar en familia a Suecia, dentro de unos días llegaréis a Gripsholm y habéis abierto un mapa que nadie debía poder alterar.</p><p>Mis padres eran cartógrafos. Prepararon esta Carta para este viaje, pero anoche alguien entró en su estudio. Las cámaras dejaron de grabar durante nueve minutos. Cuando volvieron, ellos ya no estaban.</p>' },
  { k: 'IDENTIDAD CONFIRMADA', title: 'Me llamo Saga.', photo: true, html: '<p>Una <em>saga</em> es una historia larga. Mis padres encontraban divertido llamar así a la hija de dos cartógrafos.</p><p>Yo conozco la Carta, pero algo no encaja. Intuyo que han cambiado algunos lugares y pistas.</p><p>Vosotras podéis ayudarme a reconstruirla antes de que una pista falsa nos lleve por el camino equivocado.</p>' },
  { k: 'LA SOMBRA', title: 'El mapa ha perdido sus relaciones.', html: '<p>Alguien ha vuelto a entrar en el sistema. No sé quiénes son, pero mis padres los llamaban <strong>La Sombra</strong>.</p><p>Antes de desaparecer dejaron una instrucción: <em>«No sigáis las coordenadas de esta Carta sin más. Buscad antes su sentido».</em></p><p>Os pido que me ayudéis a devolver el sentido a esta Carta para poder encontrar a mis padres.</p>' },
  { k: 'UNA PREGUNTA ABIERTA', title: 'El sistema os ha dejado entrar.', html: '<p>Este sistema debía reconocer únicamente a mi familia. Sin embargo, os ha dejado entrar.</p><p>Primero hagamos legible la Carta del Norte; después descubriremos por qué os estaba esperando.</p><p class="lead"><strong>Primera tarea: situar el viaje sin borrar su contexto.</strong></p>' }
];

window.DAY0_V7_MISSIONS = [
  {
    title: 'El viaje tiene un lugar', obstacle: 'La Sombra ha borrado el país al que viajáis y solo ha dejado una flecha hacia «el Norte».', label: 'Misión 01 · Situar la Carta', goal: 'Eso no sirve. Una misión empieza cuando sabes contar dónde pasa.', keys: 3, time: '4–6 min', action: 'Situar el viaje', done: 'La ruta de la Carta ya tiene un país, vecinos y una primera regla.', questions: [
      { id: 'm1-map', type: 'mapPlacement', title: 'El Norte vuelve al mapa', prompt: 'Coloca los cinco países que orientan el inicio del viaje. Los nombres correctos quedarán fijados.', items: [['sweden','Suecia','geo',15.5,62],['norway','Noruega','geo',7.5,64],['finland','Finlandia','geo',26,64.5],['denmark','Dinamarca','geo',10.3,56.1],['iceland','Islandia','geo',-18.5,65]], hint: 'Suecia está al este de Noruega y al oeste de Finlandia. Islandia queda mucho más al oeste, en el Atlántico norte.', explanation: 'Suecia está al este de Noruega y al oeste de Finlandia. Estocolmo se sitúa en su costa oriental, junto al Báltico. Este es el punto de partida de la Carta.' },
      { id: 'm1-scandinavia', type: 'mapCountries', title: 'Nórdico no siempre significa escandinavo', prompt: 'Marca los tres países que se incluyen normalmente en «Escandinavia».', answer: ['Denmark','Norway','Sweden'], hint: 'Finlandia e Islandia son nórdicos, pero no suelen incluirse en este uso cultural de Escandinavia.', explanation: 'Escandinavia suele reunir Dinamarca, Noruega y Suecia. Finlandia e Islandia son países nórdicos, pero no se incluyen normalmente en ese uso de Escandinavia.', solutionMap: 'scandinavia' },
      { id: 'm1-precise', type: 'single', title: 'Una etiqueta bien usada', prompt: '¿Qué frase se ajusta mejor a lo que acabas de recuperar?', options: ['Todo lo nórdico es escandinavo.', 'Suecia es nórdica y escandinava; Finlandia es nórdica, pero no suele llamarse escandinava.', 'Escandinavia es el nombre de un único país.'], answer: 1, mapHint: 'nordic', hint: 'No son etiquetas enemigas: una es más amplia que la otra.', explanation: '«Nórdico» es un marco más amplio que «escandinavo». Saber cuál se está usando evita que el mapa convierta una palabra cómoda en una frontera inventada.' }
    ]
  },
  {
    title: 'Las cruces nórdicas', obstacle: 'La Sombra usa las cruces nórdicas para confundirnos de país.', label: 'Misión 02 · Leer sin simplificar', goal: 'La cruz nórdica es común, pero cada país tiene su bandera.', keys: 4, time: '5–7 min', action: 'Abrir las banderas', done: 'Relaciona las cruces nórdicas con sus países. Aunque las banderas se parezcan, cada país es distinto.', questions: [
      { id: 'm2-flags', type: 'flagMatch', title: 'Siete banderas con la misma cruz nórdica', prompt: 'Relaciona cada bandera con el país o territorio correcto. Las parejas válidas se quedarán fijadas.', pairs: [['dk','Dinamarca'],['se','Suecia'],['no','Noruega'],['fi','Finlandia'],['is','Islandia'],['fo','Feroe'],['ax','Åland']], hint: 'Todas las cruces se desplazan hacia el asta. Åland combina azul, amarillo y una cruz roja interior.', explanation: 'Cinco banderas corresponden a Estados y dos a territorios autónomos: Feroe y Åland. Una bandera propia no convierte automáticamente a un territorio en Estado independiente.' },
      { id: 'm2-aland', type: 'single', title: '¿Qué es Åland?', prompt: 'Åland es un archipiélago, un conjunto de islas como Canarias, en el Báltico, situado entre Suecia y Finlandia. ¿Qué es?', options: ['Territorio autónomo de Finlandia, con sueco como único idioma oficial.', 'Se habla sueco como idioma oficial, así que es una parte de Suecia.', 'Estado independiente que no guarda relación ni con Finlandia ni con Suecia.'], answer: 0, mapHint: 'aland', hint: 'Lengua y país pueden coincidir, pero no siempre es así.', explanation: 'Åland es un archipiélago autónomo de Finlandia en el Báltico. El sueco es su único idioma oficial y el territorio tiene autonomía para muchas cuestiones.' },
      { id: 'm2-legend', type: 'single', title: 'La historia que cayó del cielo', prompt: 'La tradición danesa cuenta que el Dannebrog cayó del cielo en 1219. ¿Cómo se guarda esa información con rigor?', options: ['Como un documento escrito por alguien que presenció el milagro.', 'Como una leyenda nacional importante, con versiones conocidas posteriores a la batalla.', 'Como una invención reciente de Saga.'], answer: 1, hint: 'Una tradición puede ser importante sin ser un testimonio contemporáneo.', dossier: 'La tradición se relaciona con la batalla de Lindanise, en la actual Estonia. Las versiones conocidas del relato son posteriores, de alrededor de 1500 y del siglo XVI.', explanation: 'La batalla y la expansión danesa en Estonia son históricas. Que la bandera cayera del cielo se conserva como leyenda, no como prueba documental de 1219.', estonia: true },
      { id: 'm2-quick-flags', type: 'timer', optional: true, title: 'Cruces a contrarreloj', prompt: 'Entrénate para demostrar a La Sombra que ya nadie puede confundirte con una cruz nórdica.', explanation: 'La práctica rápida queda guardada. No cambia la evidencia de la misión.' }
    ]
  },
  {
    title: 'El mar bloqueado', obstacle: 'Alguien ha dejado una frase escrita sobre la Carta: «Noruega cerró a Suecia el acceso al mar».', label: 'Misión 03 · Abrir la ruta', goal: 'Descubre qué aguas rodean Suecia, cómo se conectan sus lagos y por qué Estocolmo se construyó en un lugar tan importante.', keys: 4, time: '5–7 min', action: 'Abrir la ruta', done: 'La Carta ya no muestra el agua como una frontera: muestra una red de rutas.', questions: [
      { id: 'm3-water', type: 'waterPlacement', title: 'Mares, lagos y una ciudad entre aguas', prompt: 'Devuelve cada nombre al mapa. Los lagos tienen contorno real; los mares ocupan zonas abiertas.', items: [['baltic','mar Báltico',19.5,57],['bothnia','golfo de Botnia',20,63],['kattegat','Kattegat',11.5,57.4],['vanern','Vänern',13.4,58.9],['vattern','Vättern',14.5,58.3],['malaren','Mälaren',17.3,59.5]], hint: 'El golfo de Botnia es el brazo largo del Báltico entre Suecia y Finlandia. Kattegat queda frente a Gotemburgo.', explanation: 'El Báltico es la gran fachada oriental de Suecia. Kattegat y Skagerrak conectan su costa occidental con el mar del Norte; Mälaren, Vänern y Vättern explican muchas rutas interiores.' },
      { id: 'm3-city', type: 'stockholm', title: '¿Dónde tiene sentido una ciudad-puerto?', prompt: '«La ciudad debía estar donde ningún barco pudiera pasar entre Mälaren y Báltico sin ser visto». Marca A, B o C.', answer: 'B', hint: 'Busca el paso obligado entre el lago y el mar.', explanation: 'Estocolmo creció en el estrecho entre Mälaren y el Báltico. Esa posición servía para rutas, defensa, comercio e impuestos.' },
      { id: 'm3-coast', type: 'single', title: 'El informe de la costa cerrada', prompt: 'Alguien ha escrito: «Noruega cerró a Suecia el acceso al mar». ¿Qué frase es la verdadera?', options: ['Noruega estuvo constantemente en guerra con Suecia para bloquear su acceso al mar.', 'Suecia nunca necesitó llegar al mar y por eso no tiene salida al mar.', 'Suecia conserva una gran costa báltica y una salida occidental por Gotemburgo.'], answer: 2, hint: 'Mira las dos costas y recuerda que las fronteras se formaron durante siglos.', explanation: 'Suecia tiene costa al este, junto al mar Báltico. Al oeste tiene salida por Kattegat, al sur, entre Suecia y Dinamarca, y por Skagerrak, al norte, entre Suecia y Noruega, que se abre hacia el mar del Norte.' },
      { id: 'm3-swedish-signals', type: 'trueFalse', optional: true, title: 'Señales suecas', prompt: 'Decide si cada palabra o afirmación es sueca. No es un examen: cada tarjeta explica la respuesta antes de continuar.', explanation: 'Ya puedes reconocer algunas señales suecas sin confundirlas con las de sus vecinas.', items: [
        { label: 'IKEA', answer: true, explanation: 'Verdadero. IKEA nació en Suecia en 1943.' },
        { label: 'LEGO', answer: false, explanation: 'Falso. LEGO es una empresa danesa.' },
        { label: 'Alfred Nobel', answer: true, explanation: 'Verdadero. Alfred Nobel fue un inventor y empresario sueco.' },
        { label: 'Spotify', answer: true, explanation: 'Verdadero. Spotify se fundó en Suecia.' },
        { label: 'Nokia', answer: false, explanation: 'Falso. Nokia es una empresa finlandesa.' },
        { label: 'Volvo', answer: true, explanation: 'Verdadero. Volvo nació en Gotemburgo.' },
        { label: 'ABBA', answer: true, explanation: 'Verdadero. ABBA es un grupo sueco.' },
        { label: 'Björk', answer: false, explanation: 'Falso. Björk es islandesa.' },
        { label: 'Zara', answer: false, explanation: 'Falso. Zara nació en España.' },
        { label: 'El Nobel de la Paz se entrega en Estocolmo', answer: false, explanation: 'Falso. El Nobel de la Paz se entrega en Oslo.' },
        { label: 'Los demás premios Nobel se entregan en Estocolmo', answer: true, explanation: 'Verdadero. Física, Química, Medicina, Literatura y Economía se entregan en Estocolmo.' }
      ] }
    ]
  },
  {
    title: 'Tras la huella de Frozen', obstacle: 'La Sombra ha borrado Sápmi porque no cabe dentro de un solo país.', label: 'Misión 04 · Devolver una cultura al mapa', goal: 'Localiza Sápmi y separa una cultura indígena real de la ficción inspirada en ella.', keys: 3, time: '4–6 min', action: 'Tras la huella de Frozen', done: 'Sápmi vuelve a la Carta como territorio cultural, no como una frontera inventada.', questions: [
      { id: 'm4-sapmi-map', type: 'sapmi', title: 'La zona que atraviesa fronteras', prompt: 'La pista dice: «Cruza Noruega, Suecia y Finlandia y alcanza la península de Kola». Elige A, B o C.', answer: 'A', hint: 'No busques una provincia dentro de Suecia. La pista atraviesa cuatro Estados por el extremo norte.', explanation: 'La zona A representa de forma aproximada Sápmi. Atraviesa Noruega, Suecia, Finlandia y parte de la península de Kola en Rusia; no es un Estado ni una provincia única.' },
      { id: 'm4-sapmi-name', type: 'single', title: 'El nombre recuperado', prompt: '¿Qué descripción repara el expediente?', options: ['Sápmi es un nuevo país nórdico.', 'Sápmi es el territorio cultural tradicional del pueblo sami.', 'Sápmi es únicamente una provincia sueca.'], answer: 1, hint: 'Las fronteras estatales atraviesan este territorio cultural.', explanation: 'Los samis son un pueblo indígena y Sápmi es su territorio cultural tradicional. No todas las personas samis viven igual, crían renos ni hablan la misma lengua.', samiFlag: true },
      { id: 'm4-frozen', type: 'single', title: 'Frozen 2 no es un documental', prompt: '¿Qué relación permite disfrutar la película sin confundir ficción y realidad?', options: ['Los Northuldra son una comunidad sami real.', 'Los Northuldra son ficticios; la película tomó inspiración sami y contó con asesores samis.', 'Todos los samis viven como los Northuldra.'], answer: 1, hint: 'La inspiración cultural no convierte un personaje ficticio en una prueba documental.', explanation: 'Los Northuldra son ficticios. Frozen 2 contó con el grupo asesor sami Verddet; eso no convierte a los personajes en «los samis de verdad».', frozen: true }
    ]
  },
  {
    title: 'Tres palabras y una coordenada', obstacle: 'La Carta necesita comprobar que podéis abrir, agradecer y cerrar una conversación.', label: 'Misión 05 · Primer contacto', goal: 'Escucha y usa tres palabras cotidianas.', keys: 3, time: '3–5 min', action: 'Abrir el canal de voz', done: 'Después podéis abrir la primera coordenada.', questions: [
      { id: 'm5-hej', type: 'speech', title: 'La puerta del establecimiento', prompt: 'Entras en una tienda y la persona del mostrador te mira. ¿Qué palabra abre la conversación?', word: 'HEJ', meaning: 'hola', speech: 'hej', tip: 'Escuchar el modelo es más útil que una transcripción española.', explanation: 'Hej abre una conversación cotidiana. Úsala cuando te apetezca: no es un examen.' },
      { id: 'm5-tack', type: 'speech', title: 'El objeto recibido', prompt: 'Te entregan una comida, una entrada o una bebida. ¿Qué palabra muestra agradecimiento?', word: 'TACK', meaning: 'gracias', speech: 'tack', tip: 'La oirás constantemente durante el viaje.', explanation: 'Tack significa «gracias». Una palabra pequeña ya permite entrar en una conversación con curiosidad y respeto.' },
      { id: 'm5-hejda', type: 'speech', title: 'Al despedirse', prompt: 'La conversación termina. ¿Qué palabra puede cerrarla?', word: 'HEJ DÅ', meaning: 'adiós', speech: 'hej då', tip: 'Se escribe en dos palabras. Si el dispositivo tiene voz sueca, puedes escucharla y grabarte si quieres.', explanation: 'Hej då cierra la conversación.' }
    ]
  }
];

window.DAY0_V8_ENDING = [
  { image: 'saga-canal-asegurado.png', kicker: 'LA CARTA RECUPERADA', title: 'Lo habéis conseguido.', html: '<p>La Carta ha sustituido el Norte genérico por Suecia.</p><p>Ya tenemos mares, lagos, rutas, lenguas, territorios e idioma básico.</p><p>Pero el sistema de mis padres, diseñado para responder solo a nuestra familia, os ha dejado entrar.</p><p class="lead"><strong>Sois las personas que estaba esperando.</strong></p>', action: 'Revelar la primera coordenada' },
  { kicker: 'CONSECUENCIA DESBLOQUEADA', title: 'Una fecha. Un testigo.', html: '<div class="coordinate">59.325° N&nbsp;&nbsp;18.070° E<br><br>08·11·1520<br>TESTIGO: K █ R I N<br>ESTADO: NO REGISTRADA</div><p>La coordenada apunta a una plaza de Estocolmo: <strong>Stortorget</strong>.</p><p>La señal conserva una fecha y un nombre incompleto.</p><p>Karin puede ser una testigo, una identidad falsa o una clave que mis padres dejaron para vosotras.</p>', action: 'Seguir la señal' },
  { kicker: 'INTENTO DE ACCESO DETECTADO', title: 'Alguien más busca la coordenada.', html: '<p>Otro dispositivo acaba de intentar abrir la ruta.</p><p>No ha entrado todavía.</p><p>El siguiente día comenzará en Estocolmo.</p><p class="lead">Si encuentras tres coronas, no des por hecho que son decorativas.</p><div class="three-crowns">♛ ♛ ♛</div>', action: 'Cerrar el canal' }
];

window.DAY0_V7_MISSIONS[1].questions[2].media={file:"Danmarks_flag_1219_Lorentzen.jpg",alt:"Pintura de la leyenda del Dannebrog",caption:"La tradición del Dannebrog es una leyenda nacional; no una prueba documental contemporánea de 1219."};
