/* Día 01 · textos V8: Guion_completo_Codigo_Gripsholm_dias_00_a_10_para_revision_V8.docx.
   V4 aporta únicamente motor, mapas y recursos reutilizables. */
(() => {
  const v4 = window.DAY1_DATA || {};
  window.DAY1_DATA = {
    meta:{day:"01",store:"codigo-gripsholm-v8-day01",contentVersion:"v8-day01-final",place:"ESTOCOLMO · GAMLA STAN",title:"La plaza cerrada",landing:"Una fecha, una plaza y una voz que no debemos inventar.",badge:"cuaderno de Karin",objective:"PROTEGER UN TESTIMONIO SIN INVENTARLO",objectiveCopy:"Leeremos Estocolmo, la Unión de Kalmar y la promesa rota antes de decidir qué puede afirmar Karin.",evidenceCopy:"Cada misión conserva una prueba y una pregunta honesta.",fine:"Karin es un personaje ficticio; el contexto histórico y los lugares son reales.",verifiedTitle:"El testimonio queda protegido.",verifiedAction:"Abrir el cierre de Saga",result:{title:"La plaza cerrada",evidence:"Cuaderno de Karin protegido",openQuestion:"¿Por qué La Sombra necesita borrar el nombre Vasa?",next:{href:"dia2.html",label:"Abrir el Día 02"}}},
    prologue: [
      { k:"SAGA · COORDENADA ABIERTA", title:"Una voz en la plaza.", image:"saga-transmision-inicial.png", alt:"Saga abre la coordenada de Estocolmo", html:`<p>La coordenada nos ha traído a una plaza, una fecha y un nombre: <strong>Estocolmo · noviembre de 1520 · Karin</strong>.</p><p>Mis padres construyeron una testigo ficticia para proteger nombres y hechos reales. Así no inventamos la voz de una víctima concreta.</p><p>La Sombra ha intentado borrar la relación entre Cristián II, esta plaza y Gustav Eriksson.</p><p class="lead">Si ayudamos a Karin a conservar lo que realmente sabe, protegeremos la historia.</p>`, action:"Escuchar a Karin" },
      { k:"KARIN · RECONSTRUCCIÓN NARRATIVA", title:"Me llamo Karin.", image:"karin-testimonio-1520-v1.png", alt:"Reconstrucción narrativa de Karin en Estocolmo en 1520", html:`<p><strong>Persona ficticia; contexto histórico real.</strong></p><p>No puedo seguir dándoos pistas hasta saber de dónde venís. La Sombra ha querido borrar nuestro pasado.</p><p>Mi padre salió esta mañana y aún no ha vuelto. Si sabéis leer quiénes fuimos, quizá pueda confiar en vosotras.</p><p class="lead">Entonces os contaré lo que está pasando en la ciudad.</p>`, action:"Abrir la primera página" },
      { k:"MAPA DE ORIENTACIÓN", title:"Una ciudad, varias capas de tiempo.", routeMap:true, html:`<p>Este mapa sirve para el paseo de hoy y para entender el testimonio. Nada depende de seguir un orden exacto: Stortorget, Storkyrkan, el Palacio Real, la piedra rúnica y las tres coronas forman parte de una misma ciudad viva.</p>`, action:"Situar la plaza" }
    ],
    routePlaces: v4.routePlaces || [],
    streetKit: [
      {word:"URSÄKTA",meaning:"perdona / disculpe",speech:"Ursäkta",prompt:"Necesitas preguntar algo a una persona desconocida. ¿Cuándo usarías «Ursäkta»?",options:["Al iniciar una pregunta","Al despedirse","Al recibir algo"],answer:0,tip:"Es una forma amable de llamar la atención antes de preguntar."},
      {word:"VAR LIGGER STORTORGET?",meaning:"¿Dónde está Stortorget?",speech:"Var ligger Stortorget?",prompt:"Quieres localizar la plaza. ¿Qué frase te sirve?",options:["Var ligger Stortorget?","Tack så mycket","Hej då"],answer:0,tip:"Var significa «dónde»; ligger se usa para localizar un lugar."},
      {word:"TACK",meaning:"gracias",speech:"Tack",prompt:"Una persona te ha indicado el camino. ¿Qué dices?",options:["Tack","Ursäkta","Var ligger Stortorget?"],answer:0,tip:"Tack es la forma sencilla de dar las gracias."}
    ],
    missions: [
      {
        title:"Antes de llamarnos suecos", speaker:"Karin", photo:"karin-testimonio-1520-v1.png",
        obstacle:"El mapa llama a este territorio de dos maneras. Antes de preguntar por mi padre, decidme qué pueden significar sin dibujar el país actual sobre un tiempo en que no existía.",
        goal:"Entender Svear y Götar como comunidades y áreas de influencia; recuperar los dos caminos que conducen a Sverige y a Suecia.", keys:1,time:"4–6 min",action:"Leer el primer mapa",done:"Suecia ya no aparece como un país que surgió de golpe: el cuaderno distingue comunidades, nombres y un proceso de siglos.",
        contexts:[
          {k:"COMUNIDADES, NO FRONTERAS MODERNAS",title:"Un mapa antes del país",visual:"sveargotar",html:`<p>Entre aproximadamente <strong>800 y 1050</strong>, la llamada época vikinga reúne comunidades diversas. Muchas personas cultivaban, pescaban, criaban animales, comerciaban, trabajaban el hierro, hacían tejidos o construían barcos.</p><p><strong>Svear</strong> y <strong>Götar</strong> ayudan a hablar de grandes comunidades y áreas de influencia. No eran provincias con líneas exactas como las actuales ni una identidad nacional única.</p><p>Hacia el año 1000, Olof Skötkonung suele considerarse el primer rey cristiano de Suecia. La centralización, las leyes comunes y las instituciones fueron un proceso de siglos. Estocolmo aparece en documentos de <strong>1252</strong>, vinculada a la época de Birger Jarl.</p>`},
          {k:"DICCIONARIO RECUPERADO",title:"Dos formas, dos huellas",visual:"names",html:`<p><strong>Svea rike</strong>, «reino de los Svear», dejó la huella de <strong>Sverige</strong>, el nombre sueco del país.</p><p><strong>Svíþjóð / Svethiudh</strong>, pueblo o tierra de los Svear, dejó huellas en <strong>Suecia</strong>, <em>Sweden</em>, <em>Suède</em> y otros nombres externos emparentados.</p><p>Después de Roma, la península ibérica también reunió suevos en Gallaecia, grupos vándalos y alanos, además de reinos posteriores. Los nombres modernos guardan huellas, no fotografías exactas. Por eso no afirmamos como hecho que «Andalucía viene de los vándalos»: es una explicación popular discutida. En Europa, <em>Alemania</em> o <em>Allemagne</em> guardan la huella de los alamanes; en alemán se dice <em>Deutschland</em>.</p>`}
        ],
        questions:[{id:"d1v7m1",type:"single",visual:"sveargotar",title:"La nota que no falsifica el pasado",scene:"<strong>Contexto visible.</strong> Entre aproximadamente 800 y 1050 vivieron aquí comunidades diversas: agricultura, pesca, ganadería, hierro, tejidos, barcos y comercio. Svear y Götar ayudan a hablar de áreas de influencia, no de fronteras modernas. Hacia el año 1000, Olof Skötkonung suele considerarse el primer rey cristiano; la centralización siguió durante siglos. Estocolmo aparece en documentos de 1252, vinculada a la época de Birger Jarl.",prompt:"¿Qué nota puede quedarse en el cuaderno de Karin?",options:["Svear y Götar nombran comunidades y áreas de influencia; el reino sueco se formó gradualmente y no era todavía el Estado moderno actual.","En el año 900 ya existía Suecia con las fronteras, la bandera y el Gobierno actuales.","Nadie vivía allí hasta que llegaron los vikingos."],answer:0,hint:"Conserva a las personas y las regiones, pero no adelantes siglos de fronteras e instituciones.",dossier:"Dos caminos del nombre: Svea rike («reino de los Svear») dejó la huella de Sverige; Svíþjóð o Svethiudh («pueblo o tierra de los Svear») dejó huellas en Suecia, Sweden o Suède. Igual que los nombres de pueblos posteriores a Roma en la península ibérica, guardan rastros, no fotografías exactas. En Europa, Alemania/Allemagne conserva la huella de los alamanes, mientras que en alemán se dice Deutschland.",success:"ORIGEN LEÍDO CON MATIZ.",explanation:"El nombre del país destaca a los Svear, pero Suecia no se entiende sin los Götar. Ninguna de esas etiquetas dibuja una frontera tribal exacta."}]
      },
      {
        title:"Quiénes eran los vikingos", speaker:"Karin", photo:"karin-testimonio-1520-v1.png",
        obstacle:"Bien. Ya respetáis que Suecia no apareció de golpe. Ahora comprobad si sabéis quiénes eran de verdad los vikingos. Alguien ha colocado un casco con cuernos sobre mi cuaderno.",
        goal:"Separar una caricatura romántica de la evidencia arqueológica y devolver actividades reales a las personas de Escandinavia.", keys:1,time:"4–5 min",action:"Examinar los cascos",done:"La caricatura ha desaparecido: no todos eran vikingos y los cascos de combate conocidos no llevaban cuernos.",
        contexts:[
          {k:"GALERÍA DE EVIDENCIA",title:"Tres cascos, tres épocas",visual:"helmets",html:`<p><strong>Gjermundbu</strong>: época vikinga, Noruega; casco sin cuernos. <strong>Viksø</strong>: Edad del Bronce, hacia el primer milenio a. C.; cascos de bronce con cuernos, probablemente ceremoniales y muchos siglos anteriores. <strong>Siglo XIX</strong>: romanticismo, arte, teatro y ópera difundieron el vikingo con cuernos.</p><p>Las tres tarjetas deben leerse juntas: una imagen espectacular no sustituye fecha, función ni arqueología.</p>`},
          {k:"PERSONAS DEVUELTAS AL MAPA",title:"No era un pueblo entero",html:`<p><strong>¿Eran todos vikingos?</strong> No. «Vikingo» se asocia sobre todo a participar en expediciones de comercio, exploración, saqueo o guerra; no define a toda la población escandinava.</p><p><strong>¿Qué hacían además?</strong> Agricultura, ganadería, pesca, artesanía, trabajo doméstico, intercambio local, construcción naval y comercio.</p><p><strong>¿Qué podía viajar?</strong> Pieles, hierro, ámbar, madera y lana; también plata, vidrio, seda y otros objetos de redes que conectaban el Báltico, Europa oriental y el mundo islámico.</p>`}
        ],
        questions:[{id:"d1v7m2",type:"single",visual:"helmets",title:"La prueba que resiste la fecha",scene:"<strong>Galería de evidencia.</strong> Gjermundbu pertenece a la época vikinga y no tiene cuernos. Los cascos de Viksø son de la Edad del Bronce, muchos siglos anteriores; la imagen popular con cuernos se extendió en el arte, teatro y ópera románticos del siglo XIX.",prompt:"¿Qué pieza se parece más a un casco de época vikinga?",options:["El casco de Gjermundbu, de época vikinga y sin cuernos.","Los cascos de Viksø, con cuernos y de la Edad del Bronce.","El vestuario romántico del siglo XIX."],answer:0,hint:"No basta con que una pieza sea del Norte: compara fecha, función y evidencia arqueológica.",dossier:"«Vikingo» se asocia sobre todo a participar en expediciones de comercio, exploración, saqueo o guerra; no define a toda la población escandinava. Además había agricultura, ganadería, pesca, artesanía, trabajo doméstico, construcción naval e intercambio. Podían viajar pieles, hierro, ámbar, madera y lana; también plata, vidrio y seda. La historia incluye asimismo violencia y esclavización.",success:"CARICATURA DESCARTADA.",explanation:"La evidencia no permite presentar los cuernos como uniforme vikingo. La diversidad de vidas y actividades importa tanto como las expediciones."}]
      },
      {
        title:"Los mares y sus rutas", speaker:"Karin", photo:"karin-testimonio-1520-v1.png",
        obstacle:"Los mares no nos separaban solo de otros lugares. Eran caminos. Adivinad adónde podían llevarnos antes de volver a mi época.",
        goal:"Leer rutas de pesca, comercio, guerra, exploración y viajes cotidianos sin convertirlas en pasaportes modernos.", keys:1,time:"4–6 min",action:"Abrir las rutas",done:"El mapa vuelve a leer mares, ríos y costas como conexiones: no todo viaje terminaba en una expedición militar.",
        contexts:[
          {k:"MAPA EXPLORATORIO",title:"Este, oeste y mar cercano",visual:"vikingRoutes",html:`<p><strong>Oeste:</strong> islas británicas, Islandia, Groenlandia y zonas de América del Norte. <strong>Este:</strong> ríos de Europa oriental hacia el mar Negro, Bizancio y redes del mundo islámico. <strong>Mares cercanos:</strong> pesca, comercio y viajes cotidianos dentro de Escandinavia y el Báltico.</p><p>En L’Anse aux Meadows, Terranova, la arqueología confirma un pequeño asentamiento nórdico de hace más de mil años. Llegar a América del Norte no significa que entendieran «un continente» como lo nombramos hoy ni que lo ocuparan de manera duradera.</p>`}
        ],
        questions:[{id:"d1v7m3",type:"match",visual:"vikingRoutes",title:"Leer una ruta sin reducirla a saqueo",scene:"<strong>Mapa exploratorio.</strong> Hacia el oeste: islas británicas, Islandia, Groenlandia y zonas de América del Norte. Hacia el este: ríos de Europa oriental, mar Negro, Bizancio y redes del mundo islámico. Cerca: pesca, comercio y viajes entre costas escandinavas y bálticas. En L’Anse aux Meadows, Terranova, la arqueología confirma un pequeño asentamiento nórdico de hace más de mil años; no significa que entendieran «un continente» como lo nombramos hoy.",prompt:"Relaciona cada recorrido con una descripción posible.",pairs:[["Oeste","Islandia, Groenlandia y zonas de América del Norte."],["Este","Ríos de Europa oriental hacia Bizancio y redes del mundo islámico."],["Cercano","Pesca, comercio y viajes entre costas escandinavas y bálticas."]],hint:"Una ruta puede combinar mar y río; no todas terminan en una expedición militar.",dossier:"Las líneas del mapa muestran tendencias geográficas, no fronteras ni rutas únicas de todas las personas.",success:"MARES LEÍDOS COMO RUTAS.",explanation:"Los mismos mares podían servir para pescar, comerciar, viajar y guerrear."}]
      },
      {
        title:"Una corona, tres reinos", speaker:"Karin", photo:"karin-testimonio-1520-v1.png",
        obstacle:"Una corona, tres reinos. ¿Fue buena idea? No lo sé. Mi padre no vuelve y en la ciudad todos hablan de Cristián. Esta fecha es noviembre de 1520; para entenderla hay que seguir lo que se rompió antes.",
        goal:"Comprender cómo llegó la crisis a Estocolmo: Unión de Kalmar, leyes propias, élites, Sten Sture, Kristina y Gustav Trolle.", keys:1,time:"5–7 min",action:"Seguir la cadena",done:"La crisis de la Unión ya no parece una pelea simple entre dos bandos: una corona compartida no eliminaba leyes, élites ni conflictos.",
        contexts:[
          {k:"LA CADENA QUE LLEGA HASTA NOVIEMBRE",title:"1397–1520: antes de la puerta",visual:"kalmar",html:`<div class="history-timeline"><div><strong>1397</strong><span>Dinamarca, Noruega y Suecia comparten monarca; Suecia conserva leyes, instituciones y élites propias.</span></div><div><strong>1517</strong><span>El Consejo del Reino y Estocolmo apoyan deponer a Gustav Trolle y derribar Stäket.</span></div><div><strong>19 ene 1520</strong><span>Sten Sture es herido en Bogesund, junto a Åsunden; Kristina Gyllenstierna dirige la resistencia.</span></div><div><strong>septiembre</strong><span>Estocolmo abre sus puertas tras promesas de amnistía, seguridad y respeto a bienes.</span></div><div><strong>4 noviembre</strong><span>Gustav Trolle corona a Cristián II rey de Suecia.</span></div></div><p>La Unión buscaba reforzar coronas e intereses dinásticos frente a potencias económicas como la Liga Hanseática. Compartir rey no eliminaba impuestos, disputas por recursos ni deseos de gobernarse mediante regentes suecos.</p>`},
          {k:"QUIÉN ES QUIÉN",title:"Cinco personas, cinco posiciones",html:`<p><strong>Cristián II:</strong> rey de Dinamarca y Noruega; busca ser reconocido como rey de Suecia.</p><p><strong>Sten Sture el Joven:</strong> regente sueco y adversario de Cristián; muere en 1520.</p><p><strong>Kristina Gyllenstierna:</strong> viuda de Sten; dirige la resistencia de Estocolmo.</p><p><strong>Gustav Trolle:</strong> arzobispo de Uppsala; aliado de Cristián y protagonista de la acusación posterior.</p><p><strong>Gustav Eriksson:</strong> noble sueco cuyo papel crecerá después de la crisis; no aparece aquí como héroe resuelto.</p>`}
        ],
        questions:[{id:"d1v7m4",type:"single",visual:"kalmar",title:"¿Qué no resolvió la corona compartida?",scene:"<strong>La cadena que llega hasta noviembre.</strong> 1397: Dinamarca, Noruega y Suecia comparten monarca, pero no se convierten en un Estado idéntico. 1517: el Consejo del Reino y representantes de Estocolmo apoyan deponer a Gustav Trolle y derribar Stäket. 19 de enero de 1520: Sten Sture el Joven es herido en Bogesund, junto al lago Åsunden; Kristina Gyllenstierna dirige la resistencia. Septiembre: Estocolmo abre sus puertas tras promesas de amnistía, seguridad y respeto a bienes. El 4 de noviembre Trolle corona a Cristián II rey de Suecia.",prompt:"Si tres reinos comparten monarca, pero cada uno conserva leyes, élites e intereses, ¿qué situación es más probable?",options:["La unión puede reforzar algunas decisiones, pero no elimina identidades, disputas por poder, impuestos o recursos.","Los tres reinos se convierten automáticamente en un Estado idéntico sin conflictos internos.","Un mismo rey impide cualquier guerra, protesta o rivalidad."],answer:0,hint:"Una corona compartida puede unir intereses, pero no borra de un día para otro leyes, grupos sociales ni decisiones locales.",dossier:"Cristián II era rey de Dinamarca y Noruega y reclamaba Suecia; Sten Sture era regente sueco; Kristina dirigió la resistencia tras su muerte; Gustav Trolle era arzobispo de Uppsala y aliado de Cristián. Gustav Eriksson aún no es un héroe resuelto en la plaza: su papel crecerá después.",success:"CRISIS DE LA UNIÓN ENTENDIDA.",explanation:"La Unión de Kalmar buscaba reforzar coronas y sus intereses frente a poderes económicos como la Liga Hanseática, pero compartir rey no borraba los conflictos."}]
      },
      {
        title:"Tres pruebas, una copia", speaker:"Karin", photo:"karin-testimonio-1520-v1.png",
        obstacle:"Se ha optado por la amnistía. Mi padre sigue sin aparecer. Van a coronar a Cristián y tengo documentos importantes. ¿Cuál escondo?",
        goal:"Aprender una frase actual de sueco y proteger un conjunto de pruebas que permita comparar una promesa con los hechos.", keys:1,time:"4–5 min",action:"Proteger la copia",done:"La copia conserva nombres, promesa y ceremonia: ahora Karin podrá comparar lo que se dijo con lo que ocurrió.",
        contexts:[],
        questions:[{id:"d1v7m5",type:"single",title:"El paquete que permite comparar promesas y hechos",scene:"<strong>Sueco actual.</strong> Si hoy necesitas preguntar por alguien: <strong>Var är min pappa?</strong> significa «¿Dónde está mi padre?». Var = dónde; är = está/se encuentra; min = mi; pappa = papá. Karin habla desde 1520: no fingimos que sea exactamente su lengua. Antes de este reto puedes usar el kit de idioma para escuchar la frase.",prompt:"Karin solo puede proteger un paquete. ¿Cuál le ayudará mejor a comprobar qué se prometió y qué ocurrió después?",options:["Lista de invitadas e invitados + copia de la amnistía + nota o carta de la coronación.","Receta sin fecha + dibujo decorativo + trozo de tela sin procedencia.","Solo una lista de nombres, sin promesa ni acto con los que compararla."],answer:0,hint:"Una evidencia fuerte permite relacionar personas, una promesa y un hecho; una sola pieza puede dejar demasiadas dudas.",success:"COPIA ESCONDIDA.",explanation:"El conjunto permite comparar quiénes fueron invitadas e invitados, qué se prometió y qué pasó después. El padre de Karin aparece en la lista, pero eso aún no confirma su destino."}]
      },
      {
        title:"Las puertas se cierran", speaker:"Karin", photo:"karin-testimonio-1520-v1.png",
        obstacle:"Ha terminado la coronación. Han cerrado las puertas de la ciudad. Ya nos hemos rendido. ¿Por qué hay tanta gente armada? ¿Dónde está mi padre?",
        goal:"Comparar la amnistía prometida con la situación que Karin observa después de la coronación.", keys:1,time:"3–4 min",action:"Comparar las pruebas",done:"La contradicción queda anotada: una promesa de seguridad no encaja con invitados retenidos, soldados y puertas cerradas.",
        contexts:[
          {k:"PROMESA Y CONTRADICCIÓN",title:"Dos columnas para una misma ciudad",html:`<div class="evidence-grid two"><div><b>ANTES DE ABRIR LAS PUERTAS</b><span>Amnistía, seguridad personal y respeto a bienes.</span></div><div><b>DESPUÉS DE LA CORONACIÓN</b><span>Soldados armados, invitados retenidos y puertas cerradas.</span></div></div><p class="lead">Una promesa se entiende comparando quién la hace, a quién protege y qué sucede después.</p>`}
        ],
        questions:[{id:"d1v7m6",type:"single",title:"La evidencia que activa la alerta",scene:"<strong>Promesa y contradicción.</strong> Antes de abrir las puertas: amnistía, seguridad personal y respeto a bienes. Después de la coronación: soldados armados, invitados retenidos y puertas cerradas. Una promesa se entiende comparando quién la hace, a quién protege y qué sucede después.",prompt:"¿Qué observación obliga a Karin a revisar la amnistía en vez de darla por segura?",options:["Tras la amnistía, los invitados están retenidos y la ciudad se llena de soldados armados.","La plaza tiene adoquines.","Es noviembre y hace frío."],answer:0,hint:"Compara la protección prometida con la situación real de quienes debían sentirse seguros.",success:"ALERTA JUSTIFICADA.",explanation:"Una lista de invitadas e invitados no dice quién salió de la reunión. Karin puede conservar una búsqueda abierta sin inventar un final."}]
      },
      {
        title:"El Baño de Sangre de Estocolmo", speaker:"Karin", photo:"karin-testimonio-1520-v1.png",
        obstacle:"Trolle ha vuelto con acusaciones antiguas. ¿Pero de qué va? La coronación ha terminado. ¿Por qué siguen reteniendo a los invitados?",
        goal:"Entender cómo una acusación de herejía dejó sin protección la amnistía política y nombrar lo ocurrido sin disfrazarlo de batalla.", keys:1,time:"4–6 min",action:"Nombrar lo ocurrido",done:"El cuaderno nombra una represión: detenciones y ejecuciones posteriores a una coronación y una promesa de amnistía.",
        contexts:[
          {k:"UNA ACUSACIÓN QUE CAMBIA DE LEY",title:"La amnistía deja de proteger",html:`<div class="evidence-grid two"><div><b>AMNISTÍA POLÍTICA</b><span>Promesa de no castigar acciones políticas pasadas.</span></div><div><b>ACUSACIÓN DE HEREJÍA</b><span>Asunto de ley eclesiástica; permite apartar a los acusados de esa protección.</span></div></div><p>Gustav Trolle acusó a adversarios de Sten Sture de herejía por su relación con su deposición y la destrucción de Stäket. No demuestra que todas las personas detenidas fueran culpables de un mismo delito probado: dio apariencia legal a una represión contra adversarios políticos.</p><p><strong>Paralelismo con España:</strong> el duque de Alba creó el Consejo de los Tumultos en los Países Bajos en 1567, llamado después «Consejo de Sangre». No es el mismo hecho: ayuda a reconocer cómo una institución y un lenguaje legal pueden utilizarse para reprimir oposición.</p>`}
        ],
        questions:[{id:"d1v7m7",type:"single",title:"El titular que no disfraza lo ocurrido",scene:"<strong>Una acusación que cambia de ley.</strong> Gustav Trolle acusó a adversarios de Sten Sture de herejía por su relación con su deposición y la destrucción de Stäket. Al presentarlo como asunto de ley eclesiástica, la amnistía política dejó de protegerles. Esto no demuestra que todas las personas detenidas fueran culpables de un mismo delito probado: dio apariencia legal a una represión contra adversarios políticos. En España, el Consejo de los Tumultos creado por el duque de Alba en los Países Bajos en 1567 muestra, en otro contexto, cómo una institución y un lenguaje legal pueden servir para reprimir oposición.",prompt:"¿Qué titular describe el expediente con mayor precisión?",options:["El Baño de Sangre de Estocolmo: detenciones y ejecuciones de adversarios después de la coronación y de una promesa de amnistía.","La batalla de Stortorget: dos ejércitos se enfrentaron en la plaza tras la coronación.","Una crisis política sin violencia posterior: la coronación cerró el conflicto sin detenciones."],answer:0,hint:"No hubo dos ejércitos luchando en Stortorget, sino detenciones y ejecuciones posteriores a la ceremonia.",success:"HECHO NOMBRADO CON PRECISIÓN.",explanation:"Cristián II y Gustav Trolle engañaron con la amnistía. Algunas personas lograron escapar; Karin puede esperar que su padre fuera una de ellas, sin afirmarlo como certeza."}]
      },
      {
        title:"La ciudad recuerda, pero no se congela", speaker:"Karin", photo:"karin-testimonio-1520-v1.png",
        obstacle:"Quedan pruebas para que no se olvide lo ocurrido. Venid conmigo por Estocolmo. No para fingir que la ciudad es igual que en 1520, sino para aprender a leer lo que conserva.",
        goal:"Recorrer Stortorget y Gamla Stan con cuatro pistas: leyenda de las piedras, coro de Storkyrkan, piedra rúnica U 53 y tres coronas del Ayuntamiento.", keys:1,time:"6–10 min",action:"Abrir el paseo de evidencia",done:"Karin conserva una conclusión honesta: su padre fue invitado, algunas personas escaparon y la búsqueda continúa abierta.",
        contexts:[
          {k:"GUÍA VISUAL · GAMLA STAN",title:"Una plaza y tres capas de tiempo",mapImage:"gamla-stan-map.png",mapAlt:"Mapa real de Gamla Stan para situar Stortorget, Storkyrkan, Prästgatan y el Palacio Real",mapCaption:"Mapa de orientación de Gamla Stan · © OpenStreetMap contributors · CC BY-SA",html:`<p><strong>Lugar:</strong> Stortorget está vinculada a las ejecuciones de noviembre de 1520. <strong>Símbolo:</strong> fachadas, placas y relatos turísticos pueden ayudar a recordar, pero hay que comprobar qué fecha y qué evidencia respalda cada detalle. <strong>Ciudad viva:</strong> Gamla Stan conserva trazas del pasado; no es una fotografía intacta de 1520.</p><p>Elige las paradas que os interesen: no hay que hacerlas todas ni seguir este orden.</p>`},
          {k:"PARADA 1 · STORTORGET 20",title:"Las piedras que cuentan una leyenda",visual:"stones",html:`<p>Busca Schantzska huset, la casa roja de fachada escalonada. Muchas guías dicen que hay una piedra por cada persona ejecutada. Es una historia potente, pero no una prueba: la casa se reconstruyó en el siglo XVII, más de un siglo después, y no existe documentación que confirme que las piedras se colocaran por las víctimas.</p><p>La frase honesta es: <strong>«Las piedras se relacionan por tradición con el Baño de Sangre, pero no prueban cuántas personas murieron.»</strong></p>`},
          {k:"PARADA 2 · STORKYRKAN",title:"El coro que ya no está y el castillo que se perdió",visual:"choir",html:`<p>Busca en el pavimento el contorno del antiguo coro medieval y después mira hacia el Palacio Real. Gustav Vasa ordenó desmontar el coro en el siglo XVI para mejorar el campo de tiro defensivo del castillo de <strong>Tre Kronor</strong>.</p><p>Tre Kronor fue el palacio-castillo de la monarquía hasta que un incendio lo destruyó en 1697. El Palacio Real actual ocupa el mismo gran entorno, pero no es el mismo edificio.</p>`},
          {k:"PARADA 3 · PRÄSTGATAN Y KÅKBRINKEN",title:"Una piedra que no habla «rúnico»",visual:"runeAlley",html:`<p>Busca la piedra rúnica U 53, de alrededor de mil años y empotrada en el muro. Las runas no son un idioma: son signos de escritura. Esta piedra contiene un texto en nórdico antiguo y conserva un mensaje familiar.</p><p>Lo preciso es decir: <strong>«Las runas son una forma de escribir; el idioma del texto puede ser nórdico antiguo.»</strong> No tocar ni frotar la piedra.</p>`},
          {k:"PARADA 4 · MÅRTEN TROTZIGS GRÄND",title:"La calle más estrecha de Estocolmo",mapImage:"la calle más estrecha de toda la capital sueca.jpg",mapAlt:"Mårten Trotzigs gränd, la calle más estrecha de Estocolmo",mapCaption:"Mårten Trotzigs gränd · un pasadizo estrecho y escalonado de Gamla Stan.",html:`<p>Muy cerca de Prästgatan está Mårten Trotzigs gränd, famosa por ser la calle más estrecha de Estocolmo. Sus fachadas y escaleras recuerdan que Gamla Stan fue una ciudad de pasos estrechos, casas pegadas y recorridos cotidianos.</p><p>Una calle antigua no es una fotografía de 1520. Sirve para imaginar la escala de la ciudad, no para inventar lo que ocurrió en cada esquina.</p>`},
          {k:"PARADA 5 · DOS MIRADORES POSIBLES",title:"Las tres coronas al otro lado del agua",mapImage:"las tres coronoas.jpg",mapAlt:"Las tres coronas doradas de la torre del Ayuntamiento de Estocolmo",mapCaption:"Las tres coronas doradas del Ayuntamiento, vistas al otro lado del agua.",visual:"crowns",html:`<p>Desde Monteliusvägen o Riddarholmen, al otro lado del agua, busca las tres coronas doradas de la torre del Ayuntamiento. Son alternativas, no una ruta que deba hacerse de una vez.</p><p>La torre se terminó en 1923; las coronas son un símbolo histórico de Suecia. No prueban por sí solas una teoría única sobre su origen, pero muestran cómo la ciudad moderna lleva símbolos antiguos hacia el paisaje actual.</p>`},
          {k:"SAGA · INTERLUDIO",title:"Vasa antes de ser rey",speaker:"Saga",character:true,dark:true,visual:"raceMaps",html:`<p>En noviembre de 1520, Gustav Eriksson aún no era el rey Gustav Vasa. Era un joven noble que había sido rehén en Dinamarca, había escapado y estaba huyendo. Su padre, Erik Johansson, fue ejecutado en el Baño de Sangre.</p><p>A finales de 1520 buscó apoyo en Dalarna, huyó hacia Noruega y regresó para encabezar la rebelión en 1521. En 1523 fue elegido rey. El <strong>Vasaloppet</strong>, creado en 1922, recorre 90 km de Sälen a Mora en sentido inverso a la huida tradicional. Es memoria cultural, no un GPS de 1521; igual que la maratón, una carrera puede recordar una tradición sin demostrar cada detalle.</p>`}
        ],
        questions:[{id:"d1v7m8",type:"single",visual:"runeAlley",title:"La frase que Karin puede escribir",scene:"<strong>Paseo de evidencia.</strong> Stortorget 20: las piedras claras de Schantzska huset se relacionan por tradición con el Baño de Sangre, pero no prueban un número de muertes. Junto a Storkyrkan: el contorno del coro medieval y el Palacio Real recuerdan que Tre Kronor no es el edificio actual. Prästgatan y Kåkbrinken: la piedra U 53 usa runas, una escritura; el idioma del texto era nórdico antiguo. Desde Riddarholmen o Monteliusvägen: las tres coronas doradas del Ayuntamiento, terminado en 1923, llevan un símbolo antiguo a un paisaje moderno. Puedes abrir el mapa inicial para escoger las paradas que os interesen.",prompt:"¿Qué conclusión puede guardar Karin sobre su padre sin inventar?",options:["Mi padre estaba entre las personas invitadas. No sé si sobrevivió, pero algunas personas escaparon y seguiré buscando.","Mi padre murió con seguridad, aunque no exista una prueba sobre él.","Mi padre escapó con Gustav Vasa, aunque ninguna fuente lo mencione."],answer:0,hint:"La esperanza es legítima. Una certeza inventada no protege a Karin ni a la historia.",dossier:"Interludio Vasa: en noviembre de 1520 Gustav Eriksson aún no era rey. Buscó apoyo en Dalarna, huyó hacia Noruega y regresó para encabezar la rebelión en 1521; fue elegido rey en 1523. Vasaloppet, creado en 1922, recorre 90 km de Sälen a Mora en sentido inverso a la huida tradicional. Es memoria cultural, no un GPS de 1521. Igual que el maratón, una carrera moderna puede recordar una tradición sin demostrar cada detalle.",success:"BÚSQUEDA GUARDADA CON HONESTIDAD.",explanation:"La ciudad conserva capas y preguntas, no una fotografía intacta de 1520. Karin agradece que no convirtamos su historia en una leyenda cómoda."}]
      }
    ]
  };

  // Ajuste editorial V8: textos aceptados del guion y respuestas personalizadas.
  // No se trasladan al juego las notas internas de maquetación del documento.
  const d = window.DAY1_DATA;
  const m = d.missions;
  const q = m.map(item => item.questions[0]);
  Object.assign(m[0], {closing:"No confundís un nombre con una historia sencilla. Empiezo a creer que puedo confiar en vosotras."});
  Object.assign(m[1], {closing:"Ya sabéis que no todos los suecos eran vikingos y que los vikingos no llevaban cuernos. Eso sí: ¿a quién se le ocurrió que los cuernos eran una buena idea para un casco?"});
  Object.assign(m[2], {closing:"Éramos buenos en muchas aguas: para pescar, comerciar, viajar y guerrear. Ya sé que sois de fiar. Ahora volvemos a mi tiempo: no sé dónde está mi padre y creo que la ciudad está a punto de cambiar."});
  Object.assign(m[3], {closing:"La Unión de Kalmar llevaba más de un siglo con problemas. Compartir una corona no resolvía las disputas por poder, leyes y recursos."});
  Object.assign(m[4], {closing:"Mi padre estaba en la lista. Si la amnistía es verdad, quizá vuelva pronto. Algo me huele mal: hay demasiados soldados daneses en las calles."});
  Object.assign(m[5], {closing:"Mi padre fue invitado. Pero no sé si fue a la cena, si consiguió escapar o si sigue retenido."});
  Object.assign(m[6], {closing:"Ojalá mi padre fuese una de las personas que lograron escapar. Quien sí escapó fue Gustav Eriksson."});
  Object.assign(m[7], {title:"La ciudad recuerda",closing:"No sé si mi padre está vivo. Pero sé que algunas personas escaparon y ahora sé qué pruebas puedo conservar. Gracias por mantener viva la historia de Estocolmo."});

  Object.assign(q[0], {title:"¿Cuál es el origen de Suecia?",reaction:"Ya sabemos que Suecia fue un país que tardó siglos en formarse."});
  Object.assign(q[1], {title:"El verdadero casco vikingo",reaction:"Hemos quitado el disfraz del vikingo con cuernos. Ahora ya sabemos cómo eran los vikingos de verdad."});
  Object.assign(q[2], {title:"Las rutas vikingas",reaction:"Las rutas vuelven a conectar agua, comercio y viajes."});
  Object.assign(q[3], {
    title:"¿Qué no resolvió tener una corona compartida?",
    options:["Los tres reinos se convierten automáticamente en un Estado idéntico sin conflictos internos.","Un mismo rey impide cualquier guerra, protesta o rivalidad.","La unión puede reforzar algunas decisiones, pero no elimina identidades, disputas por poder, impuestos o recursos."],
    answer:2,
    reaction:"Ahora conocemos el conflicto: Cristián II y Gustav Trolle apoyaban la Unión de Kalmar. Sten Sture y Kristina Gyllenstierna dirigían la resistencia en Estocolmo."
  });
  Object.assign(q[4], {title:"Amnistía y cena",reaction:"Ya tengo el documento de la amnistía, la coronación con las promesas y la lista de invitados. Mi padre está entre ellos. Ojalá pueda verle pronto."});
  Object.assign(q[5], {title:"La invitación y las promesas",reaction:"Ya sabemos que Cristián II y Gustav Trolle, con la excusa de la celebración, han planteado una trampa."});
  Object.assign(q[6], {title:"El Baño de Sangre",reaction:"Muchos murieron, pero algunas personas lograron escapar."});
  Object.assign(q[7], {reaction:"La búsqueda de mi padre sigue abierta, pero Estocolmo no olvida lo que pasó en noviembre de 1520."});

  // Pantallas V8 que antes todavía conservaban texto de la versión V7.
  Object.assign(m[0].contexts[1], {
    k:"NOMBRES RECUPERADOS",
    title:"Dos huellas, dos nombres",
    html:`<p><strong>Svea rike</strong>, «reino de los Svear», dejó la huella de <strong>Sverige</strong>, el nombre sueco del país.</p><p><strong>Svíþjóð / Svethiudh</strong>, pueblo o tierra de los Svear, dejó huellas en <strong>Suecia</strong>, <em>Sweden</em>, <em>Suède</em> y otros nombres externos emparentados.</p><p>En la península ibérica, después de la caída del Imperio romano, también se reunieron distintos pueblos.</p><p>Los suevos y vándalos eran de origen germánico; los alanos, de origen iraní. Antes de la entrada musulmana llegaron los godos y visigodos.</p><p>Es discutido si el origen de Andalucía viene de los vándalos.</p>`
  });
  Object.assign(q[4], {
    scene:"",
    prompt:"Karin tiene documentos muy importantes. Pero solo puede proteger uno. ¿Cuál elegirías?",
    explanation:"El conjunto permite comparar quiénes fueron invitados a la cena, qué se prometió y qué pasó después. El padre de Karin aparece en la lista, pero todavía no le hemos visto."
  });
  Object.assign(q[5], {
    prompt:"Las puertas del castillo acaban de cerrarse. Lo que comenzó como una celebración por la coronación de Cristián II se ha convertido en una trampa.<br><br>Antes de entrar en Estocolmo, el rey había prometido una amnistía y paz: sus antiguos adversarios no serían castigados. Muchos lo creyeron y han ido a la cena de coronación.<br><br>Ahora el arzobispo Gustav Trolle los acusa de herejía, un delito contra la Iglesia. Esa acusación podría dejar fuera del perdón político lo ocurrido en Stäket.<br><br><strong>Hay soldados daneses en las puertas de Estocolmo. ¿Qué va a pasar?</strong>",
    options:["Tras la amnistía, los invitados serán retenidos y la ciudad se llena de soldados armados.","Cristián II cumplirá su promesa y respetará los bienes y derechos de todos los invitados a su cena.","La cena es para obligar a los asistentes a donar todo su dinero a Gustav Trolle para construir otro castillo."],
    answer:0,
    hint:"Ponte en lo peor. De lo prometido, nada de nada. La vida no es justa, es real.",
    explanation:"Todos los invitados están retenidos sin ningún motivo. No se están respetando las condiciones negociadas con Kristina, la viuda de Sten Sture."
  });

  m[6].contexts.push({k:"SAGA · CONSECUENCIA",title:"Lo que cambió",speaker:"Saga",character:true,dark:true,html:`<p>El Baño de Sangre no explica por sí solo toda la caída de la Unión. Pero desacreditó gravemente a Cristián II y ayudó a movilizar la oposición.</p><p>Gustav encabezaría una rebelión y sería elegido rey en <strong>1523</strong>. Esa historia continúa en el Día 02.</p>`});
})();

(()=>{const m=window.DAY1_DATA.missions;
  m[6].questions[0].media={file:"Stockholm_Bloodbath.jpg",alt:"Representación histórica del Baño de Sangre de Estocolmo",caption:"El Baño de Sangre de Estocolmo · detenciones y ejecuciones tras la promesa de amnistía."};
  m[7].contexts[1].mapImage="Schantzska_huset_and_Seyfridtzska_huset_buildings,_Stortorget,_Gamla_stan,_Stockholm,_Sweden_julesvernex2.jpg";
  m[7].contexts[1].mapAlt="Schantzska huset y Seyfridtzska huset en Stortorget";
  m[7].contexts[1].mapCaption="Stortorget 20 · las piedras se relacionan por tradición con el Baño de Sangre, pero no prueban un número de víctimas.";
  m[7].contexts[3].mapImage="Prästgatan_runsten_närbild.JPG";
  m[7].contexts[3].mapAlt="Detalle de la piedra rúnica de Prästgatan";
  m[7].contexts[3].mapCaption="Prästgatan · las runas son una forma de escritura; el texto está en nórdico antiguo.";
})();

// Revisión literal del Día 01 contra el guion V8 aceptado.
// Se conservan únicamente correcciones ortográficas y de precisión histórica.
(() => {
  const d=window.DAY1_DATA, m=d.missions, q=m.map(x=>x.questions[0]);
  Object.assign(d.prologue[0],{html:`<p>La coordenada nos ha traído a una plaza, una fecha y un nombre: <strong>Estocolmo · noviembre de 1520 · Karin</strong>.</p><p>Mis padres construyeron una testigo ficticia, Karin, para proteger nombres y hechos reales.</p><p>La Sombra ha intentado borrar justo la relación entre Cristián II, esta plaza y Gustav Eriksson.</p><p class="lead">Si ayudamos a Karin a conservar lo que realmente sabe, podremos proteger la historia.</p>`});
  Object.assign(d.prologue[1],{html:`<p><strong>Persona ficticia; contexto histórico real.</strong></p><p>No puedo seguir dándoos pistas hasta saber de dónde venís.</p><p>La Sombra ha querido borrar nuestro pasado para que nadie recuerde lo que de verdad ha pasado y solo quede su versión.</p><p>Mi padre salió esta mañana y aún no ha vuelto. Si sabéis leer quiénes fuimos, quizá pueda confiar en vosotras.</p><p class="lead">Entonces os contaré lo que está pasando en la ciudad.</p>`});
  Object.assign(d.prologue[2],{title:"Una ciudad, muchas historias.",html:`<p>Este mapa sirve para el paseo de hoy. También sirve para entender lo que ocurrió hace siglos y lo que sigue sucediendo hoy.</p><p>No hay un orden exacto: Stortorget, Storkyrkan, el Palacio Real, la piedra rúnica y las tres coronas forman parte de la misma ciudad.</p>`});

  Object.assign(m[0],{obstacle:"El mapa llama a este territorio de dos maneras. Antes de ayudarme con mi padre, necesito saber que sois de confianza.",goal:"Entender qué eran Svear y Götar y el proceso de creación de Suecia.",done:"Saber qué comunidades y nombres dieron forma a Suecia."});
  Object.assign(m[0].contexts[0],{html:`<p>Entre aproximadamente <strong>800 y 1050</strong>, la llamada época vikinga reúne comunidades muy distintas. Muchas personas cultivaban, pescaban, criaban animales, comerciaban, trabajaban el hierro, hacían tejidos o construían barcos.</p><p><strong>Svear</strong> y <strong>Götar</strong> eran grandes comunidades y áreas de influencia. No eran provincias con líneas exactas como las actuales ni tenían una identidad nacional única.</p><p>Hacia el año 1000, Olof Skötkonung suele considerarse el primer rey cristiano de Suecia. La centralización, las leyes comunes y las instituciones fueron un proceso de siglos.</p><p>El nombre de Estocolmo aparece por primera vez en documentos de <strong>1252</strong>, vinculado a la época de Birger Jarl.</p>`});
  Object.assign(m[0].contexts[1],{html:`<p><strong>Svea rike</strong>, «reino de los Svear», dejó la huella de <strong>Sverige</strong>, el nombre sueco del país.</p><p><strong>Svíþjóð / Svethiudh</strong>, pueblo o tierra de los Svear, dejó huellas en <strong>Suecia</strong>, <em>Sweden</em>, <em>Suède</em> y otros nombres externos emparentados.</p><p>En la península ibérica, después de la caída del Imperio romano en el año 411, también se reunieron distintos pueblos. Los suevos y vándalos son de origen germánico; los alanos, de origen iraní. Antes de la entrada musulmana llegaron los godos y visigodos.</p><p>Es discutido si el origen de Andalucía viene de los vándalos.</p>`});
  Object.assign(q[0],{prompt:"Elige la frase que mejor lo define.",dossier:"Dos caminos del nombre: Svea rike («reino de los Svear») dejó la huella de Sverige; Svíþjóð o Svethiudh («pueblo o tierra de los Svear») dejó huellas en Suecia, Sweden o Suède. Igual que los nombres de pueblos posteriores a Roma en la península ibérica, guardan rastros, no fotografías exactas.<br><br>En Europa, Alemania o Allemagne debe su nombre a los alamanes para quienes no eran de allí; en alemán llaman a su país Deutschland, «tierra del pueblo».",explanation:"El nombre del país destaca a los Svear, pero Suecia no se entiende sin los Götar. Ninguna de estas comunidades tenía fronteras modernas."});

  Object.assign(m[1],{obstacle:"Bien. Ya respetáis que Suecia no apareció de golpe sino que fue un proceso de siglos. Ahora comprobad si sabéis quiénes eran de verdad los vikingos. Alguien ha colocado un casco con cuernos sobre mi cuaderno.",goal:"¿Los vikingos responden a la imagen de Vicky el Vikingo? ¿A qué se dedicaban de verdad?",done:"Conocer quiénes eran de verdad los vikingos."});
  Object.assign(m[1].contexts[0],{k:"COLECCIÓN DE CASCOS VIKINGOS",html:`<p><strong>Gjermundbu:</strong> época vikinga, Noruega; casco sin cuernos.</p><p><strong>Viksø:</strong> Edad del Bronce, hacia el primer milenio a. C.; cascos de bronce con cuernos, probablemente ceremoniales y muchos siglos anteriores.</p><p><strong>Siglo XIX:</strong> romanticismo, arte, teatro y ópera difundieron el vikingo con cuernos. Las tres tarjetas deben leerse juntas: una imagen no debe esconder la realidad.</p>`});
  Object.assign(m[1].contexts[1],{k:"VIKINGOS EN EL MAPA",html:`<p><strong>¿Eran todos vikingos?</strong> No. «Vikingo» se asocia sobre todo a participar en expediciones de comercio, exploración, saqueo o guerra; no define a toda la población escandinava.</p><p><strong>¿Qué hacían además?</strong> Agricultura, ganadería, pesca, artesanía, trabajo doméstico, intercambio local, construcción naval y comercio.</p><p><strong>¿Con qué comerciaban?</strong> Pieles, hierro, ámbar, madera y lana; también plata, vidrio, seda y otros objetos de redes que conectaban el Báltico, Europa oriental y el mundo islámico.</p>`});
  Object.assign(q[1],{title:"El verdadero casco vikingo",prompt:"¿Qué pieza se parece más a un casco de la época vikinga?",explanation:"Los cuernos en un casco serían un problema para la lucha: podrían engancharse. Los cascos con cuernos vienen de la Edad del Bronce y tenían uso ceremonial; no se usaban para el combate vikingo."});

  Object.assign(m[2],{goal:"Leer rutas de pesca, comercio, guerra, exploración y viajes cotidianos.",done:"La Carta vuelve a leer mares, ríos y costas como conexiones. Las conexiones no solo se hacían por motivos de guerra: había más intereses."});
  Object.assign(m[2].contexts[0],{mapImage:"colon-vikingos-llegaron-antes.png",mapAlt:"Ilustración histórica de Cristóbal Colón al descubrir rastros nórdicos en una playa de América del Norte",mapCaption:"Así que los vikingos habían llegado antes que yo.",html:`<p><strong>Oeste:</strong> islas británicas, Islandia, Groenlandia y zonas de América del Norte. <strong>Este:</strong> ríos de Europa oriental hacia el mar Negro, Bizancio y redes del mundo islámico. <strong>Mares cercanos:</strong> pesca, comercio y viajes cotidianos dentro de Escandinavia y el Báltico.</p><p>En L’Anse aux Meadows, Terranova, la arqueología confirma un pequeño asentamiento nórdico de hace más de mil años. Llegar a América del Norte no significa que entendieran «un continente» como lo nombramos hoy ni que lo ocuparan de manera duradera.</p><p>Colón llegó después: los vikingos habían llegado antes.</p>`});

  Object.assign(m[3],{obstacle:"Una corona, tres reinos. ¿Fue buena idea? No lo sé. Mi padre no vuelve y en la ciudad todos hablan de Cristián. Estamos en noviembre de 1520: para entender lo que está pasando hay que mirar un poco el pasado.",goal:"Comprender cómo ha llegado Estocolmo a esta situación de crisis: Unión de Kalmar, leyes propias, élites, Sten Sture, Kristina y Gustav Trolle.",done:"Entender por qué había crisis y la visión de cada una de las partes."});
  Object.assign(m[3].contexts[0],{k:"DE DÓNDE VIENEN LOS PROBLEMAS",title:"1397–hasta noviembre de 1520",mapImage:"Christians_II.,_König_von_Dänemark.jpg",mapAlt:"Retrato histórico de Cristián II de Dinamarca",mapCaption:"Cristián II, rey de Dinamarca y Noruega, fue coronado rey de Suecia en Estocolmo en noviembre de 1520.",html:`<div class="history-timeline"><div><strong>1397</strong><span>Dinamarca, Noruega y Suecia comparten monarca; Suecia conserva leyes, instituciones y élites propias.</span></div><div><strong>1517</strong><span>El Consejo del Reino, con Sten Sture a la cabeza, y Estocolmo apoyan deponer a Gustav Trolle y derribar Stäket.</span></div><div><strong>19 ene 1520</strong><span>Sten Sture es herido en la batalla de Bogesund, junto a Åsunden; muere después. Kristina Gyllenstierna dirige la resistencia.</span></div><div><strong>septiembre 1520</strong><span>Estocolmo abre sus puertas tras promesas de amnistía, seguridad y respeto a bienes.</span></div><div><strong>4 noviembre 1520</strong><span>Gustav Trolle corona a Cristián II rey de Suecia.</span></div></div><p>La Unión buscaba reforzar coronas e intereses dinásticos frente a potencias económicas como la Liga Hanseática. Compartir rey no eliminaba impuestos, disputas por recursos ni deseos de gobernarse mediante regentes suecos.</p>`});
  Object.assign(m[3].contexts[1],{html:`<p><strong>Cristián II:</strong> rey de Dinamarca y Noruega; conquistó el trono sueco y fue coronado en Estocolmo en noviembre de 1520.</p><p><strong>Sten Sture el Joven:</strong> regente sueco y dirigente de la oposición a Cristián II; fue herido en enero de 1520 y murió durante el traslado a Estocolmo.</p><p><strong>Kristina Gyllenstierna:</strong> esposa de Sten; asumió la defensa de Estocolmo.</p><p><strong>Gustav Trolle:</strong> arzobispo de Uppsala; aliado de Cristián y protagonista de la acusación posterior de herejía.</p><p><strong>Gustav Eriksson:</strong> noble sueco cuyo papel crecerá después de la crisis; logró escapar.</p>`});
  Object.assign(q[3],{prompt:"Si tres reinos, Dinamarca, Noruega y Suecia, comparten monarca, pero cada uno conserva sus leyes, élites e intereses, ¿qué es lo que puede pasar?",hint:"Una corona compartida puede unir algunos intereses, pero cada país quiere conservar sus leyes y privilegios sociales.",explanation:"La Unión de Kalmar buscaba reforzar las tres coronas y sus intereses frente a poderes económicos como la Liga Hanseática. Pero compartir rey no borraba los conflictos internos que existían."});

  Object.assign(m[4],{goal:"¿Qué está pasando en Estocolmo?",done:"Hay una lista de invitadas e invitados a la coronación."});
  Object.assign(m[5],{goal:"¿Se va a cumplir la amnistía prometida?",done:"¿Qué va a pasar después de la coronación? ¿Se irán los soldados?"});
  Object.assign(m[5].contexts[0],{html:`<div class="evidence-grid two"><div><b>ANTES DE ABRIR LAS PUERTAS</b><span>Amnistía, seguridad personal y respeto a bienes.</span></div><div><b>DESPUÉS DE LA CORONACIÓN</b><span>Soldados armados, invitados retenidos y puertas cerradas.</span></div></div><p class="lead">¿Van a cumplir con la amnistía?</p>`});
  Object.assign(m[6],{obstacle:"Trolle ha vuelto con acusaciones antiguas, cuando destruyeron su castillo. ¿Pero de qué va? La coronación ha terminado. ¿Por qué siguen reteniendo a los invitados?",goal:"Entender cómo una acusación de herejía dejó sin protección la amnistía política y contar a los cuatro vientos lo que va a pasar.",done:"Le diremos a todo el mundo lo que está pasando. No puede ser que no cumplan lo pactado."});
  Object.assign(q[6],{title:"El Baño de Sangre",prompt:"¿Qué pasó después?",explanation:"Cristián II y Gustav Trolle engañaron a sus adversarios políticos con la amnistía."});

  Object.assign(m[7],{title:"La ciudad recuerda",goal:"Recorrer Stortorget y Gamla Stan con algunos recuerdos de lo ocurrido.",done:"Karin conserva una conclusión honesta: su padre fue invitado, algunas personas escaparon y ojalá su padre fuera una de ellas."});
  Object.assign(m[7].contexts[1],{html:`<p>Busca Schantzska huset, la casa roja de fachada escalonada. Muchas guías dicen que hay 82 piedras, una por cada persona ejecutada.</p><p>Es una historia potente, pero no una prueba: la casa se reconstruyó en el siglo XVII, más de un siglo después, y no existe documentación que confirme que las piedras se colocaran por las víctimas. En realidad, hay 94 piedras.</p>`});
  Object.assign(m[7].contexts[2],{k:"PARADA 2 · EL CORO QUE YA NO ESTÁ Y EL CASTILLO QUE SE PERDIÓ",title:"Storkyrkan",html:`<p>Busca en el pavimento el contorno del antiguo coro medieval y después mira hacia el Palacio Real. Gustav Vasa ordenó desmontar el coro en el siglo XVI para mejorar el campo de tiro defensivo del castillo de <strong>Tre Kronor</strong>.</p><p>Tre Kronor fue el palacio-castillo de la monarquía hasta que un incendio lo destruyó en 1697. El Palacio Real actual ocupa el mismo gran entorno, pero no es el mismo edificio.</p>`});
  Object.assign(m[7].contexts[3],{html:`<p>Busca la piedra rúnica U 53, de alrededor de mil años y empotrada en el muro. Las runas no son un idioma: son signos de escritura.</p><p>Esta piedra contiene un texto en nórdico antiguo y conserva un mensaje familiar: «Torsten y Frögunn… la piedra en memoria de…, su hijo». El texto es incompleto: faltan fragmentos.</p><p>Lo preciso es decir: <strong>«Las runas son una forma de escribir; el idioma del texto puede ser nórdico antiguo.»</strong> No tocar ni frotar la piedra.</p>`});
  Object.assign(q[7],{explanation:"La ciudad conserva restos del pasado. Karin agradece que mantengamos viva la historia real de lo ocurrido."});
})();
