window.DAY1_DATA = {
  prologue: [
    {
      k: "TRANSMISIÓN 01 DISPONIBLE",
      title: "K—1520 intenta abrirse.",
      html: `<div class="coordinate">PRIMERA APERTURA · 18–24 MIN<br>CIERRE · AL FINAL DEL DÍA<br>CRONÓMETRO · DESACTIVADO</div><p>El canal contiene referencias a ejecuciones históricas. No muestra violencia gráfica.</p><p class="lead">La hora de entrada quedará registrada, pero no empieza ninguna cuenta atrás.</p>`,
      action: "Abrir la transmisión"
    },
    {
      k: "SAGA · UBICACIÓN OCULTA",
      title: "La coordenada no estaba vacía.",
      image: "saga-transmision-inicial.png",
      alt: "Saga abre la transmisión desde un interior de Estocolmo",
      html: `<p>Dentro hay una voz, una plaza y una fecha: <strong>8 de noviembre de 1520</strong>.</p><p>También hay cuatro capas falsas. Si entras sin retirarlas, llamarás «Suecia» a un país que todavía no existía como hoy, confundirás una unión con una conquista sencilla y seguirás a un vikingo con cuernos que jamás estuvo allí.</p><p class="lead">Necesito que limpies el acceso antes de salir.</p><details class="dossier"><summary>¿QUÉ HA DETECTADO EL MAPA?</summary><p>Cuatro paquetes dañados: nombre del país, identidad vikinga, rutas del Norte y Corona de Kalmar. Al repararlos se abrirá un testimonio humano.</p></details>`,
      action: "Retirar la primera capa"
    },
    {
      k: "MAPA DE ORIENTACIÓN",
      title: "Dos tiempos. Una misma ciudad.",
      routeMap: true,
      html: `<p>Primero abrirás el acceso desde el hotel. Después podrás buscar pruebas en estas calles. Nada depende de seguir un recorrido exacto.</p>`,
      action: "Continuar"
    },
    {
      k: "TESTIMONIO K—1520 · INTEGRIDAD 18 %",
      title: "Me llamo Karin.",
      image: "karin-testimonio-1520-v1.png",
      alt: "Reconstrucción fotográfica realista de Karin en Estocolmo en 1520",
      html: `<p>Si puedes oírme, todavía no han cerrado la plaza. Mi padre ha entrado en el castillo con otros hombres. Dicen que habrá paz.</p><p>Yo no me fío de una paz que necesita soldados en cada puerta.</p><p class="lead">No puedo entregarte mi encargo hasta saber desde qué Suecia vienes. Aquí ese nombre aún está cambiando.</p><details class="dossier character-note" open><summary>RECONSTRUCCIÓN NARRATIVA</summary><p>Karin y su padre no son personas históricas documentadas. Permiten recorrer hechos, lugares y personajes reales sin inventarles palabras a las víctimas conocidas.</p></details>`,
      action: "Responder a Karin"
    }
  ],

  routePlaces: [
    ["Stortorget", "La plaza del Baño de Sangre de Estocolmo y centro del testimonio de Karin."],
    ["Storkyrkan", "Aquí fue coronado Cristián II. En el exterior queda además una silueta medieval bajo los pies."],
    ["Palacio Real", "Ocupa el entorno del antiguo castillo Tre Kronor, donde se celebró el banquete de 1520."],
    ["Prästgatan / Kåkbrinken", "En una esquina se conserva una piedra rúnica reutilizada en un muro."],
    ["Mårten Trotzigs gränd", "El callejón se estrecha hasta unos 90 centímetros: una parada breve y fácil de comprobar."],
    ["Riddarholmen", "Abre la vista hacia el Mälaren y ayuda a entender Estocolmo como ciudad entre aguas."],
    ["Monteliusvägen", "Desde este paseo se leen las islas, Riddarholmen y el Ayuntamiento al otro lado del agua."],
    ["Ayuntamiento", "Busca las tres coronas doradas de su torre: no están en Stortorget."]
  ],

  streetKit: [
    {word:"URSÄKTA",meaning:"Disculpe / perdona",speech:"Ursäkta",prompt:"Necesitas llamar la atención de alguien antes de preguntar. ¿Qué dices?",options:["Ursäkta","Tack","Hej då"],answer:0,tip:"Úsala antes de una pregunta o cuando necesitas pasar."},
    {word:"VAR LIGGER STORTORGET?",meaning:"¿Dónde está Stortorget?",speech:"Var ligger Stortorget?",prompt:"Has perdido la plaza. ¿Qué frase pide su ubicación?",options:["Vad kostar Stortorget?","Var ligger Stortorget?","Jag heter Stortorget"],answer:1,tip:"Var significa «dónde» y ligger, «está situado»."},
    {word:"TACK",meaning:"Gracias",speech:"Tack",prompt:"Te han indicado el camino. ¿Cómo cierras la conversación?",options:["Tack","Ursäkta","Var ligger?"],answer:0,tip:"Tack es una de las palabras que más utilizarás durante el viaje."}
  ],

  missions: [
    {
      title:"El país de los dos nombres", speaker:"Karin",
      obstacle:"El mapa llama a este territorio de dos maneras. Una abre la cerradura; la otra explica por qué en español decís «Suecia».",
      goal:"Reconstruye el nombre, localiza a Svear y Götar y evita colocar un Estado moderno en plena época vikinga.",
      keys:3,time:"4–5 min",minimum:30,action:"Recuperar el nombre",done:"El territorio ya no aparece como un país que surgió de golpe.",
      questions:[
        {id:"d1m1k1",type:"match",visual:"names",title:"Dos fragmentos, dos caminos",scene:"El diccionario del mapa está partido. Une cada fragmento con el nombre que dejó tras de sí.",prompt:"Reconstruye las dos rutas del nombre.",pairs:[["Svea rike · reino de los Svear","Sverige"],["Svethiudh · pueblo de los Svear","Suecia, Sweden, Suède…"]],hint:"Rike sigue conteniendo la idea de reino o territorio.",dossier:"La antigua forma relacionada con Svethiudh no desapareció. En islandés, Suecia sigue siendo Svíþjóð.",success:"NOMBRE RECUPERADO",explanation:"Svearike se contrajo hasta Sverige. Muchas lenguas extranjeras, en cambio, formaron su nombre desde la familia de Svethiudh. Por eso «Suecia» y «Sverige» apenas se parecen."},
        {id:"d1m1k2",type:"match",visual:"sveargotar",title:"Dos pueblos sin una frontera dibujada",scene:"Una falsificación ha pintado una línea exacta entre Svear y Götar. En aquella época no existía una frontera estatal moderna.",prompt:"Devuelve cada comunidad a su zona aproximada.",pairs:[["Svear","Svealand, Uppland y entorno del Mälaren"],["Götar","Västergötland y Östergötland, en Götaland"]],hint:"Svealand conserva una pista; Västergötland y Östergötland conservan la otra.",dossier:"No eran dos Estados cerrados. Eran comunidades y áreas de poder conocidas mediante fuentes tardías, tradiciones y arqueología. Ambas resultaron fundamentales en la formación medieval del reino.",success:"TERRITORIOS RECONSTRUIDOS",explanation:"El nombre del país destaca a los Svear, pero Suecia no se entiende sin los Götar. El reino se formó gradualmente al integrar territorios, centros de poder, leyes, cristianización y monarquía."},
        {id:"d1m1k3",type:"single",title:"El país que todavía no estaba terminado",scene:"El mapa fecha una escena hacia el año 900 y escribe: «El Estado sueco envía una expedición nacional».",prompt:"Repara la frase sin borrar la geografía.",options:["Gentes de regiones de la actual Suecia participan en redes y expediciones; el reino aún no es el Estado moderno.","Suecia ya tiene las fronteras, la bandera y el Gobierno actuales.","No vive nadie en la zona hasta que llegan los vikingos."],answer:0,hint:"Un territorio puede estar habitado y conectado mucho antes de convertirse en un reino unificado.",dossier:"No existe un minuto fundacional único. Monarquía, cristianización e integración territorial avanzaron durante siglos. 1523 será decisivo para la Suecia de los Vasa, pero no es el comienzo de toda su historia.",success:"FECHA DESBLOQUEADA",explanation:"En la época vikinga existían comunidades, reyes y redes de poder, pero no una Suecia con ciudadanía, fronteras y símbolos nacionales como los actuales."}
      ]
    },
    {
      title:"El vikingo que nunca existió", speaker:"Saga",
      obstacle:"Alguien ha colocado un casco con cuernos sobre el testimonio. Es una firma perfecta: reconocible, espectacular y falsa.",
      goal:"Retira tres falsificaciones sin convertir a los vikingos en héroes limpios ni en caricaturas.",
      keys:3,time:"4–5 min",minimum:30,action:"Detectar al impostor",done:"El falso vikingo ha desaparecido. Quedan personas reales, actividades distintas y motivos incómodos.",
      questions:[
        {id:"d1m2k1",type:"single",visual:"helmets",title:"El casco imposible",scene:"Tres piezas aseguran demostrar que los vikingos combatían con cuernos: Gjermundbu, Viksø y una ópera del siglo XIX.",prompt:"¿Cuál constituye una prueba válida de ese uso habitual?",options:["El casco vikingo de Gjermundbu, sin cuernos","Los cascos de Viksø, de la Edad del Bronce","El vestuario romántico del siglo XIX","Ninguna"],answer:3,hint:"No basta con que un objeto sea escandinavo. Debe pertenecer a la época y demostrar un uso comparable.",dossier:"Los cuernos añadirían puntos donde un arma podría engancharse. Tampoco existe apoyo arqueológico para presentarlos como equipo habitual de combate vikingo.",success:"IMPOSTOR RETIRADO",explanation:"No hay pruebas de cascos vikingos de combate con cuernos. Los de Viksø son muchos siglos anteriores. El único casco vikingo completo conocido, hallado en Gjermundbu, no tiene cuernos."},
        {id:"d1m2k2",type:"single",title:"No era un pueblo entero",scene:"El sistema ha etiquetado a cada agricultor, artesana, niña y comerciante escandinavo del año 900 como «vikingo».",prompt:"Selecciona la corrección más precisa.",options:["Vikingo describe sobre todo una actividad o participación en expediciones; no toda persona escandinava lo era.","Vikingo era la ciudadanía oficial de Suecia, Noruega y Dinamarca.","Solo eran soldados profesionales de un único rey."],answer:0,hint:"Piensa en algo que una persona podía hacer durante una etapa, no en un pasaporte.",dossier:"La mayor parte de la vida dependía de granjas, pesca, artesanía, comercio y familias. Las expediciones podían incluir intercambio, guerra, saqueo, migración y exploración.",success:"IDENTIDAD REPARADA",explanation:"«Vikingo» no equivale a «todo escandinavo». Comerciantes, guerreros, colonos y navegantes podían compartir rutas sin constituir una única profesión ni nacionalidad."},
        {id:"d1m2k3",type:"multi",title:"Lo que el frío no explica",scene:"Una nota afirma: «Bajaron al sur porque tenían frío». Karin necesita una explicación que resista una inspección.",prompt:"Recupera cuatro motores plausibles.",options:["Comercio","Botín y esclavización","Prestigio y rivalidades políticas","Asentamiento y acceso a tierras","Querían vivir siempre en clima tropical","Todos obedecían un plan único de Suecia"],answer:[0,1,2,3],hint:"El clima forma parte del contexto, pero no convierte cientos de viajes distintos en una huida común hacia el calor.",dossier:"Las redes vikingas también capturaron y comerciaron con personas esclavizadas hacia el este y hacia el oeste. No conviene romantizarlo.",success:"MOTIVOS RECUPERADOS",explanation:"Tecnología naval, comercio, violencia, esclavización, prestigio, política y asentamiento explican mejor las rutas. El medio ambiente importa, pero «hacía frío» no basta."}
      ]
    },
    {
      title:"Las rutas divididas", speaker:"Saga",
      obstacle:"Los barcos parecen salir del mismo país moderno y dirigirse siempre al oeste. Las dos cosas son falsas.",
      goal:"Separa las redes orientales, occidentales y atlánticas sin asignar pasaportes que todavía no existían.",
      keys:3,time:"5–6 min",minimum:35,action:"Abrir las rutas",done:"El mapa vuelve a mostrar redes, no tres pueblos encerrados en destinos obligatorios.",
      questions:[
        {id:"d1m3k1",type:"match",visual:"vikingRoutes",title:"Este, oeste y océano",scene:"Las rutas eran tendencias y redes superpuestas. No una división absoluta por nacionalidades modernas.",prompt:"Relaciona cada red con su recorrido más característico.",pairs:[["Redes orientales","Báltico y ríos hacia Constantinopla y el Caspio"],["Redes occidentales","Islas Británicas, Francia e Iberia"],["Redes atlánticas","Islandia, Groenlandia y Norteamérica"]],hint:"Birka y Gotland miraban al Báltico; Noruega abría el Atlántico norte.",dossier:"También hubo contactos entre rutas y personas de orígenes diversos. El mapa muestra tendencias geográficas, no fronteras humanas perfectas.",success:"RUTAS ABIERTAS",explanation:"Las áreas de la actual Suecia tuvieron una fuerte orientación oriental; las de Dinamarca y Noruega aparecen mucho en Occidente; Noruega e Islandia fueron decisivas en el Atlántico."},
        {id:"d1m3k2",type:"single",visual:"aland",title:"Las islas en medio",scene:"Ya sabes por qué Estocolmo controla el paso entre el Mälaren y el Báltico. Más al este, un archipiélago ocupa la ruta hacia Finlandia.",prompt:"Su bandera parece sueca y su idioma oficial es el sueco. ¿A qué país pertenece Åland?",options:["Suecia","Finlandia","Es un Estado independiente"],answer:1,hint:"La lengua y la soberanía no tienen por qué coincidir.",dossier:"Åland es autónoma, desmilitarizada y posee parlamento propio. Tiene algo más de 30.000 habitantes; los ferris, la navegación, el comercio y el turismo son esenciales.",success:"ARCHIPIÉLAGO IDENTIFICADO",explanation:"Åland pertenece a Finlandia, aunque su único idioma oficial es el sueco. Su autonomía especial nació de una solución internacional tras una disputa entre Suecia y Finlandia."},
        {id:"d1m3k3",type:"match",visual:"ships",title:"Tres barcos, tres trabajos",scene:"El sistema ha convertido todos los barcos nórdicos en el mismo drakkar de película. En realidad, la silueta cambiaba según el trabajo: un casco largo para ganar velocidad, otro más ancho para cargar y embarcaciones menores para ríos y costas.",prompt:"Asigna cada diseño a su función principal.",pairs:[["Barco largo y estrecho","Velocidad, incursión y guerra"],["Knarr ancho y profundo","Carga, comercio y travesías oceánicas"],["Embarcación costera menor","Pesca y transporte local"]],hint:"Un barco de carga necesita volumen; uno de incursión privilegia velocidad y poco calado.",dossier:"Los barcos largos podían medir entre 20 y 40 metros y llevar muchos remeros. El knarr tenía bordas altas y un casco profundo para transportar mercancías, animales y provisiones. En los ríos orientales convenían barcos menores que pudieran remontar aguas poco profundas e incluso arrastrarse por tierra entre cuencas.",success:"FLOTA RECONSTRUIDA",explanation:"No existió un único «barco vikingo». La forma respondía a la carga, el mar, la distancia y la función. Las tres imágenes son esquemas comparativos, no reconstrucciones de una embarcación concreta."}
      ]
    },
    {
      title:"Una corona, tres reinos", speaker:"Karin",
      obstacle:"El mapa presenta la Unión de Kalmar como una conquista sencilla. Si aceptas esa versión, no entenderás por qué Estocolmo está a punto de abrir sus puertas.",
      goal:"Reconstruye la Unión de Kalmar y descubre qué quería controlar cada lado en 1520.",
      keys:3,time:"6–8 min",minimum:35,action:"Reconstruir la corona",done:"Ya conoces la promesa que puso a Estocolmo ante una decisión imposible.",
      questions:[
        {id:"d1m4k1",type:"multi",visual:"kalmar",title:"El mapa de 1397",scene:"La Unión de Kalmar nació para reunir fuerzas frente al poder económico de la Liga Hanseática y proteger intereses dinásticos en el Norte.",prompt:"Selecciona los tres reinos que compartieron monarca.",options:["Dinamarca","Noruega","Suecia","Finlandia como reino independiente","Islandia como reino independiente"],answer:[0,1,2],hint:"Finlandia estaba integrada en Suecia; Islandia dependía de Noruega.",dossier:"Compartir monarca no fusionó leyes, instituciones ni élites en un único Estado. La Corona danesa fue dominante, pero Suecia tuvo regentes y repetidas rebeliones.",success:"UNIÓN RECONSTRUIDA",explanation:"Dinamarca, Noruega y Suecia compartieron monarca desde 1397. Finlandia e Islandia estaban incluidas dentro de los reinos sueco y noruego."},
        {id:"d1m4k2",type:"multi",title:"Lo que una corona no resolvió",scene:"Cristián II quiere reforzar la autoridad real, asegurar impuestos y debilitar a una élite sueca que controla tierras, comercio y gobierno. Los partidarios de Sten Sture quieren conservar un amplio poder sueco.",prompt:"Recupera las tres causas de inestabilidad.",options:["Cada reino conservaba leyes e instituciones","Las élites competían por poder, impuestos y recursos","Compartir rey no eliminaba identidades ni conflictos","Los tres reinos se fundieron en un Estado idéntico","La unión impedía cualquier guerra interna"],answer:[0,1,2],hint:"Una unión dinástica no equivale a un Estado centralizado.",success:"CONFLICTO DESCIFRADO",explanation:"Las instituciones propias y la lucha por el control mantuvieron la unión en tensión. No fue solo «daneses contra suecos»: dentro de Suecia había partidarios de ambos proyectos."},
        {id:"d1m4k3",type:"match",title:"Los nombres antes de la puerta",scene:"Karin necesita que reconozcas a quienes están decidiendo el destino de la ciudad antes de escuchar su historia. Aquí no basta con memorizar nombres: cada persona representa un poder distinto.",prompt:"Relaciona cada persona con su posición en 1520.",pairs:[["Cristián II","rey de Dinamarca y Noruega; reclamaba también la corona sueca dentro de la Unión de Kalmar"],["Sten Sture el Joven","riksföreståndare o regente de Suecia; dirigía el gobierno contrario a Cristián"],["Gustav Trolle","arzobispo de Uppsala, máxima autoridad de la Iglesia sueca y partidario de la unión"],["Kristina Gyllenstierna","noble sueca, esposa de Sten y responsable de la defensa de Estocolmo"]],hint:"Sten no era virrey de Cristián: riksföreståndare significa regente o administrador del reino.",dossier:"Cristián encarnaba la monarquía de la unión; Sten encabezaba el gobierno sueco como regente; Trolle representaba la máxima autoridad de la Iglesia sueca y era partidario de la unión; Kristina continuó la resistencia después de la muerte de Sten.",success:"PERSONAJES IDENTIFICADOS",explanation:"Cristián encarnaba la monarquía de la unión; Sten, el gobierno sueco encabezado por un regente; Trolle, la Iglesia y el partido unionista; y Kristina, la continuidad de la resistencia tras la muerte de su marido."}
      ],
      epilogue:[
        {k:"KARIN · LA HISTORIA ANTES DE LA PUERTA",title:"La unión llevaba más de un siglo crujiendo.",html:"<p>Desde 1397, los tres reinos compartían monarca para defender intereses dinásticos y reforzarse frente a poderes como la Liga Hanseática. Pero Suecia conservaba leyes y élites propias. Muchos aceptaban la unión; otros querían gobernarse mediante sus regentes.</p>"},
        {k:"STÄKET · 1517",title:"Un arzobispo, una fortaleza y dos lealtades.",html:"<p><strong>Sten Sture el Joven, regente de Suecia</strong>, consideró que <strong>Gustav Trolle, arzobispo de Uppsala</strong>, colaboraba con <strong>Cristián II, rey de Dinamarca y Noruega</strong>.</p><p>Trolle fue depuesto. Su fortaleza de Stäket fue derribada por una decisión apoyada por el Consejo del Reino y representantes de Estocolmo: no fue una acción secreta y personal de Sten.</p><p>La disputa con la Iglesia dio a Cristián una justificación y una oportunidad para intervenir, aunque la guerra tenía también causas políticas, dinásticas y económicas.</p>"},
        {k:"LAGO ÅSUNDEN · ENERO DE 1520",title:"La bala que dejó la ciudad sin regente.",html:"<p><strong>Sten Sture el Joven, regente de Suecia</strong>, fue herido en la pierna por una bala de cañón durante la batalla de Bogesund, junto al lago Åsunden. Allí se enfrentaron las fuerzas suecas de Sten y el ejército enviado por <strong>Cristián II de Dinamarca</strong>.</p><p>Sten murió semanas después, mientras lo trasladaban hacia Estocolmo. Su esposa, <strong>Kristina Gyllenstierna, noble sueca de unos 26 años</strong>, tomó el mando de la resistencia de la capital.</p>"},
        {k:"ESTOCOLMO · SEPTIEMBRE DE 1520",title:"Cristián ofrece una salida.",html:"<p><strong>El rey Cristián II de Dinamarca y Noruega</strong> ha vencido en campo abierto y reclama la corona sueca, pero Estocolmo todavía resiste bajo el mando de Kristina.</p><p>Para conseguir que la ciudad abra las puertas promete amnistía, seguridad personal y respeto a los bienes de sus adversarios.</p><p>Karin no sabe lo que ocurrirá después. Tú sí sabes que una promesa puede copiarse, conservarse y compararse con los hechos.</p>"},
        {k:"DECISIÓN",title:"¿Abrirías las puertas?",choiceId:"open-gates",options:["Sí. La amnistía parece una salida razonable.","No. Mantendría la resistencia mientras fuera posible.","Solo con copias y testigos de cada garantía."],html:"<p>Elige como si estuvieras dentro de la ciudad. No hay una respuesta correcta: tu decisión cambia la forma en que Karin te hablará, no lo que ocurrió.</p>"}
      ]
    },
    {
      title:"La mujer tras las murallas", speaker:"Karin",photo:"karin-testimonio-1520-v1.png",
      obstacle:"Estocolmo ha abierto las puertas. La paz depende de una palabra que el mapa ha borrado del acuerdo.",
      goal:"Ayuda a Karin a comprender la amnistía, proteger una prueba y seguir a Kristina sin conocer todavía el desenlace.",
      keys:4,time:"6–8 min",minimum:40,action:"Entrar sin ser descubiertos",done:"Karin conserva una prueba. La celebración puede comenzar, pero la guardia no se retira.",
      questions:[
        {id:"d1m5k1",type:"order",visual:"asunden",title:"Del lago a las murallas",scene:"Para entender por qué negocia Kristina, reconstruye lo ocurrido tras el combate de Åsunden.",prompt:"Ordena los cuatro pasos.",items:[["a","Sten Sture resulta herido por una bala de cañón"],["b","Muere durante el traslado hacia Estocolmo"],["c","Kristina dirige la resistencia de la ciudad"],["d","Cristián ofrece condiciones para la rendición"]],answer:["a","b","c","d"],hint:"La muerte de Sten deja a Kristina al frente antes de la negociación.",success:"SECUENCIA ABIERTA",explanation:"Sten murió después de ser herido. Kristina sostuvo la defensa y negoció cuando la situación militar hizo muy difícil continuar."},
        {id:"d1m5k2",type:"single",title:"La defensora de Estocolmo",scene:"Karin ve llegar mensajes con un mismo sello. No pertenecen a un rey ni a un general danés.",prompt:"¿Quién dirige la defensa y negocia la rendición?",options:["Kristina Gyllenstierna","Gustav Trolle","Karin"],answer:0,hint:"Es la viuda de Sten Sture y ya ha sido presentada antes de esta decisión.",dossier:"Kristina tenía unos 26 años. Tras la muerte de su marido sostuvo durante meses la resistencia desde Estocolmo y negoció las condiciones de rendición.",success:"DEFENSORA IDENTIFICADA",explanation:"Kristina Gyllenstierna fue una dirigente política y militar real. Karin, en cambio, es la voz ficticia desde la que recorres la escena."},
        {id:"d1m5k3",type:"multi",title:"El sello de amnistía",scene:"Cristián ofrece garantías para que Estocolmo abra las puertas. Karin necesita saber qué protege realmente el documento.",prompt:"Selecciona las cláusulas que harían creíble la rendición.",options:["Amnistía para los partidarios de Sten Sture","Respeto a bienes y seguridad","Olvido de las acciones políticas pasadas","Entrega inmediata de todos los acusados","Ejecuciones públicas pactadas"],answer:[0,1,2],hint:"Si no conoces la palabra, abre el expediente antes de decidir.",dossier:"Amnistía significa que la autoridad renuncia a castigar determinados actos anteriores, normalmente políticos. La ciudad confió en que los adversarios del rey quedarían protegidos.",success:"PROMESA DESCIFRADA",explanation:"Amnistía, seguridad y respeto de bienes permitieron la rendición. Precisamente por eso lo sucedido después se recuerda como una traición."},
        {id:"d1m5k4",type:"single",anyAnswer:true,title:"Tres pruebas, una sola copia",scene:"La coronación se prepara, pero la guardia se acerca. Karin solo puede esconder un documento.",prompt:"¿Qué prueba debe poner a salvo?",options:["La promesa de amnistía","La acusación de Gustav Trolle","La lista de invitados"],choiceResults:["Demostrará que el rey había prometido perdonar a sus adversarios.","Permitirá seguir cómo un conflicto político se convirtió en delito religioso.","Servirá para identificar quién entró en la celebración y quedó atrapado."],hint:"No existe una elección perfecta. Decide qué información quieres conservar.",success:"CONFIANZA DE KARIN AUMENTADA",explanation:"Has decidido con poco tiempo y sin saber qué prueba resultará más importante. Tu elección no cambia lo ocurrido; cambia la forma en que descubrirás la verdad."}
      ]
    },
    {
      title:"La invitación", speaker:"Karin",photo:"karin-testimonio-1520-v1.png",
      obstacle:"La coronación ha terminado. Las puertas del castillo se cierran y una acusación cambia de carpeta.",
      goal:"Sigue la prueba elegida, descubre cómo se sorteó la amnistía y reconstruye qué fue realmente el Baño de Sangre.",
      keys:4,time:"6–8 min",minimum:45,action:"Seguir el documento",done:"La trampa queda reconstruida sin convertirla en batalla ni fingir una cifra exacta.",
      questions:[
        {id:"d1m6k1",type:"order",title:"Una fiesta que cambia de forma",scene:"Cristián II entra en Estocolmo, es coronado y celebra un banquete. Después, el tono cambia.",branchChoice:"d1m5k4",prompt:"Ordena la secuencia que Karin presencia.",items:[["a","Entrada de Cristián en Estocolmo"],["b","Coronación en Storkyrkan"],["c","Banquete en el castillo Tre Kronor"],["d","Puertas cerradas y detenciones"]],answer:["a","b","c","d"],hint:"La violencia no comenzó como una batalla en la plaza.",success:"TRAMPA RECONSTRUIDA",explanation:"La coronación y el banquete crearon apariencia de reconciliación. Después se cerraron las puertas y comenzaron las detenciones."},
        {id:"d1m6k2",type:"single",title:"La acusación que cambia de carpeta",scene:"Sten había impulsado la deposición de Gustav Trolle y el derribo de Stäket al considerarlo aliado de Cristián. Sten ha muerto; Trolle ha recuperado su cargo y reclama contra quienes lo depusieron.",prompt:"¿Qué acusación permite intentar dejar fuera de la amnistía política a los adversarios?",options:["Herejía, como delito contra la Iglesia","Piratería en el archipiélago","Falsificación de moneda"],answer:0,hint:"La nueva carpeta convierte el conflicto político en materia religiosa.",dossier:"No puede reducirse todo a una invención personal de Trolle. La decisión de Stäket existió y participaron autoridades suecas. Lo decisivo fue utilizar la herejía para sostener que el perdón político no protegía a los acusados.",success:"CAMBIO DETECTADO",explanation:"La acusación de herejía permitió presentar el conflicto como delito religioso y sortear la amnistía. La responsabilidad concreta de cada decisión sigue siendo discutida por los historiadores."},
        {id:"d1m6k3",type:"single",title:"No fue una batalla",scene:"Suecia recuerda lo ocurrido como Stockholms blodbad: el Baño de Sangre de Estocolmo. El informe del mapa intenta llamarlo batalla.",prompt:"¿Qué pasó realmente?",options:["Dos ejércitos lucharon en igualdad de condiciones en la plaza","Personas detenidas fueron sometidas a un proceso dirigido y ejecutadas","Fue un accidente durante la coronación"],answer:1,hint:"Las víctimas ya estaban bajo control del vencedor.",success:"INFORME REPARADO",explanation:"No fue una batalla campal. Tras detenciones y un proceso por herejía, decenas de personas fueron ejecutadas en Stortorget los días 8 y 9 de noviembre de 1520."},
        {id:"d1m6k4",type:"single",title:"Ochenta, ochenta y dos, casi cien",scene:"Las fuentes y los recuentos no permiten una exactitud total. Un verdugo afirmó haber ejecutado a 82 personas, pero no conocemos todos los nombres.",prompt:"¿Cómo protege Karin la cifra?",options:["Afirma que fueron exactamente 82 y elimina toda duda","Habla de unas 80–100 víctimas y explica por qué varían los recuentos","Sustituye la cifra por miles para aumentar el peligro"],answer:1,hint:"Una horquilla explicada es más rigurosa que una falsa precisión.",success:"RECUENTO PROTEGIDO",explanation:"Las estimaciones suelen situarse en torno a 80–100 ejecutados. La cifra 82 procede del relato atribuido al verdugo, no de una lista completa e indiscutible."}
      ]
    },
    {
      title:"La ciudad conserva pruebas", speaker:"Karin",photo:"karin-testimonio-1520-v1.png",
      obstacle:"Cinco siglos después, la plaza conserva huellas. Algunas son pruebas; otras, leyendas que parecen demasiado perfectas.",
      goal:"Busca cuatro señales reales en Gamla Stan o ábrelas en la app y decide qué demuestra cada una.",
      keys:4,time:"4–8 min",minimum:30,action:"Salir a la plaza",done:"Has separado piedra, silueta, símbolo y leyenda sin perder el hilo de Karin.",
      questions:[
        {id:"d1m7k1",type:"single",visual:"stones",onsite:true,title:"Las piedras que mienten bien",scene:"En Stortorget busca Schantzska huset, la casa roja de fachada escalonada del número 20. Mira las piedras claras alrededor de las ventanas.",prompt:"Una leyenda dice que hay 82, una por víctima. ¿Cuántas hay realmente?",options:["82, como afirma la leyenda","100, el máximo habitual de la estimación","94; no forman una lista histórica de víctimas"],answer:2,hint:"Puedes contarlas o abrir la prueba visual. El propio edificio ofrece una cifra distinta a la leyenda.",dossier:"La fachada actual es posterior a 1520. Relacionar cada piedra con una víctima es una tradición popular, no un registro contemporáneo.",success:"LEYENDA DETECTADA",explanation:"Hay 94 piedras claras. La leyenda de las 82 víctimas es memorable, pero el número y la fecha de la fachada impiden tratarla como lista histórica."},
        {id:"d1m7k2",type:"single",visual:"choir",onsite:true,title:"Iglesia, castillo y una silueta bajo los pies",scene:"Junto a Storkyrkan busca en el pavimento el contorno del antiguo coro medieval. Después mira hacia el Palacio, donde estuvo Tre Kronor.",prompt:"¿Qué conexión permite reconstruir esa silueta?",options:["Une la iglesia de la coronación con el entorno del castillo y el banquete","Marca el lugar donde se hundió el Vasa","Es la frontera actual entre Suecia y Dinamarca"],answer:0,hint:"La respuesta conecta dos escenarios consecutivos de noviembre de 1520.",dossier:"Más adelante te contaré quién era Gustav Eriksson y por qué el nombre Vasa acabó en un barco. Su historia empieza precisamente con quienes no salieron de esta celebración.",success:"ESCENARIO RECUPERADO",explanation:"Storkyrkan y Tre Kronor estaban a pocos pasos: coronación, banquete, detenciones y plaza formaban un escenario urbano muy concentrado."},
        {id:"d1m7k3",type:"match",visual:"runeAlley",onsite:true,title:"Una piedra mucho más antigua que Karin",scene:"En la esquina de Prästgatan y Kåkbrinken hay una piedra de granito de unos mil años incrustada en los cimientos de una casa. Las runas no son un idioma: son los signos de escritura utilizados para grabar el texto en nórdico antiguo.",prompt:"Relaciona cada hallazgo con lo que demuestra.",pairs:[["Piedra rúnica U 53","La ciudad reutilizó una piedra con escritura de época vikinga, anterior a 1520"],["Callejón de unos 90 cm","La escala física de una calle posterior de Gamla Stan"]],hint:"Una piedra antigua puede estar reutilizada; el nombre documentado del callejón es posterior a 1520.",dossier:"La inscripción conservada puede traducirse aproximadamente: «Torsten y Frögunn, ellos… la piedra en memoria de…, su hijo». El nombre del hijo y parte del verbo se han perdido porque la piedra está rota. Fue reutilizada como material de construcción y quedó colocada con la inscripción hacia Prästgatan. Sabemos que estaba en una pared a comienzos del siglo XVII, pero no consta que esta casa concreta existiera ya en 1520.",success:"CAPAS URBANAS SEPARADAS",explanation:"La piedra U 53 es de época vikinga, pero su ubicación actual es una reutilización posterior. Quedó empotrada en los cimientos con la cara inscrita hacia fuera. Gamla Stan superpone así una piedra de alrededor del siglo XI, una casa de fecha posterior y calles cuyo nombre actual tampoco tiene por qué existir en tiempos de Karin."},
        {id:"d1m7k4",type:"single",visual:"crowns",onsite:true,title:"Las tres coronas no están en la plaza",scene:"Desde Monteliusvägen o Riddarholmen busca la torre del Ayuntamiento, al otro lado del agua. En la cima hay tres coronas doradas.",prompt:"¿Qué puedes afirmar con seguridad sobre ese emblema?",options:["Es un símbolo sueco antiguo, pero su origen exacto admite varias interpretaciones","Demuestra que el Ayuntamiento fue el castillo de Cristián II","Representa con certeza única a Dinamarca, Noruega y Suecia"],answer:0,hint:"Distingue la antigüedad del símbolo de una explicación única sobre su origen.",dossier:"Las Tres Coronas aparecen como emblema sueco desde la Edad Media. Se han propuesto distintas interpretaciones; no conviene presentar una sola como certeza.",success:"SÍMBOLO LOCALIZADO",explanation:"Las tres coronas de la torre son una forma perfecta de reconocer el emblema durante el paseo, pero no prueban por sí solas una teoría única sobre su origen."}
      ]
    },
    {
      title:"El nombre que falta", speaker:"Karin",photo:"karin-testimonio-1520-v1.png",
      obstacle:"El testimonio está a punto de cerrarse. Karin quiere sacar de la plaza el nombre de un joven que no estaba allí.",
      goal:"Identifica a Gustav antes de que fuera rey, sigue la tradición de su huida y abre la coordenada del barco del Día 02.",
      keys:3,time:"6–7 min",minimum:30,action:"Recuperar al ausente",done:"El nombre ha salido de Stortorget. Karin puede cerrar su reconstrucción sin fingir que fue una fuente histórica.",
      questions:[
        {id:"d1m8k1",type:"single",visual:"gustav",title:"Vasa antes de ser rey",scene:"En noviembre de 1520, Gustav Eriksson era un joven noble, antiguo rehén y fugitivo. Su padre, Erik Johansson, murió en el Baño de Sangre. Gustav pidió apoyo en Dalarna contra Cristián, no lo obtuvo y se dirigió hacia Noruega.",prompt:"¿Qué ocurre después, según la tradición que inspira Vasaloppet?",options:["Dos esquiadores lo alcanzan cerca de Sälen y le piden que regrese","Es coronado rey esa misma noche en Stortorget","Funda inmediatamente la carrera de esquí"],answer:0,hint:"La carrera moderna conmemora una persecución tradicional; Gustav no organizó ningún deporte.",dossier:"Como sabe Julia por su trabajo sobre Islandia, un patronímico identifica la filiación: Eriksson significa «hijo de Erik». Más tarde la historiografía lo llamó Vasa por el emblema familiar, interpretado como una gavilla o haz, una vase. No significa que la Suecia actual use siempre patronímicos como Islandia.",success:"NOMBRE RECUPERADO",explanation:"La tradición cuenta que Lars y Engelbrekt alcanzaron a Gustav cerca de Sälen. Vasaloppet recorre hoy 90 km desde Sälen hasta Mora, en dirección contraria a aquella persecución."},
        {id:"d1m8k2",type:"single",visual:"raceMaps",title:"Dos carreras nacidas de un mensajero",scene:"Vasaloppet recuerda una persecución política tradicional. El maratón moderno se inspira en otra carrera legendaria, esta vez entre Maratón y Atenas.",prompt:"¿Qué comparación es correcta?",options:["Vasaloppet: 90 km; maratón moderno: 42,195 km","Ambas carreras miden exactamente 90 km","La distancia olímpica de 1896 ya era exactamente 42,195 km"],answer:0,hint:"El mapa incluye una barra proporcional: 90 km es algo más del doble de 42,195.",dossier:"La carrera olímpica de 1896 fue de unos 40 km. La distancia de 42,195 km se estandarizó más tarde. La carrera del mensajero pertenece a la tradición y no debe contarse como crónica segura.",success:"ESCALA RECUPERADA",explanation:"Vasaloppet mide 90 km entre Sälen y Mora. El maratón moderno mide 42,195 km. Ambos convierten relatos de urgencia y mensajeros en pruebas deportivas posteriores."},
        {id:"d1m8k3",type:"match",visual:"finalSignal",title:"Un nombre, dos puertas",scene:"Gustav fue elegido rey en 1523 y la ruptura con la Unión de Kalmar abrió la Suecia de la dinastía Vasa. Un siglo después, ese nombre apareció sobre un enorme barco de guerra.",prompt:"Completa el enlace antes de que cierren Stortorget.",pairs:[["Gustav Eriksson","futuro rey y fundador de la dinastía"],["Vasa","nombre posterior del linaje y emblema familiar"],["Vasa · 1628","buque de guerra encargado por Gustav II Adolf para reforzar y exhibir el poder naval sueco"]],hint:"Primero fue una persona y una dinastía; después, el nombre de un barco.",dossier:"El Vasa se construyó entre 1626 y 1628. Era un buque real muy armado y profusamente decorado. Resultó demasiado alto y estrecho para su peso: una ráfaga lo escoró y el agua entró por las portas inferiores de los cañones, que estaban abiertas. Se hundió el 10 de agosto de 1628 tras navegar unos veinte minutos. Anders Franzén localizó el pecio en 1956 y el barco volvió a la superficie el 24 de abril de 1961, después de 333 años bajo el agua.",success:"COORDENADA REVELADA",explanation:"La crisis de 1520 impulsó la oposición que llevó a Gustav al poder. El Vasa, encargado en 1625 por su nieto Gustav II Adolf, debía ser una máquina de guerra y una declaración flotante de poder. Su hundimiento y su recuperación en 1961 convierten el Día 02 en una investigación sobre ambición, ingeniería y propaganda.",finalSignal:true}
      ]
    }
  ]
};
