window.DAY2_DATA = {
  title: "Veinte minutos a flote",
  totalKeys: 30,
  prologue: [
    {
      k: "TRANSMISIÓN 02 DISPONIBLE",
      title: "El barco aparece. El nombre no.",
      image: "saga-transmision-inicial.png",
      alt: "Saga abre la transmisión del Día 02",
      html: `<p>La coordenada del Día 01 ha abierto un expediente del astillero real. Alguien ha sustituido un nombre por una acusación: <strong>M. NILSDOTTER → SABOTAJE</strong>.</p><p>El Vasa se hundió en 1628. Si aceptamos un culpable falso, la siguiente ruta desaparecerá.</p><p class="lead">Necesito que reconstruyas cuatro datos: propósito, advertencia, ruta y regreso.</p>`,
      action: "Abrir el expediente"
    },
    {
      k: "SAGA · CANAL DE TEXTO",
      title: "Hoy nadie hablará por un retrato.",
      html: `<p>La mujer borrada fue real: <strong>Margareta Nilsdotter</strong>. Tras morir su marido, continuó el negocio familiar y las responsabilidades del astillero.</p><p>No conservamos un retrato fiable. No voy a inventarle un rostro. La encontrarás en contratos, cuentas y decisiones.</p><details class="dossier" open><summary>REGLA DEL CANAL</summary><p>Toda la historia se presenta por escrito. Solo las expresiones suecas permiten escuchar un modelo y grabarte de forma opcional.</p></details>`,
      action: "Conservar el nombre"
    },
    {
      k: "MAPA DE ORIENTACIÓN",
      title: "Ocho puntos antes de salir.",
      routeMap: true,
      html: `<p>Abre todos los lugares. No hay nada que adivinar: conocer el terreno es la primera parte de la misión.</p>`,
      action: "Continuar"
    }
  ],
  routePlaces: [
    ["Museo Vasa", "Guarda el barco original. Mira los tres mástiles del tejado: indican su altura aparejado."],
    ["Skansen", "Museo al aire libre fundado en 1891 con edificios, oficios, plantas y animales de distintas regiones."],
    ["ABBA The Museum", "Vestuario, discos y puesta en escena del grupo sueco que ganó Eurovisión en 1974."],
    ["Rosendals Trädgård", "Jardines, cultivos, invernaderos, panadería y una posible pausa de fika."],
    ["Strandvägen", "La avenida de la orilla conecta Östermalm con Djurgården."],
    ["Östermalms Saluhall", "Mercado cubierto para reconocer pescado, arenque, salmón y productos suecos."],
    ["Fjällgatan", "Mirador hacia Saltsjön, Skeppsholmen, Djurgården y las rutas del agua."],
    ["Salida al archipiélago", "Desde los muelles la ciudad se prolonga hacia miles de islas, islotes y escollos."]
  ],
  missions: [
    {
      title:"Abrir el terreno", speaker:"Saga", keys:3, time:"4–5 min", minimum:30, action:"Desplegar el mapa",
      obstacle:"El expediente utiliza lugares que todavía no has situado. Entrar a ciegas haría pasar una pista por una casualidad.",
      goal:"Abre el recorrido, la salida oriental y tres desvíos posibles. Aquí no existen respuestas incorrectas.",
      done:"El terreno, la salida hacia el Báltico y las alternativas del día ya están abiertas.",
      questions:[
        {id:"d2m1k1",type:"explore",visual:"dayMap",title:"Ocho puntos del día",scene:"Saga ha unido los lugares de la jornada, pero las fichas siguen cerradas.",prompt:"Abre los ocho puntos y descubre qué debes mirar en cada uno.",items:[
          ["Museo Vasa","Tres mástiles en el tejado anticipan la altura del barco."],["Skansen","Edificios y formas de vida de regiones distintas de Suecia."],["ABBA The Museum","Cuatro iniciales, cuatro personas y una estética imposible de ocultar."],["Rosendals Trädgård","Huerto, invernaderos, panadería y fika."],["Strandvägen","La avenida de la orilla conduce hacia Djurgården."],["Östermalms Saluhall","Un mercado para leer la gastronomía sueca."],["Fjällgatan","La salida oriental de Estocolmo vista desde arriba."],["Muelle","El comienzo del archipiélago y de la ruta que el Vasa no completó."]],success:"TERRENO ABIERTO",explanation:"No has memorizado una lista: ya sabes cómo se relacionan los lugares y qué puede devolverte cada uno."},
        {id:"d2m1k2",type:"explore",visual:"eastMap",title:"El mapa se abre hacia el este",scene:"La costa no termina al salir de Estocolmo. Se fragmenta durante kilómetros.",prompt:"Abre las seis señales hasta alcanzar el Báltico.",items:[
          ["Estocolmo","Una ciudad construida sobre islas y pasos de agua."],["Fjäderholmarna","Primer grupo de islas conocido como puerta del archipiélago."],["Vaxholm","Ciudad y fortaleza en una de las entradas marítimas de Estocolmo."],["Archipiélago interior","Islas más grandes, pobladas y arboladas."],["Archipiélago exterior","Islotes y escollos más expuestos al Báltico."],["Åland","Autonomía de Finlandia situada entre Suecia y Finlandia; su idioma oficial es el sueco."]],success:"SALIDA ORIENTAL ABIERTA",explanation:"Estocolmo se prolonga hacia el Báltico mediante islas, canales, islotes y escollos."},
        {id:"d2m1k3",type:"explore",visual:"plans",title:"Tres desvíos de la aventura",scene:"La ruta puede abrirse en varias direcciones. Aunque no recorras cada lugar físicamente, ninguno quedará fuera de la investigación.",prompt:"Abre las tres alternativas y descubre qué pista guarda cada una.",items:[["Djurgården y Skansen","Naturaleza, edificios históricos y formas de vida de distintas regiones de Suecia."],["ABBA y Fotografiska","Dos maneras muy distintas de contar Suecia mediante imágenes, música y cultura visual."],["Archipiélago y miradores","Islas, pasos de agua y puntos elevados para entender cómo Estocolmo se abre al Báltico."]],success:"ALTERNATIVAS ABIERTAS",explanation:"Los tres desvíos forman parte de la aventura. Si no llegas a visitarlos todos, la aplicación conservará sus pistas esenciales."}
      ]
    },
    {
      title:"La firma que falta", speaker:"Margareta", keys:4, time:"6–7 min", minimum:35, action:"Abrir el libro de cuentas",
      obstacle:"Mi nombre ha desaparecido del contrato y una palabra ocupa su lugar: SABOTAJE.",
      goal:"Recupera la dinastía, el propósito del barco y el trabajo real del astillero.",
      done:"Margareta vuelve al contrato y la primera acusación falsa pierde fuerza.",
      questions:[
        {id:"d2m2k1",type:"match",visual:"vasaLine",title:"El nieto del hombre ausente",scene:"El nombre del barco procede del mismo linaje que recuperaste en Stortorget.",prompt:"Une cada nombre con su lugar en la cadena.",pairs:[["Gustav Eriksson / Gustav Vasa","fundador de la dinastía"],["Gustav II Adolf","nieto de Gustav Vasa y rey que encargó el barco"],["vase","término antiguo asociado al haz del emblema familiar"],["Vasa","barco que toma el nombre de la dinastía"]],hint:"El hombre del Día 01 no encargó el barco: fue su nieto.",success:"LINAJE RECUPERADO",explanation:"El nombre del joven perseguido terminó identificando una dinastía y, un siglo después, un barco de guerra."},
        {id:"d2m2k2",type:"multi",visual:"warMaps",title:"No era un barco de paseo",scene:"Gustav II Adolf reinó veintiún años y pasó dieciocho en guerra. El Vasa se encargó en 1625 mientras Suecia combatía contra Polonia-Lituania.",prompt:"Recupera los tres usos coherentes del Vasa.",options:["Combatir y reforzar la flota","Apoyar operaciones suecas en el Báltico","Exhibir el poder y la legitimidad del rey","Transportar visitantes entre museos de Djurgården"],answer:[0,1,2],hint:"Era un barco de guerra y también una declaración política.",dossier:"La Guerra de los Treinta Años comenzó en 1618 dentro del Sacro Imperio. Mezcló religión con rivalidades territoriales y dinásticas. Suecia intervino directamente en 1630: el Vasa llevaba dos años hundido.",success:"PROPÓSITO RECUPERADO",explanation:"Sus 64 cañones debían convertirlo en artillería, transporte militar y propaganda flotante."},
        {id:"d2m2k3",type:"order",title:"Después de Henrik",scene:"Henrik Hybertsson murió en 1627. El barco, los contratos y cientos de trabajadores no podían detenerse.",prompt:"Reconstruye la continuidad del astillero.",items:[["a","Gustav II Adolf encarga nuevos barcos"],["b","Henrik Hybertsson dirige el diseño inicial"],["c","Henrik enferma y muere"],["d","Margareta continúa el negocio y asume el contrato"],["e","Hein Jakobsson mantiene la dirección técnica"]],answer:["a","b","c","d","e"],hint:"Administrar el negocio no significa diseñar personalmente cada pieza.",success:"FIRMA RECUPERADA",explanation:"Margareta Nilsdotter continuó una actividad de enorme importancia y el trabajo de cientos de personas."},
        {id:"d2m2k4",type:"single",visual:"shipyard",title:"Un astillero internacional",scene:"Carpintería, herrería, velas, cuerdas, escultura, compras y administración funcionaban a la vez.",prompt:"Detecta la frase infiltrada.",options:["Trabajaban especialistas suecos, finlandeses y de otros países","Llegaban materiales de distintas regiones de Europa","Todos hablaban el mismo idioma y usaban exactamente las mismas medidas","El Vasa fue una obra colectiva"],answer:2,hint:"Un gran astillero del siglo XVII reunía tradiciones y sistemas distintos.",success:"INFILTRACIÓN RETIRADA",explanation:"El astillero reunía oficios, lenguas, materiales y tradiciones constructivas diferentes. Margareta debía mantener funcionando todo ese sistema."}
      ]
    },
    {
      title:"Veinte minutos a flote", speaker:"Margareta", keys:4, time:"7–8 min", minimum:40, action:"Repetir la prueba",
      obstacle:"Una nota asegura que nadie pudo prever el naufragio. Los registros dicen lo contrario.",
      goal:"Recupera la advertencia y reconstruye los veinte minutos sin buscar un enemigo imaginario.",
      done:"La advertencia ya consta en el expediente y SABOTAJE empieza a fragmentarse.",
      questions:[
        {id:"d2m3k1",type:"single",visual:"masts",onsite:true,title:"Los mástiles que atraviesan el tejado",scene:"Antes de entrar se ven tres mástiles que no pertenecen a la madera original del barco.",prompt:"¿Qué representan?",options:["Decoración sin relación con el barco","La posición y altura aproximada del Vasa aparejado","Antenas de comunicación camufladas"],answer:1,hint:"El edificio ayuda a imaginar algo que no cabe dentro.",success:"ALTURA RECUPERADA",explanation:"El palo mayor habría alcanzado aproximadamente 52 metros desde la quilla. Busca fuera cuál de los tres es el más alto."},
        {id:"d2m3k2",type:"single",visual:"stability",title:"La prueba sí existió",scene:"Treinta hombres corrieron de una banda a otra mientras el barco estaba amarrado. La demostración tuvo que interrumpirse.",prompt:"¿Qué reveló?",options:["Los cañones estaban sin amarrar","El barco tenía poca estabilidad y el centro de gravedad alto","La tripulación estaba cansada","El puerto tenía demasiada sal"],answer:1,hint:"El problema aparecía al desplazar peso lateralmente.",success:"ADVERTENCIA RECUPERADA",explanation:"La inestabilidad se conocía antes de zarpar. La prueba existió; no produjo una decisión capaz de detener el viaje."},
        {id:"d2m3k3",type:"multi",title:"¿Por qué no lo arreglaron?",scene:"El rey estaba con el ejército en Prusia. Cambiar el Vasa implicaba retrasar la flota, gastar más y admitir que un proyecto real tenía un problema.",prompt:"Fija los cuatro factores plausibles.",options:["Límites de cálculo de la época","Presión militar y política","Coste y retraso de una reconstrucción","Miedo a contradecir un proyecto del rey","Certeza de que el tiempo sería perfecto siempre"],answer:[0,1,2,3],hint:"Una previsión meteorológica perfecta no existía ni podía resolver el diseño.",success:"DECISIÓN DESCIFRADA",explanation:"No faltó una advertencia. Faltó una organización capaz de convertirla en una decisión incómoda."},
        {id:"d2m3k4",type:"order",visual:"sinkingRoute",title:"La cadena de los veinte minutos",scene:"El expediente intenta sustituir una cadena de causas por una explosión enemiga.",prompt:"Ordena lo que ocurrió desde Tre Kronor hasta Beckholmen.",items:[["a","Sale con las portas de los cañones abiertas"],["b","Una primera ráfaga lo inclina y logra recuperarse"],["c","Una ráfaga más fuerte vuelve a escorarlo"],["d","El agua entra por las portas inferiores"],["e","Pierde la capacidad de recuperarse y se hunde"]],answer:["a","b","c","d","e"],hint:"Primero se inclina; después el agua entra por aberturas que quedan demasiado cerca de la superficie.",success:"CADENA RECUPERADA",explanation:"Navegó unos 1.300 metros y alrededor de veinte minutos. Una ráfaga convirtió la inestabilidad en una entrada irreversible de agua. Murieron alrededor de treinta personas; la app no muestra restos humanos."}
      ]
    },
    {
      title:"El barco que volvió", speaker:"Saga", keys:4, time:"6–7 min", minimum:40, action:"Iniciar la búsqueda",
      obstacle:"El mar conservó el casco, pero abrirlo al aire podía destruirlo otra vez.",
      goal:"Localiza el roble negro, comprende el agua salobre y eleva el barco sin romperlo.",
      done:"El regreso de 1956 a 1961 ya forma parte del registro.",
      questions:[
        {id:"d2m4k1",type:"single",visual:"franzen",title:"Una bicicleta, un gato y un trozo de roble",scene:"Anders Franzén buscó sistemáticamente el barco Vasa desde 1954 y extrajo toda clase de restos del fondo del puerto.",prompt:"¿Qué hallazgo justificaba repetir el sondeo veinte metros más allá?",options:["Una bicicleta oxidada","Un fragmento de roble negro","Una botella moderna","Una moneda suelta"],answer:1,hint:"Buscaba una gran estructura naval de madera.",success:"PECIO LOCALIZADO",explanation:"El 25 de agosto de 1956 apareció roble negro en dos puntos. El buzo Per Edvin Fälting confirmó después una pared de madera con dos filas de portas."},
        {id:"d2m4k2",type:"multi",visual:"brackish",title:"¿Por qué quedaba madera?",scene:"El Báltico no es agua oceánica normal. Mezcla aportes salados y agua dulce de numerosos ríos.",prompt:"Construye la combinación que ayudó a conservar el Vasa.",options:["Baja salinidad","Ausencia o escasez del gusano de barco","Agua fría, oscura y con poco oxígeno","Enterramiento parcial en barro","Una capa secreta de barniz real"],answer:[0,1,2,3],hint:"Salobre significa menos sal que el océano; eso cambia qué organismos pueden vivir allí.",success:"CONSERVACIÓN EXPLICADA",explanation:"La baja salinidad impidió que prosperaran organismos capaces de devorar el casco. El hierro se corroyó y la madera no quedó químicamente intacta."},
        {id:"d2m4k3",type:"order",visual:"salvage",title:"Seis túneles bajo un barco",scene:"Las ideas de llenarlo de pelotas de ping-pong o congelarlo en hielo quedaron descartadas.",prompt:"Ordena el rescate real.",items:[["a","Los buzos excavan seis túneles bajo el casco"],["b","Pasan cables de acero"],["c","Conectan los cables a los pontones Oden y Frigg"],["d","Elevan el pecio por etapas"],["e","Tapan huecos y preparan el casco"],["f","El Vasa rompe la superficie el 24 de abril de 1961"]],answer:["a","b","c","d","e","f"],hint:"Los cables deben pasar bajo el casco antes de conectarse a los pontones.",success:"REGRESO RECUPERADO",explanation:"El Vasa salió a la superficie el 24 de abril de 1961 a las 09:03, después de elevaciones progresivas."},
        {id:"d2m4k4",type:"single",visual:"wood",onsite:true,title:"El agua lo protegía; el aire podía destruirlo",scene:"La madera saturada podía encogerse, agrietarse y deformarse si se secaba sin tratamiento.",prompt:"¿Qué solución se aplicó durante años?",options:["Dejarlo secar al sol","Barnizar solo la superficie","Pulverizar polietilenglicol, PEG","Devolverlo al fondo cada noche"],answer:2,hint:"Había que sustituir gradualmente parte del agua de la madera.",success:"MADERA ESTABILIZADA",explanation:"El tratamiento con PEG duró diecisiete años. En el museo busca madera moderna más clara: aproximadamente el 98 % de la madera del Vasa es original."}
      ]
    },
    {
      title:"La pausa que no se improvisa", speaker:"Saga", keys:4, time:"5–6 min", minimum:30, action:"Preparar la pausa",
      obstacle:"El canal necesita una pausa que parezca normal. Un café bebido corriendo no bastará.",
      goal:"Comprende la fika, reconoce el bollo y pide cuatro en sueco.",
      done:"La pausa ya puede camuflar una reunión y el sueco operativo queda guardado.",
      questions:[
        {id:"d2m5k1",type:"multi",visual:"fikaScenes",title:"No es solamente café",scene:"Fika puede ser sustantivo y verbo. Suele incluir una bebida y algo dulce, pero lo esencial es parar y compartir.",prompt:"Recupera las tres escenas que conservan esa idea.",options:["Compañeros hacen una pausa en el trabajo","Amigos se encuentran en una cafetería","Una familia toma café, zumo y bollos en un parque","Alguien bebe café corriendo mientras responde correos"],answer:[0,1,2],hint:"La bebida sola no crea la pausa.",success:"PAUSA RECUPERADA",explanation:"Se parece a «tomar un café» en España, pero fika nombra explícitamente el momento de detenerse y relacionarse."},
        {id:"d2m5k2",type:"single",title:"¿A qué hora se hace?",scene:"El horario ha sido manipulado: FIKA · OBLIGATORIA A LAS 16:00.",prompt:"Corrige la orden.",options:["Siempre exactamente a las 16:00","Puede hacerse por la mañana o por la tarde; algunos trabajos la programan","Solo los domingos","Solo con amistades, nunca con compañeros"],answer:1,hint:"Es una costumbre flexible, aunque algunos trabajos fijan una o dos pausas.",success:"HORARIO REPARADO",explanation:"No existe una hora nacional. Puede hacerse con familia, amistades, compañeros o durante una cita."},
        {id:"d2m5k3",type:"match",visual:"bun",title:"El bollo que activa el canal",scene:"El 4 de octubre Suecia celebra Kanelbullens dag, creado en 1999. Los bollos, sin embargo, acompañan la fika todo el año.",prompt:"Reconstruye la palabra.",pairs:[["kanel","canela"],["bulle","bollo"],["kanelbulle","un bollo de canela"],["kanelbullar","varios bollos de canela"]],hint:"La terminación cambia al pasar de uno a varios.",success:"PALABRA RECONSTRUIDA",explanation:"Kanelbulle es singular y kanelbullar, plural. La canela suele ir acompañada de cardamomo y azúcar perlado."},
        {id:"d2m5k4",type:"speech",title:"Cuatro bollos, por favor",scene:"Sois cuatro. Saga necesita que el pedido no llame la atención.",prompt:"¿Qué frase pide un bollo para cada persona?",options:["Fyra kanelbullar, tack.","Två biljetter, tack.","Var ligger kanelbullen?"],answer:0,word:"FYRA KANELBULLAR, TACK.",meaning:"Cuatro bollos de canela, por favor.",speech:"Fyra kanelbullar, tack.",tip:"Fyra es cuatro; tack puede funcionar aquí como por favor.",success:"CLAVE DE VOZ ACTIVADA",explanation:"La app no puntúa tu pronunciación. Puedes escuchar el modelo, grabarte y comparar ambas versiones."}
      ]
    },
    {
      title:"La isla de todos los tiempos", speaker:"Saga", keys:4, time:"6–7 min", minimum:35, action:"Recorrer las capas de la isla",
      obstacle:"Djurgården aparece como un parque sin pasado. Debajo hay animales reales, caza, tabernas, casas trasladadas y música pop.",
      goal:"Recupera cuatro capas de la isla sin confundirlas entre sí.",
      done:"Djurgården vuelve a mostrar siglos de usos superpuestos.",
      questions:[
        {id:"d2m6k1",type:"order",visual:"djurgarden",title:"Antes de llamarse Djurgården",scene:"La isla se conoció como Walmundsön antes de quedar vinculada de nuevo a la Corona.",prompt:"Ordena las tres capas que dieron forma a su nombre.",items:[["a","1452 · vuelve a ser propiedad real"],["b","1579 · Johan III crea un recinto de animales"],["c","1680s · Karl XI lo cerca como parque de caza"]],answer:["a","b","c"],hint:"Primero vuelve a la Corona; después llegan el recinto y la caza.",success:"NOMBRE RECUPERADO",explanation:"Djur significa animal y gård alude aquí a recinto. En 1733 ya había 32 establecimientos con licencia para servir bebidas: no fue un espacio eternamente vacío."},
        {id:"d2m6k2",type:"single",visual:"skansen",onsite:true,title:"Casas que viajaron hasta Skansen",scene:"Casas, talleres y granjas de regiones y épocas distintas aparecen juntas en una colina.",prompt:"¿Por qué están allí?",options:["Fueron trasladadas o recreadas para mostrar formas de vida de Suecia","Toda Suecia vivía antiguamente en Djurgården","Son decorados de una película","Skansen fue una ciudad medieval amurallada"],answer:0,hint:"Busca carteles con la región de procedencia de cada edificio.",success:"CASAS IDENTIFICADAS",explanation:"Artur Hazelius fundó Skansen en 1891. Es el museo al aire libre más antiguo del mundo."},
        {id:"d2m6k3",type:"explore",visual:"rosendal",title:"Un jardín productivo",scene:"Rosendal no es solo un decorado floral. El mapa detecta un sistema que produce, cocina y reúne.",prompt:"Abre sus cinco piezas.",items:[["Invernaderos","Protegen cultivos y prolongan temporadas."],["Huerto y frutales","El paisaje también produce alimentos."],["Panadería","Transforma ingredientes en pan y bollos."],["Cafetería","Convierte la comida en una pausa compartida."],["Temporada","Lo que se ofrece cambia con el calendario del jardín."]],success:"JARDÍN ABIERTO",explanation:"Desde 1983 una fundación gestiona Rosendal como jardín, cultivo, alimentación y lugar de descanso."},
        {id:"d2m6k4",type:"single",visual:"abba",onsite:true,title:"Cuatro letras y cuatro personas",scene:"Agnetha, Björn, Benny y Anni-Frid dejaron sus iniciales en un nombre que todavía se reconoce en todo el mundo.",prompt:"¿Qué acontecimiento impulsó el salto internacional de ABBA?",options:["Ganar Eurovisión en 1974 con Waterloo","Inaugurar el Museo Vasa en 1961","Actuar en la coronación de Gustav II Adolf","Ganar Sanremo en 1982"],answer:0,hint:"La canción compartía nombre con una batalla napoleónica.",success:"SEÑAL POP RECUPERADA",explanation:"ABBA ganó Eurovisión en Brighton en 1974. Si visitas el museo, busca cómo color, brillo, silueta y plataformas ayudaban a ver sus trajes desde lejos."}
      ]
    },
    {
      title:"Treinta mil fragmentos", speaker:"Saga", keys:4, time:"6–7 min", minimum:35, action:"Abrir la ruta marítima",
      obstacle:"La ruta del Vasa se pierde entre miles de islas y vuelve a confundir Åland con un país independiente.",
      goal:"Distingue archipiélago, población, Vaxholm, Älvsnabben y Åland.",
      done:"La ruta ya diferencia ciudad, archipiélago, mar abierto y autonomía.",
      questions:[
        {id:"d2m7k1",type:"single",visual:"archipelagoCompare",title:"¿Qué es un archipiélago?",scene:"Para reconstruir la ruta prevista del Vasa necesitas entender el territorio que debía atravesar. Canarias tiene pocas islas grandes; Estocolmo suma islas, islotes y escollos por millares.",prompt:"Elige la definición que sirve para ambos.",options:["Conjunto o cadena de islas próximas y relacionadas geográficamente","Una isla rodeada de lagos","Un país formado siempre por siete islas","Cualquier costa con puertos"],answer:0,hint:"El número y el tamaño pueden variar mucho.",success:"CONCEPTO RECUPERADO",explanation:"El recuento de Estocolmo incluye alrededor de 30.000 islas, islotes y escollos; muchas piezas son diminutas. Ese era el paisaje marítimo que esperaba al Vasa."},
        {id:"d2m7k2",type:"match",visual:"islandLives",title:"¿Vive alguien allí?",scene:"El Vasa no se dirigía hacia un mar vacío. El sistema afirma que todas las islas están deshabitadas o llenas de turistas. Las dos cosas son falsas.",prompt:"Relaciona cada escena con una forma de ocupación del archipiélago.",pairs:[["Roca sin edificios","sin vivienda visible"],["Casa aislada","uso permanente o de verano"],["Muelle con pequeño núcleo","pueblo conectado por barco"],["Vaxholm","localidad activa todo el año"]],hint:"El archipiélago combina naturaleza, viviendas dispersas y núcleos urbanos.",success:"VIDA LOCAL RECUPERADA",explanation:"Los ferris son parte de la vida cotidiana. Hay islas deshabitadas, segundas residencias, granjas, pueblos y localidades permanentes. Vaxholm era la primera parada prevista del Vasa."},
        {id:"d2m7k3",type:"order",visual:"vasaRoute",title:"Vaxholm no era el destino final del Vasa",scene:"Los familiares y demás invitados del Vasa debían bajar en Vaxholm. Después, el barco de guerra tenía que continuar hasta Älvsnabben para reunirse con la flota.",prompt:"Ordena la ruta prevista del Vasa y señala dónde quedó interrumpida.",items:[["a","Estocolmo y Tre Kronor"],["b","Naufragio junto a Beckholmen"],["c","Vaxholm · desembarco previsto de invitados"],["d","Älvsnabben · reunión prevista con la flota"]],answer:["a","b","c","d"],hint:"El Vasa naufragó antes de alcanzar Vaxholm.",success:"RUTA DEL VASA RECUPERADA",explanation:"Desde Älvsnabben el Vasa podía recibir órdenes para Gdańsk o Stralsund. Naufragó en Estocolmo y nunca alcanzó siquiera Vaxholm, su primera parada."},
        {id:"d2m7k4",type:"match",visual:"aland",title:"Åland vuelve a la señal",scene:"La bandera parece sueca y se habla sueco, pero la soberanía no depende de los colores ni de la lengua.",prompt:"Recupera cuatro datos rápidos.",pairs:[["País","Finlandia"],["Estatus","autonomía desmilitarizada"],["Idioma oficial","sueco"],["Isla principal","Fasta Åland · Mariehamn, capital de Åland"]],hint:"Åland no es un Estado independiente ni pertenece a Suecia.",success:"ARCHIPIÉLAGO IDENTIFICADO",explanation:"Åland suma 6.757 islas y alrededor de 30.000 habitantes. Navegación, ferris, turismo y transformación de productos agrícolas y pesqueros son actividades importantes."}
      ]
    },
    {
      title:"La ruta que el Vasa no completó", speaker:"Saga", keys:3, time:"5–6 min", minimum:30, action:"Leer el paisaje",
      obstacle:"Tenemos los datos, pero el mapa exige una comprobación sobre el paisaje real antes de eliminar SABOTAJE.",
      goal:"Lee el archipiélago, compara los dos miradores y emite el veredicto final.",
      done:"La falsificación ha desaparecido y una carretera sustituye a la ruta marítima.",
      questions:[
        {id:"d2m8k1",type:"explore",visual:"boatView",title:"La ciudad desde el agua",scene:"Puedes hacerlo durante el barco o abrir los ejemplos visuales desde tierra.",prompt:"Localiza o consulta los cuatro elementos.",items:[["Isla habitada","Una casa o núcleo demuestra que el archipiélago también es territorio vivido."],["Paso estrecho","Los barcos siguen canales entre costas y rocas."],["Baliza","Las señales convierten un paisaje fragmentado en una ruta navegable."],["Transición","Las fachadas urbanas ceden espacio a orillas más verdes y abiertas."]],success:"PAISAJE LEÍDO",explanation:"El archipiélago es una red de pasos, señales, viviendas, poblaciones y rocas, no un decorado de islas iguales."},
        {id:"d2m8k2",type:"explore",visual:"viewpoints",title:"Dos miradores, dos aguas",scene:"El Día 01 miraste hacia el Mälaren. Hoy la ruta necesita también la salida oriental.",prompt:"Abre ambos miradores y la tarjeta de Strandvägen.",items:[["Fjällgatan","Vista hacia Saltsjön, Skeppsholmen y Djurgården: la salida oriental."],["Monteliusvägen","Vista hacia Riddarholmen, Ayuntamiento y Mälaren: la entrada occidental."],["Strandvägen","Significa avenida o camino de la orilla y conecta Östermalm con Djurgården."]],success:"DOS AGUAS CONECTADAS",explanation:"Estocolmo se entiende entre el Mälaren y la salida hacia el Báltico. Los miradores permiten leer ambas direcciones."},
        {id:"d2m8k3",type:"single",visual:"finalRecord",title:"Cuatro hechos abren una carretera",scene:"PROPÓSITO: guerra y poder. ADVERTENCIA: inestabilidad conocida. RUTA: Vaxholm hacia Älvsnabben. REGRESO: 1956 hacia 1961.",prompt:"¿Qué veredicto permite eliminar SABOTAJE?",options:["Margareta saboteó el barco","Una ráfaga imprevisible fue la única causa","Diseño inestable, advertencia sin consecuencias, presión y portas abiertas formaron una cadena","El agua salobre hundió el barco"],answer:2,hint:"El expediente ha recuperado una cadena de decisiones, no un único culpable.",success:"EXPEDIENTE REPARADO",explanation:"No existen pruebas de sabotaje. El nombre de Margareta queda limpio y VAXHOLM abre el último registro consultado por los padres de Saga.",finalSignal:true}
      ]
    }
  ]
};
