/* Día 02 · fuente única: 03_Guiones/V_6_final_aprobada/dia_02_v6_final_aprobada.md.
   V4 aporta únicamente el motor y los recursos visuales que siguen siendo útiles. */
window.DAY1_DATA={
  meta:{day:"02",store:"codigo-gripsholm-v7-day02",contentVersion:"v7-final-day2",place:"ESTOCOLMO · DJURGÅRDEN",title:"El barco al que quisieron culpar",landing:"Una acusación falsa ha entrado en el expediente.",badge:"expediente de Margareta",objective:"COMPROBAR SI HAY EVIDENCIA DE SABOTAJE",objectiveCopy:"Miraremos el encargo, el astillero, el accidente y lo que el barco devolvió tres siglos después.",evidenceCopy:"Cada misión devuelve una parte del expediente de Margareta.",fine:"Las escenas en primera persona de Margareta son una reconstrucción narrativa basada en fuentes; no son citas literales.",verifiedTitle:"El nombre de Margareta está limpio.",verifiedAction:"Abrir el cierre de Saga",result:{title:"El barco al que quisieron culpar",evidence:"Expediente de Margareta recuperado",openQuestion:"¿Por qué La Sombra necesita que una mujer que dirigió un astillero desaparezca de la historia?",next:{href:"dia3.html",label:"Abrir el Día 03"}}},
  prologue:[
    {k:"SAGA · EXPEDIENTE ALTERADO",title:"Una mentira añadida",image:"saga-transmision-inicial.png",alt:"Saga abre el expediente del Vasa",html:`<p>Ayer protegimos una historia que La Sombra quería borrar. Hoy ha hecho lo contrario: ha añadido una mentira.</p><p>El archivo acusa a una mujer de haber saboteado el barco más famoso de Suecia. No vamos a limpiar su nombre con una frase bonita: vamos a mirar el encargo, el astillero, el accidente y lo que el barco devolvió tres siglos después.</p>`,action:"Abrir el expediente"},
    {k:"MARGARETA NILSDOTTER · PERSONA HISTÓRICA",title:"La mujer a la que quieren culpar",image:"vasa-museum-public-domain.jpg",alt:"El Vasa conservado en el Museo Vasa",html:`<p><strong>Reconstrucción narrativa basada en fuentes.</strong> Mi marido, Henrik Hybertsson, recibió el contrato para construir barcos del rey. Cuando murió, el trabajo no desapareció: quedaban materiales que comprar, cuentas que pagar y cientos de personas cuya tarea debía coordinarse.</p><p>Si el barco sale bien, todos mirarán al rey. Si sale mal, sé que será muy fácil buscar a alguien cerca a quien culpar.</p><p>Saga añade: en los meses de mayor actividad trabajaban más de cuatrocientas personas. Margareta sostuvo el funcionamiento del astillero cuando Henrik ya no pudo hacerlo.</p>`,action:"Abrir el expediente de Margareta"}
  ],
  routePlaces:[],
  missions:[
    {title:"La ciudad desde la que sale el barco",speaker:"Margareta",photo:"vasa-museum-public-domain.jpg",characterCaption:"persona histórica · reconstrucción narrativa basada en fuentes",keys:1,time:"4–6 min",action:"Mirar el puerto",obstacle:"Antes de hablar del desastre, mirad Estocolmo. Un puerto no es solo agua: necesita una ciudad que lo abastezca, islas que orienten la salida y una ruta hacia el Báltico.",goal:"Situar la ciudad, el puerto y la ruta que el Vasa no llegó a completar.",done:"Puerto, archipiélago y salida hacia el Báltico ya forman parte del expediente.",reaction:"La ruta ya no parece una línea vacía: ciudad, islas y mar regional explican por qué este puerto podía movilizar una flota.",closing:"Ya veis que el barco no nació en una bañera aislada. Ahora toca entender por qué el rey quería que fuese enorme.",contexts:[
      {k:"MAPA DE AGUA · ESTOCOLMO",title:"Estocolmo no es una isla sola",visual:"d2Port",html:`<p><strong>Gamla Stan y Tre Kronor:</strong> núcleo político junto al agua. <strong>Astillero histórico:</strong> área naval del Estocolmo del siglo XVII. <strong>Beckholmen:</strong> el Vasa se hundió cerca de esta isla tras navegar apenas unos 1.300 metros. <strong>Djurgården:</strong> hoy conserva el barco en el Museo Vasa.</p><p>Hacia el este se abre una cadena de islas y pasos: el archipiélago. Åland queda mucho más lejos, entre Suecia y Finlandia, como referencia del Báltico.</p>`},
      {k:"RUTA PREVISTA Y RUTA REAL",title:"La ruta que el Vasa no llegó a hacer",visual:"d2Port",html:`<p><strong>10 de agosto de 1628:</strong> salida desde el muelle bajo Tre Kronor, unos 1.300 metros de puerto y naufragio junto a Beckholmen.</p><p><strong>Plan de la Armada:</strong> escala en Vaxholm para que bajaran familiares y otros pasajeros; después, base naval de Älvsnabben y órdenes posibles para reforzar el bloqueo de Gdańsk o apoyar la escuadra de Stralsund.</p><p>El Vasa se hundió antes de alcanzar Vaxholm. Gdańsk y Stralsund fueron destinos militares posibles, no lugares a los que llegara.</p>`}
    ],questions:[{id:"d2v7m1",type:"single",title:"La nota que explica el puerto",prompt:"¿Qué explicación describe mejor por qué Estocolmo era útil para construir y movilizar un barco de guerra?",options:["La ciudad combinaba muelles, población, abastecimiento, aguas protegidas entre islas y una salida hacia el Báltico.","Estaba aislada de las rutas marítimas y solo podía comunicarse por carretera.","Se eligió porque ya existía allí el Museo Vasa."],answer:0,hint:"Mira la relación entre ciudad, islas, pasos de agua y mar regional.",success:"PUERTO Y SALIDA ENTENDIDOS.",explanation:"Un mismo mapa sirve para tres escalas: dónde se construyó el barco, por qué la salida estaba protegida y qué mar conectaba la guerra."}]},
    {title:"El rey quiere un barco para guerrear",speaker:"Margareta",photo:"vasa-museum-public-domain.jpg",characterCaption:"persona histórica · reconstrucción narrativa basada en fuentes",keys:1,time:"5–6 min",action:"Abrir el encargo",obstacle:"El rey quiere más barcos para la guerra. Mi marido recibió un encargo enorme: un barco que transportara fuerza, disparara lejos y mostrara el poder de la Corona antes incluso de entrar en combate.",goal:"Relacionar el nombre Vasa con la dinastía y entender el encargo militar de 1628.",done:"El Vasa aparece como proyecto de guerra y poder, no como barco de paseo.",reaction:"El nombre del barco ya une la plaza de 1520 con la dinastía de su nieto. La Sombra no podrá convertirlo en una casualidad.",closing:"Un encargo así no se resuelve con una persona y un martillo. Ahora mirad el trabajo que había dentro de él.",contexts:[
      {k:"DÍA 1 → DÍA 2",title:"El nieto del hombre ausente",visual:"gustav",html:`<p><strong>Gustav Eriksson / Gustav Vasa:</strong> escapó de la crisis de 1520 y fue elegido rey en 1523. <strong>Karl IX:</strong> hijo de Gustav Vasa y padre de Gustav II Adolf. <strong>Gustav II Adolf:</strong> nieto de Gustav Vasa; rey que impulsó el encargo del Vasa.</p><p><strong>Vasa</strong> era también el emblema dinástico, una gavilla o haz de ramas. El barco convierte ese linaje en símbolo flotante.</p>`},
      {k:"BÁLTICO · 1628",title:"Una guerra y una nueva forma de pelear en el mar",visual:"d2War",html:`<p>Suecia estaba en guerra con la Mancomunidad Polaco-Lituana. El Vasa podía reforzar el bloqueo de Gdańsk o apoyar la protección de Stralsund.</p><p>La ambición no era inventar el primer barco armado de la historia: era concentrar una fuerza excepcional en un barco enorme, con <strong>dos cubiertas de artillería</strong>. Salió con <strong>64 cañones</strong>; ocho portas permanecían vacías porque la fundición real no producía las piezas al ritmo del astillero.</p>`}
    ],questions:[{id:"d2v7m2",type:"single",title:"El plan que encaja con un Vasa",prompt:"Si fueras quien planifica la guerra en el Báltico en 1628, ¿qué uso explica mejor un barco como el Vasa?",options:["Llevar artillería y tropas, reforzar rutas y puertos aliados, y mostrar una fuerza capaz de enfrentarse a otras flotas.","Llevar visitantes a una isla para disfrutar del verano.","Navegar sin cañones ni emblemas para que nadie se fijara en él."],answer:0,hint:"El mapa muestra una guerra por rutas y puertos. Mira para qué sirven dos cubiertas de cañones.",success:"ENCARGO DE GUERRA LEÍDO.",explanation:"Su artillería, su capacidad de transporte y su decoración hacían del Vasa una fuerza militar y una declaración política."}]},
    {title:"El astillero que tenía que conseguir lo imposible",speaker:"Margareta",photo:"vasa-museum-public-domain.jpg",characterCaption:"persona histórica · reconstrucción narrativa basada en fuentes",keys:1,time:"6–7 min",action:"Abrir el libro de cuentas",obstacle:"No diseñé el casco. Pero una cosa es un dibujo o una medida, y otra conseguir madera, hierro, velas, cuerdas, salarios y oficios para que cientos de personas puedan terminar un barco a tiempo.",goal:"Entender qué sostenía Margareta y qué reveló la advertencia de estabilidad antes de la salida.",done:"El expediente diferencia la gestión de Margareta del diseño técnico y conserva la advertencia que existió.",reaction:"La advertencia existió y el trabajo de Margareta queda visible: coordinar no era lo mismo que diseñar el casco.",closing:"La advertencia existió. Eso no significa que alguien tuviera una solución exacta y decidiera esconderla. Lo que ocurrió después fue peor.",contexts:[
      {k:"PERSONAS, OFICIOS Y CUENTAS",title:"La mujer que sostenía el astillero",visual:"d2Shipyard",html:`<p>Henrik Hybertsson era maestro constructor naval y responsable del diseño; murió en la primavera de <strong>1627</strong>. Margareta Nilsdotter continuó la dirección del astillero. Las fuentes del Museo Vasa la sitúan al frente de una gran parte de la gestión y de varios cientos de trabajadores.</p><p>En meses cálidos podían trabajar más de 400 personas: suecos, finlandeses, personas del Báltico, daneses, alemanes y trabajadores estacionales neerlandeses. Convivían lenguas, oficios y sistemas de medidas.</p><p><strong>Margareta:</strong> «Yo llevo cuentas, suministros y el trabajo de mucha gente. Si el barco sale bien, todos mirarán al rey. Si sale mal, todos buscarán a quién culpar.»</p>`},
      {k:"UNA SEÑAL, NO UNA SOLUCIÓN MÁGICA",title:"La advertencia que no resolvió el problema",visual:"d2Stability",html:`<p><strong>No fue el día de la botadura.</strong> El casco se botó en la primavera de 1627 y durante el año siguiente se añadió aparejo, equipo y artillería. Semanas antes de la salida de agosto de 1628, el capitán avisó de que el Vasa era inestable. El vicealmirante Klas Fleming ordenó una demostración: treinta hombres corrieron de babor a estribor. Se detuvo tras tres pasadas por miedo a que el barco volcara en el muelle.</p><p>Era una señal importante, no un cálculo moderno exacto. La ciencia para predecir estabilidad y velocidad estaba aún más de un siglo en el futuro.</p>`},
      {k:"MUSEO VASA · MIRAR HACIA ARRIBA",title:"Los tres mástiles que salen del museo",image:"vasa-museum-public-domain.jpg",character:true,speaker:"Saga",html:`<p>Los tres mástiles del tejado del museo no son los originales: muestran la altura total que habría tenido el Vasa con los mástiles levantados. El mástil principal alcanzaba aproximadamente <strong>52 metros desde la quilla hasta la punta</strong>.</p><p>Las partes superiores originales no sobrevivieron; la altura es una reconstrucción razonada. El Vasa se expone como barco amarrado en invierno, no con todo el velamen desplegado.</p>`}
    ],questions:[{id:"d2v7m3",type:"single",title:"El problema de verdad",prompt:"¿Qué problema describe mejor el reto de Margareta al dirigir el astillero tras la muerte de Henrik?",options:["Mantener materiales, pagos y oficios coordinados entre cientos de personas, sin sustituir el trabajo técnico del constructor naval.","Sustituir a quienes diseñaban, construían y abastecían el astillero, tomando ella sola cada decisión técnica y artesanal.","Terminar el barco sin proveedores ni trabajadores, porque un astillero era una oficina pequeña."],answer:0,hint:"La gestión hace posible que muchos oficios distintos lleguen a tiempo.",success:"TRABAJO DE MARGARETA VISIBLE.",explanation:"Margareta sostuvo un sistema de compras, pagos, materiales y personas. No hace falta inventar que diseñó el casco para reconocer la importancia de su trabajo."}]},
    {title:"Sabotaje",speaker:"Margareta",photo:"vasa-museum-public-domain.jpg",characterCaption:"persona histórica · reconstrucción narrativa basada en fuentes",keys:1,time:"5–6 min",action:"Abrir el modelo",obstacle:"El Vasa salió del puerto el 10 de agosto de 1628. Apenas estuvo a flote unos veinte minutos. Mucha gente vio el desastre y, aun así, alguien ha decidido escribir que yo lo provoqué.",goal:"Separar vulnerabilidad, detonante e investigación posterior sin inventar una culpable cómoda.",done:"La acusación de sabotaje pierde su única apariencia de explicación.",reaction:"La cadena de causas está completa. Una acusación sin fuente no puede sustituir lo que explican el diseño, la ráfaga y el agua.",closing:"Se puede saber que algo salió mal sin fingir que se conoce una conspiración. Quizá el barco conserve pruebas mejores que los rumores.",contexts:[
      {k:"MODELO CAUSAL",title:"Dos causas que actúan juntas",visual:"d2Sinking",html:`<p><strong>Vulnerabilidad previa:</strong> casco relativamente estrecho y parte superior demasiado alta y pesada; centro de gravedad elevado e inestabilidad.</p><p><strong>Detonante de aquel día:</strong> una racha lo escora; las portas inferiores estaban abiertas y el agua entra. El peso del agua impide recuperarse.</p><p>Cerrar las portas habría evitado esa entrada inmediata de agua. No habría borrado el problema de estabilidad: quizá habría dado tiempo para volver y modificar el barco.</p>`},
      {k:"INVESTIGACIÓN POSTERIOR",title:"Lo que se investigó y lo que no se demostró",html:`<p>Después del hundimiento se escuchó a personas relacionadas con el barco y se discutieron decisiones de construcción y navegación. Los responsables del astillero defendieron que se había construido según las medidas aprobadas por el rey.</p><p>No se aclaró una responsabilidad única ni se castigó a una sola persona. Tampoco existe prueba de un pago secreto polaco a Margareta. La etiqueta de sabotaje se elimina porque no tiene fuente que la sostenga.</p>`}
    ],questions:[{id:"d2v7m4",type:"single",title:"La explicación que no necesita una culpable cómoda",prompt:"¿Qué conclusión conserva todo lo que muestra el modelo?",options:["El Vasa era peligrosamente inestable; la ráfaga y el agua que entró por las portas abiertas hicieron que se hundiera.","Las portas abiertas explican por sí solas el hundimiento; la estabilidad del barco no influyó.","La acusación contra Margareta basta para concluir que hubo sabotaje, aunque no exista evidencia material."],answer:0,hint:"Distingue una vulnerabilidad de fondo del hecho que convirtió el riesgo en naufragio.",success:"CAUSAS ORDENADAS.",explanation:"No hay evidencia de sabotaje. Una explicación honesta conserva las causas combinadas y distingue la responsabilidad de la culpa inventada."}]},
    {title:"El barco que volvió",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"5–6 min",action:"Mirar lo que devolvió el mar",obstacle:"Margareta no pudo saberlo, pero el Vasa volvió a la superficie 333 años después, en 1961. El mar no había guardado una carta de sabotaje: había guardado el barco, sus objetos y muchas preguntas respondibles.",goal:"Entender cómo se localizó, elevó y conservó el Vasa y qué tipo de pruebas puede aportar un objeto.",done:"El propio barco devuelve una explicación más difícil y más útil que un rumor.",reaction:"El Vasa no contiene una prueba mágica. Conserva objetos, madera y señales que permiten hacer preguntas concretas.",closing:"Margareta no necesita que nadie la perdone: la evidencia desmonta una acusación sin base.",contexts:[
      {k:"1956 → 1961",title:"Seis túneles, cables y una subida lenta",visual:"d2Recovery",html:`<p>Anders Franzén localizó el Vasa mediante sondeos. Buzos excavaron <strong>seis túneles</strong> bajo el casco con chorros de agua, pasaron cables de acero y los conectaron a pontones de elevación. El barco se levantó por etapas hasta que pudo volver a flotar.</p><p>El <strong>24 de abril de 1961</strong> volvió a ver la luz. No fue el final: empezó una conservación de décadas.</p>`},
      {k:"AGUA SALOBRE",title:"Por qué quedaba tanto Vasa",visual:"d2Brackish",html:`<p>El Báltico mezcla agua dulce y salada: es <strong>salobre</strong>. El gusano de barco no prospera allí como en mares más salados y el poco oxígeno del fondo ayudó a conservar la madera. Por eso se conserva aproximadamente el <strong>98 %</strong> de la estructura original.</p><p>Salir del agua no era un final feliz automático: la madera húmeda podía encogerse, deformarse y agrietarse. El museo sigue controlando ambiente, soporte y conservación.</p>`}
    ],questions:[{id:"d2v7m5",type:"match",title:"El objeto que sirve como prueba",prompt:"Relaciona cada hallazgo con lo que permite saber.",pairs:[["Carro de cañón","Cómo se colocaba y manejaba la artillería."],["Baúl","Que una persona llevaba pertenencias y vida cotidiana a bordo."],["Barril y huesos","Qué provisiones podía llevar una travesía."],["Fragmentos","Que el rescate recuperó más de 30.000 objetos, no una única prueba mágica."]],hint:"Cada objeto responde una pregunta concreta sobre el barco y quienes viajaban en él.",success:"BARCO LEÍDO COMO EVIDENCIA.",explanation:"Las pruebas materiales explican trabajo, vida cotidiana y tecnología. Ninguna sustituye el análisis de todo el conjunto."}]},
    {title:"Vamos a retomar fuerzas. ¿Un fika?",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"3–4 min",action:"Abrir la pausa",obstacle:"Habéis seguido un encargo, una advertencia, un hundimiento y una investigación. ¿Qué tal va vuestro sueco? Vamos a hacer una pausa.",goal:"Entender qué es fika y guardar una frase útil de sueco actual sin convertirla en un examen.",done:"La frase práctica queda guardada para pedir un fika de verdad.",reaction:"Esta evidencia no se queda en la pantalla: si os apetece, podéis usarla en una cafetería.",closing:"El objetivo ahora no es una pantalla. Es una pausa compartida antes de continuar hacia Djurgården.",contexts:[
      {k:"SUECO ACTUAL · PAUSA PRÁCTICA",title:"Fika es más que café",visual:"d2Fika",html:`<p><strong>Fika</strong> es una pausa social: café u otra bebida, algo de comer y tiempo para conversar o descansar. No es una carrera para beber café ni una hora fija.</p><p><strong>kanelbulle</strong> es un bollo de canela. Es muy popular hoy; no lo colocamos como si fuera una merienda de 1628.</p>`},
      {k:"TARJETA PARA USAR HOY",title:"Fyra kanelbullar, tack.",speaker:"Saga",character:true,html:`<p><strong>Fyra kanelbullar, tack.</strong> = «Cuatro bollos de canela, por favor».</p><div class="evidence-grid three"><div><b>FYRA</b><span>cuatro</span></div><div><b>KANELBULLAR</b><span>bollos de canela</span></div><div><b>TACK</b><span>gracias; aquí, por favor</span></div></div><p>Es una frase práctica para usar hoy; nunca se puntúa la pronunciación.</p>`}
    ],questions:[{id:"d2v7m6",type:"single",title:"La pausa que no se improvisa",prompt:"¿Qué descripción encaja mejor con fika?",options:["Una pausa compartida con bebida, algo de comer y tiempo para hablar o descansar.","Beber café deprisa mientras se responden mensajes.","Una obligación nacional exactamente a las cuatro de la tarde."],answer:0,hint:"La bebida sola no crea la pausa.",success:"FIKA ENTENDIDO.",explanation:"Puede ser con familia, amistades o compañeros. En España se parece a tomar un café, pero fika destaca el gesto de detenerse y compartir."}]},
    {title:"La isla de todos los tiempos",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"4–5 min",action:"Recorrer las capas de la isla",obstacle:"El Vasa ya no está en el astillero de Margareta. Está en Djurgården, una isla que ha cambiado de función muchas veces.",goal:"Leer Djurgården como paisaje de caza real, museos, jardines y cultura contemporánea.",done:"La isla vuelve a mostrar siglos de usos superpuestos.",reaction:"Un paisaje no necesita congelarse para guardar su historia. Djurgården cambia de uso y aún conserva huellas.",closing:"En pocos kilómetros caben una historia naval, jardines, casas de otras regiones y música. Pero aún falta mirar hacia dónde iba a salir el Vasa.",contexts:[
      {k:"MAPA DE VISITA",title:"Djurgården no es solo el Museo Vasa",visual:"d2Djurgarden",html:`<p><strong>Djurgården:</strong> su nombre conserva una relación histórica con parque de caza real. <strong>Skansen:</strong> reúne edificios y entornos para explicar oficios y formas de vida de distintas regiones; no significa que toda Suecia viviera igual. <strong>Rosendal:</strong> jardín y cultivo dentro de la ciudad. <strong>ABBA:</strong> música popular contemporánea.</p><p>Una isla puede guardar al mismo tiempo memoria de siglos y vida cultural actual. No hace falta visitarlo todo para entender sus capas.</p>`}
    ],questions:[{id:"d2v7m7",type:"single",title:"La isla que cambia sin borrar lo anterior",prompt:"¿Qué frase explica mejor Djurgården?",options:["Fue zona de caza real y hoy reúne museos, jardines, paseos y espacios culturales: sus usos han cambiado con el tiempo.","Nació como Museo Vasa y antes no existía ninguna historia en la isla.","Todo lo que se ve conserva exactamente la misma función que en el siglo XVII."],answer:0,hint:"Un paisaje histórico puede cambiar de uso y seguir dejando rastros.",success:"ISLA LEÍDA POR CAPAS.",explanation:"Djurgården ayuda a entender cómo una ciudad usa, transforma y conserva su paisaje."}]},
    {title:"La ruta que el Vasa no completó",speaker:"Margareta",photo:"vasa-museum-public-domain.jpg",characterCaption:"persona histórica · reconstrucción narrativa basada en fuentes",keys:1,time:"4–5 min",action:"Abrir el mapa regional",obstacle:"El Vasa no llegó a su destino. Aun así, su ruta sirve para leer el archipiélago y recordar que un mapa físico y un mapa político no cuentan exactamente lo mismo.",goal:"Distinguir archipiélago, lengua y soberanía antes de cerrar el expediente.",done:"La ruta diferencia ciudad, archipiélago, mar abierto y autonomía; la etiqueta de sabotaje ya no tiene dónde esconderse.",reaction:"El expediente ya puede guardar una frase completa: el proyecto fue ambicioso, el accidente tuvo causas comprobables y la acusación contra Margareta no tiene evidencia.",closing:"Gracias por mirar el barco, no el rumor. La ruta ya puede abrirse hacia Örebro y Tiveden.",contexts:[
      {k:"MAPA REGIONAL",title:"Islas, lengua y soberanía",visual:"d2Aland",html:`<p>Un <strong>archipiélago</strong> es un conjunto de islas y las aguas entre ellas. <strong>Åland</strong> está entre Suecia y Finlandia, a la entrada del golfo de Botnia. Hoy es autónoma, mayoritariamente de lengua sueca, pertenece a Finlandia y tiene estatuto de desmilitarización.</p><p>Estar cerca de Suecia y hablar sueco no convierte automáticamente a Åland en parte de Suecia. Geografía, lengua y soberanía responden a preguntas distintas. Como ocurre con muchas zonas de España y Europa, una comparación sirve para separar cercanía, lengua e instituciones, no para igualar historias distintas.</p>`}
    ],questions:[{id:"d2v7m8",type:"single",title:"La tarjeta que abre la ruta",prompt:"¿Qué frase puede guardar el expediente de Margareta antes de abrir la carretera?",options:["El Vasa fue un barco de guerra muy ambicioso; Margareta dirigió el astillero tras la muerte de Henrik; el hundimiento combinó inestabilidad y agua por portas abiertas; no hay evidencia de sabotaje.","Como el barco se hundió, Margareta debió de ser culpable aunque no diseñara el casco ni exista una fuente.","El viento explica todo y el diseño del barco no importa."],answer:0,hint:"Conserva propósito, trabajo, causas y límites de la evidencia.",success:"EXPEDIENTE DE MARGARETA RECUPERADO.",explanation:"La evidencia no absuelve con una frase sentimental: elimina una acusación que no tiene base y deja una explicación verificable."}]}
  ],
  ending:[
    {image:"saga-canal-asegurado.png",caption:"Saga · transmisión del Atlas",k:"SAGA · EXPEDIENTE RECUPERADO",title:"Margareta no saboteó el Vasa.",html:`<p>El barco era inestable. La advertencia existió. Aun así zarpó con las portas abiertas y una ráfaga convirtió el problema en naufragio.</p><p>Quien manipuló el expediente quería un culpable sencillo. Nosotras hemos recuperado una cadena de decisiones y pruebas.</p>`,action:"Devolver el nombre"},
    {image:"vasa-museum-public-domain.jpg",caption:"Margareta Nilsdotter · reconstrucción narrativa basada en fuentes",k:"MARGARETA · CIERRE DE LA RECONSTRUCCIÓN",title:"Mi nombre vuelve al contrato.",html:`<p>No construí el barco sola. Nadie lo hizo.</p><p>Mantuve el astillero, sus cuentas y sus trabajadores cuando Henrik murió. El Vasa no llegó a la guerra, pero conservó durante siglos el trabajo de todos.</p><p class="lead">Ahora buscad la ruta que alguien consultó después de Estocolmo.</p>`,action:"Revelar la siguiente ruta"},
    {image:"saga-canal-asegurado.png",caption:"Saga · siguiente coordenada",k:"SEGUNDA CONSECUENCIA",title:"El mar se cierra. Se abre una carretera.",html:`<div class="coordinate">ESTOCOLMO → ÖREBRO → TIVEDEN<br>NOMBRE ASOCIADO · ENGELBREKT<br>CONSULTA DESCONOCIDA · +6 HORAS</div><p>Ese fue el último itinerario auténtico de mis padres. Seis horas después, otro dispositivo consultó la misma carretera.</p><p class="lead">Alguien va detrás de ellos.</p>`,action:"Cerrar el canal"}
  ]
};

// Día 02 · ajustes de contenido V8 aceptado y práctica de sueco actual.
(() => {
  const d=window.DAY1_DATA, m=d.missions, q=m.map(x=>x.questions[0]);
  d.meta.store="codigo-gripsholm-v8-day02";
  d.meta.contentVersion="v8-day02-final";
  d.prologue[1].html=`<p><strong>Reconstrucción narrativa basada en fuentes.</strong></p><p>Mi marido, Henrik Hybertsson, recibió el contrato para construir barcos del rey. Cuando murió, el trabajo no desapareció: quedaban materiales que comprar, cuentas que pagar y cientos de personas cuya tarea debía coordinarse.</p><p>Si el barco sale bien, los cumplidos serán para el rey. Si sale mal, será muy fácil ponerme a mí como culpable.</p><p>En los meses de mayor actividad trabajaban más de cuatrocientas personas. Yo sostuve el funcionamiento del astillero cuando Henrik murió.</p>`;
  Object.assign(q[0],{title:"Entender el puerto",options:["Aunque no tenía rutas marítimas claras, tenía buen abastecimiento por carretera.","La ciudad combinaba muelles, población, abastecimiento, aguas protegidas entre islas y una salida hacia el Báltico.","Se eligió porque ya existía allí el Museo Vasa."],answer:1,hint:"Un puerto lo tiene que tener todo.",explanation:"En este mapa entendemos dónde se construyó el barco, por qué la salida estaba protegida y cómo conectaba el mar con la guerra.",reaction:"Estocolmo era el sitio ideal para construir una flota de guerra."});
  Object.assign(q[1],{options:["Llevar tropas para desembarcarlas de golpe y hacer incursiones por tierra.","Especializarse en cañones para bombardear ciudades y posiciones enemigas desde el mar.","Llevar artillería y tropas, reforzar rutas y puertos aliados, y mostrar una fuerza capaz de enfrentarse a otras flotas."],answer:2,reaction:"El nombre del barco ya une la plaza de 1520 con la dinastía de su nieto. La Sombra no podrá quitar importancia al nombre de la dinastía."});
  Object.assign(q[2],{explanation:"Margareta sostuvo un sistema de compras, pagos, materiales y personas. Aunque no diseñó el casco, su trabajo fue muy importante.",reaction:"La advertencia de la inestabilidad del Vasa existió. Mi trabajo fue coordinar todos los equipos para terminarlo."});
  Object.assign(q[3],{options:["La acusación contra Margareta basta para concluir que hubo sabotaje, aunque no exista evidencia material.","El Vasa era peligrosamente inestable; la ráfaga y el agua que entró por las portas abiertas hicieron que se hundiera.","Klas Fleming dejó las portas abiertas porque los polacos le pagaron para hundir el barco."],answer:1,hint:"Estaba claro que tarde o temprano el barco se iba a hundir porque estaba mal diseñado.",explanation:"No hay evidencia de sabotaje. La evidencia muestra un barco mal diseñado; nunca se pudo comprobar quién fue responsable.",reaction:"Yo no tuve nada que ver. Me arruiné porque adelanté dinero que luego no me pagaron, y perdí mi prestigio y el astillero."});
  Object.assign(q[4],{
    reaction:"El Vasa conserva un conjunto de pruebas para conocer la verdad de lo que pasó hace más de 300 años.",
    solutionNote:`<p><strong>Barril:</strong> recipiente para almacenar y conservar provisiones durante una travesía.</p><p><strong>Huesos:</strong> restos de carne y pescado que permiten saber qué alimentos se habían cargado.</p><p>Juntos no cuentan el menú exacto de cada persona, pero sí muestran que el Vasa llevaba provisiones preparadas para navegar.</p>`
  });
  Object.assign(q[5],{reaction:"Vamos a practicar vuestro sueco: Fyra kanelbullar, tack."});
  Object.assign(q[6],{success:"ISLA LEÍDA."});
  Object.assign(q[7],{options:["El Vasa fue un barco de guerra muy ambicioso; Margareta dirigió el astillero tras la muerte de Henrik; el hundimiento combinó inestabilidad y agua por portas abiertas; no hay evidencia de sabotaje.","El barco se hundió en plena guerra contra Polonia-Lituania; hubo sabotaje porque alguien quería que fracasara.","Fue mala suerte: hacía mal tiempo cuando botaron el barco."],answer:0,hint:"Recuerda tu visita al museo.",explanation:"La investigación no encontró sabotaje ni permitió señalar una sola persona como culpable. El barco era inestable y las portas abiertas dejaron entrar el agua.",reaction:"Mi nombre está limpio de toda culpa. La investigación no me acusó: no diseñé el casco ni decidí la salida.",solutionNote:`<p><strong>Después del hundimiento:</strong> al día siguiente empezó la búsqueda de responsabilidades. El capitán fue detenido e interrogado; una comisión escuchó a oficiales, marineros y constructores.</p><p>Las declaraciones apuntaron a un barco inestable. Klas Fleming conocía la demostración en la que treinta hombres hicieron balancear el Vasa, pero no fue interrogado. También había presión del rey Gustav II Adolf para que el barco saliera al mar. Los constructores defendieron que trabajaron con dimensiones aprobadas por el rey.</p><p><strong>El resultado:</strong> no se estableció una responsabilidad única y nadie fue castigado. Por eso no es correcto afirmar que el juicio declaró formalmente culpable al rey o al vicealmirante.</p><p><strong>Margareta después:</strong> no fue acusada en la investigación. Se volvió a casar y murió al dar a luz en 1630, durante su tercer matrimonio. Las fuentes no permiten afirmar que la expulsaran de Estocolmo o que perdiera el astillero por el naufragio.</p>`});
  m[5].contexts.splice(0,0,{k:"PROVISIONES A BORDO",title:"Una travesía también se prepara comiendo",html:`<p>El Vasa solo navegó unos minutos, pero sus bodegas y documentos muestran qué se había preparado para una travesía larga.</p><p>Había carne y pescado salados o secos, pan duro, guisantes, sal y cerveza de barco. Los barriles con huesos encontrados en la bodega indican sobre todo vacuno, además de algo de cerdo, cordero, pescado y aves.</p><p>La comida debía durar. Antes de las conservas, secar, salar o guardar en salmuera ayudaba a que carne y pescado no se estropearan.</p><p>No era un banquete. La tripulación compartía cuencos de madera en pequeños grupos; una comida posible era sopa de guisantes con carne salada.</p><p><strong>El Vasa no llegó a hacer aquella travesía, pero sus restos permiten reconstruir las provisiones que llevaba previstas.</strong></p>`});
  m[5].contexts[2]={k:"TARJETA PARA USAR HOY",title:"Fyra kanelbullar, tack.",speaker:"Saga",character:true,html:`<p>«Cuatro bollos de canela, por favor».</p><p>Una frase práctica para usar hoy; nunca se puntúa la pronunciación.</p>`,speech:{word:"FYRA KANELBULLAR, TACK.",meaning:"Cuatro bollos de canela, por favor.",speech:"Fyra kanelbullar, tack.",tip:"Fyra = cuatro · kanelbullar = bollos de canela · tack = gracias / por favor."}};
  delete d.streetKit;
  delete d.streetKitAfterMission;
})();

// Recuperaciones explícitas de V4 solicitadas por el guion V8.
(() => {
  const d=window.DAY1_DATA, m=d.missions;
  Object.assign(m[6],{
    keys:4,time:"6–7 min",minimum:35,
    obstacle:"Djurgården aparece como un parque sin pasado. Debajo hay animales reales, caza, tabernas, casas trasladadas y música pop.",
    goal:"Recupera cuatro capas de la isla sin confundirlas entre sí.",
    done:"Djurgården vuelve a mostrar siglos de usos superpuestos.",
    contexts:[{k:"MAPA DE VISITA",title:"Djurgården no es solo el Museo Vasa",visual:"d2Djurgarden",html:`<p><strong>Djurgården:</strong> su nombre conserva una relación histórica con parque de caza real. <strong>Skansen:</strong> reúne edificios y entornos para explicar oficios y formas de vida de distintas regiones; no significa que toda Suecia viviera igual. <strong>Rosendal:</strong> jardín y cultivo dentro de la ciudad. <strong>ABBA:</strong> música popular contemporánea.</p><p>Una isla puede guardar al mismo tiempo memoria de siglos y vida cultural actual. No hace falta visitarlo todo para entender sus capas.</p>`}],
    questions:[
      {id:"d2m6k1",type:"order",visual:"djurgarden",title:"Antes de llamarse Djurgården",scene:"La isla se conoció como Walmundsön antes de quedar vinculada de nuevo a la Corona.",prompt:"Ordena las tres capas que dieron forma a su nombre.",items:[["a","1452 · vuelve a ser propiedad real"],["b","1579 · Johan III crea un recinto de animales"],["c","1680s · Karl XI lo cerca como parque de caza"]],answer:["a","b","c"],hint:"Primero vuelve a la Corona; después llegan el recinto y la caza.",success:"NOMBRE RECUPERADO",explanation:"Djur significa animal y gård alude aquí a recinto. En 1733 ya había 32 establecimientos con licencia para servir bebidas: no fue un espacio eternamente vacío."},
      {id:"d2m6k2",type:"single",visual:"skansen",onsite:true,title:"Casas que viajaron hasta Skansen",scene:"Casas, talleres y granjas de regiones y épocas distintas aparecen juntas en una colina.",prompt:"¿Por qué están allí?",options:["Fueron trasladadas o recreadas para mostrar formas de vida de Suecia","Toda Suecia vivía antiguamente en Djurgården","Son decorados de una película","Skansen fue una ciudad medieval amurallada"],answer:0,hint:"Busca carteles con la región de procedencia de cada edificio.",success:"CASAS IDENTIFICADAS",explanation:"Artur Hazelius fundó Skansen en 1891. Es el museo al aire libre más antiguo del mundo."},
      {id:"d2m6k3",type:"explore",visual:"rosendal",title:"Un jardín productivo",scene:"Rosendal no es solo un decorado floral. El mapa detecta un sistema que produce, cocina y reúne.",prompt:"Abre sus cinco piezas.",items:[["Invernaderos","Protegen cultivos y prolongan temporadas."],["Huerto y frutales","El paisaje también produce alimentos."],["Panadería","Transforma ingredientes en pan y bollos."],["Cafetería","Convierte la comida en una pausa compartida."],["Temporada","Lo que se ofrece cambia con el calendario del jardín."]],success:"JARDÍN ABIERTO",explanation:"Desde 1983 una fundación gestiona Rosendal como jardín, cultivo, alimentación y lugar de descanso."},
      {id:"d2m6k4",type:"single",visual:"abba",onsite:true,title:"Cuatro letras y cuatro personas",scene:"Agnetha, Björn, Benny y Anni-Frid dejaron sus iniciales en un nombre que todavía se reconoce en todo el mundo.",prompt:"¿Qué acontecimiento impulsó el salto internacional de ABBA?",options:["Ganar Eurovisión en 1974 con Waterloo","Inaugurar el Museo Vasa en 1961","Actuar en la coronación de Gustav II Adolf","Ganar Sanremo en 1982"],answer:0,hint:"La canción compartía nombre con una batalla napoleónica.",success:"SEÑAL POP RECUPERADA",explanation:"ABBA ganó Eurovisión en Brighton en 1974. Su nombre reúne las iniciales de Agnetha Fältskog, Björn Ulvaeus, Benny Andersson y Anni-Frid Lyngstad."}
    ]
  });
  m[2].contexts[1].k="UNA SEÑAL ANTES DE BOTAR EL BARCO";
  Object.assign(m[0].questions[0],{explanation:"En este mapa entenderemos:<br>— dónde se construyó el barco,<br>— por qué la salida estaba protegida y,<br>— cómo conectaba el mar con la guerra"});
  Object.assign(m[1].questions[0],{options:["Llevar tropas para poder desembarcarlas de golpe y poder hacer incursiones por tierra.","Especializarse en cañones para poder bombardear ciudades y posiciones del enemigo desde el mar dando soporte a las tropas de a pie.","Llevar artillería y tropas, reforzar rutas y puertos aliados, y mostrar una fuerza capaz de enfrentarse a otras flotas."],hint:"El mapa muestra una guerra por controlar las rutas y los puertos.<br>Mira para qué sirven dos cubiertas de cañones."});
  [0,1,2,3,7].forEach(i=>m[i].photo="margareta-nilsdotter-reconstruccion-v1.png");
  d.prologue[1].image="margareta-nilsdotter-reconstruccion-v1.png";
  d.prologue[1].portraitFocus=true;
  Object.assign(m[0].contexts[0],{visual:null,mapImage:"mapa-vasa-estocolmo-puerto.svg",mapAlt:"Mapa esquemático de Estocolmo, el puerto, Beckholmen, Djurgården y Vaxholm",mapCaption:"Mapa de orientación · ciudad, islas, puerto y salida hacia el Báltico."});
  Object.assign(m[0].contexts[1],{visual:null,mapImage:"mapa-vasa-ruta-prevista.svg",mapAlt:"Mapa esquemático de la ruta real y de la ruta prevista del Vasa",mapCaption:"Rojo continuo: lo que ocurrió. Azul discontinuo: el plan que quedó interrumpido antes de Vaxholm."});
})();

(()=>{const m=window.DAY1_DATA.missions;m[6].questions[1].media={file:"Seglora_kyrka.JPG",alt:"Iglesia de Seglora trasladada a Skansen",caption:"Seglora kyrka · un edificio histórico trasladado a Skansen para interpretar formas de vida de Suecia."};})();
