/* Día 03 · texto aceptado del guion V8. Cuando el guion indica «Recuperar V4»,
   se traslada la actividad completa, no un resumen. */
window.DAY1_DATA={
  meta:{day:"03",store:"codigo-gripsholm-v7-day03",contentVersion:"v7-final-day3",place:"ESTOCOLMO → ÖREBRO → TIVEDEN",title:"El puente y el hombre al que llamaron bandido",landing:"La Sombra ha cambiado un nombre por una etiqueta cómoda.",badge:"Informe Engelbrekt",objective:"COMPROBAR POR QUÉ ENGELBREKT NO ERA UN BANDIDO",objectiveCopy:"Seguiremos un cruce, una red de comercio, abusos concretos y una rebelión que llegó a limitar al rey.",evidenceCopy:"Cada misión ilumina una conclusión del Informe Engelbrekt.",fine:"Las intervenciones de Engelbrekt son reconstrucciones narrativas basadas en fuentes; la estatua no es un retrato exacto.",verifiedTitle:"El Informe Engelbrekt está completo.",verifiedAction:"Abrir el cierre de Saga",result:{title:"El puente y el hombre al que llamaron bandido",evidence:"Informe Engelbrekt recuperado",openQuestion:"¿Qué gana La Sombra cuando convierte una protesta contra abusos en la historia de un simple bandido?",next:{href:"dia4.html",label:"Abrir el Día 04"}}},
  prologue:[
    {k:"SAGA · RUTA ALTERADA",title:"La ruta que La Sombra ha insultado",image:"saga-transmision-inicial.png",alt:"Saga abre la ruta hacia Örebro",html:`<p>La ruta que salió de Estocolmo tiene un nombre: <strong>Engelbrekt</strong>. La Sombra no la ha borrado; ha hecho algo más cómodo. Ha escrito una sola palabra encima: <strong>«bandido»</strong>.</p><p>Antes de llegar a Tiveden necesitamos saber a quién estamos siguiendo. No para convertirlo en héroe perfecto, sino para entender por qué mineros, campesinos, ciudades y parte de la élite sueca se unieron a una protesta contra el rey de la Unión de Kalmar.</p>`,action:"Abrir el informe"},
    {k:"ENGELBREKT ENGELBREKTSSON · FIGURA HISTÓRICA",title:"Engelbrekt entra en el informe",image:"engelbrekt-statue-orebro.jpg",alt:"Estatua posterior de Engelbrekt ante la iglesia de San Nicolás de Örebro",html:`<p><strong>Estatua posterior: no es retrato fotográfico ni prueba de su aspecto.</strong></p><p><strong>Reconstrucción narrativa basada en fuentes:</strong> «No soy el traidor. Un rey que permite que sus funcionarios expriman a su pueblo tampoco puede pedir obediencia como si nada hubiera pasado.»</p><p>Antes de juzgarme, seguid el hierro. Mirad quién podía venderlo, quién cobraba por el camino y quién decidía si nuestras quejas llegaban al rey.</p>`,action:"Seguir el hierro"}
  ],routePlaces:[],
  missions:[
    {title:"Un viaje, tres paisajes",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"4–5 min",action:"Abrir el mapa de la jornada",obstacle:"Hoy no cruzamos solo una carretera. Pasamos de Estocolmo a una ciudad de río y de allí a un bosque entre grandes lagos.",goal:"Situar la ruta actual y reconocer que agua y tierra conectan el interior de formas distintas.",done:"La ruta queda leída como una secuencia de mar, río, caminos, bosque y lagos.",reaction:"El interior no está aislado del mar ni de las ciudades: el agua puede ser una carretera para personas, noticias y carga.",closing:"Ya sabemos adónde vamos. Ahora toca entender por qué una ciudad llamada Örebro podía importar mucho más de lo que parece en un navegador.",contexts:[{k:"MAPA REAL · JORNADA ACTUAL",title:"Estocolmo, Örebro y Tiveden",visual:"d3Route",html:`<p><strong>Estocolmo:</strong> punto de partida marítimo de los Días 1 y 2. <strong>Mälaren:</strong> gran lago que comunica con el interior. <strong>Örebro y Svartån:</strong> cruce de rutas, puente y castillo en un río. <strong>Hjälmaren:</strong> lago al este de Örebro. <strong>Tiveden:</strong> bosque y relieve entre los grandes lagos Vänern y Vättern.</p><p>Más adelante veremos canales. Hoy no adelantamos el Göta Canal ni fingimos que existía en 1434: solo vemos el problema que resolvería siglos después. Para mover mucho peso, el agua puede ser una carretera.</p>`}],questions:[{id:"d3v7m1",type:"single",title:"La frase que lee bien el viaje",prompt:"¿Qué frase describe mejor la jornada?",options:["Viajamos desde una ciudad marítima a un cruce de río y caminos, y terminamos en bosque y lagos; agua y tierra se conectan de maneras distintas.","Tiveden es una isla situada frente al puerto de Estocolmo.","Antes de las carreteras no existían rutas ni conexiones entre estos lugares."],answer:0,hint:"Mira los lagos y el río: el interior no está aislado.",success:"RUTA ACTUAL ENTENDIDA.",explanation:"La ruta une escalas distintas: puerto, grandes lagos, ciudad de paso y bosque."}]},
    {title:"Cuatro caminos, un puente",speaker:"Engelbrekt",photo:"engelbrekt-statue-orebro.jpg",characterCaption:"figura histórica · reconstrucción narrativa basada en fuentes · estatua posterior",keys:1,time:"5–6 min",action:"Mirar el cruce",obstacle:"¿Eso del puente de Örebro qué es? No es una postal. Es el lugar donde el río obliga a parar, comerciar y decidir quién controla el paso.",goal:"Entender por qué un banco de grava, el Svartån, el puente y el castillo concentraban poder.",done:"Puente, agua, defensa y comercio vuelven a formar una sola explicación.",reaction:"Örebro no era una esquina de la historia: quien controlaba el cruce podía afectar a la mina, al mercado y al camino hacia el rey.",closing:"Ahora entendéis por qué Örebro no era una esquina de la historia. Quien controlaba el cruce podía afectar a la mina, al mercado y al camino hacia el rey.",contexts:[
      {k:"ÖRE + BRO",title:"El nombre guarda un paso",visual:"d3Crossroads",html:`<p>En esta zona, un banco de grava hacía el <strong>Svartån</strong> más fácil de cruzar. Con el tiempo se levantó un puente. El nombre <strong>Örebro</strong> se relaciona con <em>öre</em>, bancos de grava, y <em>bro</em>, puente.</p><p>En torno al paso crecieron comercio, una ciudad y una fortaleza. La Corona construyó defensa y control del tránsito; los mercaderes participaron durante siglos en la salida del hierro de Bergslagen y la entrada de alimentos y otros bienes.</p><p><strong>Paralelismo con España:</strong> Ponferrada procede de <em>Pons Ferrata</em>, «puente reforzado con hierro», en un paso sobre el Sil. No son la misma ciudad: ayuda a recordar cómo un cruce puede acabar dando nombre a un lugar.</p>`},
      {k:"CUATRO CAMINOS · UN PUENTE",title:"Un cruce antes de las autopistas",visual:"d3Crossroads",html:`<p><strong>Norte:</strong> Bergslagen y Dalarna; hierro, bosques, personas y noticias del interior. <strong>Este:</strong> Mälaren, Estocolmo y Báltico; mercados, órganos de gobierno y salida marítima. <strong>Sur:</strong> Östergötland; regiones agrícolas y caminos hacia otros centros urbanos. <strong>Hacia Nidaros:</strong> dirección de rutas de larga distancia y peregrinación hacia Trondheim, no una autopista única.</p><p><strong>Texto ancla:</strong> Örebro creció donde rutas terrestres coincidían con un paso de río. Controlarlo concentraba tránsito, noticias, comercio, impuestos y defensa.</p>`}
    ],questions:[{id:"d3v7m2",type:"single",title:"Por qué el castillo está en el agua",prompt:"¿Qué explica mejor que el castillo de Örebro esté en un islote del Svartån, junto al paso?",options:["El agua dificultaba el acceso; el puente concentraba el paso; la fortaleza ayudaba a vigilar, defender y controlar una ruta comercial.","Se levantó solo para que los reyes descansaran junto al río, sin defensa ni comercio.","Fue construido para controlar aviones sobre el lago."],answer:0,hint:"El agua puede ser obstáculo, transporte y parte de la defensa.",success:"PUENTE, AGUA Y DEFENSA CONECTADOS.",explanation:"La posición en el agua unía defensa, control del puente, impuestos y tránsito."}]},
    {title:"El hierro no vivía solo en la mina",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"6–7 min",action:"Ampliar el mapa",obstacle:"El hierro de Bergslagen no se quedaba allí: salía por rutas interiores y puertos. A cambio entraban sal, telas, grano y otros bienes.",goal:"Entender la Unión de Kalmar, Holstein, la Hansa y por qué una red de comercio dejó de funcionar para tanta gente.",done:"La frase «el sistema se rompió» ya contiene rutas, productos, impuestos y decisiones concretas.",reaction:"Ahora sabemos qué significaba que el sistema se rompiera: producir sin vender bien, pagar más, recibir menos y seguir sosteniendo impuestos.",closing:"Ya no hace falta decir «el sistema se rompió» como una frase misteriosa. Sabemos qué rutas, mercancías, impuestos y decisiones podían dañar la vida de una región minera.",contexts:[
      {k:"1397 → 1434",title:"De Bogislav a Erik, de Kalmar a Bergslagen",visual:"d3Baltic",html:`<p><strong>Bogislav:</strong> nació en una familia ducal de Pomerania. <strong>Margarita I:</strong> lo adoptó tras perder a su único hijo y pasó a llamarse Erik. <strong>Kalmar, 1397:</strong> Erik fue coronado rey de Dinamarca, Noruega y Suecia; compartían monarca, no todas las leyes ni intereses. <strong>1412:</strong> muere Margarita y Erik gobierna solo. <strong>1434:</strong> la tensión llega a Bergslagen.</p><p>La Unión no nació solo para luchar contra la Hansa, pero una corona común podía reforzar intereses dinásticos y la capacidad de las coronas frente a potencias comerciales. Suecia mantenía leyes, élites y necesidades propias.</p>`},
      {k:"MAPA DEL CONFLICTO",title:"Holstein no está en Suecia",visual:"d3Baltic",html:`<p><strong>Bergslagen:</strong> interior minero del centro de Suecia; necesita vender hierro y cobre y recibir bienes. <strong>Lübeck y la Hansa:</strong> red comercial influyente, no un país ni un rey único. <strong>Schleswig:</strong> entre Dinamarca y Holstein. <strong>Holstein:</strong> al sur de Schleswig, en el espacio germánico; su conflicto con Erik fue caro y se enlazó con la guerra contra ciudades hanseáticas.</p><p><strong>Qué se rompió:</strong> la guerra interrumpía o encarecía rutas. La Hansa dejó de comprar hierro y cobre suecos y de vender sal y otros productos durante el conflicto. La Corona necesitaba recaudar más. Algunas personas con privilegios podían protegerse mejor que mineros y campesinos.</p>`}
    ],questions:[{id:"d3v7m3",type:"single",title:"La decisión que incendia la protesta",prompt:"Si dirigieras Suecia en medio de esta crisis, ¿qué decisión aumentaría más el enfado en Bergslagen?",options:["Mantener impuestos altos y a un funcionario acusado de abusos, mientras vender y abastecerse se vuelve más difícil.","Investigar las denuncias y buscar que caminos y comercio vuelvan a funcionar.","Reparar un puente peligroso y facilitar el paso de mercancías."],answer:0,hint:"Piensa qué combina coste diario, pérdida de ingresos y sensación de que nadie escucha.",success:"CRISIS DE BERGSLAGEN ENTENDIDA.",explanation:"No fue un botón apagado de golpe: fue una cadena de guerra, comercio dañado, impuestos y desigualdad de protección."}]},
    {title:"La rebelión del hierro",speaker:"Engelbrekt",photo:"engelbrekt-statue-orebro.jpg",characterCaption:"figura histórica · reconstrucción narrativa basada en fuentes · estatua posterior",keys:1,time:"5–6 min",action:"Leer las quejas",obstacle:"Yo no hablaba de una idea abstracta llamada libertad. Hablaba de pagos, abusos y caminos por los que debíamos vivir. El hombre que nos representaba al rey estaba en Västerås.",goal:"Conocer a Jösse/Jens Eriksson, su cargo y las reclamaciones concretas de Bergslagen.",done:"La protesta deja de parecer una rabia sin motivo: hay funcionario, cargos, denuncias y una petición concreta.",reaction:"Engelbrekt fue portavoz de una reclamación; no hace falta inventar un programa político moderno para entender qué exigía Bergslagen.",closing:"No hablábamos de una palabra vacía. Pedíamos que se investigaran abusos, que se escucharan las quejas y que la guerra no arruinara a quienes sostenían la región.",contexts:[
      {k:"JÖSSE/JENS ERIKSSON · BAILÍO REAL",title:"Quién era el funcionario al que se denunciaba",visual:"d3Jens",html:`<p>Jösse, también llamado Jens Eriksson, era <strong>bailío</strong> —<em>fogde</em>— del rey en Västerås: administrador local de la Corona. Cobraba impuestos, gestionaba bienes y hacía cumplir órdenes.</p><p>Cuando alguien se quejaba de pagos excesivos, requisiciones, violencia o abuso de poder, era la cara que veía. Bergslagen eligió a Engelbrekt como portavoz para pedir que lo apartaran y que se investigara. El Consejo del Reino pidió cambios. Erik se negó durante demasiado tiempo.</p><p>Las fuentes describen a Jösse como recaudador abusivo y opresor de campesinos. Los relatos más espectaculares pueden exagerar detalles, pero el rechazo a su gestión y la negativa real a destituirlo fueron reales.</p>`},
      {k:"1434 SE MUEVE POR EL MAPA",title:"La protesta deja de ser local",visual:"d3Revolt",html:`<p><strong>Bergslagen y Dalarna:</strong> protesta de mineros, campesinos y rutas interiores. <strong>Borganäs y Västerås:</strong> el conflicto alcanza la fortaleza vinculada a Jösse; Borganäs es destruido en verano de 1434. <strong>Más fortalezas y ciudades:</strong> se extiende y obliga a negociar. <strong>Örebro:</strong> Engelbrekt recibe el castillo y su distrito de por vida en 1435. <strong>Arboga, 1435:</strong> es nombrado jefe militar; participan campesinos, algo muy poco habitual.</p>`}
    ],questions:[{id:"d3v7m4",type:"single",title:"Lo que Engelbrekt reclamaba",prompt:"¿Qué petición encaja con las quejas que Engelbrekt llevó en nombre de Bergslagen?",options:["Apartar o investigar al bailío acusado de abusos, escuchar quejas locales y no convertir impuestos y guerra en una ruina para productores y comerciantes.","Reservar todo el hierro para el tesoro privado de Engelbrekt.","Subir impuestos sin revisar a quien los cobraba ni las rutas de comercio."],answer:0,hint:"Busca soluciones a abusos de funcionarios, impuestos y comercio bloqueado.",success:"RECLAMACIÓN RECUPERADA.",explanation:"La protesta reunió demandas muy concretas: frenar abusos, ser escuchados y no arruinar las rutas de las que dependía la región."}]},
    {title:"El viaje que no terminó",speaker:"Engelbrekt",photo:"engelbrekt-statue-orebro.jpg",characterCaption:"figura histórica · reconstrucción narrativa basada en fuentes · estatua posterior",keys:1,time:"4–5 min",action:"Abrir el último trayecto",obstacle:"A Estocolmo, a defender nuestros derechos. Cambiar un castillo de manos no respondía todavía a la pregunta más grande: quién decidiría qué pasaba después.",goal:"Separar el último viaje documentado, sus consecuencias y los huecos que no debemos rellenar.",done:"Hecho, consecuencia y leyenda quedan separados en el informe.",reaction:"La muerte de Engelbrekt no convierte en mentira las causas por las que tanta gente se había movido.",closing:"No llegué a Estocolmo. Pero mi muerte no convierte en mentira las causas por las que tanta gente se había movido.",contexts:[{k:"1436 · VIAJE FINAL",title:"El último trayecto",visual:"d3LastJourney",html:`<p>En 1436, enfermo, Engelbrekt se retiró al castillo de Örebro. Durante un viaje hacia una reunión política en Estocolmo fue atacado y asesinado en Engelbrektsholmen, una isla del lago Hjälmaren, cerca de Göksholm.</p><p>El atacante identificado por las fuentes es el noble <strong>Måns Bengtsson Natt och Dag</strong>. No sabemos cada palabra, cada parada ni cada detalle de esa jornada. Sí sabemos que su muerte no cerró la crisis.</p>`}],questions:[{id:"d3v7m5",type:"match",title:"Hecho, consecuencia o relleno inventado",prompt:"Relaciona cada tarjeta con su clasificación.",pairs:[["Fue asesinado en 1436 en Engelbrektsholmen, cerca de Göksholm.","Hecho histórico"],["Su muerte dejó la rebelión sin su portavoz más visible y abrió una lucha por el liderazgo.","Consecuencia histórica"],["Sabemos con exactitud qué dijo justo antes de morir.","Relleno inventado"]],hint:"Una historia puede ser emocionante sin rellenar sus huecos.",success:"HISTORIA Y LEYENDA SEPARADAS.",explanation:"Las fuentes permiten conocer el asesinato y sus efectos, no escribir diálogos completos para hacerlo más dramático."}]},
    {title:"El rey también puede perder",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"4–5 min",action:"Leer la consecuencia",obstacle:"Después del asesinato de Engelbrekt la crisis siguió. No vamos a ordenar fechas que ya están delante: mirad cómo la autoridad de Erik se fue quedando sin apoyos.",goal:"Entender que la rebelión no acabó sola la Unión, pero ayudó a quebrar la autoridad del rey Erik.",done:"La crisis de un rey, la continuidad de la Unión y su ruptura posterior ya no se confunden.",reaction:"Un rey puede perder cuando rutas, impuestos y aliados dejan de sostenerlo.",closing:"Esta es la respuesta a «quién ganó». No ganó una persona para siempre: cambió qué límites podía tener un rey y quién podía exigir ser escuchado.",contexts:[{k:"1434 → 1442",title:"De rebelión a destitución",visual:"d3Erik",html:`<p><strong>1434:</strong> rebelión y consejos suecos limitan la autoridad de Erik. <strong>1436:</strong> Engelbrekt es asesinado; la crisis sigue. <strong>1436–1439:</strong> Erik se instala en Gotland y rechaza condiciones. <strong>1439:</strong> Dinamarca y Suecia lo deponen. <strong>1441:</strong> Noruega también lo aparta. <strong>1442:</strong> Noruega reconoce a Cristóbal de Baviera, aceptado así en los tres reinos.</p><p>La rebelión no terminó por sí sola la Unión de Kalmar: ayudó a quebrar la autoridad de Erik.</p>`}],questions:[{id:"d3v7m6",type:"single",title:"La conclusión que cabe en el informe",prompt:"¿Qué conclusión es más precisa?",options:["La protesta no resolvió todos los problemas, pero contribuyó a que Erik perdiera apoyos y fuera depuesto; la Unión continuó de otra manera.","Engelbrekt murió y la Unión de Kalmar terminó ese mismo día.","Un rey no puede perder el trono aunque consejos, ciudades y regiones dejen de obedecerle."],answer:0,hint:"Separa crisis de un rey, continuidad temporal de la Unión y ruptura definitiva mucho después.",success:"CONSECUENCIA POLÍTICA ENTENDIDA.",explanation:"La autoridad no depende solo de una corona: necesita apoyos, rutas, impuestos aceptables y capacidad de negociación."}]},
    {title:"Örebro mira hacia sí misma",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"5–6 min",action:"Volver al presente",obstacle:"Engelbrekt es una parte de Örebro, no toda la ciudad. Volvemos al presente para leer castillo, estatua, casas y cocina sin convertir ningún lugar en una cápsula del tiempo.",goal:"Distinguir patrimonio, reconstrucción, ciudad literaria y una frase útil de sueco actual.",done:"Örebro conserva varias épocas sin fingir que cada edificio está intacto en su lugar original.",reaction:"La memoria no es una foto: es una conversación donde hay que decir qué es fuente, qué es reconstrucción y qué es leyenda.",closing:"Örebro puede guardar edificios, inventarse una ciudad literaria y contar recetas. La memoria no es una foto: es una conversación honesta.",contexts:[
      {k:"VISITA VISUAL · CASTILLO",title:"El castillo está rodeado",visual:"d3Visit",html:`<p>Busca una vista en la que haya agua entre el castillo y la ciudad. El castillo no tiene hoy el aspecto de 1434: nació como fortificación medieval y desde finales del siglo XVI fue transformado en palacio renacentista con torreones circulares.</p><p>La posición en el agua conserva la pregunta original: ¿cómo se defiende y controla un paso de río? Si no estáis allí, la foto sirve como alternativa.</p>`},
      {k:"VISITA VISUAL · PLAZA",title:"Engelbrekt mira la plaza",visual:"d3Visit",html:`<p>Localiza la estatua frente a la iglesia de San Nicolás. No enseña la cara exacta de Engelbrekt: enseña cómo una generación posterior quiso recordarlo, asociado a la lucha contra abusos y por mayor voz política. También se vincula con la iglesia donde fue enterrado en la década de 1430.</p>`},
      {k:"TARJETAS DE CIUDAD",title:"Imagen, cocina y una frase útil",visual:"d3Culture",html:`<p><strong>Hjalmar Bergman:</strong> escritor de novelas, teatro y guiones. Wadköping fue primero su ciudad literaria ficticia, inspirada en Örebro; no confundir con Ingmar Bergman: no eran familia ni de la misma generación.</p><p><strong>Cajsa Warg:</strong> publicó en 1755 un recetario influyente. «Se toma lo que se tiene» suele atribuírsele, pero no aparece como lema literal suyo. Antes de televisión y redes, un libro podía circular de casa en casa como referencia popular.</p><p><strong>Sueco actual:</strong> <em>Var kan vi parkera?</em> = «¿Dónde podemos aparcar?». <em>Var</em> = dónde; <em>kan vi</em> = podemos; <em>parkera</em> = aparcar.</p>`}
    ],questions:[{id:"d3v7m7",type:"single",title:"Una ciudad puede conservar sin fingir",prompt:"¿Qué frase describe mejor Wadköping?",options:["Es un conjunto inaugurado en 1965 que reúne edificios históricos trasladados desde Örebro y su entorno; son reales, pero no están todos en su emplazamiento original.","Es una calle vikinga intacta desde el año 900.","Es un decorado sin edificios históricos, creado solo para una película."],answer:0,hint:"Un edificio puede ser auténtico aunque haya viajado; importa explicar de dónde viene y cuándo se reunió allí.",success:"PATRIMONIO LEÍDO CON HONESTIDAD.",explanation:"Wadköping no finge ser una ciudad intacta: permite conocer edificios reales en un conjunto interpretado."}]},
    {title:"Una ciudad, dos giros de poder",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"4–5 min",action:"Abrir las dos fechas",obstacle:"Esta ciudad vuelve a aparecer más adelante por una decisión enorme. No repetimos hoy toda la crisis de 1809: aquí solo fijamos que Örebro no recuerda una única época.",goal:"Relacionar la crisis medieval de Engelbrekt y la elección de Bernadotte sin mezclar siglos ni acontecimientos.",done:"Örebro queda leído como nodo político medieval y moderno; el siguiente tramo vuelve al bosque.",reaction:"Misma ciudad no significa misma historia: la conexión es espacial y política, no una escena repetida.",closing:"El informe Engelbrekt está completo. La siguiente coordenada no es un castillo ni un parlamento: es Tiveden.",contexts:[
      {k:"IGLESIA · 1434–1435 / 1810",title:"Dos fechas que no se parecen",visual:"d3Bernadotte",html:`<p><strong>1434–1435:</strong> la rebelión convierte a Örebro y su castillo en pieza de una crisis que limita al rey Erik. <strong>1810:</strong> tras la crisis de 1809 y la muerte del heredero Karl August, los cuatro estamentos reunidos en Örebro eligen al mariscal francés Jean Baptiste Bernadotte como heredero sueco.</p><p>En 1810 Napoleón dominaba o condicionaba gran parte de Europa, pero no gobernaba todos los países igual. España estaba en guerra contra José Bonaparte desde 1808; Suecia necesitaba heredero en una Europa de alianzas cambiantes. Bernadotte sería Karl XIV Johan desde 1818. El Día 5 desarrollará el contexto completo.</p>`},
      {k:"TRANSICIÓN · HACIA TIVEDEN",title:"La carretera vuelve al bosque",visual:"d3Route",html:`<p>Entre lagos, ríos, pasos y bosques se entiende por qué Suecia pensó durante siglos en rutas interiores. Mucho más tarde, canales como el Göta Canal unirían partes de esa geografía.</p><p>Mañana no estudiaremos todavía el canal: entramos en el bosque que hacía difícil atravesarla.</p>`}
    ],questions:[{id:"d3v7m8",type:"single",title:"La tarjeta que une sin confundir",prompt:"¿Qué frase une las dos fechas sin mezclarlas?",options:["Örebro fue importante en una crisis medieval ligada a Engelbrekt y, casi cuatro siglos después, en la elección de Bernadotte como heredero; son hechos distintos conectados por la ciudad.","Engelbrekt eligió a Bernadotte como heredero en 1434.","Napoleón construyó el castillo medieval para conquistar Bergslagen."],answer:0,hint:"Misma ciudad no significa mismo siglo.",success:"ÖREBRO COMO NODO POLÍTICO ENTENDIDO.",explanation:"La ciudad conecta historias distintas sin volverlas una sola: de crisis medieval a decisión dinástica moderna."}]}
  ],
  ending:[
    {image:"saga-canal-asegurado.png",caption:"Saga · Informe Engelbrekt",k:"SAGA · EVIDENCIA RECUPERADA",title:"Engelbrekt no era un bandido.",html:`<p>Örebro creció en un cruce de banco de grava, río, puente, caminos y defensa. Bergslagen necesitaba vender hierro y cobre, y recibir sal y otras mercancías. La guerra, el comercio dañado, los impuestos y abusos concretos ayudaron a encender la protesta.</p><p>Engelbrekt fue portavoz de Bergslagen y lideró una rebelión que se extendió por regiones, ciudades y fortalezas. No era un bandido sin causa.</p>`,action:"Conservar el informe"},
    {image:"engelbrekt-statue-orebro.jpg",caption:"Engelbrekt · estatua posterior · reconstrucción narrativa basada en fuentes",k:"ENGELBREKT · CIERRE DE LA RECONSTRUCCIÓN",title:"Una ruta, no una leyenda perfecta",html:`<p>Mi asesinato en 1436 no cerró la crisis. Erik fue depuesto en Dinamarca y Suecia en 1439; Noruega lo apartó en 1441 y reconoció a Cristóbal en 1442.</p><p>Mi historia no necesita una leyenda perfecta. Basta con no ocultar qué defendía, qué límites tuvo y por qué tantas personas lo siguieron.</p>`,action:"Revelar la siguiente coordenada"},
    {image:"saga-canal-asegurado.png",caption:"Saga · ruta hacia Tiveden",k:"TERCERA CONSECUENCIA",title:"El siguiente expediente está en el bosque.",html:`<div class="coordinate">TIVEDEN · CUADERNO DE CAMPO<br>SEÑALES · ROCA · BOSQUE · AGUA · MEMORIA<br>INTERFERENCIA · GIGANTES · MONSTRUOS · TROLLS</div><p>Alguien dejó allí un cuaderno que reemplaza geología por gigantes, agua por monstruos y memoria por trolls.</p><p class="lead">Mañana no buscaremos palabras mágicas: separaremos mito y realidad.</p>`,action:"Cerrar el canal"}
  ]
};

/* Revisión literal contra el guion V8 aceptado. */
(()=>{
  const d=window.DAY1_DATA,m=d.missions;
  Object.assign(d.meta,{store:"codigo-gripsholm-v8-day03",contentVersion:"v8-day03-final",objectiveCopy:"Seguiremos un lugar estratégico con muchos cruces, intercambios comerciales, abusos concretos y una rebelión que acabó con el rey."});
  d.prologue[0].html=`<p>La ruta que salió de Estocolmo tiene un nombre: <strong>Engelbrekt</strong>. La Sombra no la ha borrado; ha escrito encima una etiqueta cómoda: <strong>«bandido»</strong>.</p><p>Engelbrekt vivió hace casi seiscientos años, cuando Suecia, Dinamarca y Noruega compartían rey en la Unión de Kalmar. No fue rey ni héroe perfecto: fue el portavoz de una protesta contra abusos, impuestos y una guerra que dañaba las rutas del hierro.</p><p>Antes de llegar a Tiveden, necesitamos entender a quién estamos siguiendo.</p>`;
  d.prologue[1].html=`<p><strong>Estatua posterior: no es un retrato ni prueba de su aspecto.</strong></p><p><strong>Reconstrucción narrativa basada en fuentes:</strong> «No soy ningún traidor. Un rey que permite que sus funcionarios expriman a su pueblo tampoco puede pedir obediencia como si nada hubiera pasado.»</p><p>Antes de juzgarme, seguid el hierro: quién podía venderlo, quién cobraba por el camino y quién decidía si nuestras quejas llegaban al rey.</p>`;
  m[0].goal="Situar la ruta actual y entender que el agua y la tierra conectan el interior de formas distintas.";
  m[1].contexts[0].html=`<p>En esta zona, un banco de grava hacía el <strong>Svartån</strong>, «río Negro», más fácil de cruzar. Con el tiempo se levantó un puente. El nombre <strong>Örebro</strong> se relaciona con <em>öre</em>, bancos de grava, y <em>bro</em>, puente.</p><p>En torno al paso crecieron comercio, una ciudad y una fortaleza. La Corona construyó defensa y control del tránsito; los mercaderes participaron durante siglos en la salida del hierro de Bergslagen y la entrada de alimentos y otros bienes.</p><p><strong>Paralelismo con España:</strong> Ponferrada procede de <em>Pons Ferrata</em>, «puente reforzado con hierro», en un paso sobre el Sil.</p>`;
  m[1].contexts[1].html=`<p><strong>Norte:</strong> Bergslagen y Dalarna; hierro, bosques, personas y noticias del interior. <strong>Este:</strong> Mälaren, Estocolmo y Báltico; mercados, órganos de gobierno y salida marítima. <strong>Sur:</strong> Östergötland; regiones agrícolas y caminos hacia otros centros urbanos. <strong>Hacia Nidaros:</strong> dirección de rutas de larga distancia y peregrinación hacia Trondheim, no una autopista única.</p><p><strong>Texto ancla:</strong> Örebro creció donde rutas terrestres coincidían con un paso de río. Controlarlo concentraba tránsito, noticias, comercio, impuestos y defensa.</p>`;
  m[2].contexts[0].html=`<p><strong>Bogislav:</strong> nació en una familia ducal de Pomerania. <strong>Margarita I:</strong> lo adoptó tras perder a su único hijo y pasó a llamarse Erik. <strong>Kalmar, 1397:</strong> Erik fue coronado rey de Dinamarca, Noruega y Suecia; compartían monarca, no todas las leyes ni intereses. <strong>1412:</strong> muere Margarita y Erik gobierna solo. <strong>1434:</strong> la tensión llega a Bergslagen.</p><p>La Unión no nació solo para luchar contra la Hansa, pero una corona común podía reforzar intereses dinásticos y la capacidad de las coronas frente a potencias comerciales. Suecia mantenía leyes, élites y necesidades propias.</p>`;
  m[2].contexts[1].title="Sal, hierro y un mar bloqueado";
  m[2].questions[0]= {id:"d3v8m3",type:"single",title:"La decisión que incendia la protesta",prompt:"¿Qué crees que aumentaría más el enfado en Bergslagen?",options:["Investigar las denuncias y buscar que caminos y comercio vuelvan a funcionar.","Reparar un puente peligroso y facilitar el paso de mercancías.","Mantener impuestos altos y a un funcionario acusado de abusos, mientras vender y abastecerse se vuelve más difícil."],answer:2,hint:"Piensa qué combina coste diario, pérdida de ingresos y sensación de que nadie escucha.",success:"CRISIS DE BERGSLAGEN ENTENDIDA.",explanation:"No fue un botón apagado de golpe: fue una cadena de guerra, comercio dañado, impuestos y desigualdad de protección."};
  m[6].goal="Distinguir patrimonio, reconstrucción y ciudad literaria sin convertir ningún lugar en una cápsula del tiempo.";
  Object.assign(m[6],{title:"Wadköping: una ciudad trasladada",action:"Recorrer Wadköping",obstacle:"Wadköping parece una calle antigua intacta, pero cada casa llegó aquí desde otra parte de Örebro o de su entorno.",goal:"Entender cómo se conservan casas reales de madera sin fingir que siguen en su emplazamiento original.",done:"Wadköping queda leído como patrimonio trasladado, dos épocas de Örebro y dos vínculos personales distintos.",reaction:"Conservar no es congelar: una ciudad puede salvar edificios, explicar de dónde vienen y seguir dándoles vida.",closing:"Wadköping reúne casas reales de madera, dos momentos de Örebro y recuerdos de personas distintas. No es una ciudad falsa: es una historia explicada con honestidad."});
  m[6].contexts=[
    {k:"CASAS REALES · OTRO LUGAR",title:"No es un decorado",visual:"d3WadkopingIntro",html:`<p>Wadköping parece una calle antigua que hubiera sobrevivido intacta durante siglos. Pero no está en su lugar original.</p><p>Es un museo al aire libre formado por <strong>casas y patios históricos de madera</strong>, trasladados desde Örebro y sus alrededores para conservarlos. No se construyó una ciudad falsa: se salvaron edificios reales cuando la ciudad moderna cambiaba.</p><p><strong>Cada fachada tiene historia propia; juntas cuentan cómo era Örebro.</strong></p>`},
    {k:"UNA CALLE · DOS ÉPOCAS",title:"Cruza la calle y cambias de siglo",visual:"d3WadkopingEras",html:`<p>En un lado están las casas bajas, muchas de ellas rojas: muestran el Örebro de los siglos XVII, XVIII y comienzos del XIX.</p><p>En el otro aparece una ciudad posterior: el aspecto que tuvo Örebro después del gran incendio de 1854. No visitas una sola época: recorres <strong>dos momentos de la misma ciudad</strong>.</p>`},
    {k:"UNA CASA · UN NOMBRE",title:"Cajsa vivió aquí; Hjalmar imaginó Wadköping",visual:"d3WadkopingPeople",html:`<p><strong>Cajsa Warg</strong>, autora de uno de los recetarios más influyentes de Suecia, pasó su infancia en Borgarhuset. Esa casa está hoy en Wadköping y guarda una exposición sobre su vida, la comida y las especias del siglo XVIII.</p><p><strong>Hjalmar Bergman</strong>, escritor nacido y criado en Örebro, inventó el nombre ficticio de <em>Wadköping</em> para sus novelas. Su museo está en el barrio, pero <strong>no es su antigua casa</strong>.</p><p>Un lugar conserva una casa real; el otro conserva un nombre literario.</p>`}
  ];
  m[6].questions[0]={id:"d3v9m7",type:"single",title:"Una ciudad puede conservar sin fingir",prompt:"¿Qué frase describe mejor Wadköping?",options:["Es un conjunto de casas y patios históricos de madera, trasladados desde Örebro y su entorno; son reales, aunque no estén todos en su emplazamiento original.","Es una calle vikinga intacta desde el año 900.","Es un decorado sin edificios históricos, creado solo para una película."],answer:0,hint:"Un edificio puede ser auténtico aunque haya viajado; importa explicar de dónde viene y cuándo se reunió allí.",success:"PATRIMONIO LEÍDO CON HONESTIDAD.",explanation:"Wadköping reúne edificios históricos reales de madera en un conjunto interpretado. Un lado muestra los siglos XVII a comienzos del XIX; el otro, la ciudad posterior al incendio de 1854."};
  /* Recuperación completa de V4 · Misión 7, clave 4: prueba, tarjeta, escucha y práctica. */
  m[6].keys=2;
  m[6].questions.push({id:"d3v4m7k4",type:"speech",title:"Sueco para el viaje por carretera",scene:"Antes de abandonar Örebro necesitas preguntar dónde dejar el coche.",prompt:"¿Qué frase pregunta dónde podemos aparcar?",options:["Var kan vi parkera?","Fyra kanelbullar, tack.","Hej då!"],answer:0,word:"VAR KAN VI PARKERA?",meaning:"¿Dónde podemos aparcar?",speech:"Var kan vi parkera?",tip:"Var significa «dónde» y parkera se reconoce por su parecido con aparcar.",hint:"Piensa en la palabra sueca que se parece a «aparcar».",success:"CLAVE DE VOZ ACTIVADA",explanation:"Escucha el modelo, grábate y compara. La app no pone nota y no bloquea el progreso si no hay micrófono."});
})();

(()=>{const m=window.DAY1_DATA.missions;m[6].questions[0].media={file:"Wadköping_i_Örebro.jpg",alt:"Edificios históricos de Wadköping en Örebro",caption:"Wadköping reúne edificios históricos trasladados desde Örebro y su entorno."};})();

/* El mapa conserva la geografía; las viñetas sustituyen el bloque largo de explicación. */
(()=>{
  const timeline=window.DAY1_DATA.missions[2].contexts[0];
  timeline.title="Cuatro fechas para entender a Erik";
  timeline.visual="d3BalticTimeline";
  timeline.html=`<p class="fine">El mapa sitúa los reinos; las cuatro tarjetas ordenan la historia antes de entrar en el conflicto comercial.</p>`;
})();

(()=>{
  const c=window.DAY1_DATA.missions[2].contexts[1];
  c.title="Cuando las rutas se rompen";
  c.visual="d3BalticComic";
  c.html=`<p class="fine"><strong>Diálogos reconstruidos:</strong> las viñetas resumen una cadena histórica real: guerra, comercio interrumpido, escasez de bienes e impuestos más altos. La Hansa era una red de ciudades comerciales, no un país único.</p>`;
})();

/* Misión final de consulta: orientación urbana real, sin reto ni bloqueo. */
(()=>{
  const d=window.DAY1_DATA;
  d.missions.push({
    title:"Örebro a pie: cuatro paradas",speaker:"Saga",photo:"saga-transmision-inicial.png",characterCaption:"transmisión de la Carta · mapa de consulta",consultation:true,time:"consulta opcional",action:"Abrir el mapa de Örebro",
    obstacle:"El castillo, las estatuas y Wadköping no son una lección nueva: son cuatro lugares para ver cómo la historia del Día 3 sigue colocada en la ciudad.",
    goal:"Situar los cuatro lugares del día en un mapa urbano real y abrir una ficha con foto de cada uno.",
    done:"El mapa deja preparada una visita a pie desde el castillo hasta Wadköping, sin adivinar ni completar un reto.",reaction:"Las fechas no ocupan el mismo lugar, pero la ciudad permite seguirlas andando.",closing:"El mapa queda disponible como cuaderno de consulta siempre que quieras volver a Örebro.",
    contexts:[{character:true,k:"MAPA DE ÖREBRO · CONSULTA",title:"Castillo, historia y Wadköping",visual:"d3OrebroExplorer",html:`<p><strong>Esta misión es solo de consulta:</strong> no hay que adivinar ni completar un reto. El mapa sitúa los cuatro lugares y las fichas de debajo los explican con foto.</p><p>El recorrido del castillo a Wadköping ronda un kilómetro por el Svartån y el Stadsparken. Cada punto conserva su coordenada real; los nombres se colocan para que se puedan leer en el móvil.</p>`,action:"Cerrar el mapa"}]
  });
})();
