window.DAY4_DATA={
 meta:{day:"04",store:"codigo-gripsholm-day04-v1",place:"TIVEDEN · SIN CONEXIÓN",title:"El bosque que recuerda",landing:"El bosque no ha borrado las huellas. Alguien las ha mezclado.",openingTime:"Primera apertura recomendada: 15–20 minutos. Continúa con el móvil detenido durante el paseo.",objective:"RECUPERAR CUATRO HUELLAS",objectiveCopy:"Separarás grieta, hielo, fuego y leyenda para abrir el cuaderno de los padres de Saga.",routeCount:8,previousStore:"codigo-gripsholm-day03-v1",previousDay:"03",fragment:"5 de 11"},
 routePlaces:[
  ["Entrada principal","Punto de inicio de Trollkyrkorundan y Stenkällerundan. Detente aquí para consultar el mapa."],
  ["Trollkyrkorundan","Ruta roja: 4,6 km, unas 3 horas y tramos exigentes sobre roca y raíces."],
  ["Stora Trollkyrkan","La «iglesia grande» es una elevación rocosa y una antigua referencia visual."],
  ["Lilla Trollkyrkan","La «iglesia pequeña» abre vistas hacia Vättern en días despejados."],
  ["Stenkälla","Grandes bloques glaciares en la ruta amarilla Stenkällerundan."],
  ["Junker Jägare","Bloque errático próximo a Stora Trehörningen, unido a una leyenda local."],
  ["Vitsand","«Arena blanca»: playa y entrada en la orilla norte de Stora Trehörningen."],
  ["Tärnekullerundan","Ruta corta de 1,3 km desde Vitsand, pero con tramos pronunciados."]
 ],
 prologue:[
  {k:"DÍA 04 · CANAL SIN COBERTURA",title:"El bosque no está vacío. Está lleno de registros.",image:"saga-transmision-inicial.png",alt:"Saga abre la transmisión del Día 04",html:`<p>El archivo digital acaba aquí. Mis padres dejaron un <strong>cuaderno de papel</strong> en Tiveden porque sabían que una señal podía rastrearse.</p><p>Alguien ha llegado antes. Ha mezclado cuatro páginas y ha convertido procesos reales en cuentos.</p><p class="lead">Necesito que recuperes cuatro huellas: <strong>GRIETA · HIELO · FUEGO · LEYENDA</strong>.</p>`,action:"Localizar a la guardiana"},
  {k:"SAGA · CONTACTO LOCAL",title:"Alva conoce el sendero. No conoce a quien la sigue.",image:"alva-nystrom-tiveden-v1.png",alt:"Alva Nyström junto a un panel de senderos en Tiveden",html:`<p><strong>Alva Nyström</strong> tiene 19 años y trabaja como ayudante de campo durante el verano. Es un personaje ficticio contemporáneo: el paisaje, las rutas y los datos que te mostrará son reales.</p><p>Mis padres le confiaron el cuaderno. Esta mañana un hombre preguntó por Trollkyrkan y afirmó que las rocas habían sido colocadas por personas.</p><p class="lead">Alva no entregará nada hasta comprobar que sabes leer el bosque.</p>`,action:"Aceptar el cuaderno"},
  {k:"MAPA DE ORIENTACIÓN",title:"Ocho señales antes de entrar.",routeMap:true,html:`<p>Abre todos los puntos. No hay nada que adivinar: recibirás 5 kr por reconocer la ruta y sus alternativas.</p>`,action:"Continuar"},
  {k:"PROTOCOLO DE SEGURIDAD",title:"El móvil solo se abre con los pies quietos.",html:`<div class="final-record day4-code"><div><b>01</b><span>DETENTE EN LUGAR ESTABLE</span></div><div><b>02</b><span>SIGUE LA SEÑALIZACIÓN</span></div><div><b>03</b><span>NO TREPES NI MUEVAS NADA</span></div><div><b>04</b><span>USA MAPA DESCARGADO</span></div></div><p>Las rutas son cortas en kilómetros, no necesariamente fáciles. La cobertura puede ser irregular.</p>`,action:"Abrir la primera página"}
 ],
 missions:[
  {title:"El mapa antes del sendero",speaker:"Alva",keys:3,time:"4–5 min",minimum:30,action:"Desplegar el territorio",obstacle:"El cuaderno muestra tres accesos y varios nombres, pero no permite saber qué pertenece al parque y qué queda fuera.",goal:"Abre el contexto regional, las entradas y las alternativas. Aquí observar es la clave.",done:"El territorio y sus accesos ya están fijados antes de caminar.",questions:[
   {id:"d4m1k1",type:"explore",visual:"d4Regional",title:"Entre Vänern y Vättern",scene:"Tiveden no es una isla de bosque aislada del resto de Suecia.",prompt:"Abre las seis referencias del mapa regional.",items:[["Vänern","El mayor lago de Suecia, al oeste."],["Vättern","El segundo mayor, al este del parque."],["Örebro","La ciudad del Día 03 queda al norte."],["Laxå","Localidad útil al nordeste de la región."],["Askersund","Al norte de Vättern."],["Karlsborg","En la orilla occidental de Vättern."]],interludeTitle:"¿ES UN PAISAJE ÚNICO?",interlude:`<h3>Especial, pero no aislado</h3><p>Tiveden conserva uno de los pocos grandes sectores del sur de Suecia donde todavía se reconoce el carácter del antiguo bosque de pinos modelado por el fuego. No es el único paisaje de bloques glaciares y coníferas del país, pero aquí roca, lagos, grietas y bosque se concentran de una forma especialmente clara.</p><div class="landscape-compare"><div><b>TIVEDEN</b><span>granito · pinos · lagos · hielo</span></div><div><b>LA PEDRIZA</b><span>granito · clima mediterráneo · sin bosque nórdico</span></div></div><p>La comparación española sirve para imaginar la escala de los bloques, no el ecosistema: Tiveden es mucho más húmedo, oscuro y cubierto de coníferas.</p>`,success:"TERRITORIO ABIERTO",explanation:"Tiveden se extiende entre Vänern y Vättern. El parque nacional protege una parte concreta de esa región forestal."},
   {id:"d4m1k2",type:"explore",visual:"d4Park",title:"Tres entradas, varias rutas",scene:"El parque dispone de varias entradas; una ruta corta puede empezar lejos de la entrada principal.",prompt:"Abre las tres entradas y sus funciones.",items:[["Entrada principal","Trollkyrkorundan y Stenkällerundan."],["Vitsand","Playa, Stora Trehörningen y Tärnekullerundan."],["Ösjönäs","Acceso occidental y conexiones de senderos."]],success:"ACCESOS LOCALIZADOS",explanation:"Elegir la entrada correcta evita convertir pocos kilómetros de sendero en un problema de orientación."},
   {id:"d4m1k3",type:"match",visual:"d4Trails",title:"El plan tiene alternativas",scene:"Alva ha conservado tres recorridos para adaptar el día sin perder el sentido de la aventura.",prompt:"Relaciona cada ruta con sus datos oficiales aproximados.",pairs:[["Trollkyrkorundan","4,6 km · unas 3 h · roja · parcialmente exigente"],["Stenkällerundan","2,2 km · unas 1,5 h · amarilla"],["Tärnekullerundan","1,3 km · alrededor de 1 h · corta pero exigente"]],hint:"Corta no significa necesariamente fácil.",success:"ALTERNATIVAS FIJADAS",explanation:"La ruta principal es Trollkyrkorundan. Stenkällerundan conserva grandes bloques; Tärnekullerundan parte de Vitsand y tiene desniveles."}
  ]},
  {title:"Pocos kilómetros, muchas horas",speaker:"Alva",keys:4,time:"5–7 min",minimum:35,action:"Asegurar la marcha",obstacle:"El intruso ha traducido 4,6 km como un paseo llano y rápido.",goal:"Corrige la dificultad, recupera el color rojo y prepara una marcha segura.",done:"La distancia ya no oculta roca, raíces, desnivel y zonas húmedas.",questions:[
   {id:"d4m2k1",type:"single",visual:"d4Profile",title:"4,6 km no son una acera",scene:"Trollkyrkorundan atraviesa roca expuesta, raíces, desniveles y depresiones húmedas.",prompt:"¿Qué estimación protege mejor el plan familiar?",options:["Unas 3 horas, porque el terreno ralentiza","45 minutos, porque son menos de 5 km","Todo el día sin detenerse"],answer:0,hint:"La distancia no describe por sí sola la dificultad.",success:"TIEMPO REAL RECUPERADO",explanation:"La información oficial estima unas tres horas y califica partes de la ruta como exigentes."},
   {id:"d4m2k2",type:"single",visual:"d4TrailSigns",title:"El color correcto",scene:"En un cruce, una marca equivocada puede separar a Alva del cuaderno.",prompt:"¿Qué color identifica Trollkyrkorundan?",options:["Rojo","Amarillo","Negro"],answer:0,hint:"Stenkällerundan es la amarilla.",success:"SEÑAL ROJA LOCALIZADA",explanation:"Trollkyrkorundan sigue marcas rojas. El mapa oficial y la señalización física tienen prioridad sobre esta app."},
   {id:"d4m2k3",type:"multi",visual:"d4Pack",title:"La mochila que no engaña",scene:"No hay cafetería escondida detrás de cada roca.",prompt:"Fija los cinco elementos esenciales.",options:["Agua","Picnic","Calzado con agarre","Impermeable ligero","Repelente","Zapatos de vestir","Altavoz grande"],answer:[0,1,2,3,4],hint:"Piensa en autonomía, lluvia, insectos y terreno irregular.",success:"MOCHILA PREPARADA",explanation:"Agua, comida, agarre, protección ligera y repelente resuelven riesgos reales sin cargar de más."},
   {id:"d4m2k4",type:"single",visual:"d4Phone",title:"Sin mirar el móvil al borde",scene:"La siguiente pantalla llega cerca de una zona de roca.",prompt:"¿Qué haces antes de abrirla?",options:["Me detengo en un lugar estable","Sigo andando para ahorrar tiempo","Subo a un bloque para tener cobertura"],answer:0,hint:"La app nunca exige responder en movimiento.",success:"PROTOCOLO ACTIVADO",explanation:"Primero se detienen los pies; después se mira la pantalla. No salgas del sendero para buscar señal."}
  ]},
  {title:"La roca se abrió",speaker:"Alva",keys:4,time:"7–9 min",minimum:40,action:"Leer la primera huella",obstacle:"La primera página afirma que el hielo creó desde cero todas las fracturas del paisaje.",goal:"Separa grietas antiquísimas del modelado glaciar posterior.",done:"La estructura de la roca vuelve a preceder al hielo.",questions:[
   {id:"d4m3k1",type:"order",visual:"d4Geology",title:"Mucho antes del hielo",scene:"El granito ya estaba fracturado antes de la última glaciación.",prompt:"Ordena los cuatro procesos.",items:[["a","Roca antigua se fractura por movimientos de la corteza"],["b","Agua y hielo amplían zonas débiles"],["c","Glaciares arrancan, transportan y pulen"],["d","Quedan bloques, valles y depresiones húmedas"]],answer:["a","b","c","d"],hint:"Las grietas profundas son anteriores a la última capa de hielo.",success:"TIEMPO GEOLÓGICO ORDENADO",explanation:"Los valles de grieta son estructuras antiguas remodeladas muchas veces; el hielo aprovechó debilidades que ya existían."},
   {id:"d4m3k2",type:"single",visual:"d4Blocks",title:"Un tablero de bloques",scene:"Tiveden alterna plataformas secas y depresiones donde se acumulan agua y suelo.",prompt:"¿Qué explica mejor este patrón?",options:["Bloques separados por fracturas y erosión","Calles abandonadas de una ciudad vikinga","Canales excavados para turistas"],answer:0,hint:"Mira la sección esquemática de la roca.",success:"RELIEVE INTERPRETADO",explanation:"Las fracturas dividen la roca; la erosión profundiza algunos corredores y crea pequeños ambientes muy distintos."},
   {id:"d4m3k3",type:"explore",visual:"d4Rift",title:"Tiveden y el gran corte de Vättern",scene:"La misma región muestra fracturas locales y una gran depresión ocupada por Vättern.",prompt:"Abre roca, valle, lago y parque.",items:[["Roca","Granito y gneis muy antiguos."],["Valle de grieta","Depresión ligada a fracturas y erosión."],["Vättern","Gran lago al este de Tiveden."],["Parque","Mosaico de crestas, bloques y humedales."]],success:"ESCALA REGIONAL ABIERTA",explanation:"El paisaje local forma parte de una historia geológica mucho mayor que el sendero."},
   {id:"d4m3k4",type:"single",visual:"d4Notebook",title:"La primera huella",scene:"Una palabra debe ocupar la primera página del cuaderno.",prompt:"¿Cuál resume la estructura que guio al hielo?",options:["GRIETA","MAREA","PALACIO"],answer:0,hint:"Existía antes del hielo.",success:"PRIMERA HUELLA · GRIETA",explanation:"La grieta no cuenta toda la historia, pero organiza por dónde actuaron después agua, hielo y erosión."}
  ]},
  {title:"Lo que dejó el hielo",speaker:"Alva",keys:4,time:"7–9 min",minimum:40,action:"Seguir los bloques",obstacle:"La segunda página atribuye Stenkälla y Junker Jägare a constructores humanos.",goal:"Reconoce pulido, estrías, bloques erráticos y el momento aproximado del deshielo.",done:"El hielo vuelve a ser agente del paisaje, no un decorado.",questions:[
   {id:"d4m4k1",type:"match",visual:"d4IceWork",title:"Pulir, rayar, transportar",scene:"Una masa de hielo en movimiento deja distintos tipos de pruebas.",prompt:"Relaciona cada huella con el proceso.",pairs:[["Superficie lisa","abrasión y pulido"],["Estrías","fragmentos arrastrados rayan la roca"],["Bloque aislado","transporte y depósito glaciar"]],hint:"Un glaciar actúa como lija y como cinta transportadora.",success:"TRABAJO DEL HIELO RECONSTRUIDO",explanation:"El hielo puede pulir el sustrato, marcar la dirección del movimiento y abandonar bloques lejos de su origen."},
   {id:"d4m4k2",type:"single",visual:"d4Stenkalla",title:"Stenkälla, la fuente de piedra",scene:"Grandes bloques forman una cavidad que parece construida, pero no lo fue.",prompt:"¿Qué explicación conserva la evidencia?",options:["Bloques desplazados y depositados por el hielo","Templo tallado por vikingos","Decorado levantado en 1983"],answer:0,hint:"La forma humana no demuestra una obra humana.",success:"STENKÄLLA EXPLICADA",explanation:"Los bloques glaciares pueden apoyarse de forma sorprendente. No hace falta inventar constructores para admirarlos."},
   {id:"d4m4k3",type:"single",visual:"d4Junker",title:"La roca de Junker Jägare",scene:"Un bloque errático de unos quince metros conserva dos registros: uno dejó el hielo; el otro, las personas que contaron su historia.",prompt:"¿Cómo debes guardar ambas capas?",options:["Bloque glaciar como hecho; relato como leyenda","Todo es un hecho porque tiene nombre","Eliminar la leyenda porque no es geología"],answer:0,hint:"Historia natural y tradición pueden convivir si se etiquetan bien.",interludeTitle:"ABRIR LA LEYENDA COMPLETA",interlude:`<h3>La doncella que seguía buscando su cabeza</h3><p><strong>Según la leyenda</strong>, Junker Jägare era un joven noruego enamorado de una muchacha de noble nacimiento. El padre de ella quería casarla con otro hombre, así que la pareja huyó y acampó bajo la enorme roca.</p><p>Mientras Junker salió a cazar, los perseguidores los alcanzaron. Decapitaron a la joven junto al bloque. Él regresó a Noruega y nunca volvió a ser visto en Tiveden; la tradición dejó a la doncella vagando sin cabeza alrededor de la piedra.</p><p class="interlude-note"><strong>Para reconocerla:</strong> el bloque está cerca de Vitsand, en Junker jägarerundan. Desde cierto ángulo parece incluso mostrar un rostro. No consta que el relato sucediera: eso es precisamente lo que diferencia una leyenda de la roca real que tienes delante.</p>`,success:"DOS CAPAS SEPARADAS",explanation:"La roca es evidencia del hielo y quedó erguida al retirarse la capa de hielo. El relato de Junker y la doncella pertenece a la tradición local, no es una prueba del suceso narrado."},
   {id:"d4m4k4",type:"single",visual:"d4Notebook",title:"La segunda huella",scene:"La última capa de hielo se retiró de esta zona hace aproximadamente diez mil años.",prompt:"¿Qué palabra abre la segunda página?",options:["HIELO","VAPOR","SAL"],answer:0,hint:"Transportó los grandes bloques.",success:"SEGUNDA HUELLA · HIELO",explanation:"Su retirada dejó sedimentos, rocas pulidas, bloques y nuevas vías para el agua."}
  ]},
  {title:"El bosque escrito con fuego",speaker:"Alva",keys:4,time:"7–9 min",minimum:30,action:"Abrir las cicatrices",obstacle:"El intruso llama intacto a un bosque que conserva incendios, carboneo e industria.",goal:"Lee cicatrices, distingue fuego controlado y conecta Tiveden con el hierro del Día 03.",done:"El bosque ya no parece inmóvil ni ajeno a las personas.",questions:[
   {id:"d4m5k1",type:"single",visual:"d4FireScar",title:"Ochenta y seis incendios",scene:"Los anillos y cicatrices de algunos pinos permiten reconstruir fuegos anteriores a la fotografía.",prompt:"¿Cómo puede conocerse un incendio antiguo?",options:["Leyendo cicatrices y anillos de crecimiento","Preguntando a los trolls","Midiendo la cobertura móvil"],answer:0,hint:"La madera añade una capa cada año.",success:"INCENDIOS REGISTRADOS",explanation:"Un árbol puede sobrevivir y guardar en su madera la fecha aproximada de un incendio."},
   {id:"d4m5k2",type:"single",visual:"d4Burn",title:"Fuego controlado",scene:"Algunas áreas protegidas recuperan procesos naturales mediante quemas de conservación profesionales.",prompt:"Corrige la frase: «Todo fuego del parque es necesariamente accidental».",options:["Algunas quemas se planifican para conservar hábitats","Todo visitante puede encender una quema","El fuego nunca forma parte del bosque"],answer:0,hint:"Solo personal responsable puede planificarlas y ejecutarlas.",success:"PROCESO NATURAL ASISTIDO",explanation:"Una quema prescrita tiene límites, personal y seguimiento. El visitante cumple siempre las normas de fuego."},
   {id:"d4m5k3",type:"order",visual:"d4Charcoal",title:"El hierro vuelve convertido en carbón",scene:"Ayer recuperaste HIERRO. Minas y ferrerías necesitaron enormes cantidades de carbón vegetal.",prompt:"Ordena la cadena que dejó más de doscientos restos de carboneras en el parque.",items:[["a","Madera"],["b","Carbonera"],["c","Carbón vegetal"],["d","Horno o ferrería"],["e","Hierro"]],answer:["a","b","c","d","e"],hint:"La madera se transforma antes de alimentar el horno.",success:"CONEXIÓN REGIONAL RECUPERADA",explanation:"Bosque e hierro no son historias separadas: la industria dejó señales incluso donde hoy domina la naturaleza."},
   {id:"d4m5k4",type:"single",visual:"d4Deadwood",title:"Madera muerta, bosque vivo",scene:"Troncos caídos alimentan hongos, insectos y refugios; en Tiveden se han registrado cientos de especies de escarabajos.",prompt:"¿Qué corrección protege el bosque?",options:["La madera muerta es hábitat y parte del ciclo","Todo tronco muerto debe retirarse","La madera muerta demuestra abandono"],answer:0,hint:"No muevas ni toques la madera para observarla.",interludeTitle:"¿QUIÉN VIVE EN ESTE BOSQUE?",interlude:`<h3>Dos pisos separados por pocos metros</h3><div class="forest-floors"><div><b>ARRIBA · ROCA SECA</b><span>Pinos retorcidos, líquenes, brezo y arándano rojo. Algunos pinos pequeños tienen entre 200 y 300 años: crecer despacio no es ser joven.</span></div><div><b>ABAJO · GRIETA HÚMEDA</b><span>Abetos, musgos y zonas encharcadas. Un pequeño desnivel cambia la humedad y con ella todo el vecindario.</span></div></div><h3>Animales que quizá no se dejen ver</h3><p>Hay alces, corzos, linces e incluso lobos en la región, pero las poblaciones de grandes mamíferos dentro del parque son reducidas. Es más probable encontrar una huella, oír un pájaro carpintero o descubrir excrementos que cruzarse con un gran animal.</p><p>Entre las aves figuran el urogallo, el grévol, el chotacabras y pequeños búhos. La madera muerta funciona como un bloque de apartamentos para hongos, larvas y más de setecientas especies registradas de escarabajos.</p>`,success:"TERCERA HUELLA · FUEGO",explanation:"Muerte y vida forman el mismo ciclo. Las cicatrices y la descomposición conservan procesos distintos del bosque."}
  ]},
  {title:"La iglesia de los trolls",speaker:"Alva",keys:4,time:"8–10 min",minimum:35,action:"Abrir Trollkyrkan",obstacle:"La cuarta página mezcla navegantes medievales, trolls y una iglesia situada al otro lado de Vättern.",goal:"Sitúa las dos elevaciones y separa topónimo, uso visual y relatos posteriores.",done:"La palabra troll vuelve a ser una pista, no una prueba sobrenatural.",questions:[
   {id:"d4m6k1",type:"explore",visual:"d4TrollRoute",title:"Grande y pequeña",scene:"Stora y Lilla Trollkyrkan ocupan posiciones distintas en la ruta roja.",prompt:"Abre ambas elevaciones y la entrada.",items:[["Entrada principal","Inicio habitual de Trollkyrkorundan."],["Stora Trollkyrkan","Stora significa grande."],["Lilla Trollkyrkan","Lilla significa pequeña."]],success:"DOS MONTAÑAS LOCALIZADAS",explanation:"Los adjetivos suecos ayudan a leer el mapa antes incluso de conocer la historia del nombre."},
   {id:"d4m6k2",type:"explore",visual:"d4Vattern",title:"El nombre desde el agua",scene:"Las siluetas de Trollkyrkorna pudieron servir de referencia a navegantes de Vättern.",prompt:"Abre los dos extremos de la mirada.",items:[["Lilla Trollkyrkan","Elevación del bosque en Tiveden."],["Vadstena","Ciudad e iglesia al otro lado de Vättern."]],success:"LA MIRADA HA CRUZADO VÄTTERN",explanation:"En un día despejado puede distinguirse Vadstena. Una elevación terrestre era útil también para quien viajaba por agua."},
   {id:"d4m6k3",type:"single",visual:"d4Legend",title:"¿Estaban llenos de trolls?",scene:"Los visitantes posteriores ampliaron la imagen de un bosque enteramente poblado por trolls.",prompt:"El intruso afirma que el nombre demuestra que allí se adoraban trolls. ¿Qué corrección protege la evidencia?",options:["El nombre y sus relatos no demuestran ese ritual","Es cierto porque aparece la palabra troll","Los trolls fueron expulsados en 1983"],answer:0,hint:"Un topónimo abre preguntas, no demuestra una religión.",interludeTitle:"ABRIR EL EXPEDIENTE DE LOS TROLLS",interlude:`<h3>¿Buenos o malos?</h3><p>Ninguna de las dos cosas de forma fija. En el folclore sueco los trolls eran «los otros»: seres imprevisibles vinculados a montañas, rocas y lugares apartados. Podían engañar, raptar o hacer perder el camino, pero algunos relatos también los muestran negociando, ayudando o recompensando a quien actuaba con respeto.</p><p>Antes de mapas precisos y luz eléctrica, una roca con forma de cara, un eco o alguien perdido en el bosque necesitaban una explicación. El troll daba rostro a lo desconocido.</p><h3>El giro de Tiveden</h3><p>Stora y Lilla Trollkyrka servían como referencias visibles desde Vättern y son los únicos nombres antiguos de Tiveden que contienen la palabra <em>troll</em>. La propia información del parque resume la sorpresa: la población local hablaba más de espíritus guardianes de la naturaleza y seres domésticos; los trolls llegaron con fuerza de la mano de los turistas.</p><div class="story-signal"><b>STIGMANSPASSET</b><span>El nombre se asocia al paso de los salteadores. El desfiladero estrecho es real; la tradición dice que allí esperaban ladrones, pero no se sabe si alguno hizo peligroso el lugar.</span></div><h3>Un bosque que parece una novela</h3><p><em>Ronja, la hija del bandolero</em> vive entre un castillo partido, un bosque peligroso y dos familias rivales. La escribió Astrid Lindgren, la creadora de <strong>Pippi Calzaslargas</strong>, mucho más conocida en España.</p><p>Ronja es famosísima en Suecia y ha tenido película y series. La usamos como espejo cultural porque ayuda a sentir un bosque de salteadores y criaturas; <strong>no hay pruebas de que Tiveden inspirara específicamente la obra</strong>.</p>`,success:"TÓPICO DESACTIVADO",explanation:"Según la información del parque, son los únicos topónimos antiguos de Tiveden que contienen troll. Eso no prueba un culto y, de hecho, la imagen de un Tiveden lleno de trolls creció especialmente con el turismo."},
   {id:"d4m6k4",type:"single",visual:"d4Notebook",title:"La cuarta huella",scene:"El cuaderno ya muestra GRIETA · HIELO · FUEGO · [ ].",prompt:"¿Qué palabra completa la serie?",options:["LEYENDA","FRONTERA","PALACIO"],answer:0,hint:"Junker Jägare y los trolls pertenecen a esta capa.",success:"CUARTA HUELLA · LEYENDA",explanation:"La clave está completa, pero Alva exige comprobar que describe un paisaje real."}
  ]},
  {title:"El bosque bajo tus pies",speaker:"Alva",keys:4,time:"durante el paseo",minimum:35,action:"Activar observación",obstacle:"Las cuatro palabras encajan demasiado bien. Falta confirmar señales reales sin abandonar el sendero.",goal:"Observa cuatro procesos. Si no aparecen en tu ruta, abre el ejemplo visual.",done:"Roca, bloque, árbol y agua confirman el cuaderno.",questions:[
   {id:"d4m7k1",type:"single",visual:"d4WetDry",onsite:true,title:"Seco arriba, húmedo abajo",scene:"Detente en un lugar estable y busca roca expuesta junto a una depresión con más vegetación.",prompt:"¿Qué huella estás leyendo?",options:["GRIETA","MAREA","DUNA"],answer:0,hint:"Las depresiones retienen agua y suelo.",success:"GRIETA CONFIRMADA",explanation:"Los bloques elevados se secan rápido; las grietas y depresiones forman pequeños ambientes húmedos."},
   {id:"d4m7k2",type:"single",visual:"d4Stenkalla",onsite:true,title:"Una roca fuera de escala",scene:"Localiza desde un punto seguro un bloque mucho mayor que las piedras del sendero.",prompt:"¿Qué agente pudo transportarlo y abandonarlo?",options:["Una capa de hielo en movimiento","Una crecida de esta mañana","Los constructores del aparcamiento"],answer:0,hint:"No trepes ni pases bajo un bloque para completar la clave.",success:"HIELO CONFIRMADO",explanation:"El glaciar transportó bloques y los dejó cuando perdió capacidad o se fundió."},
   {id:"d4m7k3",type:"single",visual:"d4FireScar",onsite:true,title:"El árbol no cuenta su edad por tamaño",scene:"Busca un pino retorcido, una cicatriz oscura o madera muerta desde el sendero.",prompt:"¿Por qué no puedes calcular la edad solo por la altura?",options:["El crecimiento depende del suelo y la exposición","Todos dejan de crecer a los diez años","Los viejos siempre son los más altos"],answer:0,hint:"Un pino pequeño puede tener doscientos o trescientos años.",success:"FUEGO Y TIEMPO CONFIRMADOS",explanation:"Las condiciones pobres ralentizan el crecimiento. Tamaño y edad no son equivalentes."},
   {id:"d4m7k4",type:"single",visual:"d4DarkWater",onsite:true,title:"El agua oscura",scene:"Observa desde un lugar seguro un lago o pequeña lámina de agua del bosque.",prompt:"¿Qué puede darle un tono parecido al té?",options:["Sustancias húmicas del suelo y la vegetación","Canela de Örebro","Óxido añadido por el parque"],answer:0,hint:"El color no significa necesariamente contaminación.",interludeTitle:"¿HAY VIDA BAJO EL AGUA?",interlude:`<p>Sí. El tono marrón procede de materia vegetal disuelta y no significa que el lago esté vacío. En Stora Trehörningen viven, entre otros, <strong>percas, lucios y rutilos</strong>.</p><p>Muchos pequeños lagos del bosque son ácidos y pobres en nutrientes: mantienen menos vida que un lago muy fértil, pero no son piscinas muertas. Un lucio puede esperar inmóvil entre la vegetación mientras tú solo ves agua color té.</p>`,success:"LECTURA DEL BOSQUE COMPLETADA",explanation:"La materia vegetal libera sustancias húmicas. Estos pequeños lagos suelen ser ácidos y pobres en nutrientes, aunque mantienen peces y otra vida acuática."}
  ]},
  {title:"La orilla blanca",speaker:"Alva",keys:3,time:"6–8 min",minimum:30,action:"Abrir la orilla",obstacle:"Las cuatro huellas abren el cuaderno, pero la coordenada está cifrada con arena y agua.",goal:"Localiza Stora Trehörningen, explica Vitsand y activa una frase sueca útil.",done:"La playa, el hielo y el idioma cierran el cuaderno.",questions:[
   {id:"d4m8k1",type:"explore",visual:"d4Lake",title:"El lago de tres esquinas",scene:"Los nombres del mapa funcionan como pequeñas instrucciones.",prompt:"Abre los tres fragmentos suecos.",items:[["stora","grande"],["trehörningen","el de tres esquinas"],["vitsand","arena blanca"]],success:"TOPÓNIMOS DESCIFRADOS",explanation:"Stora Trehörningen es el mayor lago dentro del parque. Vitsand está en su orilla norte."},
   {id:"d4m8k2",type:"single",visual:"d4Meltwater",title:"Una playa creada por el deshielo",scene:"El agua de fusión clasificó y depositó sedimentos al retirarse el hielo.",prompt:"¿Qué une a Junker Jägare y Vitsand?",options:["Ambos conservan huellas del hielo y su retirada","Ambos se construyeron en 1983","Ambos son iglesias medievales"],answer:0,hint:"Uno es un bloque; la otra, arena seleccionada por agua.",interludeTitle:"SEÑAL OPCIONAL · LOS NENÚFARES ROJOS",interlude:`<h3>Fagertärn queda fuera del parque nacional</h3><p>Está en la región de Tiveden y puede funcionar como una excursión distinta, no como una parada obligatoria de esta ruta. Su rareza son los nenúfares que van del rosa al rojo oscuro.</p><p>El color apareció por una mutación natural. En todo lo demás son como los nenúfares blancos. Un estudiante aficionado a la botánica, Bernhard Agaton Kjellmark, los dio a conocer en 1856. La noticia provocó tanto expolio de plantas para colecciones que fueron protegidas en 1905.</p><p class="interlude-note">La historia del pescador que entrega a su hija al espíritu acuático Näcken es una leyenda atractiva, pero no hemos encontrado una fuente fiable que la vincule a Fagertärn. Por eso no la presentamos como tradición local.</p>`,success:"ÚLTIMO PROCESO RECUPERADO",explanation:"El mismo sistema glaciar puede explicar una roca gigantesca y granos finos de arena. Fagertärn añade otra señal natural de la región, pero queda fuera del parque nacional."},
   {id:"d4m8k3",type:"speech",visual:"d4Voice",title:"Sueco para encontrar la ruta",scene:"Alva ha ocultado la última coordenada detrás de una pregunta sencilla.",prompt:"¿Cuándo usarías «Var börjar Trollkyrkorundan?»",options:["Cuando buscas el inicio de la ruta","Cuando pides permiso para bañarte","Cuando preguntas la edad de un árbol"],answer:0,word:"Var börjar Trollkyrkorundan?",meaning:"¿Dónde empieza Trollkyrkorundan?",tip:"Var = dónde · börjar = empieza",speech:"Var börjar Trollkyrkorundan?",success:"CLAVE DE VOZ ACTIVADA",explanation:"No necesitas pronunciación perfecta. Puedes mostrar el nombre escrito y preguntar dónde empieza la ruta.",finalSignal:true}
  ]}
 ]
};
