/* Día 04 · Fuente editorial única: Guion completo V8 aceptado.
   Alva Nyström es un personaje ficticio contemporáneo: sus intervenciones son recreación narrativa. */
window.DAY1_DATA={
  meta:{day:"04",store:"codigo-gripsholm-v7-day04",contentVersion:"v7-final-day4",place:"ÖREBRO → TIVEDEN",title:"El bosque que parece encantado",landing:"La Sombra ha convertido un cuaderno de campo en un cuento equivocado.",badge:"Cuaderno de campo",objective:"SEPARAR MITO, OBSERVACIÓN Y EXPLICACIÓN",objectiveCopy:"Seguiremos roca, agua, fuego, bosque y relatos para descubrir qué dejó cada uno en Tiveden.",evidenceCopy:"Cada misión recupera una página útil del cuaderno de campo.",fine:"Alva Nyström es un personaje ficticio. Los lugares, procesos y pautas de observación se basan en fuentes del parque y de historia natural.",verifiedTitle:"El cuaderno de campo vuelve a leerse bien.",verifiedAction:"Abrir el cierre de Saga",result:{title:"El bosque que parece encantado",evidence:"Cuaderno de campo recuperado",openQuestion:"Si el bosque guardó tanta memoria, ¿qué historia humana puede estar escondida al otro lado de los lagos?",next:{href:"dia5.html",label:"Abrir el Día 05"}}},
  prologue:[
    {k:"SAGA · CUADERNO ALTERADO",title:"El bosque no necesita trucos",image:"saga-transmision-inicial.png",alt:"Saga abre la ruta hacia Tiveden",html:`<p>La Sombra ha alterado el cuaderno de campo. Ahora dice que un gigante lanzó las rocas, que un monstruo tiñe los lagos y que los trolls construyeron los pasos del bosque.</p><p>Alva os ayudará a responder sin estropear las historias. Hoy separaremos tres cosas: <strong>lo que vemos</strong>, <strong>lo que lo explica</strong> y <strong>lo que se cuenta</strong>.</p>`,action:"Abrir el cuaderno"},
    {k:"ALVA NYSTRÖM · PERSONAJE FICTICIO",title:"Una guía para mirar con cuidado",image:"alva-nystrom-tiveden-v1.png",alt:"Alva Nyström, personaje ficticio, en Tiveden",html:`<p><strong>Alva Nyström tiene 19 años y es un personaje ficticio contemporáneo.</strong> Trabaja durante el verano ayudando a registrar observaciones y a orientar a visitantes.</p><p>«No puedo prometeros un alce, un lince o un troll. Sí puedo enseñaros a mirar sin inventar lo que no hemos visto. Una leyenda puede ser preciosa, pero no se convierte en prueba científica por serlo.»</p><div class="evidence-grid three"><div><b>LO QUE VEMOS</b><span>Una roca enorme entre pinos.</span></div><div><b>LO QUE LO EXPLICA</b><span>Un glaciar pudo moverla.</span></div><div><b>LO QUE SE CUENTA</b><span>Un cazador perdió aquí a su amada.</span></div></div>`,action:"Empezar a observar"}
  ],routePlaces:[],
  missions:[
    {title:"El gigante no era un gigante",speaker:"Alva",photo:"alva-nystrom-tiveden-v1.png",characterCaption:"personaje ficticio · cuaderno de campo",keys:1,time:"5–6 min",action:"Leer la roca",obstacle:"La Sombra dice que un gigante lanzó los bloques. Antes de discutir con un gigante, vamos a leer dos edades muy distintas del paisaje.",goal:"Distinguir las fracturas antiguas de la roca y el trabajo posterior del hielo.",done:"Las grietas antiguas y el hielo explican el caos de bloques de Tiveden.",reaction:"No necesitamos un gigante para explicar una roca enorme: necesitamos muchísimo tiempo, una tierra fracturada y hielo en movimiento.",closing:"Primer gigante desenmascarado. La roca no ha perdido misterio: ahora sabemos que el misterio real duró miles de años.",contexts:[
      {character:true,k:"MAPA REAL · HACIA TIVEDEN",title:"Un bosque entre grandes lagos",visual:"d4TivedenMap",html:`<p>Tiveden se sitúa entre <strong>Vänern</strong> y <strong>Vättern</strong>, dos de los grandes lagos suecos. Ayer vimos cómo pasos, ríos y puentes condicionaban las rutas alrededor de Örebro. Hoy veremos la parte física: roca, bosque y lagos también decidían por dónde podía circular la gente.</p>`},
      {character:true,k:"ROCA ANTIGUA · HIELO RECIENTE",title:"Dos edades que no se deben mezclar",visual:"d4Geology",html:`<p>Las fracturas de la roca de Tiveden son enormemente más antiguas que la última Edad de Hielo. La última capa de hielo terminó de retirarse de esta zona hace unos 10.000 años. No creó toda la roca: aprovechó grietas, arrancó y arrastró bloques, y dejó otros al retirarse.</p><p>Stenkälla muestra bloques y cavidades sorprendentes; no hace falta que alguien los construyera.</p>`},
      {character:true,k:"JUNKER JÄGARES STEN",title:"Una roca y una historia",visual:"d4Junker",html:`<p>Junker Jägares sten es un bloque errático: el hielo lo transportó y quedó aquí cuando el hielo se retiró. También hay una leyenda local de amor y pérdida asociada a un joven cazador. La geología y el relato pueden convivir, pero no dicen lo mismo.</p>`}
    ],questions:[{id:"d4v7m1",type:"match",title:"Guarda cada capa en su archivo",prompt:"Relaciona cada afirmación con la lectura que le corresponde.",pairs:[["El hielo pudo transportar y depositar un bloque enorme.","Explicación geológica"],["La roca conserva una leyenda local vinculada a un joven cazador.","Memoria / relato"],["La roca prueba que existió un gigante blanco.","No sostenido por la evidencia"]],hint:"Una leyenda no se borra: se etiqueta con honestidad.",success:"ROCA LEÍDA EN DOS CAPAS.",explanation:"El paisaje combina tiempos geológicos y recuerdos humanos. Confundirlos empobrece los dos."}]},
    {title:"El lago no guarda un monstruo",speaker:"Alva",photo:"alva-nystrom-tiveden-v1.png",characterCaption:"personaje ficticio · cuaderno de campo",keys:1,time:"5–6 min",action:"Seguir el agua",obstacle:"Vitsand sorprende: arena clara junto a bosque oscuro. La Sombra dice que el color del agua pertenece a un monstruo.",goal:"Explicar el agua oscura, la arena clara y la leyenda de lago sin inventar criaturas.",done:"El agua y la arena guardan huellas del suelo y del deshielo; el monstruo famoso vive en la leyenda de otro lago.",reaction:"Oscura no significa sucia, y clara no significa siempre segura. El color es una pista del entorno, no una prueba de magia.",closing:"Segundo caso cerrado. El lago sigue siendo interesante sin convertirlo en una criatura inventada.",contexts:[
      {character:true,k:"VITSAND · STORA TREHÖRNINGEN",title:"Arena clara, agua color té",visual:"d4Vitsand",html:`<p>En el agua de muchos bosques, sustancias húmicas procedentes de hojas, suelo y materia orgánica dan un tono parecido al té. El color no sustituye las normas de baño ni permite valorar por sí solo la calidad del agua.</p><p>La arena de Vitsand muestra otro proceso: el agua de fusión del hielo transportó y clasificó granos que quedaron depositados en la orilla.</p>`},
      {character:true,k:"MAPA DE SUECIA · OTRA LEYENDA",title:"El monstruo que sí tiene nombre",visual:"d4Storsjon",html:`<p>La leyenda sueca del monstruo <strong>Storsjöodjuret</strong> pertenece a <strong>Storsjön</strong>, junto a Östersund, en Jämtland: no a este lago forestal. Hay relatos desde el siglo XVII y personas que dicen haberlo visto, pero no es una especie confirmada por la ciencia.</p><p>Un mapa evita que una leyenda viaje de un lago a otro sin darnos cuenta.</p>`}
    ],questions:[{id:"d4v7m2",type:"single",title:"La playa creada por el deshielo",prompt:"¿Qué une una gran roca errática y la arena de Vitsand?",options:["Las dos fueron instaladas el mismo año al crear el parque.","Son dos huellas de la retirada del hielo: una dejó bloques; el agua de fusión clasificó y depositó arena.","Son restos de una fortaleza vikinga enterrada."],answer:1,hint:"El hielo puede dejar bloques grandes y el agua de fusión ordenar granos pequeños.",success:"HIELO Y ARENA CONECTADOS.",explanation:"No hay base para afirmar un monstruo en Stora Trehörningen: aquí leemos suelo, vegetación, luz, agua y sedimentos."}]},
    {title:"Un bosque antiguo, no un bosque sin historia",speaker:"Alva",photo:"alva-nystrom-tiveden-v1.png",characterCaption:"personaje ficticio · cuaderno de campo",keys:1,time:"5–6 min",action:"Leer las cicatrices",obstacle:"La Sombra llama «intocado» a un bosque que conserva incendios y huellas de trabajo humano.",goal:"Entender cómo un bosque puede ser antiguo y conservar al mismo tiempo fuego, carbón vegetal y usos humanos.",done:"Los anillos, cicatrices y carboneras muestran una historia ecológica y humana.",reaction:"Un bosque antiguo no tiene por qué ser un bosque sin pasado humano. Cambiar una palabra puede cambiar lo que creemos que estamos viendo.",closing:"Tercer engaño corregido. No es una postal perfecta ni una fábrica antigua: es un paisaje vivo, con pinos viejos, fuego, carbón y memoria.",contexts:[
      {character:true,k:"PINO · CARBÓN · ANILLOS",title:"El fuego puede quedar escrito",visual:"d4Forest",html:`<p>Estudios de muestras de pinos y carbón registraron al menos <strong>86 incendios entre 1371 y 1853</strong> en la zona estudiada de Tiveden. Una cicatriz puede quedar cubierta por anillos posteriores: al estudiarlos se puede estimar cuándo ocurrió el fuego.</p><p>El fuego no es automáticamente bueno ni malo: importan su intensidad, frecuencia, lugar y especies.</p>`},
      {character:true,k:"DÍA 3 · EL HIERRO VUELVE",title:"Carbón vegetal para una región de hierro",visual:"d4Fire",html:`<p>Ayer Engelbrekt mostró que el hierro de Bergslagen no vivía solo en la mina. Para fundirlo hacían falta combustible, rutas y trabajo. En el parque se han identificado más de doscientos restos de carboneras: madera calentada con poco oxígeno para obtener carbón vegetal.</p><p>Así bosque e hierro se conectan sin fingir que todo el parque fue una industria.</p>`}
    ],questions:[{id:"d4v7m3",type:"single",title:"Ochenta y seis incendios",prompt:"¿Cómo puede conocerse un incendio ocurrido antes de que existieran fotografías?",options:["Preguntando a un robot que viviera en el bosque medieval.","Mirando solo el color de una aguja de pino actual.","Analizando anillos y cicatrices de árboles, junto con carbón conservado en el suelo."],answer:2,hint:"Un árbol puede conservar una cicatriz y seguir creciendo.",success:"FUEGO LEÍDO EN LOS ÁRBOLES.",explanation:"Las carboneras enlazan el bosque con el hierro visto en el Día 3. La madera muerta también puede ser hábitat y parte del ciclo natural."}]},
    {title:"Los trolls no pusieron los carteles",speaker:"Alva",photo:"alva-nystrom-tiveden-v1.png",characterCaption:"personaje ficticio · cuaderno de campo",keys:1,time:"4–5 min",action:"Escuchar la leyenda",obstacle:"Un paso estrecho, bloques altos y nombres como Trollkyrka invitan a contar historias. Eso no convierte el cuento en un informe arqueológico.",goal:"Conservar los relatos de trolls y salteadores sin presentarlos como hechos demostrados.",done:"Los nombres y los relatos guardan imaginación y memoria; la geología y los documentos dicen otra clase de cosas.",reaction:"Un nombre de lugar abre preguntas; no es una excavación ni una prueba automática de lo que ocurrió.",closing:"Los trolls pueden quedarse en los cuentos y el paso puede seguir dando respeto. No hace falta usar un nombre bonito para inventar un hecho.",contexts:[
      {character:true,k:"STIGMANSPASSET · TROLLKYRKA",title:"Un paso que sí daba respeto",visual:"d4Trolls",html:`<p>Stigmanspasset se asocia a historias de salteadores; Trollkyrka, a trolls. Un paso estrecho entre bloques puede parecer aislado y difícil de vigilar, aunque eso no pruebe una emboscada concreta. Tampoco hay documentos que demuestren ceremonias de trolls.</p><p>Las leyendas son una manera humana de contar un bosque difícil. Merecen respeto, pero no una etiqueta falsa de «hecho confirmado».</p>`},
      {character:true,k:"MICROCLASE DE SUECO",title:"Bosque y relato",visual:"d4Swedish",html:`<p><strong>skog</strong> = bosque · <strong>sjö</strong> = lago · <strong>troll</strong> = troll · <strong>berättelse</strong> = relato o historia contada.</p><p>No hace falta pronunciarlo perfecto: basta con reconocer que el idioma también guarda paisajes.</p>`}
    ],questions:[{id:"d4v7m4",type:"single",title:"El nombre no es una excavación",prompt:"¿Qué frase usa el nombre Trollkyrka con más cuidado?",options:["Como no hay pruebas de trolls, no merece la pena conocer las leyendas del lugar.","«Trollkyrka» conserva una imaginación ligada a trolls; el nombre no demuestra que allí hubiera un templo de trolls.","Si un lugar se llama Trollkyrka, está demostrado que los trolls vivieron allí."],answer:1,hint:"Una leyenda puede tener valor sin ser evidencia arqueológica.",success:"LEYENDA ETIQUETADA CON RESPETO.",explanation:"Tiveden conserva relatos de trolls y salteadores. Sus nombres no sustituyen a la evidencia."}]},
    {title:"Quién vive cuando nadie sale en la foto",speaker:"Alva",photo:"alva-nystrom-tiveden-v1.png",characterCaption:"personaje ficticio · cuaderno de campo",keys:1,time:"5–6 min",action:"Mirar las pistas",obstacle:"El bosque puede parecer silencioso y, sin embargo, estar lleno de vida que no vemos.",goal:"Reconocer pistas de animales sin perseguirlos ni prometer que aparecerán.",done:"Observar significa reconocer señales y aceptar que el animal puede no mostrarse.",reaction:"Una huella, una pluma o un sonido son pistas, no permiso para acercarse ni para inventar que hemos visto un animal.",closing:"El bosque no está vacío cuando nadie sale en la foto. La buena observación deja espacio y distancia.",contexts:[
      {character:true,k:"GUÍA DE OBSERVACIÓN · SIN GARANTÍAS",title:"Huellas, no personajes de cuento",visual:"d4Animals",html:`<p>Una huella grande de pezuña hendida puede corresponder a un <strong>alce</strong>; una más pequeña, a un <strong>corzo</strong>. Una pluma sugiere un ave, pero no identifica por sí sola una especie. El urogallo puede vivir en bosques como este; el lince euroasiático es muy esquivo.</p><p>Las fotos son una guía para observar. No prometen avistamientos y no se debe salir del sendero ni acercarse a crías.</p>`},
      {character:true,k:"SUECIA Y ESPAÑA · DOS LINCES",title:"Parecidos en el nombre, distintos en el mapa",visual:"d4Lynx",html:`<p>El <strong>lince euroasiático</strong> vive en Suecia y el <strong>lince ibérico</strong> en España y Portugal. Son especies distintas. El parecido del nombre no significa que tengan la misma distribución, hábitat o situación de conservación.</p>`}
    ],questions:[{id:"d4v7m5",type:"match",title:"Una pista no es una promesa",prompt:"Relaciona cada señal con la interpretación más prudente.",pairs:[["Huella grande de pezuña hendida","Puede corresponder a un alce."],["Huella pequeña de pezuña hendida","Puede corresponder a un corzo."],["Pluma en un camino","Puede ser una pista de ave, no una identificación completa."],["Sin rastros visibles","No demuestra que el bosque esté vacío."]],hint:"Observación cuidadosa no es adivinación.",success:"OBSERVACIÓN SIN INVASIÓN.",explanation:"No hay que tocar rastros, perseguir animales ni acercarse para disfrutar de una señal."}]},
    {title:"Una flor que no necesita magia",speaker:"Alva",photo:"alva-nystrom-tiveden-v1.png",characterCaption:"personaje ficticio · cuaderno de campo",keys:1,time:"3–4 min",action:"Abrir la señal opcional",obstacle:"Fuera del parque hay otra historia que parece inventada: nenúfares rojos junto a nenúfares blancos.",goal:"Cerrar el día distinguiendo una rareza natural real de una explicación fantástica.",done:"La variación roja de Fagertärn es una señal natural protegida, no una planta construida por una leyenda.",reaction:"Una rareza natural no necesita volverse sobrenatural para ser extraordinaria.",closing:"El cuaderno está completo: roca, agua, fuego, relatos y seres vivos han dejado huellas distintas. Ya podemos seguir hacia los lagos.",contexts:[
      {character:true,k:"SEÑAL OPCIONAL · FAGERTÄRN",title:"Nenúfares rojos y blancos",visual:"d4Fagertarn",html:`<p><strong>Fagertärn queda fuera del Parque Nacional de Tiveden.</strong> En este lago se conocen desde el siglo XIX nenúfares rojos junto a blancos. El color procede de una variación genética; el lugar está protegido para no dañar una población muy especial.</p><p>No hace falta arrancar, tocar ni recoger una flor para entender por qué importa.</p>`}
    ],questions:[{id:"d4v7m6",type:"single",title:"El veredicto de la flor",prompt:"¿Qué frase describe mejor los nenúfares rojos de Fagertärn?",options:["Son una variación natural protegida que se conoce desde el siglo XIX.","Demuestran que los trolls pintaron todos los lagos suecos.","Fagertärn es una parte cerrada del Museo Vasa."],answer:0,hint:"El dato curioso no necesita una explicación fantástica.",success:"RAREZA NATURAL ENTENDIDA.",explanation:"Fagertärn añade otra señal de la región: una flor extraordinaria con explicación natural."}]}
  ],
  ending:[
    {image:"alva-nystrom-tiveden-v1.png",caption:"Alva Nyström · personaje ficticio",k:"ALVA · CUADERNO RECOMPUESTO",title:"Cuatro maneras de leer un bosque",html:`<p>Roca, agua, fuego, bosque y personas han dejado huellas distintas. Una leyenda puede acompañarlas sin sustituirlas.</p><p>No hemos quitado magia a Tiveden. Hemos recuperado una magia mejor: la de un paisaje que tardó muchísimo tiempo en formarse y que todavía podemos cuidar.</p>`,action:"Guardar el cuaderno"},
    {image:"saga-canal-asegurado.png",caption:"Saga · transmisión recuperada",k:"SAGA · EVIDENCIA DEL DÍA",title:"Tiveden no es un decorado de cuentos.",html:`<p>Hielo, roca, fuego, agua, bosque y personas han dejado huellas distintas. La Sombra quería mezclarlas para que todo pareciera una sola historia cómoda.</p><p class="lead">La siguiente pregunta sigue abierta: si el bosque guardó tanta memoria, ¿qué historia humana puede estar escondida al otro lado de los lagos?</p>`,action:"Revelar la siguiente coordenada"},
    {image:"saga-canal-asegurado.png",caption:"Saga · rumbo a Karlsborg",k:"COORDENADA SIGUIENTE",title:"Un lago, una fortaleza y un miedo",html:`<div class="coordinate">KARLSBORG · VÄTTERN<br>UNA INVASIÓN · UNA RUTA INTERIOR · UN ESTADO QUE QUIERE RESISTIR</div><p>Al otro lado del bosque, un gran lago conectará la naturaleza con una decisión de Estado. La Sombra ya está intentando borrar por qué Suecia quiso mover lo imprescindible lejos de la costa.</p>`,action:"Cerrar el canal"}
  ]
};

/* Revisión contra el guion V8 aceptado. */
(()=>{
  const d=window.DAY1_DATA,m=d.missions;
  Object.assign(d.meta,{store:"codigo-gripsholm-v8-day04",contentVersion:"v9-day04-geologia-tiveden"});
  d.prologue[0].html=`<p>La Sombra ha alterado el cuaderno de campo. Ahora dice que un gigante lanzó las rocas, que un monstruo tiñe los lagos y que los trolls construyeron los pasos del bosque.</p><p>Alva os ayudará a responder sin estropear las historias. Hoy separaremos tres cosas: <strong>lo que vemos</strong>, <strong>lo que lo explica</strong> y <strong>lo que se cuenta</strong>.</p>`;
  d.prologue[1].html=`<p><strong>Alva Nyström tiene 19 años y es un personaje ficticio contemporáneo.</strong> Trabaja durante el verano ayudando a registrar observaciones y a orientar a visitantes.</p><p>«No puedo prometeros que hoy encontremos un alce, un lince o un troll. Pero sí puedo mostraros qué hay de real en los bosques, qué cuentan sus leyendas y cómo distinguir una historia fantástica de las pistas que deja la naturaleza.»</p><div class="evidence-grid three"><div><b>LO QUE VEMOS</b><span>Una roca enorme entre pinos.</span></div><div><b>LO QUE LO EXPLICA</b><span>Un glaciar pudo moverla.</span></div><div><b>LO QUE SE CUENTA</b><span>Un cazador perdió aquí a su amada.</span></div></div>`;
  m[0].obstacle="La Sombra dice que un gigante lanzó estas rocas. Antes de discutir con gigantes, vamos a leer lo que cuenta el paisaje: una historia escrita en piedra durante dos tiempos muy distintos de la Tierra.";
  m[0].contexts[0].html=`<p>Tiveden se sitúa entre <strong>Vänern</strong> y <strong>Vättern</strong>, dos de los grandes lagos suecos. Ayer vimos cómo pasos, ríos y puentes condicionaban las rutas alrededor de Örebro. Hoy veremos la parte física: roca, bosque y lagos también decidían por dónde podía circular la gente.</p><p><a class="official-sheet" href="assets/images/faktablad-stenkallerundan-eng.pdf" target="_blank" rel="noopener">Abrir la ficha de la ruta Stenkällerundan (en inglés)</a></p>`;
  m[0].contexts[1].html=`<p><strong>Primero la roca; mucho después, el hielo.</strong> La base de Tiveden es roca muy antigua y ya tenía fracturas naturales antes de la última Edad de Hielo. No todas las grietas tienen la misma edad, pero el hielo no creó el granito desde cero.</p><p>La última glaciación comenzó hace unos <strong>115.000 años</strong>. Hacia hace <strong>20.000 años</strong>, Escandinavia estaba cubierta por una gran capa de hielo. En el sur de Suecia empezó a retirarse hace unos 15.000–16.000 años; los últimos restos desaparecieron del norte sueco hace casi 10.000 años.</p><p>Mientras se movía, el hielo aprovechaba zonas débiles de la roca. Las piedras atrapadas en su base desgastaban la superficie; en lugares fracturados podía arrancar, mover o dejar bloques. Al retirarse, quedaron expuestas cavidades y masas de roca que hoy parecen un caos entre los pinos.</p><p><strong>Después del hielo, el proceso siguió.</strong> El agua de deshielo, las heladas y la vegetación continúan alterando lentamente el terreno. Stenkälla significa aproximadamente «fuente de piedra» y sus bloques muestran esta historia larga, no una construcción humana.</p>`;
  m[0].contexts[2].html=`<p>Junker Jägares sten es un gran bloque errático: el hielo lo transportó hasta aquí y lo dejó al retirarse hace unos 10.000 años.</p><p>La leyenda sitúa aquí el refugio de una joven y de Junker Jägare, el cazador al que amaba. Huían para evitar un matrimonio impuesto, pero fueron descubiertos. Cuando él volvió del bosque, comprendió que la había perdido.</p>`;
  m[0].questions[0].explanation="Combinar geología y leyendas permite descubrir el paisaje de una forma más amena, distinguiendo siempre entre lo que explica la ciencia y lo que cuenta la tradición.";
  m[0].reaction="No necesitamos un gigante para explicar una roca enorme: necesitamos muchísimo tiempo, una grieta y el hielo en movimiento.";
  m[0].closing="La roca sigue teniendo su aire de misterio. Pero ahora sabemos que es el resultado de miles de años.";
  m[1].goal="Explicar el agua oscura, la arena clara y la leyenda de lago.";
  m[1].done="Daremos explicación al agua, a la arena y también al monstruo: hasta en el lugar del monstruo se equivoca La Sombra.";
  m[1].contexts[1].html=`<p>La leyenda sueca del monstruo <strong>Storsjöodjuret</strong> pertenece a <strong>Storsjön</strong>, junto a Östersund, en Jämtland: no a este lago forestal.</p><p>Hay relatos desde el siglo XVII y personas que dicen haberlo visto, pero no es una especie confirmada por la ciencia. La Sombra ha cambiado de lago la leyenda del monstruo.</p>`;
  m[1].questions[0].prompt="Mira la gran roca de Junker Jägare y la playa de Vitsand. Parecen lugares muy distintos, pero los dos nos dan una pista sobre el mismo paisaje. ¿Cuál?";
  m[1].questions[0].options=["Los dos fueron creados al mismo tiempo para construir el parque nacional.","Los dos son huellas de la última Edad de Hielo: el hielo dejó la gran roca y el agua que se derritió fue acumulando la arena.","Los dos son restos de una fortaleza vikinga enterrada."];
  m[2].obstacle="La Sombra llama «completamente virgen» a un bosque que conserva incendios y huellas de trabajo humano.";
  m[2].contexts[1].html=`<p>Ayer Engelbrekt mostró que el hierro de Bergslagen no vivía solo en la mina. Para fundirlo hacían falta combustible, rutas y trabajo.</p><p>En el parque se han identificado más de doscientos restos de carboneras: madera calentada con poco oxígeno para obtener carbón vegetal. Así bosque e hierro convivieron sin hacerse daño.</p>`;
  m[2].reaction="Un bosque antiguo no tiene por qué ser un bosque sin pasado humano. Es posible la convivencia y la conservación.";
  m[3].obstacle="La Sombra presenta los nombres de Trollkyrka y Stigmanspasset como pruebas de trolls y salteadores. El paisaje inspira relatos, pero no confirma por sí solo lo que cuenta una leyenda.";
  m[3].goal="Distinguir la forma real del lugar, sus usos documentados y las historias que inspira.";
  m[3].done="El paso y las cumbres son reales. Los relatos siguen siendo valiosos cuando sabemos qué parte está documentada y qué parte pertenece a la imaginación.";
  m[3].contexts[0].html=`<p><strong>Stigmanspasset</strong> es una garganta natural estrecha: el sendero pasa entre paredes rocosas altas. Su nombre se relaciona con los <em>stigmän</em>, salteadores de caminos.</p><p>El relieve ayuda a entender por qué nació la leyenda: un paso cerrado puede parecer un lugar fácil para esconderse y difícil de vigilar. Pero el parque es claro: no se sabe si hubo salteadores que atacaran allí a viajeros. El paisaje hace la historia verosímil; no confirma un asalto concreto.</p><p><strong>Stora Trollkyrka</strong> y <strong>Lilla Trollkyrka</strong> no son iglesias ni edificios. Son dos cumbres rocosas. Desde Lilla Trollkyrka, en un día despejado, se puede ver Vadstena al otro lado del lago Vättern.</p><p>El parque explica que ambas cumbres fueron referencias visibles para la navegación en Vättern. Incluso plantea, como posibilidad, que fueran los navegantes quienes les dieran sus nombres.</p><p><em>Trollkyrka</em> conserva una forma de imaginar un paisaje alto, extraño y visible desde lejos. Es valioso como nombre y como relato, pero no demuestra templos, trolls ni ceremonias antiguas.</p>`;
  m[3].contexts[1].html=`<p><strong>Jag är i skogen.</strong> = «Estoy en el bosque».</p><p>Palabras que aparecen en la frase: <strong>skog</strong> = bosque · <strong>sjö</strong> = lago · <strong>troll</strong> = troll · <strong>berättelse</strong> = relato o historia contada.</p><p>No hace falta pronunciarlo perfecto: basta con reconocer que el idioma también guarda paisajes.</p>`;
  m[3].contexts[1].speech={word:"JAG ÄR I SKOGEN.",meaning:"Estoy en el bosque.",speech:"Jag är i skogen.",tip:"Jag = yo · är = estoy/soy · i = en · skogen = el bosque."};
  m[3].questions[0].explanation="Tiveden conserva relatos de trolls y salteadores. Los nombres y el relieve los hacen comprensibles, pero no sustituyen pruebas de un asalto, un templo o trolls reales.";
  m[4].goal="Reconocer pistas de animales.";
  m[4].done="Observar significa reconocer señales y aceptar que no siempre vamos a ver los animales.";
  m[4].reaction="Una huella, una pluma o un sonido son pistas, no dan permiso para acercarse ni para perseguir animales.";
  m[5].contexts[0].html=`<p><strong>Fagertärn queda fuera del Parque Nacional de Tiveden.</strong> En este lago se conocen desde el siglo XIX nenúfares rojos junto a blancos.</p><p>El color procede de una variación genética; el lugar está protegido para no dañar una población muy especial. No hace falta arrancar, tocar ni recoger una flor para entender por qué es importante.</p>`;
  d.ending[0].html=`<p>Ni gigantes, ni monstruos, ni trolls. Tiveden sigue teniendo su magia, incluso sin las leyendas.</p><p>Hemos recuperado una magia mejor: la de un paisaje que tardó muchísimo tiempo en formarse y que todavía podemos cuidar.</p>`;
  d.ending[1].html=`<p>La Sombra quería confundir las leyendas e historias con la realidad.</p><p class="lead">La siguiente pregunta sigue abierta: si el bosque tiene tantos años, ¿qué historia humana puede estar escondida al otro lado de los lagos?</p>`;
  m.push({title:"Elige tu día en Tiveden",speaker:"Alva",photo:"alva-nystrom-tiveden-v1.png",characterCaption:"personaje ficticio · cuaderno de campo",consultation:true,time:"consulta opcional",action:"Abrir el mapa del parque",obstacle:"No hay una sola visita correcta. El parque tiene rutas oficiales de distintas longitudes; este mapa reúne cuatro recorridos y las paradas que hemos visto hoy.",goal:"Orientarte para elegir una ruta y localizar playa, roca, pasos y cumbres antes de visitar el parque.",done:"Tienes un mapa de consulta: eliges por tiempo, distancia y lo que quieres ver; la señalización del parque tiene siempre la última palabra.",reaction:"Un buen mapa no te obliga a hacer todo: te ayuda a decidir qué te apetece hoy.",closing:"Mapa guardado como consulta. No cuenta como reto ni hay que resolver nada para seguir el día.",contexts:[{character:true,k:"MAPA DEL PARQUE · CONSULTA",title:"Elige tu día en Tiveden",visual:"d4ParkRoutes",html:`<p><strong>Esta misión es solo de consulta:</strong> no hay que adivinar ni completar un reto. Toca los números del mapa para abrir cada parada con su foto y una explicación corta.</p><p>Las cuatro líneas son trazados simplificados de rutas oficiales: <strong>Trehörningsrundan</strong> (la vuelta larga del lago), <strong>Junker jägarerundan</strong> (Vitsand y la roca), <strong>Stigmansrundan</strong> (paso estrecho y bloques) y <strong>Trollkyrkorundan</strong> (cumbres rocosas).</p><p>El parque tiene más recorridos señalizados. Antes de caminar, comprueba el estado, el mapa y las indicaciones en la <a class="official-sheet" href="https://en.tiveden.se/hiking/" target="_blank" rel="noopener">página oficial de rutas de Tiveden</a>.</p>`,action:"Cerrar el mapa"}]});
})();

(()=>{const m=window.DAY1_DATA.missions;
  m[1].questions[0].media={file:"Vitsand.jpg",alt:"Playa de Vitsand",caption:"Vitsand · arena clara junto al agua oscura del bosque."};
  m[1].contexts[0].mapImage="vitsand-playa-2026.jpg";
  m[1].contexts[0].mapAlt="Playa de arena de Vitsand junto al lago y el bosque";
  m[1].contexts[0].mapCaption="Vitsand · arena clara, agua y bosque · foto del autor del viaje, 2026";
  m[4].contexts[0].mediaGallery=null;
  m[4].contexts[1].mediaGallery=null;
})();
