/* Día 05 · Fuente editorial única: Guion completo V8 aceptado.
   Baltzar von Platen y Carlos XIV Juan aparecen por documentos, mapas y retratos: no se les atribuyen diálogos inventados. */
window.DAY1_DATA={
  meta:{day:"05",store:"codigo-gripsholm-v7-day05",contentVersion:"v7-final-day5",place:"TIVEDEN → KARLSBORG → HJO → HÖKERUM",title:"Invasión: la fortaleza que esperaba una guerra",landing:"La Sombra ha insertado una frase nueva en un protocolo histórico.",badge:"Protocolo Karlsborg",objective:"ENTENDER POR QUÉ SUECIA QUISO GUARDAR SU ESTADO EN EL INTERIOR",objectiveCopy:"Seguiremos Vättern, la crisis de 1809, el canal, Karlsborg y Hjo para reconstruir una ruta de continuidad.",evidenceCopy:"Cada misión ilumina una parte del Protocolo Karlsborg.",fine:"Baltzar von Platen y Carlos XIV Juan se presentan mediante documentos y contexto histórico; no les atribuimos frases inventadas.",verifiedTitle:"El Protocolo Karlsborg está completo.",verifiedAction:"Abrir el cierre de Saga",result:{title:"Invasión: la fortaleza que esperaba una guerra",evidence:"Protocolo Karlsborg reconstruido",openQuestion:"¿Qué busca La Sombra en la red textil de Hökerum y por qué necesita que olvidemos quién construyó las rutas?",next:{href:"dia6.html",label:"Abrir el Día 06"}}},
  prologue:[
    {k:"SAGA · PROTOCOLO INTERFERIDO",title:"Un país entero cabe en una lista",image:"saga-transmision-inicial.png",alt:"Saga abre la ruta desde Tiveden hacia Karlsborg",html:`<p>La línea de agua que vimos ayer tenía nombre: <strong>Vättern</strong>. Mis padres siguieron su orilla hasta una fortaleza construida para el peor día posible.</p><p>Si Estocolmo quedaba amenazada, el rey, el Gobierno, el Parlamento, las reservas y los documentos esenciales debían ponerse a salvo allí. He encontrado una copia del protocolo. Casi todo pertenece al siglo XIX. Casi.</p><p>Alguien ha añadido una línea con la misma tinta que alteró el mapa de mis padres: <strong>EL MAPA</strong>.</p>`,action:"Abrir el protocolo"},
    {k:"BALTZAR VON PLATEN · DOCUMENTO, NO VOZ INVENTADA",title:"Un plan que no llegó a ver terminado",image:"saga-transmision-inicial.png",alt:"Saga presenta el documento sobre Baltzar von Platen",html:`<p>Baltzar von Platen fue oficial de Marina, político e impulsor del Göta Canal. Formó parte de la comisión de defensa de 1809 y defendió una gran fortaleza en el interior.</p><p>Murió antes de ver acabados el canal y Karlsborg. No puede hablarnos: seguiremos sus planes, no una frase imaginada.</p>`,action:"Abrir el mapa"}
  ],routePlaces:[],
  missions:[
    {title:"El lago que une la ruta",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"4–5 min",action:"Situar Vättern",obstacle:"Antes de hablar de invasiones, situemos el terreno. Tiveden queda entre grandes masas de agua; Karlsborg y Hjo comparten una de sus orillas.",goal:"Entender que Vättern no es un fondo azul: es una posible ruta interior entre lugares del viaje.",done:"Vättern une Tiveden, Karlsborg y Hjo en el mapa de hoy.",reaction:"Ahora el lago no es un paisaje de fondo: ayuda a explicar una ruta interior y varias ciudades del viaje.",closing:"Ya sabemos qué lago une la jornada. Falta descubrir qué miedo llevó a convertir su orilla en una pieza de defensa.",contexts:[
      {character:true,k:"MAPA DE LA JORNADA",title:"Dos lagos y una ruta interior",visual:"d5Route",html:`<p><strong>Vänern</strong> es el lago más grande de Suecia. <strong>Vättern</strong> es el segundo por superficie: largo, profundo y eje de hoy. <strong>Tiveden</strong> queda entre ambos. Karlsborg y Hjo se sitúan en la orilla occidental de Vättern.</p><p>El sistema Göta combina costa, ríos, grandes lagos, tramos excavados y esclusas. No es una zanja continua de un extremo a otro.</p>`},
      {character:true,k:"CUATRO LAGOS PARA RECORDAR",title:"El agua vuelve a conectar los días",visual:"d5Lakes",html:`<p><strong>Vänern:</strong> el mayor. <strong>Vättern:</strong> el del día. <strong>Mälaren:</strong> entrada histórica hacia Estocolmo y Gripsholm. <strong>Hjälmaren:</strong> cerca de Örebro y del último viaje de Engelbrekt.</p><p>Un lago puede ser frontera, vía de pesca, paisaje, ruta comercial o problema defensivo según la época.</p>`}
    ],questions:[{id:"d5v7m1",type:"single",title:"La orilla correcta",prompt:"¿Qué afirmación sitúa bien la jornada?",options:["Karlsborg y Hjo comparten la orilla occidental de Vättern; Tiveden queda entre Vänern y Vättern.","Hjo y Karlsborg están en dos costas distintas del Atlántico.","Vättern es un lago forestal pequeño dentro del Parque Nacional de Tiveden."],answer:0,hint:"Mira el mapa: el bosque queda entre dos lagos y las dos ciudades junto al mismo.",success:"VÄTTERN SITUADO.",explanation:"Vättern organiza geografía, defensa, transporte y vida cotidiana en el recorrido de hoy."}]},
    {title:"Cuando el reino perdió el este",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"7–8 min",action:"Ver el cambio de mapa",obstacle:"La Sombra ha dejado la fortaleza sin causa, como si fuera una idea exagerada. Primero debemos ver qué cambió en 1809.",goal:"Comprender la pérdida de Finlandia, el giro de Bernadotte y por qué Suecia pensó en una reserva interior.",done:"La crisis de 1809 deja de ser una fecha: cambia la frontera y la manera de proteger el Estado.",reaction:"Bernadotte no cambió de alianza por capricho. La pérdida de Finlandia y el peligro de Napoleón obligaron a elegir entre intereses muy difíciles.",closing:"La respuesta fue una reserva interior. Pero una fortaleza sin una ruta para mover lo necesario sería solo un edificio aislado.",contexts:[
      {character:true,k:"1808–1809 · FRONTERA ANTES Y DESPUÉS",title:"Finlandia no era todavía un país separado",visual:"d5Finland",html:`<p>En 1808 Rusia invadió Finlandia, entonces parte del reino de Suecia. Por el tratado de Fredrikshamn de 1809, Suecia cedió Finlandia y Åland a Rusia. Finlandia pasó a ser un Gran Ducado autónomo dentro del Imperio ruso.</p><p>No fue una guerra entre la Finlandia y la Suecia actuales: el mapa político era distinto.</p>`},
      {character:true,k:"1807 → 1819 · ALIANZAS QUE CAMBIAN",title:"De mariscal francés a Carlos XIV Juan",visual:"d5Bernadotte",html:`<p><strong>1807:</strong> Napoleón y el zar Alejandro I se alían en Tilsit. <strong>1808:</strong> Rusia invade Finlandia. <strong>1809:</strong> tras derrotas y una crisis de gobierno, Gustavo IV Adolfo es depuesto; Carlos XIII ocupa el trono con una nueva Constitución.</p><p><strong>1810:</strong> el Riksdag reunido en Örebro elige como heredero a Jean Baptiste Bernadotte, mariscal francés. <strong>1812:</strong> Napoleón ocupa la Pomerania sueca; Bernadotte se acerca a Rusia y acepta que Finlandia permanezca rusa a cambio de apoyo para obtener Noruega. <strong>1818:</strong> reina como Carlos XIV Juan. <strong>1819:</strong> comienza Karlsborg.</p><p><strong>Paralelismo con España:</strong> Francia entró en 1808 con la excusa de invadir Portugal, aliado de Gran Bretaña. La crisis de Godoy, las abdicaciones de Bayona y José Bonaparte abrieron otra guerra. La misma Europa napoleónica afectó a cada país de forma distinta.</p>`}
    ],questions:[{id:"d5v7m2",type:"single",title:"Un plan después de 1809",prompt:"Estocolmo queda más expuesta desde el este. ¿Qué plan responde mejor a ese nuevo riesgo?",options:["Reunir Gobierno, reservas y documentos en un muelle abierto hacia el Báltico.","Preparar un lugar interior, comunicado por una ruta de agua, al que puedan trasladarse instituciones y recursos esenciales.","Elegir una isla sin comunicaciones: cuanto más aislada, más fácil será mantener el país conectado."],answer:1,hint:"No se trata solo de esconder una caja: hay que conservar decisiones, comunicaciones y abastecimiento.",success:"PLAN DE CONTINUIDAD ENTENDIDO.",explanation:"En 1812 Suecia se alió con Rusia contra Napoleón. Las alianzas no son premios de amistad: son decisiones de interés y con costes."}]},
    {title:"La ruta que no es una zanja",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"5–6 min",action:"Abrir el sistema Göta",obstacle:"Baltzar von Platen imaginó una fortaleza interior y una vía que conectara el país. No vamos a leer el Göta Canal como una simple raya azul.",goal:"Entender que el sistema Göta combina agua existente y obra humana para unir interior, costa y niveles distintos.",done:"La ruta interior queda reconstruida como un sistema mixto de costa, lagos, ríos, canal y esclusas.",reaction:"Una infraestructura no la hace una sola persona famosa: la diseñan, excavan, mantienen y usan miles de personas.",closing:"Una ruta puede mover más que barcos. Ahora debemos decidir qué era tan importante como para llevarlo a Karlsborg.",contexts:[
      {character:true,k:"1810–1832 · SISTEMA GÖTA",title:"Un canal hecho también de lagos",visual:"d5Gota",html:`<p>El Göta Canal mide 190 km; 87 km se excavaron a mano. Tiene 58 esclusas y enlaza Sjötorp, junto a Vänern, con Mem, en el Báltico.</p><p>Es una combinación de agua que ya existía y obra humana. La ruta se relaciona con el mundo que imaginaba Baltzar von Platen, aunque no fuese una autopista de evacuación preparada para una emergencia moderna.</p>`},
      {character:true,k:"LA TIERRA NO SE MOVIÓ SOLA",title:"Una obra de miles de manos",visual:"d5Workers",html:`<p>La información del canal atribuye su construcción a unos 58.000 soldados de 16 regimientos, además de técnicos y otros trabajadores. Muchas tareas se hicieron a mano, con jornadas largas.</p><p>Como las catedrales, palacios e infraestructuras españolas, una obra de esta escala tiene canteros, carpinteros, albañiles, herreros, transportistas, artesanos y proveedores detrás.</p>`}
    ],questions:[{id:"d5v7m3",type:"single",title:"El mensaje que cabe en el mapa",prompt:"Después de observar el sistema Göta, ¿qué explicación es más exacta?",options:["Se excavó una única zanja recta de costa a costa, sin aprovechar lagos ni ríos.","Se diseñó sobre todo para ocio; transporte y comercio fueron secundarios.","Usa costa, lagos, ríos, tramos excavados y esclusas para salvar lugares sin agua continua o con cambios de altura."],answer:2,hint:"Enciende una capa cada vez: lago, río, canal y esclusa hacen trabajos distintos.",success:"RUTA INTERIOR RECONSTRUIDA.",explanation:"El sistema muestra por qué el agua podía mover carga y conectar el interior mucho mejor que un carro lento y de poca capacidad."}]},
    {title:"Una capital dentro de la muralla",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"5–6 min",action:"Leer el plano de Karlsborg",obstacle:"La Sombra ha borrado las etiquetas del plano y lo ha dejado como un castillo enorme sin sentido. Hay que devolver a cada lugar su función.",goal:"Comprender Karlsborg como plan de continuidad del Estado, no como una residencia ni una simple caja fuerte.",done:"Gobierno, Parlamento, documentos, reservas, defensas y abastecimiento recuperan su lugar en el protocolo.",reaction:"La pregunta sigue vigente aunque cambien los medios: ¿cómo conserva un Estado su capacidad de decidir y proteger información esencial durante una crisis?",closing:"Una fortaleza no es solo piedra ni un plano. También es para quién se diseñó y quién tuvo que levantarla.",contexts:[
      {character:true,k:"KARLSBORG · 678 METROS",title:"Una barrera para conservar funciones",visual:"d5Karlsborg",html:`<p>El Slutvärnet mide 678 metros. La cifra no demuestra que fuera «mejor» por ser grande: muestra que Karlsborg no era una residencia pequeña. Era una barrera defensiva con espacio para las funciones que debían mantenerse en una crisis.</p><p>La iglesia de guarnición podía acoger al Riksdag. Había depósitos para la caja del Estado y lugar para armas, hospital, banco, farmacia y comercios.</p><p><strong>Paralelismo con España:</strong> el Alcázar de Segovia fue fortaleza y residencia real medieval; no es el equivalente de Karlsborg, pero ayuda a entender cómo defensa, residencia y archivos pueden concentrarse en un lugar defendible.</p>`},
      {character:true,k:"QUIÉN CONSTRUYÓ",title:"La piedra no se movió sola",visual:"d5Workers",html:`<p>Soldados, oficiales, trabajadores especializados y prisioneros de fortaleza participaron en Karlsborg. Sus condiciones no fueron iguales.</p><p>El recinto hoy denominado <strong>Valle de Cuelgamuros</strong>, conocido durante décadas como <strong>Valle de los Caídos</strong>, obliga en España a mirar con cuidado la memoria del trabajo: participaron presos en el sistema franquista de redención de penas por el trabajo. No es el mismo caso histórico que Karlsborg; sirve para no contar una gran obra sin trabajadores, desigualdad ni memoria.</p>`}
    ],questions:[{id:"d5v7m4",type:"single",title:"¿Qué cabe en un plan de continuidad?",prompt:"El plan no podía trasladar a toda Suecia. ¿Qué conjunto permite que el Estado siga funcionando durante una crisis?",options:["Tropas y armas, sin documentos, autoridades civiles ni suministros.","Gobierno y Parlamento; documentos y reservas; defensas y abastecimiento imprescindible.","Solo reservas de valor, sin quienes deben decidir, comunicarse ni organizar el abastecimiento."],answer:1,hint:"No es una mudanza ni una caja fuerte: piensa qué permite tomar y sostener decisiones.",success:"PROTOCOLO DE CONTINUIDAD RESTAURADO.",explanation:"Hoy los países también mantienen planes, archivos protegidos e instalaciones seguras cuyos detalles no son públicos."}]},
    {title:"La fortaleza que llegó tarde",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"4–5 min",action:"Abrir la línea de tiempo",obstacle:"El protocolo parecía perfecto sobre el papel. Pero el mundo no se queda quieto mientras se construyen edificios durante décadas.",goal:"Leer los noventa años de Karlsborg sin reducirlos a éxito total o fracaso total.",done:"Karlsborg se entiende como un plan superado en parte por la tecnología, pero con usos posteriores y valor histórico.",reaction:"Las historias rara vez son «éxito total» o «fracaso total». Se puede explicar un plan superado sin borrar todo lo que vino después.",closing:"La siguiente evidencia no está tras una muralla. Está al otro lado del lago.",contexts:[
      {character:true,k:"1819 → 1909",title:"La obra que ocupó noventa años",visual:"d5Timeline",html:`<p>Karlsborg se construyó entre 1819 y 1909. Mientras se levantaba, cambiaban la artillería, los transportes y las comunicaciones. Cuando quedó terminada, la potencia y el alcance de los cañones habían debilitado la idea de concentrar la defensa en el centro del país.</p><p><strong>Para comparar tiempos:</strong> El Escorial empezó en 1563 y su gran obra terminó en 1584: 21 años. La Sagrada Familia comenzó en 1882 y continúa en construcción. Una obra cambia mientras la construyen generaciones distintas.</p>`}
    ],questions:[{id:"d5v7m5",type:"single",title:"¿Un fracaso completo?",prompt:"¿Qué lectura hace justicia a Karlsborg?",options:["Fue la capital permanente de Suecia durante noventa años, tal como se planeó.","Su misión original de capital de reserva quedó superada por cambios tecnológicos, pero siguió teniendo usos militares y hoy conserva memoria histórica y patrimonial.","Como la tecnología cambió, dejó de tener cualquier función posterior o valor histórico."],answer:1,hint:"No confundas un plan inicial que deja de ser suficiente con que nada de lo construido importe.",success:"KARLSBORG LEÍDA CON MATIZ.",explanation:"El tiempo también cambia el significado de un edificio: una fortaleza puede convertirse en testigo de un miedo y una estrategia que ya no funcionan igual."}]},
    {title:"Vättern, barrera y camino",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"4–5 min",action:"Mirar el lago con prudencia",obstacle:"Vättern podía ser ruta, frontera natural y fuente de vida. No se parece a los lagos oscuros de Tiveden, aunque ambos guarden huellas del hielo.",goal:"Comparar el lago forestal y el gran lago abierto sin decidir si uno es «limpio» y otro «sucio» por el color.",done:"Vättern queda leído como un lago profundo, frío y cambiante que exige prudencia.",reaction:"Un gran lago no se entiende por una foto de una orilla: profundidad, temperatura, viento y oleaje cambian el día.",closing:"La fortaleza protegía lo oficial. El lago sostenía pesca, agricultura, artesanía, comercio y ciudades. Hjo conserva una parte de esa red.",contexts:[
      {character:true,k:"TIVEDEN Y VÄTTERN",title:"Dos lagos, dos historias",visual:"d5Water",html:`<p>Los lagos forestales de Tiveden pueden parecer color té por sustancias húmicas del suelo y la vegetación. Vättern es enorme, abierto, profundo y, en general, más claro. El color por sí solo no dice «sucio» o «limpio».</p><p>Vättern alcanza aproximadamente 128 metros de profundidad máxima y ronda 40 de media. Su volumen tarda en calentarse.</p>`},
      {character:true,k:"UN LAGO TIENE PISOS",title:"No todos los peces viven en el mismo lugar",visual:"d5LakeLife",html:`<p>Orilla, agua abierta, desembocaduras y profundidad ofrecen ambientes distintos. Las especies adaptadas al frío no usan exactamente el mismo «piso» que las de una zona somera o de río.</p><p>Esta tarjeta no promete avistamientos ni propone pescar: solo enseña a mirar el lago sin molestar.</p>`}
    ],questions:[{id:"d5v7m6",type:"single",title:"Leer un lago con prudencia",prompt:"Es verano y una orilla de Vättern parece tranquila. ¿Qué decisión demuestra mejor que has entendido el lago?",options:["Comprobar las condiciones del día y no suponer que temperatura u oleaje de una orilla representan todo un lago grande, profundo y frío.","Dar por hecho que el agua será cálida porque se ve azul y el aire está caliente.","Concluir que la profundidad impide que haya vida acuática."],answer:0,hint:"El gran volumen tarda en calentarse y las condiciones pueden variar.",success:"VÄTTERN LEÍDO CON PRUDENCIA.",explanation:"La prudencia forma parte de leer la naturaleza: mirar condiciones reales y seguir la información local."}]},
    {title:"Hjo sigue contando",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"5–6 min",action:"Abrir Hjo",obstacle:"Hjo no guarda su memoria en una cámara secreta. La guarda en el puerto, el río, las casas y las decisiones que tomó después de perder parte de su ciudad.",goal:"Leer una ciudad histórica como un lugar que se repara, usa y transforma.",done:"Puerto, río, madera, balneario y memoria urbana quedan conectados en Hjo.",reaction:"Conservar no es encerrar una ciudad en una vitrina: es repararla, usarla y recordar de qué está hecha.",closing:"Hjo demuestra que una ciudad puede perder edificios y seguir guardando memoria en sus rutas, casas y decisiones.",contexts:[
      {character:true,k:"HJO · PUERTO, RÍO, PLAZA Y PARQUE",title:"Una ciudad junto a Vättern",visual:"d5Hjo",html:`<p>El puerto, Hjoån, la plaza, Stadsparken, las casas de madera y la orilla muestran funciones distintas de una ciudad lacustre: llegada, agua, encuentro, descanso, vivienda y comercio.</p><p>Hjo forma con Eksjö y Nora el grupo de las «Tres Ciudades de Madera». Recibieron un reconocimiento Europa Nostra en 1990: no es una declaración UNESCO.</p>`},
      {character:true,k:"1794 · INCENDIO Y RECONSTRUCCIÓN",title:"La ciudad no empieza de cero",visual:"d5Hjo",html:`<p>Un incendio destruyó la iglesia medieval y otros edificios de Hjo en 1794. También se encontraron monedas fundidas. La catástrofe no borra la ciudad: abre una historia de reconstrucción, cambios y cuidado de lo que queda.</p><p>En el siglo XIX Hjo se desarrolló también como destino de baños, salud y ocio junto al lago; el parque y las villas recuerdan esa etapa.</p>`}
    ],questions:[{id:"d5v7m7",type:"single",title:"Después del incendio",prompt:"¿Qué conclusión convierte la catástrofe de 1794 en una historia urbana, no en una anécdota?",options:["Tras el incendio dejó de importar conservar edificios antiguos: una ciudad puede empezar de cero en cualquier parte.","La reconstrucción conservó exactamente trazado y materiales sin ninguna decisión ni cambio.","Una ciudad puede perder edificios y conservar memoria si se reconstruye, reorganiza sus espacios y cuida lo que queda."],answer:2,hint:"Una ciudad histórica no necesita estar intacta para tener memoria.",success:"MEMORIA URBANA LEÍDA.",explanation:"Hjo conserva capas distintas: puerto, casas de madera, parque de balneario y una vida cotidiana junto a Vättern."}]},
    {title:"Lo que no cabe en una cámara acorazada",speaker:"Saga",photo:"saga-transmision-inicial.png",keys:1,time:"4–5 min",action:"Seguir la marca",obstacle:"Mis padres dejaron la siguiente pista en cosas que parecen menos importantes: un barco, una creadora y una funda de tela. Ahí es donde La Sombra no esperaba que miráramos.",goal:"Seguir una pista desde Hjo hacia Hökerum sin convertir una ciudad o una fortaleza en la respuesta a todo.",done:"La evidencia apunta a una red textil del interior de Västergötland.",reaction:"Un país no solo vive en sus instituciones: también en rutas, talleres, diseños, oficios y conexiones entre personas.",closing:"Hemos recuperado el Protocolo Karlsborg. La marca de La Sombra continúa hacia Hökerum.",contexts:[
      {character:true,k:"S/S TRAFIK Y ESTRID ERICSON",title:"Un barco y una creadora",visual:"d5Culture",html:`<p>El vapor <strong>S/S Trafik</strong>, en servicio desde 1892, recuerda que Vättern conectaba puertos, personas y mercancías antes de las carreteras modernas.</p><p><strong>Estrid Ericson</strong> nació en Öregrund, creció vinculada a Hjo y fundó Svenskt Tenn en Estocolmo en 1924. Su historia une formación artesanal, empresa y colaboración con Josef Frank.</p>`},
      {character:true,k:"SUECO ÚTIL",title:"Un helado, por favor",visual:"d5Swedish",html:`<p><strong>Jag skulle vilja ha en glass, tack.</strong></p><p>Significa: «Me gustaría un helado, por favor». Es una tarjeta para escuchar y usar; no una prueba de pronunciación.</p>`}
    ],questions:[{id:"d5v7m8",type:"single",title:"La pista que no es un tesoro",prompt:"En una funda de tela aparece la misma marca que alteró el protocolo. El mapa señala Hökerum. ¿Qué conclusión abre la siguiente jornada?",options:["La Sombra no buscó solo cámaras oficiales: ha usado una ruta hacia el interior de Västergötland y una pista vinculada a tejidos.","Como Hjo aparece en la ruta, la pista debe referirse a una capital alternativa.","Karlsborg sigue siendo el único lugar relevante; no hace falta mirar hacia Hökerum."],answer:0,hint:"Sigue la dirección marcada, no el edificio más grande.",success:"RUTA TEXTIL ABIERTA.",explanation:"La investigación deja el lago y entra en otra forma de hacer país: talleres, redes y paisajes del interior."}]}
  ],
  ending:[
    {image:"saga-canal-asegurado.png",caption:"Saga · Protocolo Karlsborg",k:"SAGA · EVIDENCIA RECUPERADA",title:"Una derrota cambió cómo Suecia se protegía.",html:`<p>La crisis de 1809 y la nueva frontera mostraron que una capital expuesta no bastaba. Vättern y el sistema Göta ayudan a comprender por qué Suecia imaginó una ruta interior.</p><p>Karlsborg se proyectó como capital de reserva: no para mover a toda la población, sino para mantener instituciones, documentos, reservas y defensa.</p>`,action:"Guardar el protocolo"},
    {image:"saga-canal-asegurado.png",caption:"Saga · memoria de las rutas",k:"SAGA · LO QUE EL PLANO NO DEBÍA OCULTAR",title:"Las grandes obras tienen personas detrás.",html:`<p>Planos, trabajos, desigualdades y memoria forman parte de Karlsborg y del canal. Hjo recuerda que un país también vive en sus casas reparadas, sus oficios y sus puertos.</p><p>La Sombra quería dejar una fortaleza sin causa y una ruta sin constructores. Ahora el Protocolo Karlsborg vuelve a tener sentido.</p>`,action:"Revelar la siguiente coordenada"},
    {image:"saga-canal-asegurado.png",caption:"Saga · ruta hacia Hökerum",k:"COORDENADA SIGUIENTE",title:"La marca sigue el hilo de una tela.",html:`<div class="coordinate">HÖKERUM · VÄSTERGÖTLAND<br>REDES · TALLERES · INTERIOR<br>SEÑAL · UNA MARCA TEXTIL</div><p>La tarde termina en Hökerum. La siguiente pista deja el lago y entra en otra forma de hacer país: talleres, redes y paisajes del interior.</p>`,action:"Cerrar el canal"}
  ]
};

/* Revisión contra el guion V8 aceptado. Los visuales indicados desde V4 se mantienen completos. */
(()=>{
  const d=window.DAY1_DATA,m=d.missions;
  Object.assign(d.meta,{store:"codigo-gripsholm-v8-day05",contentVersion:"v8-day05-final"});
  d.prologue[0].html=`<p>La línea de agua que vimos ayer tenía nombre: <strong>Vättern</strong>. Mis padres siguieron su orilla hasta una fortaleza construida para el peor día posible.</p><p>Si Estocolmo quedaba amenazada, el rey, el Gobierno, el Parlamento, las reservas y los documentos esenciales debían ponerse a salvo allí. He encontrado una copia del protocolo. Casi todo pertenece al siglo XIX. Casi.</p><p>Alguien ha añadido una línea con la misma tinta que alteró el mapa de mis padres: <strong>LA CARTA</strong>.</p>`;
  d.prologue[1].html=`<p>Baltzar von Platen fue oficial de Marina, político y el gran impulsor del canal de Göta. Después de que Suecia perdiera Finlandia, participó en la búsqueda de una defensa que no dependiera únicamente de la costa.</p><p>Su idea conectaba agua, transporte y protección: una ruta interior y una fortaleza capaz de albergar las instituciones del país.</p><p>Murió antes de verla terminada. No puede guiarnos con su voz, pero dejó mapas suficientes para seguir su razonamiento.</p>`;
  m[0].goal="Entender que Vättern no es un lago más: es una posible ruta interior para situaciones de emergencia nacional.";
  m[0].contexts[0].html=`<p><strong>Vänern</strong> es el lago más grande de Suecia. <strong>Vättern</strong> es el segundo por superficie: largo, profundo y eje de hoy. Tiveden queda entre ambos. Karlsborg y Hjo se sitúan en la orilla occidental de Vättern.</p><p>El sistema Göta combina costa, ríos, grandes lagos, tramos excavados y esclusas. No es una simple zanja continua de un extremo a otro.</p>`;
  m[0].contexts[1].html=`<p><strong>Vänern:</strong> el mayor. <strong>Vättern:</strong> el del día. <strong>Mälaren:</strong> entrada histórica hacia Estocolmo y Gripsholm. <strong>Hjälmaren:</strong> cerca de Örebro y del último viaje de Engelbrekt.</p><p>Un lago puede ser una frontera, un lugar de pesca, un bonito paisaje, parte de una ruta comercial o un sistema defensivo según la época.</p>`;
  m[0].questions[0].explanation="Vättern es el punto de referencia del día: geografía, defensa, transporte y vida cotidiana en el recorrido de hoy.";
  m[0].reaction="El lago es mucho más que simple agua: ayuda a explicar una ruta interior y varias ciudades del viaje.";
  m[1].goal="Comprender la pérdida de Finlandia, el giro de Bernadotte y por qué Suecia pensó en un refugio al interior del país.";
  m[1].done="La crisis de 1809 deja de ser una fecha: habían cambiado las fronteras y debía cambiar la forma de proteger el Estado.";
  m[1].contexts=[
    {character:true,k:"1808–1809 · FRONTERA ANTES Y DESPUÉS",title:"¿Por qué comenzó la guerra?",visual:"d5Finland",html:`<p>Suecia había combatido contra Napoleón junto a Gran Bretaña, Rusia y Austria. Todo cambió en 1807, cuando Napoleón y Alejandro I acordaron la paz en Tilsit. Rusia aceptó presionar a Suecia para que se sumara al bloqueo comercial contra Gran Bretaña.</p><p>El rey sueco Gustavo IV Adolfo, profundamente contrario a Napoleón, se negó. Gran Bretaña era además un socio comercial y el único aliado importante que le quedaba. Rusia invadió Finlandia sin una declaración previa de guerra en febrero de 1808.</p><p>Suecia defendía Finlandia con tropas de las dos partes del reino y apoyo diplomático y naval británico. Rusia terminó reuniendo más hombres y suministros en los puntos decisivos.</p>`},
    {character:true,k:"GUERRA DE FINLANDIA",title:"¿Hubo una rebelión finlandesa?",html:`<p>Dinamarca-Noruega no acudió a ayudar a Suecia. Era el adversario histórico sueco y, tras el ataque británico a Copenhague de 1807, quedó alineado con Francia. Presionada por Rusia y Francia, Noruega declaró la guerra a Suecia en 1808.</p><p>No hubo una rebelión nacional finlandesa que entregara el territorio a Rusia. En 1808 hubo decisiones locales, rendiciones y cambios de lealtad, pero numerosos campesinos finlandeses hostigaron a las tropas rusas. Los soldados que defendían Finlandia formaban parte del ejército del reino sueco.</p>`},
    {character:true,k:"GEOGRAFÍA DEL RIESGO",title:"¿Por qué interesaba Finlandia a Rusia?",html:`<p>Finlandia protegía el flanco noroccidental del Imperio ruso. Controlarla alejaba la frontera de San Petersburgo y permitía dominar mejor el golfo de Finlandia y Åland.</p><p>Desde Åland, además, la ruta marítima hacia Estocolmo quedaba peligrosamente cerca.</p>`},
    {character:true,k:"1808–1809 · LA DERROTA",title:"¿Por qué perdió Suecia?",html:`<p>El plan sueco consistía en retirarse hacia el norte mientras la gran fortaleza de Sveaborg, frente a Helsinki, resistía hasta que el deshielo permitiera llevar refuerzos por mar. Sveaborg se rindió en mayo de 1808, mucho antes de lo esperado.</p><p>Suecia logró algunas victorias y la resistencia campesina complicó el avance ruso, pero fallaron varios desembarcos, escasearon suministros y refuerzos, y Rusia consiguió concentrar una fuerza superior. En 1809 las tropas rusas cruzaron Åland, alcanzaron territorio de la actual Suecia y amenazaron Estocolmo.</p>`},
    {character:true,k:"17 SEPTIEMBRE DE 1809",title:"¿Cómo terminó?",html:`<p>El fracaso provocó la destitución de Gustavo IV Adolfo y una nueva constitución sueca. El Tratado de Fredrikshamn obligó a Suecia a ceder Finlandia, Åland y territorios del nordeste al Imperio ruso.</p><p>Alejandro I mantuvo en Finlandia buena parte de sus leyes, religión y administración. Se convirtió en un gran ducado autónomo gobernado por el zar: no era todavía un Estado independiente, pero empezó a disponer de instituciones propias diferenciadas.</p>`},
    {character:true,k:"TRES CORONAS",title:"Ya no estaban unidas",html:`<p>La Unión de Kalmar había reunido las coronas de Dinamarca, Noruega y Suecia desde 1397, pero Suecia salió definitivamente de ella con Gustav Vasa en 1523. En 1808 no existía esa unión desde hacía casi tres siglos.</p><p>Dinamarca y Noruega sí continuaban unidas bajo el mismo rey. Esa unión duró hasta 1814, cuando Dinamarca tuvo que ceder Noruega a Suecia. Los noruegos aprobaron su propia constitución y entraron después en una unión con Suecia que duraría hasta 1905.</p>`},
    {character:true,k:"1807 → 1819 · ALIANZAS QUE CAMBIAN",title:"De mariscal francés a Carlos XIV Juan",visual:"d5Bernadotte",html:`<p><strong>1807:</strong> Napoleón y el zar Alejandro I se alían en Tilsit. <strong>1808:</strong> Rusia invade Finlandia. <strong>1809:</strong> Gustavo IV Adolfo es depuesto; Carlos XIII ocupa el trono con una nueva Constitución.</p><p><strong>1810:</strong> el Riksdag reunido en Örebro elige como heredero a Jean Baptiste Bernadotte, mariscal francés. <strong>1812:</strong> Napoleón ocupa la Pomerania sueca; Bernadotte se acerca a Rusia. <strong>1818:</strong> reina como Carlos XIV Juan. <strong>1819:</strong> comienza Karlsborg.</p><p>En 1808 Suecia rechazaba las exigencias de Napoleón; dos años después eligió como heredero a uno de sus antiguos mariscales. No significaba que Suecia se hubiera convertido en una posesión francesa: necesitaba estabilidad dinástica, prestigio militar y una persona capaz de moverse en el nuevo tablero europeo.</p><details class="dossier"><summary>CONTEXTO · LO QUE PASABA EN ESPAÑA</summary><p>En 1808, mientras Rusia atacaba la Finlandia sueca, Napoleón intervino en España, forzó las abdicaciones de Carlos IV y Fernando VII y colocó a su hermano José Bonaparte en el trono. Comenzó la Guerra de la Independencia.</p><p>Suecia y España no combatían la misma guerra ni compartían el mismo enemigo inmediato. El paralelismo es otro: en ambos extremos de Europa, la expansión de las grandes potencias derribó certezas políticas y obligó a reorganizar el Estado.</p></details>`}
  ];
  m[1].questions[0].hint="No se trata solo de esconderse. Hay que buscar un lugar seguro, abastecido, bien comunicado y desde el que se puedan tomar decisiones.";
  m[1].questions[0].explanation="Por mar y por los grandes lagos, un solo barco podía transportar mucho más que varios carros. El problema era que la costa podía estar vigilada y los lagos interiores todavía no formaban una ruta continua.";
  m[1].reaction="No era una solución mágica ni inmediata. Primero había que excavar el canal y construir esclusas. Después, carros y caballos seguirían siendo necesarios para muchos trayectos cortos.";
  m[2].contexts[0].html=`<p>El sistema Göta combina costa, río, canales y grandes lagos. No es una zanja continua: los tramos excavados y las esclusas unen niveles y vías de agua diferentes.</p><p>Es la experiencia completa recuperada del recorrido V4: una ruta que se abre por etapas para entender cómo se conecta el país.</p>`;
  m[3].goal="Comprender Karlsborg como plan de continuidad del Estado. No se trata de una residencia ni de una caja fuerte para guardar bienes.";
  m[3].contexts[0].html=`<p>El Slutvärnet mide 678 metros. La cifra no demuestra que fuera «mejor» por ser grande: muestra que Karlsborg no era una residencia pequeña. Era una barrera defensiva con espacio para las funciones que debían mantenerse en una crisis.</p><p>La iglesia de guarnición podía acoger al Riksdag. Había depósitos para la caja del Estado y lugar para armas, hospital, banco, farmacia y comercios.</p><p><strong>Paralelismo con España:</strong> el Alcázar de Segovia fue fortaleza y residencia real medieval. No es el equivalente de Karlsborg, pero ayuda a entender cómo defensa, residencia y archivos pueden concentrarse en un lugar defendible.</p>`;
  m[3].contexts[1].html=`<p>Soldados, oficiales, trabajadores especializados y prisioneros de fortaleza participaron en Karlsborg.</p>`;
  m[4].goal="Entender que el plan tardó en ejecutarse más de lo previsto: unos noventa años, y qué usos tuvo después.";
  m[4].done="Karlsborg se ha adaptado a los tiempos y ahora tiene otras funciones.";
  m[4].contexts[0].html=`<p>Karlsborg se construyó entre 1819 y 1909. Mientras se levantaba, cambiaban la artillería, los transportes y las comunicaciones. Cuando quedó terminada, la potencia y el alcance de los cañones habían debilitado la idea de concentrar la defensa en el centro del país.</p><p>Para comparar tiempos: El Escorial empezó en 1563 y su gran obra terminó en 1584, en 21 años. La Sagrada Familia comenzó en 1882 y todavía continúa en construcción.</p>`;
  m[4].reaction="Las historias rara vez son «éxito total» o «fracaso total». Se puede evolucionar un plan que ha quedado anticuado.";
  m[5].contexts[1].html=`<p>Orilla, agua abierta, desembocaduras y profundidad ofrecen ambientes distintos. Las especies adaptadas al frío no usan exactamente el mismo «piso» que las de una zona somera o de río.</p><p>Esta tarjeta no promete avistamientos ni propone pescar: solo enseña a mirar el lago sin molestar.</p>`;
  m[6].contexts[1].html=`<p>Un incendio destruyó la iglesia medieval y otros edificios de Hjo en 1794. También se encontraron monedas fundidas. La catástrofe no borra la ciudad: abre una historia de reconstrucción, cambios y cuidado de lo que queda.</p><p>En el siglo XIX Hjo se desarrolló también como destino de baños, salud y ocio junto al lago; el parque y las villas recuerdan esa etapa.</p>`;
  m[7].contexts[1].speech={word:"JAG SKULLE VILJA HA EN GLASS, TACK.",meaning:"Me gustaría un helado, por favor.",speech:"Jag skulle vilja ha en glass, tack.",tip:"Jag skulle vilja ha = me gustaría tener · en glass = un helado · tack = gracias / por favor."};
  d.ending[1].html=`<p>Planos, trabajos, desigualdades y memoria forman parte de Karlsborg y del canal. Hjo recuerda que un país también vive en sus casas reparadas, sus oficios y sus puertos.</p><p>La Sombra quería dejar una fortaleza sin sentido histórico y hacer desaparecer un canal. Ahora el Protocolo Karlsborg vuelve a tener sentido.</p>`;
  /* Recuperaciones completas de V4 indicadas por el guion: actividad, respuestas y gráfica asociada. */
  m[1].keys=2;
  m[1].questions.push({id:"d5v4m2k2",type:"match",visual:"d5Bernadotte",title:"Europa arde en dos extremos",scene:"En 1808 Napoleón colocaba familiares y aliados en tronos europeos, mientras Rusia atacaba la parte oriental de Suecia.",prompt:"Relaciona cada escenario con su consecuencia.",pairs:[["España · 1808","Napoleón impone a su hermano José y comienza la Guerra de la Independencia"],["Finlandia · 1808","Rusia invade territorio del reino sueco"],["Suecia · 1810","El mariscal francés Bernadotte es elegido heredero"],["Noruega · 1814","Pasa de la corona danesa a una unión con Suecia"]],hint:"La misma Europa napoleónica produjo respuestas distintas.",success:"EUROPA CONECTADA",explanation:"Jean Baptiste Bernadotte había servido a Napoleón, pero como heredero sueco acabó combatiendo contra él. Su dinastía continúa en el trono."});
  m[2].keys=2;
  m[2].questions.push({id:"d5v4m3k2",type:"explore",visual:"d5Gota",title:"Un canal hecho también de lagos",scene:"La ruta no es una zanja continua: combina costa, río, canales y grandes lagos.",prompt:"Abre las seis etapas de costa a costa.",items:[["Mem","Entrada oriental desde el Báltico."],["Canal de Göta","Tramos excavados y esclusas."],["Vättern","Gran lago central."],["Vänern","Mayor lago de Suecia."],["Göta älv y Trollhättan","Salida occidental con esclusas y río."],["Gotemburgo","Acceso al Kattegat y al mar del Norte."]],success:"VÍA INTERIOR ABIERTA",explanation:"El sistema permite cruzar Suecia utilizando unos 190 km de canal de Göta más lagos y otras vías navegables."});
  m[5].keys=2;
  m[5].questions.push({id:"d5v4m6k3",type:"match",visual:"d5LakeLife",title:"No todos los peces viven en el mismo piso",scene:"La orilla, el agua abierta y la profundidad ofrecen ambientes distintos.",prompt:"Relaciona cada pez con una forma sencilla de reconocer su hábitat.",pairs:[["Lucio","cazador de orillas y vegetación"],["Perca","zonas litorales y aguas intermedias"],["Salmón de lago","agua abierta"],["Salvelino ártico","agua profunda, fría y bien oxigenada"]],hint:"El pez adaptado al frío busca la profundidad.",success:"VIDA BAJO EL AGUA",explanation:"Un lago profundo no es una sola habitación: sus temperaturas y hábitats cambian con la profundidad."});
})();

(()=>{
  const m=window.DAY1_DATA.missions;
  m[0].questions[0]={id:"d5v8m1",type:"match",contextVisual:"d5Lakes",title:"Los cuatro lagos en el mapa",scene:"Sitúa los nombres y después relaciona cada lago con su etiqueta completa.",prompt:"Une cada lago con la explicación que le corresponde.",pairs:[["Vänern","El mayor lago de Suecia."],["Vättern","El gran lago del día: Karlsborg y Hjo están en su orilla occidental."],["Mälaren","Entrada histórica hacia Estocolmo y Gripsholm."],["Hjälmaren","Lago próximo a Örebro y al último viaje de Engelbrekt."]],hint:"No intentes memorizar cuatro manchas azules: lee cada etiqueta completa y vuelve al mapa.",success:"LAGOS SITUADOS.",explanation:"Los cuatro lagos ya tienen nombre, tamaño o función. Ahora Vättern deja de ser un fondo azul: organiza la jornada."};
  m[2].questions[0].solutionVisual="d5Lock";
  m[2].questions[1].scene="Usa el mismo mapa de la misión: cada etapa aparece una sola vez y con un nombre legible.";
  m[5].contexts[1].mediaGallery=null;
  m[7].contexts[0].html=`<p>El vapor <strong>S/S Trafik</strong>, en servicio desde 1892, recuerda que Vättern conectaba puertos, personas y mercancías antes de las carreteras modernas.</p><p><strong>Estrid Ericson</strong> nació en Öregrund en 1894 y creció en Hjo. La experiencia de vivir junto al lago y en el hotel familiar forma parte de su historia antes de ir a Estocolmo.</p><p>Allí se formó, trabajó como profesora y consultora, y en 1924 fundó <strong>Svenskt Tenn</strong> con Nils Fougstedt. En 1934 incorporó a Josef Frank, arquitecto austríaco que había dejado Viena ante el avance del antisemitismo.</p><p>La ficha de esta pantalla separa los hechos comprobados de una idea muy repetida: no hay una relación directa documentada con Coco Chanel que debamos presentar como historia.</p>`;
})();
