window.DAY5_DATA={
 meta:{day:"05",store:"codigo-gripsholm-day05-v1",place:"KARLSBORG · VÄTTERN · HJO",title:"La capital que esperaba una guerra",landing:"Suecia preparó una capital de reserva. Alguien ha añadido una ruta que no pertenece a 1809.",openingTime:"Primera apertura recomendada: 15–20 minutos. Las estaciones del recorrido pueden completarse después.",objective:"SEPARAR EL PLAN DE LA INFILTRACIÓN",objectiveCopy:"Reconstruirás la retirada del Estado, el canal y la cámara acorazada para descubrir qué línea conduce al Día 06.",routeCount:8,previousStore:"codigo-gripsholm-day04-v1",previousDay:"04",fragment:"6 de 11"},
 routePlaces:[
  ["Tiveden","Punto de salida. El bosque del Día 04 queda al norte de Karlsborg."],
  ["Fortaleza de Karlsborg","Gran fortaleza del siglo XIX en la península de Vanäs, junto a Vättern."],
  ["Slutvärnet","Edificio defensivo central de 678 metros, pensado como último reducto."],
  ["Puerto y canal de Göta","La vía de agua conectó Vättern con el sistema interior y las dos costas."],
  ["Ruta 49","Carretera por la orilla occidental de Vättern; las paradas deben hacerse solo en lugares seguros."],
  ["Puerto de Hjo","Escala comercial, balnearia y de navegación en la orilla occidental del lago."],
  ["Stadsparken y ciudad de madera","Parque del antiguo balneario y conjunto urbano reconocido por Europa Nostra."],
  ["Hökerum","Final de la jornada y primera pista de la región textil del Día 06."]
 ],
 prologue:[
  {k:"DÍA 05 · TRANSMISIÓN REABIERTA",title:"El bosque termina. La retirada empieza.",image:"saga-transmision-inicial.png",alt:"Saga abre la transmisión del Día 05",html:`<p>La señal del cuaderno cruza Vättern y entra en una fortaleza diseñada para guardar un país entero.</p><p>Mis padres dejaron una lista: <strong>corona, Parlamento, oro, archivos y armas</strong>. Alguien añadió una sexta carga que no existía en 1809.</p><p class="lead">Necesito que reconstruyas el plan antes de que la organización use esa línea para encontrarnos.</p>`,action:"Abrir el plan de retirada"},
  {k:"SAGA · PERSONAJE DEL DÍA",title:"Baltzar von Platen dibujó la salida por agua.",image:"baltzar-von-platen-public-domain.jpg",alt:"Retrato histórico de Baltzar von Platen",html:`<p><strong>Baltzar Bogislaus von Platen (1766–1829)</strong> fue oficial de marina, político y principal impulsor del canal de Göta. No es un personaje ficticio: el retrato es una obra histórica de dominio público.</p><p>Tras perder Finlandia, Suecia necesitaba mover personas y recursos lejos de las costas expuestas. Von Platen defendió una vía interior que utilizara lagos, canales y esclusas.</p><p class="lead">Su proyecto conecta la fortaleza con el agua. También permite esconder una ruta dentro de otra.</p>`,action:"Aceptar sus planos"},
  {k:"MAPA DE ORIENTACIÓN",title:"Ocho señales entre el bosque y la región textil.",routeMap:true,html:`<p>Abre los ocho puntos. No hay nada que adivinar: recibirás 5 kr por reconocer la ruta completa antes de salir.</p>`,action:"Continuar"},
  {k:"FUNCIÓN DEL JUGADOR",title:"Hoy no evacúas una ciudad. Proteges la continuidad del Estado.",html:`<div class="final-record day5-code"><div><b>01</b><span>RECUPERA LA LÍNEA DE AGUA</span></div><div><b>02</b><span>DECIDE QUÉ DEBE SALVARSE</span></div><div><b>03</b><span>SEPARA 1809 DE LA RUTA MODERNA</span></div><div><b>04</b><span>LLEVA LA PISTA HASTA HÖKERUM</span></div></div><p>Las preguntas fijan ideas sencillas. Los desplegables guardan el contexto histórico completo para quien quiera abrirlo.</p>`,action:"Activar la primera misión"}
 ],
 missions:[
  {title:"La línea de agua",speaker:"Baltzar von Platen",keys:3,time:"4–5 min",minimum:30,action:"Desplegar los lagos",obstacle:"El mapa solo conserva dos manchas de agua y una carretera hacia el sur.",goal:"Reconoce Vättern, sitúa los grandes lagos y abre las tres etapas del día.",done:"La jornada ya tiene escala regional.",questions:[
   {id:"d5m1k1",type:"explore",visual:"d5TwoLakes",title:"Dos lagos y una ruta interior",scene:"Tiveden queda entre dos enormes reservas de agua. Karlsborg y Hjo comparten la orilla occidental de una de ellas.",prompt:"Abre las seis referencias del mapa.",items:[["Vänern","El mayor lago de Suecia."],["Vättern","El segundo mayor; largo, estrecho y profundo."],["Tiveden","Entre los dos lagos."],["Karlsborg","Orilla occidental de Vättern."],["Hjo","Más al sur, en la misma orilla."],["Hökerum","Al suroeste, camino de la región textil."]],success:"LÍNEA REGIONAL ABIERTA",explanation:"El día desciende por el lado occidental de Vättern y después gira hacia Hökerum."},
   {id:"d5m1k2",type:"single",visual:"d5SwedishLakes",title:"El lago correcto",scene:"La fortaleza de Karlsborg y Hjo están junto al mismo lago.",prompt:"¿Qué nombre recuperas?",options:["Vättern","Mälaren","Vänern"],answer:0,hint:"Es el segundo lago más grande de Suecia.",interludeTitle:"LOS GRANDES LAGOS DE SUECIA",interlude:`<p><strong>Vänern</strong> es el mayor y se abre hacia Gotemburgo por el Göta älv. <strong>Vättern</strong> es el segundo y contiene Visingsö. <strong>Mälaren</strong> desemboca en Estocolmo; <strong>Hjälmaren</strong> está junto a Örebro.</p><p>El mapa de solución mantiene sus proporciones y añade las ciudades que ya forman parte del viaje.</p>`,success:"VÄTTERN RECUPERADO",explanation:"Karlsborg y Hjo se encuentran en la orilla occidental de Vättern. No debe confundirse con el mayor Vänern."},
   {id:"d5m1k3",type:"explore",visual:"d5DayStages",title:"Tres etapas, una misma jornada",scene:"El protocolo divide el desplazamiento para no perder el hilo entre historia y paisaje.",prompt:"Abre fortaleza, orilla y ciudad de madera.",items:[["Karlsborg","Fortaleza, Slutvärnet, puerto y canal."],["Ruta 49","Bosques y aperturas hacia Vättern."],["Hjo","Puerto, parque y casas de madera."]],success:"JORNADA DIVIDIDA",explanation:"Primero se reconstruye el plan defensivo; después se sigue Vättern hasta una ciudad que conservó su escala humana."}
  ]},
  {title:"El reino pierde el este",speaker:"Baltzar von Platen",keys:4,time:"8–10 min",minimum:40,action:"Reconstruir 1809",obstacle:"El expediente afirma que Finlandia se independizó mediante una rebelión y que Suecia quedó sin respuesta.",goal:"Recupera los bandos, el tratado y la nueva estrategia sueca.",done:"La pérdida de Finlandia explica por qué Karlsborg mira hacia el interior.",questions:[
   {id:"d5m2k1",type:"multi",visual:"d5FinlandWar",title:"Antes y después de 1809",scene:"Rusia invadió Finlandia, entonces parte del reino sueco, en 1808. No fue una guerra nacional entre Finlandia y Suecia.",prompt:"Selecciona las cuatro piezas que reparan el informe.",options:["Rusia invadió la Finlandia sueca","Napoleón y Alejandro I habían acordado presionar a Suecia","Suecia recibió ayuda británica limitada","El Tratado de Fredrikshamn cedió Finlandia y Åland a Rusia","Finlandia se rebeló sola y derrotó a Suecia","La Unión de Kalmar seguía gobernando las tres coronas"],answer:[0,1,2,3],hint:"Busca invasión rusa, diplomacia napoleónica, apoyo limitado y tratado.",interludeTitle:"POR QUÉ SUECIA PERDIÓ FINLANDIA",interlude:`<h3>Europa obligó a Suecia a elegir</h3><p>En Tilsit, en 1807, Napoleón y el zar <strong>Alejandro I</strong> pactaron. Rusia debía obligar a Suecia a sumarse al bloqueo contra Gran Bretaña. El rey sueco Gustavo IV Adolfo se negó y Rusia invadió Finlandia en febrero de 1808.</p><p>Suecia combatió con fuerzas suecas y finlandesas; Rusia disponía de más capacidad para reemplazar tropas y abastecer el frente. Gran Bretaña ayudó con dinero y presencia naval, pero no recuperó el territorio. Dinamarca-Noruega era aliada de Napoleón y declaró la guerra a Suecia: no existía ya una unión de las tres coronas. La Unión de Kalmar había quedado rota en 1523.</p><h3>El resultado</h3><p>El Tratado de Fredrikshamn de 1809 obligó a Suecia a ceder Finlandia, Åland y territorios orientales a Rusia. Finlandia se convirtió en un Gran Ducado autónomo dentro del Imperio ruso. Para Rusia era una zona de seguridad frente a San Petersburgo; para Suecia, la pérdida demostraba que Estocolmo y la costa oriental eran vulnerables.</p>`,success:"GUERRA RESTITUIDA",explanation:"Finlandia no se separó mediante una rebelión nacional. Rusia derrotó a Suecia dentro de las guerras napoleónicas y el tratado cambió la frontera."},
   {id:"d5m2k2",type:"match",visual:"d5NapoleonEurope",title:"Europa arde en dos extremos",scene:"En 1808 Napoleón colocaba familiares y aliados en tronos europeos, mientras Rusia atacaba la parte oriental de Suecia.",prompt:"Relaciona cada escenario con su consecuencia.",pairs:[["España · 1808","Napoleón impone a su hermano José y comienza la Guerra de la Independencia"],["Finlandia · 1808","Rusia invade territorio del reino sueco"],["Suecia · 1810","El mariscal francés Bernadotte es elegido heredero"],["Noruega · 1814","Pasa de la corona danesa a una unión con Suecia"]],hint:"La misma Europa napoleónica produjo respuestas distintas.",success:"EUROPA CONECTADA",explanation:"Jean Baptiste Bernadotte había servido a Napoleón, pero como heredero sueco acabó combatiendo contra él. Su dinastía continúa en el trono."},
   {id:"d5m2k3",type:"single",visual:"d5CentralDefense",title:"¿Dónde guardarías la continuidad?",scene:"Estocolmo estaba cerca del Báltico. El nuevo plan buscaba profundidad defensiva, agua y comunicaciones interiores.",prompt:"¿Qué lugar protege mejor ese objetivo?",options:["Karlsborg, junto a Vättern y la futura vía interior","Una nueva fortaleza en la costa abierta de Estocolmo","Åland, recién cedida a Rusia"],answer:0,hint:"La clave es alejarse de la costa amenazada sin quedar aislado.",success:"CENTRO DEFENSIVO LOCALIZADO",explanation:"Karlsborg fue elegida para alojar funciones esenciales mientras el ejército retrasaba una invasión."},
   {id:"d5m2k4",type:"order",visual:"d5Timeline1809",title:"De Örebro a Karlsborg",scene:"La crisis cambió rey, heredero y sistema defensivo en pocos años.",prompt:"Ordena la reacción sueca.",items:[["a","1809 · Suecia pierde Finlandia y depone a Gustavo IV Adolfo"],["b","1810 · Örebro elige a Jean Baptiste Bernadotte como heredero"],["c","1818 · Bernadotte reina como Carlos XIV Juan"],["d","1819 · comienzan las obras de Karlsborg"]],answer:["a","b","c","d"],hint:"Primero se pierde el este; después se elige heredero y comienza la obra.",success:"REACCIÓN ORDENADA",explanation:"Karlsborg no fue una ocurrencia aislada: formó parte de la reorganización política y militar posterior a 1809."}
  ]},
  {title:"Mover un país sin carreteras",speaker:"Baltzar von Platen",keys:4,time:"7–9 min",minimum:40,action:"Abrir el canal",obstacle:"La fortaleza debe recibir armas, oro, personas y documentos antes de que el enemigo cierre las rutas costeras.",goal:"Compara transportes de 1809 y reconstruye el canal de Göta.",done:"La vía interior ya puede mover la carga del Estado.",questions:[
   {id:"d5m3k1",type:"explore",visual:"d5Transport",title:"El hombre que conectó los lagos",scene:"Un carro era flexible, pero lento y con poca carga. Un barco podía transportar mucho más si existía una vía continua.",prompt:"Abre las cuatro funciones de von Platen.",items:[["Marino","Conocía barcos, puertos y limitaciones de la navegación."],["Político","Defendió el proyecto ante la corona y el Parlamento."],["Ingeniero organizador","Coordinó técnicos, capital y mano de obra."],["Director del canal","Impulsó una red que utilizaba lagos y tramos excavados."]],interludeTitle:"¿QUÉ HABRÍAS ELEGIDO EN 1809?",interlude:`<div class="transport-grid"><div><b>CABALLOS Y CARROS</b><span>Flexibles, pero lentos; cada animal mueve una carga limitada y necesita caminos, alimento y relevos.</span></div><div><b>CARRETERA NUEVA</b><span>Útil para personas y mensajes, muy costosa para trasladar toneladas.</span></div><div><b>AGUA INTERIOR</b><span>Un barco mueve grandes cargas. El problema es salvar desniveles y unir lagos.</span></div></div><p>Von Platen eligió combinar Vättern, Vänern y canales artificiales. Las <strong>esclusas</strong> funcionan como ascensores de agua: una cámara se llena o vacía para subir o bajar el barco. Así también se navega «contra corriente» sin exigir que el barco remonte una cascada.</p>`,success:"AUTOR DEL PLAN RECUPERADO",explanation:"Von Platen no construyó solo el canal, pero convirtió una idea antigua en un proyecto político y técnico ejecutable."},
   {id:"d5m3k2",type:"explore",visual:"d5GotaCanal",title:"Un canal hecho también de lagos",scene:"La ruta no es una zanja continua: combina costa, río, canales y grandes lagos.",prompt:"Abre las seis etapas de costa a costa.",items:[["Mem","Entrada oriental desde el Báltico."],["Canal de Göta","Tramos excavados y esclusas."],["Vättern","Gran lago central."],["Vänern","Mayor lago de Suecia."],["Göta älv y Trollhättan","Salida occidental con esclusas y río."],["Gotemburgo","Acceso al Kattegat y al mar del Norte."]],success:"VÍA INTERIOR ABIERTA",explanation:"El sistema permite cruzar Suecia utilizando unos 190 km de canal de Göta más lagos y otras vías navegables."},
   {id:"d5m3k3",type:"multi",visual:"d5Cargo",title:"¿Qué protegería Suecia?",scene:"En caso de invasión, el plan no podía trasladar a toda la población. Debía conservar lo imprescindible para que el país siguiera funcionando.",prompt:"¿Qué cosas protegería Suecia para poder seguir funcionando durante una guerra?",options:["Familia real y Gobierno","Parlamento y administración esencial","Reservas de oro y archivos","Armas y munición","Personal militar y servicios","Toda la población de Estocolmo","Un contenedor de tejidos con código de barras"],answer:[0,1,2,3,4],hint:"Piensa en quién toma decisiones, qué documentos y recursos necesita y quién defiende el lugar.",success:"PLAN DE EMERGENCIA RECUPERADO",explanation:"Karlsborg fue concebida como refugio de quienes dirigían y sostenían el Estado. Como los refugios de continuidad de gobierno actuales, protegía instituciones, no a toda la sociedad; ese límite también forma parte de la historia."},
   {id:"d5m3k4",type:"single",visual:"d5Anachronism",title:"Una línea que no pertenece al siglo XIX",scene:"Entre oro, archivos y munición aparece un registro moderno.",prompt:"¿Qué elemento revela la infiltración?",options:["Un contenedor textil con código de barras","Cajas de documentos oficiales","Munición almacenada"],answer:0,hint:"Los códigos de barras no pertenecen a 1809.",success:"INFILTRACIÓN AISLADA",explanation:"La línea moderna no forma parte del plan de Karlsborg. Apunta hacia la región textil del siguiente día."}
  ]},
  {title:"Una capital dentro de la muralla",speaker:"Baltzar von Platen",keys:4,time:"8–10 min",minimum:40,action:"Entrar en el reducto",obstacle:"El inventario muestra edificios, personas y materiales, pero ha borrado quién podía refugiarse y quién construyó el lugar.",goal:"Recupera la firma de Bernadotte, el Slutvärnet, las funciones y la mano de obra.",done:"La fortaleza vuelve a mostrar poder y coste humano.",questions:[
   {id:"d5m4k1",type:"single",visual:"d5Bernadotte",onsite:true,title:"La firma del rey francés",scene:"Busca el monograma de Carlos XIV Juan. Antes de ser rey sueco fue Jean Baptiste Bernadotte, mariscal de Napoleón y heredero elegido en Örebro.",prompt:"¿Qué conexión activa esa firma?",options:["Örebro · Bernadotte · Karlsborg","Vasa · 1628 · Vaxholm","Cristián II · 1520 · Stortorget"],answer:0,hint:"El Día 03 terminó una elección y este día muestra su política defensiva.",success:"FIRMA CONECTADA",explanation:"La elección de 1810 y la fortaleza iniciada en 1819 pertenecen a la misma reorganización sueca."},
   {id:"d5m4k2",type:"single",visual:"d5Slutvarnet",title:"Seiscientos setenta y ocho metros",scene:"El Slutvärnet debía ser cuartel, muralla y último refugio defensivo.",prompt:"¿Qué cifra recupera su longitud aproximada?",options:["678 metros","68 metros","6,78 kilómetros"],answer:0,hint:"Es extraordinariamente largo, pero no mide varios kilómetros.",success:"REDUCTO MEDIDO",explanation:"El edificio central se extiende unos 678 metros y organiza gran parte de la imagen monumental de Karlsborg."},
   {id:"d5m4k3",type:"match",visual:"d5FortressFunctions",title:"Iglesia, Parlamento, oro y cien mil rifles",scene:"En una retirada, cada espacio debía asumir una función concreta.",prompt:"Relaciona cada lugar con su uso previsto.",pairs:[["Iglesia de la guarnición","Parlamento en caso de guerra"],["Cámara acorazada","Reservas de oro y valores"],["Tyghuset","Armas, material y hasta unos cien mil rifles"],["Slutvärnet","Cuartel, defensa y servicios del reducto"]],hint:"La iglesia podía cambiar de función política.",success:"CAPITAL DE RESERVA ARMADA",explanation:"Karlsborg era un sistema de continuidad estatal, no solo una muralla."},
   {id:"d5m4k4",type:"multi",visual:"d5Workers",title:"La tierra no se movió sola",scene:"La obra necesitó décadas de trabajo. El expediente ha dejado solo a los oficiales.",prompt:"Recupera los grupos que también construyeron Karlsborg.",options:["Soldados","Trabajadores civiles","Presos empleados en trabajos forzados","Ingenieros y artesanos","Trolls del bosque","Máquinas excavadoras modernas"],answer:[0,1,2,3],hint:"La obra combinó dirección técnica, tropa, civiles y trabajo penitenciario.",interludeTitle:"RECORDAR SIN EQUIPARAR",interlude:`<p>Usar cautivos o población sometida en grandes obras aparece en épocas muy distintas, pero <strong>no todos los sistemas laborales fueron iguales</strong>.</p><p><strong>Guiza:</strong> muchos constructores de las pirámides fueron trabajadores organizados y mantenidos por el Estado; no encaja la imagen simple de millones de esclavos encadenados.</p><p><strong>Karlsborg:</strong> participaron soldados, civiles, artesanos y presos sometidos a trabajo.</p><p><strong>Valle de Cuelgamuros (antes Valle de los Caídos):</strong> junto a trabajadores libres participaron presos políticos mediante destacamentos penales y un sistema de redención de penas dentro de una dictadura.</p><p><strong>Canal del Bajo Guadalquivir:</strong> miles de presos políticos realizaron trabajos forzados tras la Guerra Civil española.</p><p>El coste humano no se «compensa» al terminar el edificio. Se recuerda para que la monumentalidad no borre a quienes movieron la tierra.</p>`,success:"MANO DE OBRA RECORDADA",explanation:"La fortaleza no se levantó sola. Recuperar los grupos de trabajadores añade el contexto que la piedra monumental oculta."}
  ]},
  {title:"La fortaleza que llegó tarde",speaker:"Baltzar von Platen",keys:4,time:"6–8 min",minimum:35,action:"Revisar el siglo",obstacle:"El plan calculaba unos diez años. La obra terminó cuando ferrocarril, vapor y artillería habían cambiado la guerra.",goal:"Ordena noventa años y decide si Karlsborg fue solo un fracaso.",done:"El tiempo de construcción ya forma parte del veredicto.",questions:[
   {id:"d5m5k1",type:"order",visual:"d5ConstructionTimeline",title:"La obra que ocupó un siglo",scene:"El cálculo inicial fue mucho más corto que la realidad.",prompt:"Ordena los cuatro momentos.",items:[["a","1819 · comienzan las obras"],["b","Década de 1820 · se imagina una terminación rápida"],["c","Ferrocarril, vapor y artillería alteran el contexto"],["d","1909 · la fortaleza se considera terminada"]],answer:["a","b","c","d"],hint:"Karlsborg tardó aproximadamente noventa años.",interludeTitle:"¿NOVENTA AÑOS ES MUCHO?",interlude:`<p>En España se dice que algo «dura más que la obra de El Escorial», pero el monasterio se levantó principalmente entre <strong>1563 y 1584: 21 años</strong>.</p><p>La catedral de Burgos comenzó en 1221 y tuvo su consagración inicial en 1260, aunque sus ampliaciones continuaron durante siglos. La Sagrada Família comenzó en 1882 y sigue siendo una obra prolongada. Comparar fechas exige decidir qué significa «terminar».</p><p>Karlsborg, de 1819 a 1909, tardó unos <strong>noventa años</strong>: el mundo militar que la justificó cambió antes de acabarla.</p>`,success:"NOVENTA AÑOS ORDENADOS",explanation:"El retraso no es solo una anécdota: explica por qué el proyecto perdió parte de su función original."},
   {id:"d5m5k2",type:"single",visual:"d5Technology",title:"El enemigo aprende a llegar más lejos",scene:"El ferrocarril aceleró ejércitos; el vapor redujo la dependencia del viento; la artillería ganó alcance.",prompt:"¿Qué conclusión protege el expediente?",options:["Una defensa puede quedar anticuada mientras se construye","La tecnología no cambió entre 1819 y 1909","Las murallas se volvieron invulnerables"],answer:0,hint:"Compara el ritmo de la piedra con el de la tecnología.",success:"CONTEXTO ACTUALIZADO",explanation:"La estrategia de defensa central perdió peso a medida que cambiaron movilidad y potencia de fuego."},
   {id:"d5m5k3",type:"single",visual:"d5Verdict",title:"¿Fracaso o segunda vida?",scene:"Karlsborg nunca fue utilizada como capital en guerra, pero siguió siendo guarnición, almacén, comunidad y patrimonio.",prompt:"¿Qué veredicto conserva mejor las dos caras?",options:["El objetivo original perdió vigencia, pero el lugar adquirió otros usos","Fue un éxito perfecto exactamente como se planeó","No tuvo ninguna utilidad después de 1909"],answer:0,hint:"Evita un sí o no absoluto.",success:"VEREDICTO MATIZADO",explanation:"Un proyecto puede fallar en su misión original y, al mismo tiempo, tener larga vida militar, urbana y cultural."},
   {id:"d5m5k4",type:"single",visual:"d5Anachronism",title:"La ruta antigua sigue siendo una buena coartada",scene:"La organización ocultó una mercancía moderna dentro de un inventario histórico.",prompt:"¿Qué pista conservas para el Día 06?",options:["El contenedor textil con código de barras","La cámara de oro de 1819","La artillería de la fortaleza"],answer:0,hint:"La pista anacrónica sigue hacia Hökerum.",success:"LÍNEA MODERNA CONSERVADA",explanation:"Comprender la historia permite detectar lo que no pertenece a ella."}
  ]},
  {title:"El lago que parece un mar",speaker:"Baltzar von Platen",keys:4,time:"7–9 min",minimum:35,action:"Leer Vättern",obstacle:"La siguiente ruta bordea agua fría y profunda, pero el mapa la trata como un simple decorado.",goal:"Abre sus orillas, habitantes, peces y reglas de parada.",done:"Vättern vuelve a ser vía, hogar y ecosistema.",questions:[
   {id:"d5m6k1",type:"explore",visual:"d5VatternLife",title:"Cuatro orillas y dos salidas",scene:"Mucho antes del turismo, el lago conectaba asentamientos, pesca, agricultura, artesanía y comercio.",prompt:"Abre las ocho referencias del lago.",items:[["Karlsborg","Fortaleza y canal al oeste."],["Hjo","Puerto y ciudad de madera al oeste."],["Jönköping","Gran ciudad en el extremo sur."],["Vadstena","Ciudad histórica al este."],["Visingsö","Isla central habitada desde hace siglos."],["Población prehistórica","Caza, pesca y primeros asentamientos."],["Edad vikinga","Granjas, artesanía, navegación y redes regionales."],["Edad moderna","Agricultura, pesca, puertos, ferrerías y comercio."]],interludeTitle:"¿FUERON ROMANIZADOS?",interlude:`<p>Roma nunca conquistó Suecia ni administró Vättern. La región recibió objetos, monedas e influencias a través de redes comerciales europeas, pero no fue una provincia romana.</p><p>En época vikinga sus habitantes no vivían únicamente de saquear: cultivaban, criaban ganado, pescaban, producían objetos y comerciaban. El lago era una vía interior mucho antes de la carretera 49.</p>`,success:"LAGO HABITADO",explanation:"Vättern ha sido territorio de vida y circulación durante milenios; no empezó a existir como paisaje turístico."},
   {id:"d5m6k2",type:"single",visual:"d5Depth",title:"Largo, profundo, frío y claro",scene:"Vättern alcanza unos 128 metros de profundidad máxima y ronda los 40 de media. Su gran volumen tarda en calentarse.",prompt:"¿Qué precaución se deduce incluso en verano?",options:["Entrar con prudencia: el agua puede seguir muy fría","El lago siempre está templado por ser interior","La claridad garantiza poca profundidad"],answer:0,hint:"Claro no significa cálido ni somero.",interludeTitle:"PROFUNDIDAD Y MONSTRUOS",interlude:`<p>Vättern es más profundo que Vänern en su punto máximo, aunque Vänern tiene mucha más superficie. El lago Ness alcanza aproximadamente 230 metros: es menor en superficie que Vättern, pero bastante más profundo.</p><p>Escocia tiene a Nessie. Vättern no posee un monstruo famoso equivalente. Suecia reserva su gran criatura lacustre para <strong>Storsjöodjuret</strong>, la «bestia del gran lago», asociada a Storsjön, mucho más al norte.</p>`,success:"AGUA FRÍA LEÍDA",explanation:"La profundidad, el volumen y la renovación del agua ayudan a explicar su claridad y bajas temperaturas."},
   {id:"d5m6k3",type:"match",visual:"d5Fish",title:"No todos los peces viven en el mismo piso",scene:"La orilla, el agua abierta y la profundidad ofrecen ambientes distintos.",prompt:"Relaciona cada pez con una forma sencilla de reconocer su hábitat.",pairs:[["Lucio","cazador de orillas y vegetación"],["Perca","zonas litorales y aguas intermedias"],["Salmón de lago","agua abierta"],["Salvelino ártico","agua profunda, fría y bien oxigenada"]],hint:"El pez adaptado al frío busca la profundidad.",success:"VIDA BAJO EL AGUA",explanation:"Un lago profundo no es una sola habitación: sus temperaturas y hábitats cambian con la profundidad."},
   {id:"d5m6k4",type:"single",visual:"d5Road49",onsite:true,title:"La carretera no es un mirador continuo",scene:"La ruta 49 ofrece aperturas hacia Vättern, pero detenerse en el arcén convertiría una curiosidad en riesgo.",prompt:"¿Qué regla conserva la aventura?",options:["Parar solo en áreas señalizadas y seguras","Detenerse en cualquier curva con buena vista","Bajar mientras otra persona mantiene el coche en marcha"],answer:0,hint:"La fotografía no justifica una parada peligrosa.",success:"RUTA SEGURA",explanation:"El paisaje se disfruta desde las zonas autorizadas. La app no exige confirmar una vista desde un lugar inseguro."}
  ]},
  {title:"La ciudad que siguió contando",speaker:"Baltzar von Platen",keys:4,time:"7–9 min",minimum:35,action:"Abrir Hjo",obstacle:"El expediente trata Hjo como una postal inmóvil y ha borrado incendio, balneario, puerto y conservación.",goal:"Recupera la ciudad de madera y sus distintas vidas.",done:"Hjo vuelve a ser una ciudad que cambió sin perder su escala.",questions:[
   {id:"d5m7k1",type:"explore",visual:"d5HjoMap",title:"Puerto, río, plaza y parque",scene:"El plano se entiende mejor si primero se abre, sin adivinar.",prompt:"Abre las seis referencias de Hjo.",items:[["Puerto","Llegadas, comercio y S/S Trafik."],["Hjoån","Pequeño río que desemboca en Vättern."],["Plaza e iglesia","Centro urbano reconstruido tras el incendio."],["Stadsparken","Parque del antiguo balneario."],["Casas de madera","Escala y tejido urbano conservados."],["Vättern","La gran fachada oriental de la ciudad."]],success:"HJO ABIERTO",explanation:"Puerto, agua, parque y madera cuentan etapas complementarias, no atracciones aisladas."},
   {id:"d5m7k2",type:"single",visual:"d5HjoFire",title:"El incendio y las monedas fundidas",scene:"En 1794 un incendio destruyó buena parte de Hjo. El calor llegó a fundir monedas guardadas por una familia.",prompt:"¿Qué convirtió la catástrofe en una oportunidad urbana?",options:["La reconstrucción permitió reorganizar calles y edificios","La ciudad fue abandonada para siempre","Todas las casas actuales son medievales"],answer:0,hint:"Conservar madera no significa que todo sea de la misma fecha.",success:"1794 RECUPERADO",explanation:"El incendio explica por qué una ciudad antigua puede presentar una trama reconstruida y a la vez conservar identidad histórica."},
   {id:"d5m7k3",type:"single",visual:"d5WoodTowns",onsite:true,title:"Tres ciudades de madera",scene:"Hjo, Eksjö y Nora recibieron en 1990 un reconocimiento Europa Nostra por conservar sus entornos urbanos de madera.",prompt:"¿Qué debes comprobar al pasear?",options:["Cómo conviven casas antiguas, reparaciones y usos actuales","Que ninguna casa haya cambiado jamás","Que toda madera sea medieval"],answer:0,hint:"Conservar una ciudad viva exige adaptar sin borrar.",interludeTitle:"OTROS PATRIMONIOS SUECOS RELACIONADOS",interlude:`<p><strong>Gammelstad</strong>, cerca de Luleå, conserva una «ciudad-iglesia» de casas de madera usadas por población dispersa cuando acudía al culto y al mercado.</p><p>Las <strong>granjas decoradas de Hälsingland</strong> muestran cómo familias rurales expresaron prosperidad mediante grandes casas y pintura interior.</p><p><strong>Visby</strong> conserva una ciudad mercantil amurallada; <strong>Falun</strong> conecta ciudad, mina y el pigmento rojo que identifica tantas fachadas suecas.</p><p>No son iguales a Hjo. Sirven para ver que el patrimonio sueco incluye piedra, industria, paisaje y arquitectura cotidiana.</p>`,success:"PATRIMONIO VIVO",explanation:"Hjo no es valiosa por estar congelada, sino por conservar una estructura legible mientras continúa habitada."},
   {id:"d5m7k4",type:"explore",visual:"d5Spa",title:"Un balneario junto al lago",scene:"En el siglo XIX Hjo se transformó también en destino de baños, salud y ocio.",prompt:"Abre las cuatro piezas del antiguo balneario.",items:[["Agua","Baños y tratamientos asociados a la cultura termal."],["Villas","Alojamiento y pabellones para visitantes."],["Parque","Paseo, sociabilidad y aire libre."],["Ferrocarril y barcos","Mejoraron la llegada de viajeros."]],success:"CIUDAD BALNEARIA ABIERTA",explanation:"El parque actual procede de aquella cultura de salud y vacaciones, una nueva economía añadida al puerto y al comercio."}
  ]},
  {title:"Lo que no cabe en una cámara acorazada",speaker:"Saga",keys:3,time:"5–7 min",minimum:20,action:"Cerrar el inventario",obstacle:"El Estado guardó oro, armas y archivos. Hjo conserva dos patrimonios que no caben en ninguna caja.",goal:"Reconoce S/S Trafik, sigue a Estrid Ericson y activa una frase sueca.",done:"La línea moderna ya apunta hacia la región textil.",questions:[
   {id:"d5m8k1",type:"single",visual:"d5Trafik",onsite:true,title:"S/S Trafik, desde 1892",scene:"El vapor S/S Trafik conectó Hjo con puertos de Vättern y hoy continúa navegando como barco histórico.",prompt:"¿Qué demuestra mejor su conservación?",options:["Que una máquina puede seguir viva mediante uso, reparación y memoria","Que el barco nunca necesitó reparaciones","Que fue construido para la guerra de 1808"],answer:0,hint:"Patrimonio vivo no significa objeto intacto.",success:"BARCO RECONOCIDO",explanation:"S/S Trafik permite leer el tiempo del vapor, el puerto y la movilidad del lago desde un objeto todavía operativo."},
   {id:"d5m8k2",type:"order",visual:"d5Estrid",title:"Estrid antes de Svenskt Tenn",scene:"Estrid Ericson nació cerca de Hjo y llevó una sensibilidad artesanal hasta una firma internacional de diseño.",prompt:"Ordena la ruta de su historia.",items:[["a","1894 · nace en Öregrund y crece vinculada a la zona de Hjo"],["b","Se forma y trabaja con artesanía y metal"],["c","1924 · funda Svenskt Tenn en Estocolmo"],["d","Colabora con Josef Frank y construye un lenguaje de diseño reconocido"]],answer:["a","b","c","d"],hint:"Primero persona y oficio; después empresa y colaboración.",success:"ESTRID RECUPERADA",explanation:"El diseño no apareció de la nada: unió formación artesanal, empresa y colaboraciones. La pista textil del archivo ya tiene un contexto sueco."},
   {id:"d5m8k3",type:"speech",visual:"d5Voice",title:"Sueco para pedir un helado",scene:"Hjo es una buena parada de fika, bollería o helado. Saga esconde la salida detrás de una petición sencilla.",prompt:"¿Cuándo usarías «En glass, tack»?",options:["Cuando pides un helado, por favor","Cuando buscas la fortaleza","Cuando preguntas si el lago está frío"],answer:0,word:"En glass, tack.",meaning:"Un helado, por favor.",tip:"glass = helado · tack = gracias / por favor en una petición",speech:"En glass, tack.",success:"CLAVE DE VOZ ACTIVADA",explanation:"En sueco, tack también suaviza una petición. Puedes escuchar el modelo, grabarte y comparar sin nota automática.",finalSignal:true}
  ]}
 ]
};
