window.DAY6_DATA={
 meta:{day:"06",store:"codigo-gripsholm-day06-v1",place:"GOTEMBURGO",title:"La puerta occidental",landing:"El plano de 1621 conserva una salida que no debería existir. Alguien intenta borrarla antes de que llegues al Göta älv.",openingTime:"Primera apertura recomendada: 15–20 minutos. Puedes continuar mientras recorres la ciudad.",objective:"RECUPERAR LA PUERTA OCCIDENTAL",objectiveCopy:"Reconstruirás la fundación, la guerra europea, Haga, el viaje del té y el puerto actual para descubrir qué carga siguió a los padres de Saga.",routeCount:8,previousStore:"codigo-gripsholm-day05-v1",previousDay:"05",fragment:"7 de 11"},
 routePlaces:[
  ["Göta älv","El gran río que lleva el agua de Vänern hasta Kattegat y explica por qué Suecia necesitaba esta salida occidental."],
  ["Centro fortificado","Canales, calles y antigua línea de murallas de la ciudad fundada en 1621."],
  ["Haga","Barrio desarrollado fuera de las murallas, reconocible por sus casas y su vida de café."],
  ["Skansen Kronan","Fortaleza elevada con 23 cañones que nunca tuvo que disparar contra un atacante."],
  ["Saluhallen","Mercado cubierto: una parada para comprender comida cotidiana, dagens rätt y fika."],
  ["Feskekörka","Parece una iglesia, pero nació en 1874 como mercado de pescado. Su nombre significa «iglesia del pescado»."],
  ["Jardín Botánico","Jardín, investigación y conservación: una de las herencias del jubileo de 1923."],
  ["Liseberg","Parque que debía acompañar una exposición temporal y terminó quedándose en la ciudad."]
 ],
 prologue:[
  {k:"SAGA · CANAL ESCRITO",title:"La tela era una envoltura. Dentro había barro.",image:"saga-transmision-inicial.png",alt:"Saga abre la transmisión del Día 06",html:`<p>La marca de tres coronas del Día 05 no pertenecía a una fábrica. Era la señal de un plano oculto dentro de un envío moderno.</p><p>Debajo he encontrado una copia incompleta de Gotemburgo en 1621. Alguien ha borrado la salida occidental y ha añadido un nombre: <strong>Geertruyd van Dijk</strong>.</p><p class="lead">Si recuperas la ciudad que ella estaba dibujando, podremos seguir el contenedor sin que la organización detecte la ruta.</p>`,action:"Abrir el plano"},
  {k:"PERSONAJE DEL DÍA · RECREACIÓN",title:"Geertruyd copia una ciudad que todavía no existe.",image:"geertruyd-van-dijk-gotemburgo-v1.png",alt:"Recreación realista de Geertruyd en las obras de Gotemburgo de 1621",html:`<p>Geertruyd tiene dieciocho años. Su madre procede de Nya Lödöse y su padre trabaja con especialistas neerlandeses en canales y drenaje. Ella copia medidas, compuertas y nombres.</p><p><strong>Geertruyd es ficticia.</strong> El traslado de habitantes, el barro, los especialistas extranjeros y el consejo internacional son reales. Su mirada nos permite recorrerlos sin atribuirle un documento que nunca existió.</p><div class="story-signal"><b>SEÑAL INTERCEPTADA</b><span>Una lámina ha desaparecido antes de cerrar las compuertas.</span></div>`,action:"Seguir a Geertruyd"},
  {k:"MAPA DE ORIENTACIÓN",title:"Ocho señales antes de entrar.",routeMap:true,html:`<p>Abre todos los puntos. Aquí no hay nada que adivinar: primero necesitas saber dónde sucederá la misión.</p>`,action:"Activar la ruta"},
  {k:"FUNCIÓN DEL JUGADOR",title:"Hoy no conquistas una ciudad. Impides que pierda su salida.",html:`<div class="role-list"><span>01 · SIGUE EL AGUA</span><span>02 · RECONSTRUYE 1621</span><span>03 · ABRE EUROPA</span><span>04 · LOCALIZA LA CARGA</span></div><p>Las preguntas fijan ideas sencillas. Los desplegables guardan el contexto completo. Ninguna visita es obligatoria para completar el día.</p>`,action:"Activar el Día 06"}
 ],
 missions:[
  {title:"La puerta occidental",speaker:"Geertruyd",keys:3,time:"5–7 min",minimum:30,action:"Seguir el río",obstacle:"El plano termina en tierra y ha borrado la conexión entre Vänern, el Göta älv y el mar.",goal:"Abre la ruta del agua y recupera las primeras referencias de Gotemburgo.",done:"La salida occidental vuelve a comunicar el interior con Kattegat.",questions:[
   {id:"d6m1k1",type:"explore",visual:"d6WestMap",title:"Un lago, un río y una salida",scene:"El mapa ha separado tres partes de la misma vía de agua.",prompt:"Abre las cuatro señales desde el interior hasta el mar.",items:[["Vänern","El mayor lago de Suecia."],["Göta älv","Río que sale de Vänern y atraviesa Trollhättan."],["Gotemburgo","Ciudad situada cerca de su desembocadura."],["Kattegat","Salida hacia el mar del Norte y el Atlántico."]],success:"CORREDOR DE AGUA ABIERTO",explanation:"El Göta älv convirtió la desembocadura en una puerta entre el interior sueco y el comercio occidental."},
   {id:"d6m1k2",type:"single",visual:"d6CityRoute",title:"La costa no termina en la ciudad",scene:"El plano afirma que el puerto es un punto aislado.",prompt:"¿Qué corrección recupera la geografía real?",options:["El puerto forma parte de un río, una costa y una red de islas","Gotemburgo está en el centro de un lago cerrado","El río nace dentro del mercado de pescado"],answer:0,hint:"Sigue el agua hacia el oeste.",success:"ESCALA RECUPERADA",explanation:"Gotemburgo ocupa una desembocadura protegida, con islas y accesos que conducen a Kattegat. El puerto es un sistema amplio, no un punto."},
   {id:"d6m1k3",type:"match",visual:"d6Fesk",title:"La iglesia que nunca fue iglesia",scene:"Una silueta con arcos apuntados aparece junto al antiguo foso. Su apodo guarda la función en dos piezas del habla local.",prompt:"Une cada pieza de Feskekörka con su significado.",pairs:[["FESKE","pescado"],["KÖRKA","iglesia"]],hint:"Se parece mucho al sueco estándar fisk y kyrka.",interludeTitle:"UNA IGLESIA HECHA DE PALABRAS",interlude:`<p><strong>Feskekörka</strong> significa literalmente «iglesia del pescado» en el habla de Gotemburgo. La forma sueca estándar sería <em>Fiskkyrkan</em>.</p><p>Victor von Gegerfelt combinó arcos neogóticos y referencias a iglesias de madera nórdicas para crear una gran sala sin columnas que molestasen a los puestos. Desde su apertura en <strong>1874</strong> fue una lonja y mercado, nunca un templo. Tras su restauración sigue ligada a la gastronomía marina.</p>`,success:"NOMBRE DESCIFRADO",explanation:"Feske aporta el pescado y körka la iglesia. El nombre describe su aspecto y su función comercial: parece un templo, pero nació como mercado de pescado."}
  ]},
  {title:"El nieto del rebelde",speaker:"Geertruyd",keys:4,time:"7–9 min",minimum:40,action:"Abrir 1621",obstacle:"El expediente llama a Gustav II Adolf «primer Vasa» y dibuja fronteras actuales.",goal:"Recupera el corredor vulnerable, la dinastía, el nombre de la ciudad y sus símbolos.",done:"La fundación vuelve a conectar Stortorget con la costa occidental.",questions:[
   {id:"d6m2k1",type:"single",visual:"d6Coast1621",title:"Suecia casi no cabe",scene:"En 1621 Halland pertenecía a Dinamarca y Bohuslän a Noruega, unida al monarca danés.",prompt:"¿Qué franja necesitaba asegurar Suecia?",options:["La desembocadura del Göta älv","Toda la costa noruega","La isla de Åland como salida al Atlántico"],answer:0,hint:"Busca la línea entre Vänern y Kattegat.",success:"CORREDOR DE 1621 RECUPERADO",explanation:"Gotemburgo nació en una salida sueca estrecha entre territorios del rey danés. Halland y Bohuslän pasaron a Suecia más tarde."},
   {id:"d6m2k2",type:"single",visual:"d6KingFinger",onsite:true,title:"El dedo del rey",scene:"La estatua de Gustav II Adolf señala el suelo de la plaza.",prompt:"¿Qué conserva realmente ese gesto?",options:["Una leyenda fundacional representada siglos después","La grabación exacta de una frase de 1619","El lugar donde nació Gustav Vasa"],answer:0,hint:"La estatua se instaló en 1854.",interludeTitle:"¿DIJO «AQUÍ SE CONSTRUIRÁ LA CIUDAD»?",interlude:`<p>La tradición dice que el rey señaló el lugar y pronunció esa frase. No existe un acta que conserve el momento palabra por palabra.</p><p>La estatua, levantada en 1854, convirtió una decisión política compleja en una escena inolvidable. Antes estuvieron Lödöse, Nya Lödöse y un primer Gotemburgo de Karl IX destruido por los daneses en 1611.</p>`,success:"MITO BIEN ETIQUETADO",explanation:"La estatua cuenta cómo la ciudad quiso recordar su fundación; no es una fotografía del gesto ni una prueba de la frase literal."},
   {id:"d6m2k3",type:"match",visual:"d6Dynasty",title:"Cien años después de Stortorget",scene:"El fundador no es Gustav Vasa, aunque pertenece a su familia.",prompt:"Relaciona cada nombre con su posición.",pairs:[["Gustav Vasa","rey desde 1523 y abuelo"],["Karl IX","hijo de Gustav Vasa y padre"],["Gustav II Adolf","rey fundador de Gotemburgo en 1621"]],hint:"Empieza por el hombre que escapó tras 1520.",success:"DINASTÍA RECONSTRUIDA",explanation:"La ruta avanza desde el Baño de Sangre hasta el nieto de Gustav Vasa. Entre medias hubo sucesiones y conflictos, no una línea automática."},
   {id:"d6m2k4",type:"single",visual:"d6Coat",title:"El león que mira al lado equivocado",scene:"El escudo combina el antiguo león de los Folkunga —interpretado entonces como el Göta Lejon—, una espada y el pequeño escudo sueco de las tres coronas.",prompt:"¿Qué afirmación lo describe mejor?",options:["Su orientación heráldica es inusual y quedó conservada","Es un error que la ciudad todavía está obligada a reparar","Mira hacia atrás porque la heráldica lo identifica como cobarde"],answer:0,hint:"Una orientación excepcional no es lo mismo que un defecto pendiente ni tiene un significado moral automático.",interludeTitle:"POR QUÉ PARECE MIRAR AL REVÉS",interlude:`<p><strong>Primero, cambia tu punto de vista.</strong> En heráldica, derecha e izquierda son las de quien lleva el escudo. La diestra heráldica queda a la izquierda de quien lo observa. Esa es la dirección habitual de los animales.</p><p>El león de Gotemburgo mira hacia la <strong>siniestra heráldica</strong>: hacia tu derecha. Esa posición poco común aparece en los sellos utilizados por la ciudad desde el siglo XVII, aunque a lo largo del tiempo también se dibujaron versiones orientadas al lado contrario.</p><p><strong>¿Fue un error del grabador?</strong> Es una explicación repetida y posible, pero el origen exacto es discutido. No hay base para afirmar como hecho que el león sea cobarde o huya del enemigo.</p><p>En el siglo XX, la autoridad heráldica propuso una versión orientada de la forma habitual. Gotemburgo defendió la imagen que llevaba usando durante más de tres siglos. En <strong>1952</strong>, el rey Gustaf VI Adolf aprobó oficialmente el modelo tradicional con el león mirando hacia tu derecha.</p><p>La espada y el escudo de las tres coronas completan el mensaje: el león debía <strong>proteger Suecia por el oeste</strong>, frente a unos territorios daneses que entonces rodeaban el estrecho corredor de Gotemburgo.</p>`,success:"ESCUDO ABIERTO",explanation:"No es un fallo pendiente: es una excepción histórica oficial. Lo seguro es la orientación poco habitual y su aprobación en 1952; la supuesta equivocación inicial sigue siendo una explicación discutida."}
  ]},
  {title:"Una ciudad escrita sobre barro",speaker:"Geertruyd",keys:4,time:"7–9 min",minimum:35,action:"Levantar la primera capa",obstacle:"La organización afirma que doce neerlandeses construyeron una ciudad vacía.",goal:"Recupera Nya Lödöse, el traslado de población y la ingeniería bajo los canales.",done:"El barro vuelve a mostrar personas, pilotes y trabajos cotidianos.",questions:[
   {id:"d6m3k1",type:"single",visual:"d6OldCities",title:"La ciudad anterior",scene:"Nya Lödöse aparece borrada río arriba.",prompt:"¿Qué relación tuvo con Gotemburgo?",options:["Aportó habitantes, redes y experiencia a la nueva ciudad","Fue una colonia romana situada en Dinamarca","Se construyó después de Gotemburgo"],answer:0,hint:"Fue fundada en 1473.",success:"NYA LÖDÖSE RESTITUIDA",explanation:"Fundar una ciudad no significa empezar con personas nuevas. Muchos habitantes fueron trasladados y llevaron su vida comercial y comunitaria."},
   {id:"d6m3k2",type:"multi",visual:"d6Move",title:"Lo que no cabe en una carreta",scene:"El traslado solo enumera madera y herramientas.",prompt:"Recupera las tres cargas invisibles.",options:["Redes comerciales","Conocimientos de oficios","Memoria y vínculos comunitarios","Autopistas desmontables","Electricidad almacenada"],answer:[0,1,2],hint:"Busca cosas que una comunidad conserva aunque cambie de casa.",success:"VIDAS TRASLADADAS",explanation:"Los decretos trasladan privilegios; las personas trasladan habilidades, relaciones y recuerdos."},
   {id:"d6m3k3",type:"single",visual:"d6Council",title:"¿Una ciudad neerlandesa?",scene:"Un expediente dice que Gotemburgo fue construida exclusivamente por holandeses.",prompt:"Elige la corrección precisa.",options:["Ciudad sueca fundada por decisión real con población y conocimientos internacionales","Colonia neerlandesa independiente","Ciudad sin habitantes suecos hasta el siglo XIX"],answer:0,hint:"El primer consejo tenía suecos, neerlandeses, alemanes y escoceses.",success:"AUTORÍA CORREGIDA",explanation:"La experiencia neerlandesa en canales y fortificaciones fue decisiva, pero no explica por sí sola toda la población ni todo el trabajo."},
   {id:"d6m3k4",type:"match",visual:"d6Clay",title:"La ciudad bajo los pies",scene:"Canales y pilotes no eran decoración: respondían al terreno húmedo y arcilloso.",prompt:"Relaciona cada solución con su trabajo.",pairs:[["Pilotes de madera","transmitir el peso hacia capas más firmes"],["Canales","drenar y mover agua"],["Foso y murallas","dificultar un ataque"],["Muelles","acercar mercancías y almacenes"]],hint:"El suelo explica las dos primeras.",interludeTitle:"ÁMSTERDAM, 1613 · GOTEMBURGO, 1621",interlude:`<p>Ámsterdam aparece documentada ya en <strong>1275</strong>. En <strong>1613</strong> inició la gran ampliación de su anillo de canales. Cuando Gotemburgo fue fundada ocho años después, los ingenieros neerlandeses traían una experiencia muy reciente en ordenar agua, comercio y construcción sobre terreno blando.</p><p>No copiaron una postal. Adaptaron canales, drenaje, pilotes, foso y muelles a la desembocadura del Göta älv. Los canales también recibieron suciedad y residuos antes del saneamiento moderno: una solución útil podía crear problemas nuevos.</p>`,success:"INGENIERÍA RECUPERADA",explanation:"El agua hizo posible la ciudad y creó problemas nuevos. Los pilotes y canales permanecen ocultos bajo la postal urbana."}
  ]},
  {title:"Europa entra en el plano",speaker:"Saga",keys:4,time:"8–10 min",minimum:40,action:"Abrir la guerra",obstacle:"El mapa reduce treinta años de guerra a católicos contra protestantes y borra a España.",goal:"Sitúa el conflicto, sus intereses y la entrada de Suecia.",done:"La ciudad ya forma parte de un sistema europeo, no de una historia aislada.",questions:[
   {id:"d6m4k1",type:"explore",visual:"d6Europe30",title:"Una guerra que empezó lejos del mar",scene:"En 1618 una rebelión en Bohemia abrió un conflicto que se extendió por Europa.",prompt:"Abre las seis piezas del mapa.",items:[["Bohemia · 1618","Rebelión contra los Habsburgo."],["Dinamarca · 1625","Intervención de Cristián IV."],["Suecia · 1630","Desembarco de Gustav II Adolf en el Imperio."],["Francia","Católica, pero enemiga política de los Habsburgo."],["Monarquía Hispánica","Rama Habsburgo con territorios y rutas europeas."],["Westfalia · 1648","Conjunto de tratados que cerró el conflicto principal."]],success:"EUROPA ABIERTA",explanation:"La religión importó, pero también dinastías, territorios, rutas comerciales y equilibrio de poder."},
   {id:"d6m4k2",type:"order",visual:"d6WarTimeline",title:"Treinta años en cinco movimientos",scene:"El expediente ha colocado la paz antes del desembarco sueco.",prompt:"Repara la secuencia.",items:[["a","1618 · rebelión de Bohemia"],["b","1625 · intervención danesa"],["c","1630 · entrada directa de Suecia"],["d","1632 · Gustav II Adolf muere en Lützen"],["e","1648 · Paz de Westfalia"]],answer:["a","b","c","d","e"],hint:"La muerte del rey no terminó la guerra.",interludeTitle:"¿POR QUÉ SUECIA ENTRÓ EN 1630?",interlude:`<p>El rey era <strong>Gustav II Adolf</strong>, fundador de Gotemburgo. Suecia llevaba años guerreando con Polonia-Lituania; la tregua de Altmark de <strong>1629</strong> le permitió liberar tropas para intervenir en Alemania.</p><p>Quería defender aliados protestantes, impedir que los Habsburgo dominaran la costa sur del Báltico y proteger la seguridad y el comercio suecos. Desembarcó en Pomerania en 1630. No fue solo una cruzada religiosa: religión, puertos, dinastías y equilibrio de poder viajaban juntos.</p>`,success:"CRONOLOGÍA REPARADA",explanation:"Suecia continuó siendo una potencia militar tras 1632 y los acuerdos no llegaron hasta 1648."},
   {id:"d6m4k3",type:"single",visual:"d6WarActors",title:"La católica que ayuda a protestantes",scene:"Francia apoya a enemigos protestantes de los Habsburgo.",prompt:"¿Qué demuestra esta decisión?",options:["La política dinástica podía pesar más que la religión compartida","Francia se volvió protestante en 1630","Todos los católicos combatieron siempre juntos"],answer:0,hint:"Richelieu quería limitar a los Habsburgo.",interludeTitle:"TRES CORONAS, INTERESES DISTINTOS",interlude:`<p>En 1630 reinaban <strong>Gustav II Adolf</strong> en Suecia, <strong>Luis XIII</strong> en Francia y <strong>Felipe IV</strong> en la Monarquía Hispánica. El cardenal Richelieu, principal ministro francés, temía que Francia quedara rodeada por las ramas española y austríaca de los Habsburgo.</p><p>Un siglo antes, el católico <strong>Francisco I de Francia</strong> ya había buscado la alianza de <strong>Solimán el Magnífico</strong>, sultán otomano, contra Carlos V. Apoyar a alguien de otra religión para frenar a un rival dinástico no nació en la Guerra de los Treinta Años.</p>`,success:"INTERÉS POLÍTICO RECUPERADO",explanation:"Las etiquetas religiosas no bastan para explicar alianzas. Francia temía quedar rodeada por ramas de una misma dinastía."},
   {id:"d6m4k4",type:"single",visual:"d6Spain30",title:"España también estaba allí",scene:"En 1634 tropas de la Monarquía Hispánica de Felipe IV y del emperador vencieron en Nördlingen a fuerzas suecas y protestantes aliadas.",prompt:"¿Qué conexión debemos conservar?",options:["Suecia y España participaron en frentes relacionados del mismo conflicto europeo","España invadió Estocolmo en 1634","Gotemburgo pertenecía a la Monarquía Hispánica"],answer:0,hint:"Conexión no significa invasión directa de Suecia.",success:"ESPAÑA DEVUELTA AL MAPA",explanation:"La Guerra de los Treinta Años enlazó decisiones tomadas desde el Madrid de Felipe IV, la Viena imperial, el París de Luis XIII y Richelieu y el Estocolmo de Gustav II Adolf, aunque sus ejércitos no combatieran siempre entre sí."}
  ]},
  {title:"Fuera de las murallas",speaker:"Geertruyd",keys:4,time:"7–9 min",minimum:35,action:"Cruzar hacia Haga",obstacle:"El plano trata Haga como un decorado de cafés y Skansen Kronan como una ruina sin función.",goal:"Lee las casas, la fortaleza, el fika y una frase útil.",done:"Haga vuelve a ser barrio, defensa y costumbre viva.",questions:[
   {id:"d6m5k1",type:"single",visual:"d6Haga",onsite:true,title:"Piedra abajo, madera arriba",scene:"Las landshövdingehus resolvieron una norma contra incendios sin renunciar a tres plantas.",prompt:"¿Cómo están construidas?",options:["Planta baja de piedra y dos pisos superiores de madera","Tres pisos completamente de paja","Planta baja de madera y torre de hormigón"],answer:0,hint:"Mira el cambio de material sobre la primera planta.",success:"CASA LEÍDA",explanation:"La combinación se convirtió en una arquitectura característica de Gotemburgo entre finales del XIX y el XX."},
   {id:"d6m5k2",type:"single",visual:"d6Skansen",onsite:true,title:"Veintitrés cañones que nunca dispararon",scene:"Skansen Kronan dominaba la aproximación terrestre y hoy funciona como mirador.",prompt:"¿Qué paradoja conserva?",options:["Estaba preparada para combatir, pero nunca fue atacada","Fue construida como cafetería","Sus cañones hundieron el Vasa"],answer:0,hint:"Una defensa puede influir sin entrar en combate.",success:"FORTALEZA ABIERTA",explanation:"La corona de piedra recuerda la ciudad fortificada aunque el enemigo nunca obligara a usar sus cañones."},
   {id:"d6m5k3",type:"single",visual:"d6Bun",title:"Una pausa que también es institución",scene:"En Haga aparece un bollo de canela de tamaño descomunal.",prompt:"¿Qué define mejor fika?",options:["Una pausa social para café y algo de comer","El nombre sueco de la cena","Una competición para comer bollos deprisa"],answer:0,hint:"Puede ocurrir con familia, amistades o compañeros de trabajo.",interludeTitle:"NO ES SOLO BEBER CAFÉ",interlude:`<p>Fika puede ser una pausa acordada, una invitación o una forma cotidiana de conversar. El café suele acompañarse de kanelbulle u otra pieza dulce.</p><p>Se parece a «tomar un café» en España, pero la palabra sueca convierte la pausa completa en una práctica reconocible. El 4 de octubre es el Día del Bollo de Canela.</p>`,success:"PAUSA RECUPERADA",explanation:"La comida importa, pero la idea central es parar y compartir tiempo."},
   {id:"d6m5k4",type:"speech",visual:"d6Voice",title:"Dos bollos para compartir",scene:"Saga necesita una frase que funcione en el café sin exigir pronunciación perfecta.",prompt:"¿Cuándo usarías «Två kanelbullar, tack»?",options:["Al pedir dos bollos de canela","Al buscar Skansen Kronan","Al preguntar por el puerto"],answer:0,word:"Två kanelbullar, tack.",meaning:"Dos bollos de canela, por favor.",tip:"två = dos · kanelbullar = bollos de canela · tack = gracias / por favor",speech:"Två kanelbullar, tack.",success:"CLAVE DE VOZ ACTIVADA",explanation:"Puedes escuchar, grabarte y comparar. La app no pone nota ni bloquea el avance por el acento."}
  ]},
  {title:"El té que Gran Bretaña ya compraba",speaker:"Saga",keys:4,time:"8–10 min",minimum:40,action:"Abrir la bodega",obstacle:"Cantón aparece en Europa y el té viaja directamente a Londres con un sello sueco imposible.",goal:"Recupera la carga, el viaje oceánico y la red legal y clandestina.",done:"El té vuelve a conectar China, Gotemburgo, Países Bajos y Gran Bretaña.",questions:[
   {id:"d6m6k1",type:"multi",visual:"d6TeaCargo",title:"La carga que no debía oler",scene:"La Compañía Sueca de las Indias Orientales, fundada en 1731, regresa de Cantón.",prompt:"Selecciona tres mercancías características.",options:["Té","Porcelana","Seda y especias","Petróleo","Automóviles Volvo"],answer:[0,1,2],hint:"Busca productos asiáticos de gran valor en el siglo XVIII.",success:"BODEGA RECUPERADA",explanation:"El té acabó dominando el negocio. La porcelana no absorbía olores y ayudaba como carga pesada en la bodega."},
   {id:"d6m6k2",type:"explore",visual:"d6TeaWorld",title:"Dieciocho meses dentro de una línea",scene:"Una recta ha borrado océanos, vientos y estrechos.",prompt:"Abre las seis etapas de ida; el mapa mostrará después el regreso del té.",items:[["Gotemburgo","Preparación, tripulación y salida."],["Atlántico","Larga navegación hacia el sur."],["Cabo de Buena Esperanza","Paso entre Atlántico e Índico."],["Océano Índico","Vientos, escalas y meses de mar."],["Estrecho de Sonda","Paso entre Java y Sumatra."],["Cantón","Compra bajo reglas comerciales chinas."]],success:"RUTA OCEÁNICA ABIERTA",explanation:"La vuelta transportaba té, porcelana y seda desde Cantón hasta Gotemburgo. La primera expedición operó durante alrededor de dieciocho meses."},
   {id:"d6m6k3",type:"single",visual:"d6TeaEurope",title:"Inglaterra ya tenía té",scene:"El expediente pregunta por qué los británicos no lo importaban, pero sí lo hacían.",prompt:"¿Qué hacía rentable otra ruta?",options:["Los impuestos británicos elevados favorecían reexportación y contrabando","Gran Bretaña desconocía el té","Los barcos ingleses no podían navegar por el Atlántico"],answer:0,hint:"El problema era el precio fiscal, no la falta de barcos.",interludeTitle:"LEGAL EN GOTEMBURGO, CLANDESTINO DESPUÉS",interlude:`<p>La compañía sueca vendía legalmente el cargamento en subasta. Gran parte se reexportaba hacia puertos neerlandeses y desde allí podía entrar de contrabando en Gran Bretaña. También existió tráfico clandestino directo con Escocia.</p><p>Así, un producto chino podía ser comprado por una compañía sueca, subastado en Gotemburgo, revendido en Europa y bebido en una casa británica.</p>`,success:"ÚLTIMO TRAMO RESTITUIDO",explanation:"Inglaterra importaba té directamente. La ruta sueca competía aprovechando impuestos y diferencias legales."},
   {id:"d6m6k4",type:"single",visual:"d6TeaTax",title:"Cuando bajar el impuesto reduce el delito",scene:"En 1784 Gran Bretaña redujo fuertemente el impuesto del té.",prompt:"¿Qué consecuencia era lógica?",options:["El contrabando perdió parte de su ventaja","El té desapareció de Gran Bretaña","Suecia conquistó Londres"],answer:0,hint:"Si el producto legal se abarata, arriesgarse compensa menos.",success:"CAUSA Y EFECTO RECUPERADOS",explanation:"La reforma fiscal redujo el margen del té clandestino y debilitó una parte esencial del negocio reexportador sueco."}
  ]},
  {title:"La fiesta que dejó dos lugares",speaker:"Saga",keys:3,time:"5–7 min",minimum:25,action:"Abrir 1923",obstacle:"Jardín Botánico y Liseberg aparecen como alternativas incompatibles.",goal:"Abre ambos lugares y separa sus historias de una leyenda de conejos.",done:"Ciencia, ocio y cultura popular vuelven a compartir el mismo aniversario.",questions:[
   {id:"d6m7k1",type:"explore",visual:"d6Garden",title:"Un jardín que también investiga",scene:"El Jardín Botánico no es solo decoración.",prompt:"Abre sus cuatro pasaportes.",items:[["Origen","Plantas de numerosos países."],["Nombre científico","Una identificación compartida internacionalmente."],["Adaptación","Cómo sobrevive una planta en su ambiente."],["Conservación","Colecciones con información y valor científico."]],success:"JARDÍN ABIERTO",explanation:"El jardín combina paseo, cultivo, investigación y conservación desde su inauguración en 1923."},
   {id:"d6m7k2",type:"single",visual:"d6Liseberg",title:"Los conejos llegaron en un ovni",scene:"Fuera del expediente histórico aparece una afirmación de las mascotas de Liseberg.",prompt:"Verdadero o falso: los conejos verdes llegaron realmente del espacio.",options:["Falso en la realidad; verdadero dentro de su cuento","Verdadero y confirmado por astrónomos","Falso porque Liseberg no tiene mascotas"],answer:0,hint:"La tarjeta está marcada como cultura popular, no como documento histórico.",interludeTitle:"LA MADRIGUERA OFICIAL",interlude:`<p>La ficción cuenta que unos conejos verdes llegaron en un ovni durante la década de 1980, convirtieron su platillo en una atracción y vivieron bajo el parque.</p><p>Son mascotas. El Museo de Gotemburgo recoge su relato como cultura popular de la ciudad, no como acontecimiento real.</p>`,success:"FICCIÓN BIEN ETIQUETADA",explanation:"Una historia inventada también puede formar parte de la identidad de un lugar si la app deja claro qué clase de relato es."},
   {id:"d6m7k3",type:"single",visual:"d6Jubilee",title:"El año común",scene:"El parque y el jardín comparten una cerradura de cuatro cifras.",prompt:"¿Qué año abre las dos fichas?",options:["1923","1621","2023"],answer:0,hint:"La gran exposición se celebró dos años después del tricentenario de 1921.",success:"1923 RECUPERADO",explanation:"La celebración temporal dejó instituciones permanentes de ciencia y ocio."}
  ]},
  {title:"El puerto que cambió de carga",speaker:"Saga",keys:4,time:"7–9 min",minimum:30,action:"Abrir las terminales",obstacle:"El plano moderno reduce el puerto a contenedores y ha escondido un envío entre cifras europeas.",goal:"Recupera sus cargas actuales, sitúa los grandes puertos y localiza la salida del Día 07.",done:"La puerta occidental vuelve a mostrar qué mueve y hacia dónde.",questions:[
   {id:"d6m8k1",type:"match",visual:"d6PortCargo",title:"Cuatro terminales, cuatro trabajos",scene:"El puerto actual no mueve una única clase de mercancía.",prompt:"Relaciona cada carga con su sistema.",pairs:[["Contenedores","cajas normalizadas entre barco, tren y camión"],["Ro-Ro y vehículos","carga que entra y sale rodando"],["Productos forestales","papel, pasta y madera de la industria sueca"],["Energía y graneles","productos líquidos o sin contenedor"]],hint:"Ro-Ro significa roll-on/roll-off.",success:"PUERTO ACTUAL ABIERTO",explanation:"Gotemburgo conecta industria, ferrocarril, carretera y mar. Su función actual va mucho más allá del té."},
   {id:"d6m8k2",type:"single",visual:"d6PortScale",title:"Grande en Suecia, menor en Europa",scene:"El expediente compara puntos dibujados con tamaños engañosos.",prompt:"¿Qué lectura es correcta?",options:["Gotemburgo domina el comercio contenerizado sueco, pero mueve menos TEU que los gigantes europeos","Gotemburgo supera a Róterdam en contenedores","Valencia está en el mar Báltico"],answer:0,hint:"Compara las barras, no el tamaño de los países.",success:"ESCALA PORTUARIA CORREGIDA",explanation:"En 2025 Gotemburgo movió unos 934.000 TEU; Valencia 5,66 millones, Amberes-Brujas 13,53 y Róterdam 14,2 millones."},
   {id:"d6m8k3",type:"explore",visual:"d6PortsEurope",title:"Cuatro puertos dentro de Europa",scene:"Antes de comparar hay que localizar cada fachada marítima.",prompt:"Abre los cuatro puertos principales.",items:[["Gotemburgo · Suecia","Kattegat y acceso al mar del Norte."],["Róterdam · Países Bajos","Delta Rin-Mosa y mar del Norte."],["Amberes-Brujas · Bélgica","Sistema con Amberes interior y Zeebrugge costero."],["Valencia · España","Fachada mediterránea de la península ibérica."]],success:"PUERTOS LOCALIZADOS",explanation:"El mapa mantiene países, costas y posiciones reales; las cifras se comparan después en barras separadas."},
   {id:"d6m8k4",type:"speech",visual:"d6Final",title:"La última carga",scene:"El registro oculto no contiene té. Contiene una pregunta de puerto y una matrícula de salida.",prompt:"¿Cuándo usarías «Var ligger hamnen?»",options:["Cuando preguntas dónde está el puerto","Cuando pides un bollo","Cuando preguntas la edad del rey"],answer:0,word:"Var ligger hamnen?",meaning:"¿Dónde está el puerto?",tip:"var = dónde · ligger = está · hamnen = el puerto",speech:"Var ligger hamnen?",success:"PUERTA OCCIDENTAL RECUPERADA",explanation:"El registro final conecta el puerto moderno con una salida hacia la costa del Día 07.",finalSignal:true}
  ]}
 ]
};
