/* Día 07 · Fuente editorial única: 03_Guiones/V8/Documento_Base_Guion_completo_Codigo_Gripsholm_dias_07_a_10_V8.docx.
   Liv Berg es un personaje ficticio contemporáneo: sus palabras son recreación narrativa. */
window.DAY1_DATA={
  meta:{day:"07",store:"codigo-gripsholm-v8-day07",contentVersion:"v8-day7",place:"ÅSUNDEN · ULRICEHAMN · KOMOSSE",title:"El agua no es un atajo",landing:"La Sombra ha dibujado una línea rápida que confunde un lago, una batalla y una turbera.",badge:"Ruta terrestre",objective:"DEVOLVER UNA REGLA A CADA PAISAJE",objectiveCopy:"Corregiremos una ruta falsa. El agua puede conectar, guardar la historia o exigir protección.",evidenceCopy:"Cada misión corrige una parte de la ruta terrestre.",fine:"Liv Berg es un personaje ficticio. Actividades junto al lago y senderos dependen de condiciones, normas y proveedores actuales.",verifiedTitle:"La ruta terrestre vuelve a leerse bien.",verifiedAction:"Abrir el cierre de Saga",result:{title:"El agua no es un atajo",evidence:"Ruta terrestre corregida",openQuestion:"¿Qué puede guardar un humedal que parece vacío y por qué no se recorre como un atajo?",next:{href:"dia8.html",label:"Abrir el Día 08"}}},
  prologue:[
    {k:"SAGA · RUTA FALSA",title:"Una línea que se cree más lista que el paisaje",image:"saga-transmision-inicial.png",alt:"Saga abre el mapa del lago Åsunden y Komosse",html:`<p>La Sombra ha añadido a nuestro plano una ruta «rápida»: cruza Åsunden y sigue recta por Komosse.</p><p>Parece una buena idea hasta que miras qué está uniendo: un lago que cambia con el tiempo, una batalla librada sobre hielo en 1520 y una turbera que se visita por pasarelas.</p><p>Liv Berg nos ayudará a devolver cada sitio a su lugar dentro del entorno.</p>`,action:"Abrir la ruta"},
    {k:"LIV BERG · PERSONAJE FICTICIO",title:"Primero mirar el lugar",image:"liv-berg-asunden-ficcion-v1.png",alt:"Liv Berg, personaje ficticio, junto al lago Åsunden",html:`<p>Liv tiene 19 años y es una <strong>recreación narrativa ficticia</strong>. Durante el verano ayuda a orientar a visitantes de Ulricehamn y participa como voluntaria en observaciones de naturaleza.</p><p>«Una línea azul no te dice si hace viento, si el agua está fría, si hay hielo o si el suelo aguanta. Vamos a mirar el lugar antes de decidir qué camino existe.»</p>`,action:"Situar la jornada"}
  ],routePlaces:[],
  missions:[
    {title:"El mapa que confundió tres paisajes",speaker:"Liv",photo:"liv-berg-asunden-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"4–5 min",action:"Abrir el mapa",obstacle:"Antes de hablar de batalla o turbera, abrimos el mapa de verdad. Una ruta responsable empieza por saber qué hay bajo cada color.",goal:"Distinguir lago, memoria histórica junto a la orilla, casa histórica y turbera.",done:"Åsunden, Skottek, Torpa y Komosse quedan situados como lugares distintos.",reaction:"Una ruta no cruza «agua y verde»: atraviesa paisajes con reglas distintas.",closing:"Ya sabemos qué hay que corregir. Empezamos por el lago actual: no es igual en julio, enero o con viento.",contexts:[
      {character:true,k:"MAPA REAL · JORNADA DEL DÍA",title:"Seis puntos, una jornada",visual:"d7Route",html:`<p><strong>Ulricehamn:</strong> ciudad junto a Åsunden, llamada Bogesund hasta 1741. <strong>Åsunden:</strong> lago del paseo y escenario congelado de la batalla de 1520. <strong>Skottek:</strong> orilla al sur de la ciudad, ligada al monumento de Sten Sture.</p><p><strong>Torpa Stenhus:</strong> alternativa histórica junto al sistema de lagos. <strong>Komosse:</strong> gran complejo de humedales y turberas. <strong>Store Mosse:</strong> siguiente gran paisaje de turbera del viaje.</p>`}
    ],questions:[{id:"d7v7m1",type:"single",title:"El error de la línea rápida",prompt:"¿Qué error contiene la línea añadida al mapa?",options:["Confunde Suecia con España.","Dice que Ulricehamn está junto al océano.","Trata el lago, el hielo de un episodio histórico y una turbera como si fueran el mismo camino siempre disponible."],answer:2,hint:"Un mapa responsable explica el terreno y las condiciones de uso.",success:"ERROR DEL MAPA DETECTADO.",explanation:"Åsunden, Skottek y Komosse están conectados por la jornada, no por una misma regla de paso."}]},
    {title:"Un lago no vive igual todo el año",speaker:"Liv",photo:"liv-berg-asunden-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"4–5 min",action:"Mirar el lago",obstacle:"Si vais a kayak o paddle, la primera pregunta no es «¿hay agua?». Es: ¿hace viento?",goal:"Decidir actividades junto al lago según condiciones reales, normas e instrucciones.",done:"El lago queda leído como lugar de ocio y vida, no como promesa de condiciones permanentes.",reaction:"Cambiar de actividad no es perder: es leer bien el lugar.",closing:"Ya entendemos el lago actual. Pero hubo un día en que el hielo sostuvo algo difícil de imaginar: un ejército entero.",contexts:[
      {character:true,k:"ÅR DET BLÅSIGT?",title:"Antes de remar, mirar",speech:{word:"Är det blåsigt?",meaning:"¿Hace viento?",tip:"Pregunta útil antes de remar.",speech:"Är det blåsigt?"},html:`<p>Si hay alquiler de kayak o paddle, antes vienen chaleco, instrucciones y la opción de cambiar el plan si el lago no acompaña.</p><p>Un día tranquilo con actividad confirmada pide seguir instrucciones y permanecer en el área adecuada. Viento fuerte o aviso desfavorable pide una alternativa terrestre.</p>`},
      {character:true,k:"INVIERNO JUNTO AL AGUA",title:"El hielo de 1520 no es una invitación",visual:"d7Winter",html:`<p>En Suecia algunas personas practican patinaje de travesía o pesca en hielo. Pero no se da por seguro un lago porque «suele helarse»: se comprueban condiciones y zonas verificadas.</p><p>El hielo de Åsunden en 1520 es una pista de un invierno excepcional, no un permiso actual para cruzarlo.</p>`}
    ],questions:[{id:"d7v7m2",type:"single",title:"Decisión de lago",prompt:"Hay viento fuerte y el alquiler aconseja no salir con principiantes. ¿Qué decisión convierte el plan en una aventura bien hecha?",options:["Salir de todas formas porque el lago aparece en el mapa.","Cambiar a paseo, bicicleta u otra actividad y dejar el agua para condiciones adecuadas.","Usar la historia de 1520 como prueba de que el lago aguanta cualquier cosa."],answer:1,hint:"Las condiciones, las normas y las personas responsables forman parte de la ruta.",success:"DECISIÓN RESPONSABLE TOMADA.",explanation:"El paisaje no da permiso por sí solo: la mejor alternativa depende de la situación actual."}]},
    {title:"El día en que el lago fue un campo de batalla",speaker:"Liv",photo:"liv-berg-asunden-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"6–7 min",action:"Recuperar 1520",obstacle:"En el Día 1 conocisteis a Sten Sture y Kristina Gyllenstierna. Hoy estáis donde esa historia dio un giro antes de llegar a Estocolmo.",goal:"Conectar Åsunden con Sten Sture, Kristina, el Baño de Sangre y Gustav Vasa sin mezclar los hechos.",done:"Åsunden recupera su lugar como primer eslabón físico de una historia que siguió en Estocolmo.",reaction:"Ese hielo explica 1520; no significa que el hielo en invierno siempre tenga esas condiciones.",closing:"El lago no eligió la batalla. Fueron la guerra y un invierno excepcional quienes lo convirtieron durante unas horas en un camino.",contexts:[
      {character:true,k:"19 DE ENERO DE 1520",title:"Un rey, un regente y el hielo",visual:"d7Battle",html:`<p>Cristián II, rey de Dinamarca y Noruega, quería afirmar su autoridad sobre Suecia en la Unión de Kalmar. Sten Sture el Joven era el regente que defendía el gobierno sueco.</p><p>El 19 de enero de 1520, las fuerzas de Sten Sture se enfrentaron sobre el hielo de Åsunden a un ejército danés dirigido por Otto Krumpen. Una bala de cañón hirió a Sten en una pierna. Murió semanas después durante el traslado hacia Estocolmo.</p>`},
      {character:true,k:"CONEXIÓN CON EL DÍA 1",title:"La cadena que llegó a Stortorget",visual:"d7Chain",html:`<p>Åsunden: Sten Sture es herido. Después muere. Kristina Gyllenstierna dirige la resistencia de Estocolmo. En noviembre llega la coronación de Cristián II y el Baño de Sangre.</p><p>La batalla se conoce también como Bogesund —nombre antiguo de Ulricehamn—, Åsunden o Skottek.</p>`}
    ],questions:[{id:"d7v7m3",type:"single",title:"Un invierno fuera de lo normal",prompt:"¿Qué permite deducir que la batalla se librara sobre el hielo de Åsunden?",options:["Que todos los lagos suecos se cruzan con seguridad en cualquier invierno.","Que aquel frío fue excepcionalmente intenso: el hielo soportó soldados, caballos y artillería.","Que el lago estaba seco."],answer:1,hint:"La situación histórica no equivale a una norma de seguridad actual.",success:"HIELO HISTÓRICO EXPLICADO.",explanation:"La batalla muestra la dureza de aquel enero, no un consejo para utilizar hielo natural."}]},
    {title:"Skottek, el roble del disparo",speaker:"Liv",photo:"liv-berg-asunden-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"4–5 min",action:"Leer el nombre",obstacle:"Åsunden es el lago. Skottek es una orilla arbolada al sur de Ulricehamn donde un monumento conserva memoria de Sten Sture.",goal:"Entender qué puede contar un nombre de lugar sin rellenar las partes que las fuentes no prueban.",done:"Skottek conserva una memoria honesta de la batalla y de su herida.",reaction:"Un nombre puede guardar memoria sin ser un plano exacto de cada segundo de una batalla.",closing:"Skottek no necesita una escena inventada. El nombre, el lago y el monumento ya dan una memoria suficiente.",contexts:[
      {character:true,k:"ORILLA, HIELO Y MEMORIA",title:"Lo que sabemos y lo que no",visual:"d7Skottek",html:`<p>La batalla se libró sobre el hielo del lago. Skottek es la orilla arbolada donde se levanta un monumento que recuerda a Sten Sture. No sabemos exactamente dónde estaba en el instante del impacto ni podemos afirmar que dirigiera desde la retaguardia.</p><p><strong>Paralelismo:</strong> algunos monarcas se exponían mucho —Alfonso VIII de Castilla estuvo con su ejército en Las Navas de Tolosa en 1212—; otros dirigían desde posiciones más protegidas. Las posiciones variaban según estrategia y peligro.</p>`}
    ],questions:[{id:"d7v7m4",type:"match",solutionVisual:"d7SkottekPhoto",title:"Dos piezas en un nombre",prompt:"Une las dos piezas del nombre Skottek.",pairs:[["skott","disparo"],["ek","roble"],["Skottek","«Roble del disparo», asociado a la memoria local de la herida de Sten Sture"]],hint:"No es un código secreto: es memoria de un lugar guardada dentro de una palabra.",success:"NOMBRE DEL LUGAR ENTENDIDO.",explanation:"El monumento sitúa un recuerdo histórico sin transformar la orilla actual en un campo de batalla."}]},
    {title:"Antes del reino, mucho antes de la batalla",speaker:"Liv",photo:"liv-berg-asunden-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"5–6 min",action:"Abrir la historia larga",obstacle:"Cuando decimos «antes de Suecia», no queremos decir «vacío». La comarca guarda personas, nombres y cambios de poder mucho anteriores a 1520.",goal:"Relacionar presencia humana antigua, götar, Götaland y el nombre de Ulricehamn.",done:"La comarca recupera una historia de miles de años, no una sola batalla.",reaction:"Los nombres conservan relaciones históricas; no dibujan fronteras tribales exactas.",closing:"Ya tenemos una comarca completa: personas de hace miles de años, götar, ciudad medieval, batalla y una reina cuyo nombre quedó en el mapa.",contexts:[
      {character:true,k:"MUCHO ANTES DE BOGESUND",title:"Una presencia humana muy antigua",visual:"d7Ancient",html:`<p>Hacia 7700 a. C. vivió en Marbäck el llamado Bredgårdsmannen; sus restos son una de las evidencias más antiguas de presencia humana local.</p><p>Una reconstrucción basada en restos óseos no es fotografía ni permite saber su nombre, carácter o historia completa.</p>`},
      {character:true,k:"GÖTAR → GÖTALAND",title:"Un nombre que todavía organiza Suecia",visual:"d7Gotar",html:`<p>Götaland significa «tierra de los götar» y es una de las tres grandes regiones históricas de Suecia, junto con Svealand y Norrland. Dentro de ella están Västergötland y Östergötland.</p><p>Västergötland conserva una relación con los götar, pero antes del reino hubo comunidades y áreas de influencia, no fronteras tribales exactas como las actuales.</p>`},
      {character:true,k:"1741 · ULRICEHAMN",title:"Una reina dentro del nombre",visual:"d7Ulrika",html:`<p>Bogesund aparece mencionada por escrito en 1307. En 1741 pasó a llamarse Ulricehamn en honor de Ulrika Eleonora.</p><p>Fue reina por derecho propio entre 1718 y 1720. Tras morir su hermano Carlos XII, aceptó una nueva forma de gobierno que dio más peso al Riksdag y después cedió la Corona a su marido, Federico I.</p>`}
    ],questions:[{id:"d7v7m5",type:"single",title:"Götar no significa un mapa perfecto",prompt:"¿Qué afirmación explica mejor la relación entre la región y los götar?",options:["Todos los habitantes de la zona eran vikingos y vivían igual.","Los götar fundaron Ulricehamn en 1741.","Västergötland conserva en su nombre la relación con los götar; antes del reino hubo áreas de influencia, no fronteras tribales exactas."],answer:2,hint:"Recuerda el Día 1: «suecos» y «vikingos» no explican a toda la población.",success:"REGIÓN LEÍDA CON MATIZ.",explanation:"Götaland, Västergötland, Göta älv y Göteborg conservan una relación lingüística e histórica con los götar."}]},
    {title:"Una casa con ventanas para mirar y defenderse",speaker:"Liv",photo:"liv-berg-asunden-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"5–6 min",action:"Abrir Torpa",obstacle:"Torpa parece fortaleza, y tenía motivos para cuidarse. Pero también fue casa y punto de intercambio de ganado y alimentos por los valles cercanos.",goal:"Conocer Torpa como casa, comercio y defensa, y enlazarla con Katarina Stenbock y los Vasa.",done:"Torpa une lago, defensa, comercio y una rama de la familia Vasa.",reaction:"Un edificio puede ser hogar y, al mismo tiempo, estar preparado para una época insegura.",closing:"Torpa da una casa a la historia que viene después: familias, herencias y poder. Ahora veremos un lugar donde el tiempo se guarda bajo los pies.",contexts:[
      {character:true,k:"TORPA STENHUS · PARADA ALTERNATIVA",title:"Ni palacio de cuento ni cuartel puro",visual:"d7Torpa",html:`<p>Torpa fue casa señorial, punto de comercio y edificio defensivo. A finales de la Edad Media hubo amenazas de guerra y conflictos locales; a la vez, los valles de Ätran y Viskan conectaban ganado, alimentos e intercambios.</p>`},
      {character:true,k:"TRES ESPOSAS, TRES RAMAS",title:"Katarina Stenbock y el árbol Vasa",visual:"d7Family",html:`<p>Katarina Stenbock creció en Torpa y se casó con Gustav Vasa en 1552, cuando el rey había enviudado por segunda vez. No tuvieron hijos. La primera esposa del rey, Katarina de Sajonia-Lauenburgo, fue madre de Erik XIV. La segunda, Margareta Leijonhufvud, fue madre de Johan III y Karl IX.</p><p>La historia documentada basta para entender la sucesión. La tradición de Torpa añade la leyenda de que Katarina intentó ocultarse en el jardín antes de la boda; la presentamos como leyenda, no como una escena comprobada.</p>`}
    ],questions:[{id:"d7v7m6",type:"single",title:"Qué clase de edificio era",prompt:"¿Qué descripción protege mejor la historia de Torpa?",options:["Fue casa, punto de comercio y edificio defensivo: no solo una fortaleza militar ni una vivienda despreocupada de los conflictos.","Fue un palacio levantado en 1923 para Liseberg.","Era el cuartel general de Cristián II en 1520."],answer:0,hint:"Un edificio puede tener más de una función a la vez.",success:"TORPA LEÍDA CON PRECISIÓN.",explanation:"Torpa acerca al viaje una historia de élites, familias, intercambio y defensa junto a los lagos."}]},
    {title:"La tierra que tarda miles de años en crecer",speaker:"Liv",photo:"liv-berg-asunden-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"6–7 min",action:"Entrar en Komosse",obstacle:"Komosse parece suelo; también es un archivo. La Sombra lo dibuja como un atajo verde sin explicar qué hay bajo las plantas.",goal:"Comprender una turbera elevada y distinguirla de otros humedales de turba.",done:"Komosse queda leído como mosaico de humedales, agua, turba y tiempo acumulado.",reaction:"Medio milímetro parece poco, pero repetido miles de veces puede formar metros de turba.",closing:"Ya queda claro por qué la línea falsa era tan mala idea. Bajo los pies hay agua, musgos, animales, capas de turba y tiempo acumulado.",contexts:[
      {character:true,k:"KOMOSSE · HUMEDAL Y ARCHIVO",title:"Cómo empieza una turbera",visual:"d7Peat",html:`<p>En un terreno muy húmedo, los restos de plantas se descomponen de forma incompleta por falta de oxígeno. Se acumulan como turba y la superficie puede elevarse poco a poco.</p><p>Komosse no es una superficie idéntica: combina turberas, bosque húmedo, arroyos, lagunas e «islas» de suelo mineral.</p>`},
      {character:true,k:"TRES TIPOS PARA NO CONFUNDIR",title:"Elevada no significa montaña",mapImage:"turbera.jpg",mapAlt:"Turbera de Komosse",mapCaption:"Turbera · paisaje húmedo y frágil",visual:"d7PeatTypes",html:`<p><strong>Turbera baja:</strong> recibe agua del terreno, arroyos o nivel freático y suele tener más minerales. <strong>Turbera elevada:</strong> su centro ha crecido y depende sobre todo de lluvia; suele ser más ácida y pobre en nutrientes. <strong>Turbera de cobertura:</strong> se extiende como manta en climas muy húmedos, sin necesitar una cúpula central.</p><p><strong>Paralelismo con España:</strong> hay trampales y turberas de montaña, por ejemplo en el Alto Pirineo. Comparten agua y descomposición lenta, aunque no son idénticos a Komosse.</p>`},
      {character:true,k:"ESCALA Y TIEMPO",title:"Ocho metros, medio milímetro",visual:"d7PeatScale",html:`<p>En Komosse la turba suele tener 3–4 metros y en algunos puntos llega a 8. La reserva indica una media de crecimiento de unos 0,5 mm al año. Muchos metros necesitan miles de años.</p>`}
    ],questions:[{id:"d7v7m7",type:"match",contextVisual:"d7Birds",title:"Un paisaje abierto, no vacío",prompt:"Relaciona cada señal de Komosse con lo que puede indicar.",pairs:[["Grulla","Ave que cría o utiliza los humedales."],["Chorlito dorado europeo","Ave ligada a extensiones abiertas de turbera."],["Pasarela","Forma de observar sin pisar una superficie frágil."],["Antigua caseta de turba","Recuerdo de que también hubo extracción de turba, por ejemplo para camas de ganado."]],hint:"Que parezca silencioso no significa que esté vacío ni que no tenga historia humana.",success:"KOMOSSE HABITADA Y LEÍDA.",explanation:"Las imágenes de aves son guías de observación, no una garantía de avistamiento."}]},
    {title:"La pasarela que protege el tiempo",speaker:"Liv",photo:"liv-berg-asunden-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"4–5 min",action:"Reparar la ruta",obstacle:"La ruta correcta no tiene por qué ser recta. La pasarela no recorta la aventura: permite mirar sin dejar una herida nueva.",goal:"Cerrar el mapa sustituyendo la línea falsa por acceso señalizado, pasarela y carretera.",done:"La ruta final respeta lago, historia, turbera y el siguiente tramo hacia Store Mosse.",reaction:"Una línea recta no siempre es un camino. La ruta correcta respeta accesos, senderos y terreno.",closing:"Åsunden puede conectar si las condiciones lo permiten; Komosse conserva si seguimos su pasarela. No todos los caminos rápidos llevan a donde queremos llegar.",contexts:[
      {character:true,k:"BJÖRNÖLEDEN · PASARELA",title:"Cómo conocer Komosse sin dañarla",visual:"d7Boardwalk",html:`<p>La ronda de Björnöleden tiene algo más de cuatro kilómetros y discurre en gran parte por pasarelas. Estado y duración se confirman antes de salir.</p><p>La pasarela protege a la persona frente a zonas húmedas o inestables y protege turba y vegetación frente al pisoteo repetido.</p>`},
      {character:true,k:"SUECO ÚTIL",title:"Una frase para el sendero",speech:{word:"Håll dig på spången.",meaning:"Quédate en la pasarela.",tip:"Frase útil para cuidar el sendero.",speech:"Håll dig på spången."},html:`<p><strong>mosse</strong> = turbera / pantano de turba · <strong>sjö</strong> = lago.</p><p>Es una tarjeta de ayuda para el sendero, no una prueba de pronunciación.</p>`}
    ],questions:[{id:"d7v7m8",type:"single",title:"Por dónde sí se pasa",prompt:"¿Qué corrección debe hacerse a la ruta falsa en Komosse?",options:["Cruzar por donde la turba parezca seca.","Seguir huellas de animales hasta Store Mosse.","Sustituir el cruce recto por el acceso señalado y Björnöleden sobre pasarelas; después continuar por carretera."],answer:2,hint:"La ruta correcta respeta accesos, senderos y el terreno frágil.",success:"RUTA DE KOMOSSE REPARADA.",explanation:"La pasarela cuida a la vez de las personas, la vegetación y la turba acumulada durante miles de años."}]}
  ],
  ending:[
    {image:"liv-berg-asunden-ficcion-v1.png",caption:"Liv Berg · personaje ficticio · ruta corregida",k:"LIV · MAPA REPARADO",title:"Cada paisaje recupera su regla.",html:`<p>Åsunden cambia con el tiempo y las condiciones. Skottek guarda memoria sin inventar una escena completa. Torpa enlaza defensa, familia y comercio. Komosse conserva turba, agua y tiempo bajo sus pasarelas.</p><p>La línea rápida ya no engaña porque sabemos qué hay bajo ella.</p>`,action:"Guardar la ruta"},
    {image:"saga-canal-asegurado.png",caption:"Saga · Ruta terrestre",k:"SAGA · EVIDENCIA RECUPERADA",title:"El agua puede conectar, conservar memoria o exigir protección.",html:`<p>Depende del lugar, de la estación y de cómo la usamos. La Sombra esperaba que siguiéramos una línea bonita sin preguntar qué había debajo.</p><p>Ahora sabemos que una vía de agua puede ser descanso, frontera, memoria y archivo natural.</p>`,action:"Revelar la siguiente coordenada"},
    {image:"saga-canal-asegurado.png",caption:"Saga · rumbo a Store Mosse",k:"COORDENADA SIGUIENTE",title:"La turba será todavía más extensa.",html:`<div class="coordinate">STORE MOSSE · MARIEFRED<br>TIEMPO PROFUNDO · AVES · HUMEDAL<br>SEÑAL · UNA MARCA QUE NO ESTÁ ESCRITA CON TINTA</div><p>Guardamos la ruta terrestre hacia Store Mosse. El próximo paisaje de turbera nos llevará después hasta Mariefred.</p>`,action:"Cerrar el canal"}
  ]
};
