/* Día 08 · Fuente editorial única: 03_Guiones/V8/Documento_Base_Guion_completo_Codigo_Gripsholm_dias_07_a_10_V8.docx.
   Maja Lind es un personaje ficticio contemporáneo: sus palabras son recreación narrativa. */
window.DAY1_DATA={
  meta:{day:"08",store:"codigo-gripsholm-v8-day08",contentVersion:"v8-day8",place:"HÖKERUM → STORE MOSSE → MARIEFRED",title:"El mapa que parecía vacío",landing:"La Sombra ha borrado Store Mosse y ha dejado una mancha blanca camino de Gripsholm.",badge:"Mapa restaurado",objective:"DEVOLVER CONTENIDO A LA MANCHA BLANCA",objectiveCopy:"Leeremos turba, arena, aves, restauración y memoria humana antes de llegar a Mariefred.",evidenceCopy:"Cada misión devuelve una capa al mapa que parecía vacío.",fine:"Maja Lind es un personaje ficticio. Una visita breve, Naturum, la torre y un tramo señalizado cuentan como una misión completa.",verifiedTitle:"Store Mosse vuelve a aparecer en el mapa.",verifiedAction:"Abrir el cierre de Saga",result:{title:"El mapa que parecía vacío",evidence:"Mapa restaurado",openQuestion:"¿Por qué un monasterio llamado Pax Mariæ terminó dejando paso a Gripsholm, el castillo que da nombre a todo el viaje?",next:{href:"dia9.html",label:"Abrir el Día 09"}}},
  prologue:[
    {k:"SAGA · TERRENO BORRADO",title:"Un hueco entre dos carreteras",image:"saga-transmision-inicial.png",alt:"Saga abre la ruta entre Hökerum, Store Mosse y Mariefred",html:`<p>La Sombra no ha dibujado un atajo esta vez. Ha borrado un lugar entero.</p><p>Entre Hökerum y Mariefred solo deja una mancha blanca y una flecha hacia Gripsholm. Pero esa mancha se llama <strong>Store Mosse</strong>. El viaje es largo: no vamos a conquistar el parque en una mañana; vamos a leer una parte y llegar con energía a Mariefred.</p>`,action:"Abrir la mancha blanca"},
    {k:"MAJA LIND · PERSONAJE FICTICIO",title:"No es «solo musgo»",image:"maja-lind-store-mosse-ficcion-v1.png",alt:"Maja Lind, personaje ficticio, en una pasarela de Store Mosse",html:`<p>Maja tiene 20 años y es una <strong>recreación narrativa ficticia</strong>. Colabora en verano en tareas de acogida y observación de naturaleza alrededor de Store Mosse.</p><p>«Hay quien mira estas extensiones y dice “solo hay musgo”. A mí me parece como llamar “solo papel” a una biblioteca. Aquí hay turba, arena, agua, aves, trabajo humano y restauración.»</p>`,action:"Entrar en Store Mosse"}
  ],routePlaces:[],
  missions:[
    {title:"Una parada, no una carrera",speaker:"Maja",photo:"maja-lind-store-mosse-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"4–5 min",action:"Situar la mañana",obstacle:"Naturum, la torre y un tramo corto pueden ser una mañana completa. Recorrer todo Kävsjön en un día de traslado lo convertiría en algo demasiado estresante: se vería todo a la carrera.",goal:"Planificar una visita breve que respete el tiempo, el tiempo atmosférico y la llegada a Mariefred.",done:"La jornada queda diseñada como una visita útil, no como una lista agotadora.",reaction:"Cambiar de plan no borra la aventura: demuestra que tiempo, energía y paisaje cuentan.",closing:"Primera corrección: el parque no es una lista que se tacha. Ahora abrimos el hueco del mapa.",contexts:[
      {character:true,k:"HÖKERUM → STORE MOSSE → MARIEFRED",title:"Seis señales para una jornada realista",visual:"d8Route",html:`<p><strong>Hökerum:</strong> salida temprana. <strong>Carretera 151:</strong> acceso habitual a la entrada principal. <strong>Naturum:</strong> orientación e información. <strong>Torre de aves:</strong> vista hacia Kävsjön. <strong>Wibecksleden:</strong> recorrido fácil y corto, con estado y duración por confirmar. <strong>Mariefred:</strong> llegada junto al Mälaren, Pax Mariæ y Gripsholm.</p>`}
    ],questions:[{id:"d8v7m1",type:"single",title:"Cambiar de plan también es viajar bien",prompt:"Llueve con intensidad, el suelo está resbaladizo y habéis salido tarde. ¿Qué decisión conserva mejor la misión?",options:["Visitar Naturum, subir a la torre solo si es seguro y hacer un paseo corto; después continuar a Mariefred.","Forzar la ruta larga para completar todo el mapa.","Cruzar la turbera para recuperar el tiempo perdido."],answer:0,hint:"Naturum, torre y un tramo corto ya forman una visita completa en un día largo.",success:"TIEMPO DEL DÍA PROTEGIDO.",explanation:"La prioridad es comprender el lugar y llegar con seguridad, no acumular kilómetros."}]},
    {title:"Ocho mil años bajo los pies",speaker:"Maja",photo:"maja-lind-store-mosse-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"6–7 min",action:"Leer el testigo",obstacle:"Ayer aprendisteis cómo crece una turbera. Store Mosse añade escala y variedad. La pregunta correcta no es «quién ha contado hasta ocho mil», sino «cómo lo comprueban».",goal:"Entender cómo una muestra de turba permite construir una cronología rigurosa.",done:"El tiempo profundo de Store Mosse se apoya en testigos, muestras y laboratorio.",reaction:"La superficie da pistas; la edad se comprueba con capas, muestras y análisis.",closing:"Segundo error borrado: no es «musgo viejo». Es un archivo de plantas, agua y clima que se fecha con pruebas.",contexts:[
      {character:true,k:"STORE MOSSE · UN PAISAJE GRANDE",title:"Más que una turbera",mapImage:"Store_Mosse_nationalpark.jpg",mapAlt:"Paisaje del Parque Nacional de Store Mosse",mapCaption:"Store Mosse · turbera, agua y pinos",visual:"d8Peat",html:`<p>Store Mosse está dominado por turberas elevadas, pero no es una superficie idéntica: también reúne lagos, pinares de turbera, bosque húmedo y carrizales. Su turba se ha formado durante al menos 8.000 años, principalmente a partir de restos de esfagnos.</p><p>En condiciones húmedas y con poco oxígeno, las plantas se descomponen lentamente y se acumulan como turba.</p>`},
      {character:true,k:"MUESTRA CIENTÍFICA · NUNCA EXCAVAR",title:"El testigo que conserva pistas",visual:"d8Core",html:`<p>Especialistas extraen una columna estrecha de turba: un <strong>testigo</strong>. Las capas profundas suelen ser más antiguas. En laboratorio datan restos con carbono 14 y comparan polen, semillas y otras señales a distintas profundidades.</p><p>Una capa oscura vista en un borde puede sugerir acumulación; no puede decir por sí sola «tiene 8.000 años».</p>`},
      {character:true,k:"DROSERA · MIRAR, NO TOCAR",title:"Una planta que busca nutrientes de otra manera",visual:"d8Drosera",html:`<p>El suelo de una turbera elevada es muy pobre en nutrientes. Las droseras atrapan insectos con gotas pegajosas para obtener parte de lo que escasea en el suelo.</p>`}
    ],questions:[{id:"d8v7m2",type:"single",title:"Tiempo visto; edad comprobada",prompt:"¿Qué combinación permite distinguir una turba muy antigua de un depósito reciente con más rigor?",options:["Fijarse solo en que la capa se ve muy oscura.","Decidirlo por el tamaño del cartel del parque.","Tomar un testigo por especialistas, analizar restos de varias profundidades y fechar muestras en laboratorio."],answer:2,hint:"La vista puede dar una pista; la cronología necesita muestras y análisis.",success:"TIEMPO VISTO; EDAD COMPROBADA.",explanation:"Un testigo transforma capas visibles en una cronología que se puede contrastar."}]},
    {title:"Islas de arena en un mar de musgo",speaker:"Maja",photo:"maja-lind-store-mosse-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"5–6 min",action:"Mirar los rocknar",obstacle:"Donde parece que debería haber una isla, hay bosque. Los rocknar no son roca volcánica ni torres construidas: son dunas antiguas dentro de la turbera.",goal:"Leer los rocknar como dunas de arena y bosque formadas tras el deshielo.",done:"Arena, pinos y turba recuperan sus tiempos distintos dentro del mismo paisaje.",reaction:"No todo lo alto es roca: aquí arena y bosque dibujan islas dentro del humedal.",closing:"El mapa ya no tiene un solo color: turba, agua, arena y bosque llegaron en momentos distintos.",contexts:[
      {character:true,k:"HACE 15.000 AÑOS → HOY",title:"Cuatro momentos, un paisaje",visual:"d8Rocknar",html:`<p>El gráfico cuenta la secuencia completa: el hielo deja un lago; el lago deja arena; el viento forma dunas; pinos y turba construyen el paisaje actual. Cada parte llegó en un momento distinto.</p>`},
      {character:true,k:"PARECIDO NO ES IGUAL",title:"Una idea que también existe en España",visual:"d8Dunes",html:`<p>Hay dunas interiores y fósiles en otros lugares, también en España. Lo particular de Store Mosse es la combinación: arena de un antiguo lago glaciar, pinos que la estabilizan y una enorme turbera que creció alrededor.</p>`}
    ],questions:[{id:"d8v7m3",type:"single",title:"La tarjeta correcta de los rocknar",prompt:"¿Qué son los rocknar de Store Mosse?",options:["Torres construidas para observar el parque.","Dunas de arena cubiertas de bosque que forman islas y crestas dentro de la turbera abierta.","Rocas volcánicas que cayeron del cielo."],answer:1,hint:"No todo lo alto es roca: fíjate en arena, pinos y turbera alrededor.",success:"ISLAS DE ARENA LOCALIZADAS.",explanation:"Los rocknar muestran una segunda historia geológica dentro de Store Mosse."}]},
    {title:"La ventana de Kävsjön",speaker:"Maja",photo:"maja-lind-store-mosse-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"5–6 min",action:"Abrir la torre",obstacle:"La torre no es una máquina de fabricar avistamientos. Es una ventana: si aparece un ave, la identificamos; si no, seguimos aprendiendo con paisaje, fotos y sonidos.",goal:"Reconocer aves por pistas sin prometer que han de aparecer ni acercarse a ellas.",done:"La torre queda leída como una ventana de observación respetuosa.",reaction:"Una curiosidad es una pista interesante, no una garantía de espectáculo.",closing:"La observación no ha fallado si no hay pájaros en una foto. El paisaje también cuenta qué aves podrían necesitarlo.",contexts:[
      {character:true,k:"KÄVSJÖN · TORRE DE AVES",title:"Mirar no es tachar una lista",visual:"d8Birds",html:`<p>Desde la torre se observa sin acercarse a las aves. La grulla común tiene patas largas y una llamada como trompeta. El cisne cantor tiene pico amarillo y negro. El gallo lira macho es oscuro, con ceja roja y detalles blancos. El zarapito real tiene pico largo curvado hacia abajo.</p><p>Las fotos son ejemplos de identificación; ninguna especie está garantizada hoy.</p>`},
      {character:true,k:"SUECO ÚTIL",title:"¿Dónde está la torre de aves?",speech:{word:"Var är fågeltornet?",meaning:"¿Dónde está la torre de aves?",tip:"Frase útil para orientarse en la visita.",speech:"Var är fågeltornet?"},html:`<p><strong>fågel</strong> = ave · <strong>torn</strong> = torre.</p>`}
    ],questions:[{id:"d8v7m4",type:"match",solutionVisual:"d8Birds",title:"Cuatro aves, cuatro pistas",prompt:"Relaciona cada ave con su pista principal.",pairs:[["Grulla común · trana","Ave grande de patas largas; su llamada recuerda a una trompeta."],["Cisne cantor · sångsvan","Pico amarillo y negro; su nombre significa «cisne cantor»."],["Gallo lira · orre","Macho oscuro, ceja roja y detalles blancos; exhibiciones en primavera."],["Zarapito real · storspov","Pico largo curvado hacia abajo; ligado a espacios abiertos y húmedos."]],hint:"No hace falta verla hoy para aprender qué pistas buscar sin molestarla.",success:"VENTANA DE AVES ACTIVADA.",explanation:"Las aves se observan con distancia, silencio y la posibilidad real de no ver ninguna."}]},
    {title:"Cicatrices que también hay que leer",speaker:"Maja",photo:"maja-lind-store-mosse-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"4–5 min",action:"Mirar la restauración",obstacle:"«Protegido» no quiere decir que nadie hubiera trabajado aquí. Los pozos de turba recuerdan extracciones de la primera mitad del siglo XX.",goal:"Entender que restaurar una turbera no es esconder su historia, sino recuperar funciones de agua y vegetación.",done:"Store Mosse recupera a la vez cicatrices humanas y decisiones de conservación.",reaction:"Restaurar no inventa un pasado perfecto: mejora condiciones ecológicas de un lugar cuya historia conocemos.",closing:"La mancha blanca ya tiene tiempo, vida, uso humano y cuidado. Falta una pista de carretera sobre redes de personas.",contexts:[
      {character:true,k:"TRES MOMENTOS DEL PAISAJE",title:"Protegido no significa «nunca se ha tocado»",visual:"d8Restore",html:`<p>La turba se acumula durante miles de años. En partes del paisaje se extrajo durante la primera mitad del siglo XX. En 1982 se creó el Parque Nacional de Store Mosse. Algunas zonas alteradas se restauran para recuperar funciones de turbera elevada.</p>`}
    ],questions:[{id:"d8v7m5",type:"single",title:"Restaurar no es esconder",prompt:"¿Qué busca una restauración de turbera?",options:["Hacer que parezca una piscina recién construida.","Recuperar, en la medida posible, condiciones de agua y vegetación que permitan que el humedal funcione de nuevo.","Esconder todas las huellas humanas y dejar de explicar la historia."],answer:1,hint:"Proteger puede incluir reparar, pero no borrar la memoria de un uso anterior.",success:"CUIDADO DEL PAISAJE ENTENDIDO.",explanation:"La conservación decide qué procesos se protegen y qué condiciones se intenta recuperar."}]},
    {title:"Komosse y Store Mosse: ¿qué comparten?",speaker:"Maja",photo:"maja-lind-store-mosse-ficcion-v1.png",characterCaption:"personaje ficticio · comparación didáctica",keys:1,time:"4–5 min",action:"Abrir la comparación",obstacle:"Dos lugares pueden parecer iguales porque ambos están cubiertos de musgo y agua. La pregunta útil es qué comparten y qué cambia en cada uno.",goal:"Distinguir turbera elevada, turbera baja y otros humedales sin perder la idea principal.",done:"Komosse y Store Mosse quedan conectados por el agua, la turba y una diferencia importante de escala.",reaction:"Comparar no es decir que dos paisajes sean idénticos: es descubrir qué regla explica a los dos.",closing:"El agua ha dado la clave. Ahora el camino sale del humedal y vuelve a las redes de personas.",contexts:[
      {character:true,k:"DOS TURBERAS ELEVADAS",title:"Mismo principio",visual:"d8CompareRaised",html:`<p>En sus zonas de turbera elevada, Komosse y Store Mosse reciben principalmente agua de lluvia. El esfagno vivo queda arriba; debajo se acumula turba durante miles de años.</p>`},
      {character:true,k:"PARECIDAS, PERO NO IGUALES",title:"El proceso y la escala",visual:"d8CompareScale",html:`<p>Komosse permite ver muy bien las capas y el espesor de la turba. Store Mosse muestra ese mismo proceso extendido por un paisaje mucho mayor y más diverso.</p>`},
      {character:true,k:"EL AGUA DECIDE",title:"No todo humedal funciona igual",visual:"d8CompareWater",html:`<p>Una turbera elevada depende sobre todo de la lluvia. Una turbera baja recibe también agua del terreno. Un bosque húmedo puede tener el agua muy cerca de la superficie sin ser una turbera elevada.</p>`}
    ],questions:[{id:"d8v7m6compare",type:"single",title:"La frase que une los dos parques",prompt:"¿Qué frase compara mejor Komosse y Store Mosse?",options:["Ambas son lagos que se secaron después del hielo.","Ambas incluyen turberas elevadas alimentadas principalmente por lluvia; Store Mosse, además, reúne otros ambientes húmedos y una escala mayor.","Komosse recibe agua subterránea y Store Mosse solo agua de mar."],answer:1,hint:"Fíjate en el origen del agua y en que Store Mosse es un mosaico de ambientes.",success:"COMPARACIÓN COMPLETADA.",explanation:"Las dos ayudan a entender cómo se acumula turba durante miles de años. Store Mosse no es solo más grande: también combina más ambientes."}]},
    {title:"La red que no sale en el navegador",speaker:"Maja",photo:"maja-lind-store-mosse-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"4–5 min",action:"Escuchar la nota de carretera",obstacle:"Cerca de esta ruta está Gnosjö, asociado a Gnosjöandan: pequeñas industrias, inventiva y redes de apoyo práctico.",goal:"Entender la cooperación empresarial sin convertirla en una fórmula mágica ni negar la competencia.",done:"Gnosjöandan y FAMOSA aparecen como dos maneras distintas de afrontar cambios industriales.",reaction:"Cooperar no borra la competencia: puede hacer más resistente una red de pequeñas empresas.",closing:"Un lugar aparentemente vacío puede guardar agua, aves, trabajo y cooperación. Saga os espera junto al Mälaren.",contexts:[
      {character:true,k:"GNOSJÖANDAN",title:"El pedido imposible",visual:"d8Gnosjo",html:`<p>Gnosjöandan no significa que cada vecino tenga una fábrica ni que todos los talleres sean iguales. Es una cultura regional asociada a iniciativa, pequeñas empresas y redes de apoyo práctico.</p><p><strong>Paralelismo:</strong> en Onil, Alicante, 25 pequeñas empresas de muñecas se unieron en 1957 para afrontar nuevos plásticos e inversiones: así nació FAMOSA, Fábricas Agrupadas de Muñecas de Onil, S. A.</p><p>No es exactamente la misma historia: FAMOSA fue una agrupación concreta; Gnosjöandan es una cultura regional más amplia.</p>`}
    ],questions:[{id:"d8v7m6",type:"single",title:"El pedido imposible",prompt:"Un taller no puede terminar a tiempo una parte de un pedido. ¿Qué decisión encaja mejor con Gnosjöandan?",options:["Ocultar el problema hasta que sea demasiado tarde.","Pedir ayuda temporal a otro taller y cumplir juntos, aunque después sigan siendo competidores.","Decir que colaborar significa que ya no existen empresas distintas."],answer:1,hint:"La red puede cooperar ante un imprevisto sin dejar de estar formada por empresas distintas.",success:"RED DE GNOSJÖ LEÍDA.",explanation:"Gnosjö y el Valle del Juguete muestran que colaborar puede ser una respuesta práctica a cambios y riesgos."}]},
    {title:"La paz que cambió de forma",speaker:"Maja",photo:"maja-lind-store-mosse-ficcion-v1.png",characterCaption:"personaje ficticio · transmisión de llegada",keys:1,time:"6–7 min",action:"Llegar a Mariefred",obstacle:"Habéis llegado a Mariefred, «Paz de María». El nombre conserva un monasterio y un cambio de religión y poder que afectó a todo el reino.",goal:"Entender Pax Mariæ, el monasterio católico y por qué la Reforma cambió el control de sus bienes.",done:"Mariefred y Gripsholm recuperan sus capas: monasterio católico, Reforma y castillo Vasa.",reaction:"La Reforma no fue solo una discusión religiosa: cambió propiedades, decisiones y poder político.",closing:"Mi mapa termina aquí, pero no la historia. Mañana veréis esa idea en piedra: fortaleza, monasterio y castillo en el mismo lugar.",contexts:[
      {character:true,k:"PAX MARIÆ · PAZ DE MARÍA",title:"Católico antes, luterano después",visual:"d8Mariefred",html:`<p>Aquí hubo un monasterio cartujo. Era católico, igual que Gustav Trolle, el arzobispo del Día 1. En 1520 Suecia pertenecía aún a la Iglesia católica.</p><p>Gustav Vasa fue elegido rey en 1523. En 1527 el Riksdag de Västerås permitió a la Corona disponer de bienes eclesiásticos; durante el siglo XVI Suecia se fue convirtiendo en un reino luterano. No fue algo que pasase de un día a otro.</p>`},
      {character:true,k:"DEL MONASTERIO AL CASTILLO",title:"1493 → 1605",visual:"d8Pax",html:`<p>Las viñetas resumen una cadena: fundación del monasterio, Reforma, control real de bienes eclesiásticos, desmontaje de Pax Mariæ y nacimiento de Mariefred. Los bocadillos son una reconstrucción didáctica, no citas literales.</p>`}
    ],questions:[{id:"d8v7m7",type:"single",title:"Cristiana, pero ¿de qué Iglesia?",prompt:"¿Qué explica mejor por qué la Corona tomó el control de bienes de Pax Mariæ?",options:["Porque Suecia dejó de ser cristiana y prohibió toda religión.","Pax Mariæ era católico; durante la Reforma el reino se hizo luterano y Gustav Vasa reforzó el poder y los recursos de la Corona controlando bienes e ingresos eclesiásticos.","Porque los monjes decidieron construir un castillo de cañones para competir con el rey."],answer:1,hint:"El cambio afecta religión, propiedades y poder, pero no significa que Suecia dejara de ser cristiana.",success:"CAMBIO DE PODER ENTENDIDO.",explanation:"Pax Mariæ muestra la transformación desde una Iglesia católica poderosa hacia una Corona luterana con mayor control político y económico."}]},
    {title:"La cena que nació de una protesta",speaker:"Maja",photo:"maja-lind-store-mosse-ficcion-v1.png",characterCaption:"personaje ficticio · transmisión de llegada",keys:1,time:"5–6 min",action:"Leer la protesta",obstacle:"Cuando el rey o la corte viajaban, ¿quién ponía cama y comida? Muchas veces, la gente del pueblo. En Mariefred esa obligación se volvió demasiado cara.",goal:"Explicar cómo una necesidad cotidiana creó una posada organizada en 1609.",done:"La protesta de Mariefred deja de ser una curiosidad: es una solución a una carga doméstica real.",reaction:"La hospitalidad puede convertirse en carga cuando no es una elección y llega mucha gente.",closing:"Store Mosse ya no es un hueco. Mariefred tampoco es solo una postal: aquí una protesta cotidiana ayudó a crear una solución organizada.",contexts:[
      {character:true,k:"1609 · UNA CARGA CON CAMA INCLUIDA",title:"La protesta de los vecinos",visual:"d8Inn",html:`<p>La corte visitaba Gripsholm con frecuencia. Parte de los vecinos tenía que alojar y alimentar a las personas que viajaban con ella, a menudo sin pago. En 1609 protestaron; el 13 de febrero se concedió un privilegio al primer posadero, Jocim Smock, para organizar el servicio.</p>`},
      {character:true,k:"MADRID Y MARIEFRED",title:"La obligación de alojar también cambió casas",visual:"d8Madrid",html:`<p>En Madrid, tras fijar Felipe II la Corte en 1561, la Regalía de aposento obligaba a muchas casas a ceder espacio o soportar carga equivalente. Las «casas a la malicia» fueron una forma de intentar evitarlo.</p><p>En Mariefred la carga procedía de visitas frecuentes a Gripsholm; en Madrid, de una corte instalada. Problemas parecidos, no historias idénticas.</p><p>La Posada del Peine, cerca de la Plaza Mayor, se fundó en 1610 y hoy conserva el nombre como hotel. Es una coincidencia preciosa de época, no la misma historia.</p>`},
      {character:true,k:"SUECO ÚTIL",title:"Una mesa, por favor",speech:{word:"Ett bord, tack.",meaning:"Una mesa, por favor.",tip:"Frase útil para pedir mesa.",speech:"Ett bord, tack."},html:`<p><strong>bord</strong> = mesa · <strong>tack</strong> = gracias / por favor.</p>`}
    ],questions:[{id:"d8v7m8",type:"single",title:"Un impuesto con cama incluida",prompt:"¿Por qué protestó parte de la población de Mariefred en 1609?",options:["Porque tenían que alojar y alimentar a quienes viajaban con la corte, a menudo sin pago, y la carga se volvió demasiado costosa.","Porque preferían que la corte redujera visitas sin crear ningún servicio de alojamiento.","Porque creían que la Corona asumiría sin más todos los gastos por estar cerca de Gripsholm."],answer:0,hint:"La clave es que la obligación era costosa y no una hospitalidad elegida.",success:"PROTESTA ENTENDIDA.",explanation:"La posada nació de un problema concreto y de una solución organizada, no «mágicamente antigua»."}]}
  ],
  ending:[
    {image:"maja-lind-store-mosse-ficcion-v1.png",caption:"Maja Lind · personaje ficticio · mapa restaurado",k:"MAJA · CIERRE DEL HUMEDAL",title:"La mancha blanca ya tiene capas.",html:`<p>Store Mosse guarda turba, arena, aves, cicatrices y restauración. La torre enseña a mirar sin exigir un espectáculo y la carretera enseña que una red también puede ser cooperación.</p><p>Mariefred añade otra capa: Pax Mariæ, Reforma y una protesta que se convirtió en posada.</p>`,action:"Guardar el mapa"},
    {image:"saga-canal-asegurado.png",caption:"Saga · mapa restaurado",k:"SAGA · EVIDENCIA RECUPERADA",title:"Un paisaje que parece vacío puede contener miles de años.",html:`<p>También muchos hábitats y decisiones humanas. La Sombra había borrado Store Mosse para que el camino pareciera corto; ahora cada parada vuelve a tener historia.</p>`,action:"Abrir la puerta de Gripsholm"},
    {image:"saga-canal-asegurado.png",caption:"Saga · rumbo a Gripsholm",k:"COORDENADA SIGUIENTE",title:"El castillo que da nombre al Código.",html:`<div class="coordinate">MARIEFRED · GRIPSHOLM · MÄLAREN<br>FORTALEZA · MONASTERIO · CASTILLO<br>SEÑAL · PAX MARIÆ</div><p>Mañana entraremos en Gripsholm: descubriremos por qué antes fue fortaleza, después monasterio y por último castillo de la dinastía Vasa.</p>`,action:"Cerrar el canal"}
  ]
};
