/* Día 09 · Fuente editorial única: 03_Guiones/V8/Documento_Base_Guion_completo_Codigo_Gripsholm_dias_07_a_10_V8.docx.
   Elin Ryd es un personaje ficticio contemporáneo: sus palabras son recreación narrativa. */
window.DAY1_DATA={
 meta:{day:"09",store:"codigo-gripsholm-v8-day09",contentVersion:"v8-day9",place:"MARIEFRED · GRIPSHOLM · MÄLAREN",title:"Las llaves de los Vasa",landing:"La Sombra dejó intacta una sola palabra: GRIPSHOLM.",badge:"Código leído",objective:"ABRIR CINCO PUERTAS DEL LUGAR",objectiveCopy:"Poder, Corona, monasterio, Vasa y memoria: el código no es una contraseña, sino una forma de leer un lugar con varias vidas.",evidenceCopy:"Cada misión devuelve una capa de Gripsholm sin borrar las anteriores.",fine:"Elin Ryd es un personaje ficticio. Sus palabras son recreación narrativa basada en el contexto histórico del castillo.",verifiedTitle:"Gripsholm ya no parece una sola historia.",verifiedAction:"Abrir el cierre de Saga",result:{title:"Las llaves de los Vasa",evidence:"Código Gripsholm",openQuestion:"Si La Sombra intentó borrar todas estas capas, ¿qué necesitaban proteger los padres de Saga al dejarnos llegar hasta aquí?",next:{href:"dia10.html",label:"Abrir el Día 10"}}},
 prologue:[
  {k:"SAGA · ÚLTIMO ARCHIVO HISTÓRICO",title:"La palabra que nunca desapareció",image:"saga-canal-asegurado.png",alt:"Saga abre el mapa final del Mälaren",html:`<p>Cuando mis padres desaparecieron, dejaron una palabra entera: <strong>Gripsholm</strong>. Yo pensaba que era el lugar al que teníamos que llegar.</p><p>Ahora el archivo se abre y no muestra una coordenada. Muestra cinco puertas: <strong>poder, Corona, monasterio, Vasa y memoria</strong>.</p><p>Gripsholm no era la respuesta. Era la prueba final: comprobar si ya sabemos distinguir una postal de una historia completa.</p>`,action:"Abrir el último archivo"},
  {k:"ELIN RYD · PERSONAJE FICTICIO",title:"Un castillo tiene más de una llave",image:"elin-ryd-gripsholm-ficcion-v1.png",alt:"Elin Ryd, personaje ficticio, junto a Gripsholm",html:`<p>Elin tiene 20 años y es una <strong>recreación narrativa ficticia</strong>. Prepara reproducciones de retratos, planos y fichas de observación para visitantes de Gripsholm.</p><p>«Desde fuera parece el castillo perfecto de una postal. Pero una postal no cuenta quién construyó antes, quién cambió el uso del lugar, quién tuvo una llave, quién quedó encerrado o quién decidió qué rostros colgar en las paredes.»</p>`,action:"Entrar en Gripsholm"}
 ],routePlaces:[],missions:[
 {title:"Grip + holm",speaker:"Elin",photo:"elin-ryd-gripsholm-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"5–6 min",action:"Abrir el nombre",obstacle:"El nombre del castillo conserva a Bo Jonsson Grip, pero el mapa de su poder no debe confundirse con un país moderno.",goal:"Entender qué podía controlar un gran noble medieval y qué significa Gripsholm.",done:"El nombre enlaza un noble, su emblema y un islote del Mälaren.",reaction:"El mapa reúne tierras, castillos, derechos y cargos; no dibuja una frontera moderna.",closing:"Primera puerta: antes de los Vasa, Gripsholm ya hablaba de agua, rutas y poder.",contexts:[
   {character:true,k:"BO JONSSON GRIP · HACIA 1386",title:"Un mapa que no debe engañarnos",visual:"d9Bo",html:`<p>Bo Jonsson Grip fue uno de los nobles más poderosos de la Suecia medieval. Sus posesiones y derechos alcanzaban una parte enorme del reino de entonces.</p><p>El mapa mezcla tierras, castillos, préstamos, cargos y derechos. Controlar una fortaleza no significaba exactamente lo mismo que poseer una finca o administrar un territorio.</p>`},
   {character:true,k:"GRIP + HOLM",title:"El apellido y el islote",visual:"d9Name",html:`<p><strong>Grip</strong> remite al apellido de Bo Jonsson Grip y a su emblema de grifo, el animal fantástico que mezcla rasgos de águila y león. <strong>holm</strong> significa islote o pequeña isla.</p><p>Gripsholm significa aproximadamente «el islote de Grip».</p>`}
  ],questions:[{id:"d9m1",type:"match",title:"Desmontar Gripsholm",prompt:"Relaciona cada pieza con su significado.",pairs:[["Grip","Apellido de Bo Jonsson Grip y su emblema de grifo."],["holm","Islote o pequeña isla."],["Gripsholm","El islote de Grip, de forma aproximada."]],hint:"El castillo Vasa es posterior: el nombre guarda una capa medieval.",success:"NOMBRE Y ORIGEN CONECTADOS.",explanation:"Un nombre puede conservar una persona y un paisaje aunque el lugar cambie por completo."}]},
 {title:"Fortaleza, monasterio, castillo",speaker:"Elin",photo:"elin-ryd-gripsholm-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"6–7 min",action:"Seguir las llaves",obstacle:"La historia no cambia solo mediante conquistas: aquí hay Corona, intercambio, fundación religiosa y Reforma.",goal:"Reconstruir la cadena que llevó de la fortaleza medieval al castillo Vasa.",done:"Pax Mariæ queda unido a Mariefred y a los cambios de la Reforma.",reaction:"No todos los cambios de manos llegan por conquista. Cada uno deja una huella distinta.",closing:"Segunda puerta: el monasterio no fue un detalle entre dos castillos; explica el nombre de Mariefred.",contexts:[
   {character:true,k:"1404 → 1537",title:"Cuatro cambios, cuatro formas",visual:"d9Pax",html:`<p>Tras la muerte de Bo Jonsson Grip, la reina Margarita asumió la propiedad en 1404. En 1472, Sten Sture el Viejo obtuvo Gripsholm mediante un <strong>intercambio de propiedades con la Corona</strong>: no fue una expropiación ni una compra de un Estado moderno.</p><p>Sten Sture impulsó el monasterio cartujo de Pax Mariæ. En 1498 la finca quedó formalmente entregada al monasterio. Durante la Reforma, Gustav Vasa tomó control de bienes eclesiásticos y en 1537 comenzó el castillo actual.</p>`},
   {character:true,k:"PAX MARIÆ → MARIEFRED",title:"Una palabra que ya conocéis",visual:"d9Mariefred",html:`<p><strong>Pax Mariæ</strong> significa en latín «Paz de María». En sueco: <strong>Marias fred</strong>. <strong>fred</strong> significa paz. Mariefred conserva esa idea en el nombre de la ciudad.</p><p>El Día 8 presentó el monasterio; hoy completamos su relación con Gripsholm.</p>`}
  ],questions:[{id:"d9m2",type:"order",title:"Cada cambio dejó una huella",prompt:"Ordena la cadena de cambios de Gripsholm.",items:[["corona","1404 · la reina Margarita incorpora Gripsholm a la Corona."],["intercambio","1472 · Sten Sture el Viejo lo obtiene mediante intercambio de propiedades."],["monasterio","1493–1498 · Pax Mariæ se funda y recibe la finca."],["reforma","1526–1537 · la Reforma permite a Gustav Vasa tomar control e iniciar el castillo."]],answer:["corona","intercambio","monasterio","reforma"],hint:"No todos los cambios llegan por conquista: sigue Corona, intercambio, monasterio y Reforma.",success:"FORMAS DE CAMBIO CONECTADAS.",explanation:"La cadena explica por qué un monasterio católico forma parte de la historia del castillo Vasa."}]},
 {title:"Un hogar que también defendía",speaker:"Elin",photo:"elin-ryd-gripsholm-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"5–6 min",action:"Mirar el agua",obstacle:"El Mälaren no es un fondo de postal: conecta Gripsholm con Estocolmo y el Báltico.",goal:"Situar el castillo de 1537 en una red de agua, defensa y gobierno.",done:"Gripsholm aparece como residencia fortificada dentro de un sistema mayor.",reaction:"El agua protege, pero también conecta: por eso importa quién puede usar las rutas.",closing:"Tercera puerta: las torres cuentan menos si no miramos el lago y los caminos que las rodean.",contexts:[
   {character:true,k:"GRIPSHOLM → MÄLAREN → ESTOCOLMO → BÁLTICO",title:"El agua no es fondo de postal",visual:"d9Water",html:`<p>Desde 1537 Gustav Vasa levantó una residencia fortificada: un lugar para vivir, recibir, guardar y defender. El Mälaren conectaba el castillo con Estocolmo y, a través de sus salidas, con el Báltico.</p>`},
   {character:true,k:"SEIS LUGARES PARA LEER EL VIAJE",title:"No son seis castillos iguales",visual:"d9Castles",html:`<p>Kalmar ayuda a leer la Unión de tres reinos. Estocolmo/Tre Kronor fue centro político. Örebro fue cruce de río y rebelión. Karlsborg fue capital de reserva. Skansen Kronan defendía la aproximación a Gotemburgo. Gripsholm reunió defensa, residencia, prisión y memoria.</p>`},
   {character:true,k:"PARALELISMO · ALCÁZAR DE SEGOVIA",title:"Las funciones pueden cambiar",visual:"d9Segovia",html:`<p>El Alcázar de Segovia fue fortaleza, residencia de reyes de Castilla, prisión de Estado y, mucho después, Real Colegio de Artillería. No es la historia sueca, pero ayuda a entender que un edificio puede sobrevivir porque sus usos cambian.</p>`}
  ],questions:[{id:"d9m3",type:"single",title:"¿Por qué aquí?",prompt:"¿Qué combinación explica mejor que Gripsholm fuera útil a Gustav Vasa?",options:["El lago impedía por completo que alguien llegara al castillo.","Estaba junto al Mälaren, conectado con Estocolmo y el Báltico, y podía servir como residencia y punto defensivo.","Su posición junto al Mälaren era secundaria: bastaba una residencia cómoda lejos de Estocolmo."],answer:1,hint:"El agua protege y conecta, pero no convierte un lugar en inexpugnable por arte de magia.",success:"AGUA, DEFENSA Y GOBIERNO CONECTADOS.",explanation:"El castillo formaba parte de una nueva monarquía que necesitaba representar y proteger su poder."}]},
 {title:"Cuando las llaves cambiaron de mano",speaker:"Elin",photo:"elin-ryd-gripsholm-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"6–7 min",action:"Abrir el árbol Vasa",obstacle:"Una disputa entre familiares podía ser una crisis de Estado cuando estaba en juego la Corona.",goal:"Seguir quién tenía el poder y las llaves de Gripsholm durante el conflicto entre Erik XIV y Johan III.",done:"El castillo queda entendido como residencia y prisión política.",reaction:"En una monarquía, una discusión familiar podía cambiar alianzas, religión, leyes y guerras.",closing:"Cuarta puerta: una torre puede proteger a quienes están dentro o impedirles salir.",contexts:[
   {character:true,k:"FAMILIA VASA · PODER Y SUCESIÓN",title:"Una familia con demasiadas coronas",visual:"d9Family",html:`<p>Erik XIV, hijo mayor de Gustav Vasa, encerró en Gripsholm a su medio hermano Johan y a su esposa Katarina Jagellonica entre 1563 y 1567. Tras perder el poder en 1568, Erik XIV, Karin Månsdotter y sus hijos quedaron encerrados allí en 1571 bajo Johan III.</p>`},
   {character:true,k:"SUECIA Y ESPAÑA · 1568",title:"Un paralelo que no borra diferencias",visual:"d9Felipe",html:`<p>En España, Felipe II ordenó encerrar a su hijo y heredero, el príncipe Carlos, que murió meses después en 1568. No es la misma historia: causas, personas y final fueron distintos. El paralelo ayuda a entender que el miedo a perder el control de la sucesión podía convertirse en crisis de Estado.</p>`}
  ],questions:[{id:"d9m4",type:"single",title:"La comparación bien hecha",prompt:"¿Qué conclusión usa los dos casos con cuidado?",options:["Los dos casos muestran que una sucesión podía crear un conflicto de Estado; no permiten afirmar que las causas fueran iguales.","Como ambos incluyen prisión dentro de una familia real, basta la historia personal y no importa la sucesión.","No se pueden comparar en absoluto, porque pertenecen a reinos distintos."],answer:0,hint:"Un paralelismo sirve para comparar una pregunta, no para convertir dos historias en copias.",success:"PARALELISMO LEÍDO CON CUIDADO.",explanation:"Lo importante es seguir quién tenía el poder y qué implicaba controlarlo."}]},
 {title:"Tres retratos para leer una dinastía",speaker:"Elin",photo:"elin-ryd-gripsholm-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"5–6 min",action:"Mirar tres rostros",obstacle:"Hay cientos de retratos; no hace falta verlos todos para aprender a mirar bien una fuente.",goal:"Situar a Gustav Vasa, Erik XIV y Johan III y entender qué cuenta —y qué no— un retrato.",done:"Los retratos dejan de ser decoración: son fuentes parciales y memoria elegida.",reaction:"Una imagen puede ser importante sin ser una biografía completa.",closing:"Quinta puerta: en un museo conviene preguntar quién quiso que una cara siguiera visible.",contexts:[
   {character:true,k:"COLECCIÓN ESTATAL SUECA DE RETRATOS",title:"Tres rostros, tres preguntas",visual:"d9Portraits",html:`<p><strong>Gustav Vasa:</strong> elegido rey en 1523, impulsó el castillo y la Reforma. <strong>Erik XIV:</strong> encerró a Johan y más tarde fue preso en Gripsholm. <strong>Johan III:</strong> estuvo allí prisionero con Katarina Jagellonica y después llegó al trono.</p><p>La colección conserva rostros de unos cinco siglos. También es una decisión de memoria: quién entra, cómo se presenta y quién falta.</p>`}
  ],questions:[{id:"d9m5",type:"match",title:"Lo que un retrato puede contar",prompt:"Relaciona cada pregunta con la respuesta más cuidadosa.",pairs:[["¿Cómo quiso presentarse una persona o institución?","Sí: el retrato puede ayudar junto a otras fuentes."],["¿Qué ropa, símbolos o estilo eran importantes?","Sí: puede dar pistas junto a otras fuentes."],["¿Quién decidió conservar ese rostro?","Sí: investigando la colección y su historia."],["¿Qué pensaba alguien en secreto cada noche?","No: un retrato no puede saberlo por sí solo."]],hint:"Un cuadro no es una cámara que sepa todo, pero tampoco es decoración sin valor.",success:"RETRATO LEÍDO COMO PRUEBA PARCIAL.",explanation:"Mirar una fuente con cuidado significa usarla sin pedirle que responda a todo."}]},
 {title:"Una torre puede ser teatro",speaker:"Elin",photo:"elin-ryd-gripsholm-ficcion-v1.png",characterCaption:"personaje ficticio · recreación narrativa",keys:1,time:"5–6 min",action:"Subir al teatro",obstacle:"Gripsholm cambió con las épocas: una torre defensiva pudo convertirse en escenario; un objeto famoso puede enseñar también un error.",goal:"Reconocer los usos culturales del castillo y comparar evidencias visuales.",done:"Teatro y león enseñan que una imagen necesita contexto.",reaction:"Una imagen conocida puede ser poco fiable si quien la creó no conocía bien aquello que intentaba representar.",closing:"Sexta puerta: defensa, prisión y ocio pueden convivir en la vida larga de un castillo.",contexts:[
   {character:true,k:"GUSTAVO III · SIGLO XVIII",title:"Una torre que se convirtió en teatro",visual:"d9Theatre",html:`<p>A finales del siglo XVIII Gustavo III instaló un teatro en una de las torres renacentistas. Es uno de los teatros del siglo XVIII mejor conservados de Europa. Escenario, lugares de público y distribución interior revelan un uso pensado para mirar y escuchar.</p>`},
   {character:true,k:"EL LEÓN DE GRIPSHOLM",title:"Una imagen llamativa puede estar equivocada",visual:"d9Lion",html:`<p>El famoso león disecado no está aquí para reírse de nadie. Recuerda la misma regla que el casco vikingo del Día 1: una representación puede ser llamativa y conservar valor histórico, pero ser poco fiable si se hizo con malas referencias.</p>`},
   {character:true,k:"SUECO ÚTIL · MUSEO",title:"Una pregunta para mirar mejor",speech:{word:"Vad berättar bilden?",meaning:"¿Qué cuenta la imagen?",tip:"Pregunta útil para mirar una imagen con atención.",speech:"Vad berättar bilden?"},html:`<p><strong>bild</strong> = imagen · <strong>berättar</strong> = cuenta / relata.</p>`}
  ],questions:[{id:"d9m6",type:"single",title:"El león y el casco vikingo",prompt:"¿Qué lección comparten el león de Gripsholm y el casco vikingo de cuernos?",options:["Una imagen conocida puede ser poco fiable si quien la creó no conocía bien aquello que intentaba representar.","Una imagen con un error ya no puede enseñar nada sobre quien la produjo o conservó.","Una representación llamativa debe aceptarse literalmente si lleva mucho tiempo en un museo."],answer:0,hint:"No rechazamos los objetos: preguntamos qué sabía quien los hizo y qué evidencia utilizó.",success:"IMAGEN FAMOSA LEÍDA CON CRITERIO.",explanation:"El contexto permite valorar un objeto sin convertirlo en una verdad literal."}]},
 {title:"Dos ciudades, dos memorias",speaker:"Elin",photo:"elin-ryd-gripsholm-ficcion-v1.png",characterCaption:"personaje ficticio · opciones de tarde",keys:1,time:"5–7 min",action:"Elegir una tarde",obstacle:"El mapa ofrece Strängnäs o Sigtuna, no obliga a intentar las dos. Elegir bien también es viajar bien.",goal:"Conocer los dos caminos antes de decidir qué historia activar —o elegir descansar.",done:"La decisión queda informada, sin evidencia extra por correr más.",reaction:"Una elección de viaje también puede ser aprender qué dejas para otra ocasión y por qué.",closing:"Séptima puerta: memoria pública puede ser una elección política o una piedra junto a un camino.",contexts:[
   {character:true,k:"OPCIÓN A · STRÄNGNÄS",title:"Cuando Gustav fue elegido",visual:"d9Strangnas",html:`<p>El 6 de junio de 1523 Gustav Eriksson fue elegido rey en Strängnäs. Fue un paso decisivo hacia la monarquía Vasa, aunque el reino aún tenía que consolidar poder e instituciones. Hoy el 6 de junio es el Día Nacional de Suecia.</p>`},
   {character:true,k:"OPCIÓN B · SIGTUNA",title:"Las piedras que hablaban en público",visual:"d9Sigtuna",html:`<p>Sigtuna se formó a finales del siglo X. Sus piedras rúnicas son documentos públicos: podían recordar a una persona, mencionar un viaje, nombrar un puente o mostrar prestigio. Muchas pertenecen a la transición entre época vikinga y Edad Media cristiana.</p>`}
  ],questions:[{id:"d9m7",type:"single",title:"Elegir una historia sin correr",prompt:"¿Qué opción describe mejor las dos alternativas?",options:["Strängnäs ayuda a situar la elección de Gustav Vasa; Sigtuna muestra cómo las runas podían ser memoria pública. Se puede elegir una o descansar sin castigo.","Hay que visitar ambas en una tarde para que la evidencia sea válida.","Las piedras rúnicas eran mensajes secretos y Strängnäs no tiene relación con los Vasa."],answer:0,hint:"El objetivo es elegir con información, no convertir la tarde en una carrera.",success:"DOS RUTAS LEÍDAS CON CALMA.",explanation:"No hay una evidencia extra por hacer más kilómetros."}]},
 {title:"La orilla que guarda todas las versiones",speaker:"Elin",photo:"elin-ryd-gripsholm-ficcion-v1.png",characterCaption:"personaje ficticio · cierre de día",keys:1,time:"5–6 min",action:"Mirar desde fuera",obstacle:"Una buena vista no necesita una leyenda añadida para conectar paisaje e historia.",goal:"Reunir las capas de Gripsholm mirando agua, rutas, usos y cambios de poder.",done:"El Código Gripsholm queda entendido como método: buscar capas, fuentes y preguntas pendientes.",reaction:"Una historia completa no borra las capas incómodas: las coloca juntas con pruebas.",closing:"El castillo ya no es solo un final bonito. Es el lugar que os ha enseñado a leer el viaje entero.",contexts:[
   {character:true,k:"MÄLAREN · ORILLA · HJORHAGEN",title:"Mirar fuera también es investigar",visual:"d9View",html:`<p>El paseo de orilla y el entorno de Hjorthagen permiten ver agua, praderas, arbolado y las torres desde otro ángulo. No hace falta inventar una «ruta de Gustav Vasa»: el paisaje ya ayuda a entender defensa, rutas y usos posteriores.</p>`},
   {character:true,k:"CINCO PUERTAS",title:"El Código Gripsholm",visual:"d9Five",html:`<p>Bo Jonsson Grip y el poder medieval. Corona e intercambio. Pax Mariæ y el monasterio. Gustav Vasa y el castillo. Prisión, teatro, retratos y memoria pública.</p><p>No son versiones que se excluyen: son capas que se entienden mejor juntas.</p>`},
   {character:true,k:"SUECO PARA DESPEDIRSE",title:"Gracias por el viaje",speech:{word:"Tack för resan.",meaning:"Gracias por el viaje.",tip:"Una frase para despedirse.",speech:"Tack för resan."},html:`<p><strong>tack</strong> = gracias · <strong>resa</strong> = viaje.</p>`}
  ],questions:[{id:"d9m8",type:"order",title:"Las cinco puertas",prompt:"Ordena las capas de Gripsholm para reunir la historia completa.",items:[["poder","Bo Jonsson Grip y el poder de un noble."],["corona","Corona, intercambio y donación monástica."],["pax","Pax Mariæ y el monasterio."],["vasa","Gustav Vasa y el castillo iniciado en 1537."],["memoria","Prisión, teatro, retratos y memoria pública."]],answer:["poder","corona","pax","vasa","memoria"],hint:"No hay una sola versión verdadera que borre las demás. Las capas pueden convivir.",success:"CÓDIGO GRIPSHOLM COMPLETADO.",explanation:"Leer un lugar es buscar agua, rutas, usos, fuentes y las preguntas que todavía faltan."}]}
 ],ending:[
  {image:"elin-ryd-gripsholm-ficcion-v1.png",caption:"Elin Ryd · personaje ficticio · cierre de Gripsholm",k:"ELIN · CIERRE DEL CASTILLO",title:"Un lugar nunca tiene una sola llave.",html:`<p>Gripsholm fue fortaleza, posesión de la Corona, monasterio, castillo Vasa, prisión, residencia, teatro y colección de retratos.</p><p>Ya podéis mirar el castillo sin necesitar que sea perfecto. Cuando un lugar parece tener una sola historia, seguramente queda otra puerta por abrir.</p>`,action:"Guardar el código"},
  {image:"saga-canal-asegurado.png",caption:"Saga · evidencia recuperada",k:"SAGA · CÓDIGO LEÍDO",title:"Gripsholm no era la respuesta. Era la prueba final.",html:`<p>La Sombra quería un viaje de postales y respuestas rápidas. Vosotras habéis recuperado algo mejor: cómo preguntar, cómo comparar y cómo reconocer una prueba.</p><p>He encontrado una señal de mis padres. No es una respuesta completa todavía, pero ya no están perdidos dentro del mapa.</p>`,action:"Abrir el último favor"},
  {image:"saga-canal-asegurado.png",caption:"Saga · regreso",k:"COORDENADA SIGUIENTE",title:"Antes de volver",html:`<div class="coordinate">ÚLTIMO FAVOR · MEMORIA · REGRESO<br>UNA EVIDENCIA PARA CADA PERSONA<br>SEÑAL · PADRES DE SAGA</div><p>Mañana regresamos. Cada persona que nos ayudó quiere comprobar qué recuerdos os lleváis de Suecia. No será un examen: será una forma de devolverles la historia que protegieron.</p>`,action:"Cerrar el canal"}
 ]
};
